SELECT DTMOV,
       CODIGO,
       CODUSUR,
       SUM (VALOR) AS VALOR
  FROM (
    SELECT M.DTMOV,
           S.CODCLI AS CODIGO,
           S.CODUSUR,
           ROUND (M.QTCONT * (M.PUNITCONT + NVL (M.VLFRETE, 0) + NVL (M.VLOUTROS, 0)), 2) AS VALOR
      FROM PCMOV M
     INNER JOIN PCNFSAID S ON M.NUMTRANSVENDA = S.NUMTRANSVENDA
      LEFT JOIN VIEW_JC_VENDEDOR V ON S.CODUSUR = V.CODUSUR
     WHERE M.CODFISCAL IN (
        5102, 5109, 5403, 5405, 6102, 6108, 6403
    )
       AND V.CODGERENTE IN (
        1, 8, 9
    )
       AND M.DTMOV >= TO_DATE ('01/01/2017', 'DD/MM/YYYY')
)
 GROUP BY DTMOV,
          CODIGO,
          CODUSUR