--RELACAO VENDA ECOMMERCE PARA DEVOLUCAO ENTRE EMPRESAS-----
SELECT M.DTMOV,
       S.NUMNOTA,
       S.NUMTRANSVENDA,
       COUNT(M.CODPROD) OVER(PARTITION BY M.NUMTRANSVENDA) QT_ITENS,
       S.CODCLI,
       S.CLIENTE,
       S.CODUSUR,
       S.CODFILIAL,
       M.CODFILIALRETIRA,
       M.CODPROD,
       M.DESCRICAO,
       M.QT,
       M.PUNIT,
       S.VLFRETE,
       (CASE
         WHEN S.VLFRETE > 0 THEN
          'FRETE'
         ELSE
          NULL
       END) FRETE,
       S.VLTOTAL,
       (SELECT 'S'
          FROM PCMOV V
         WHERE V.NUMTRANSDEV = M.NUMTRANSVENDA
           AND V.CODPROD = M.CODPROD) DEVOLUCAO
  FROM PCMOV M
  JOIN PCNFSAID S ON S.NUMTRANSVENDA = M.NUMTRANSVENDA
 WHERE S.CODFILIAL = '9'
   AND S.NUMNOTA IN (7770,7563) ----VER SE TEM FRETE PARA LANCAR
 ORDER BY M.CODFILIALRETIRA, M.CODPROD;

----
SELECT M.CODFILIALRETIRA, M.CODPROD, M.DESCRICAO, SUM(M.QT) QTSOMA
    FROM PCMOV M
    JOIN PCNFSAID S ON S.NUMTRANSVENDA = M.NUMTRANSVENDA
   WHERE S.CODFILIAL = '9'
     AND S.NUMNOTA IN (7770,7563)
   GROUP BY M.CODFILIALRETIRA, M.CODPROD, M.DESCRICAO
   ORDER BY M.CODFILIALRETIRA;

--PARA PEGAR A NOTA DE VENDA PARA GERAR A DEVOLUÇÃO OTIMIZADA
WITH PRODUTOS_DEV AS
 (SELECT M.CODFILIALRETIRA, M.CODPROD, M.DESCRICAO, SUM(M.QT) QTSOMA
    FROM PCMOV M
    JOIN PCNFSAID S ON S.NUMTRANSVENDA = M.NUMTRANSVENDA
   WHERE S.CODFILIAL = '9'
     AND S.NUMNOTA IN (7770,7563)
   GROUP BY M.CODFILIALRETIRA, M.CODPROD, M.DESCRICAO
   ORDER BY M.CODFILIALRETIRA)
SELECT COUNT(M.CODPROD) OVER(PARTITION BY NUMNOTA) QTPRODUTOS,
       M.QTDEVOL,
       M.CODPROD,
       M.DESCRICAO,
       M.QT,
       M.NUMNOTA
  FROM PCMOV M, PRODUTOS_DEV D
 WHERE D.CODFILIALRETIRA = M.CODFILIAL
   AND D.CODPROD = M.CODPROD
   AND D.QTSOMA <= (M.QT - NVL(QTDEVOL, 0))
   AND M.CODFILIAL = '7'
   AND M.CODOPER = 'S'
   AND STATUS = 'AB'
   AND CODCLI = 400430 --AND M.CODPROD IN (815972,816341)
 ORDER BY QTPRODUTOS DESC, NUMNOTA, CODPROD;

----CREDITOS E VERBAS
SELECT *
  FROM (SELECT C.CODFILIAL,
               'CREDITO' TIPO,
               C.CODIGO NUMERO,
               C.DTLANC,
               C.CODCLI CODIGO,
               T.CLIENTE EMPRESA,
               C.VALOR
          FROM PCCRECLI C
          JOIN PCCLIENT T ON T.CODCLI = C.CODCLI
         WHERE C.CODCLI = 400430
           AND C.DTLANC = TRUNC(SYSDATE)
        UNION
        SELECT V.CODFILIAL,
               'VERBA' TIPO,
               V.NUMVERBA NUMERO,
               V.DTEMISSAO DTLANC,
               V.CODFORNEC CODIGO,
               F.FORNECEDOR EMPRESA,
               V.VALOR
          FROM PCVERBA V
          JOIN PCFORNEC F ON F.CODFORNEC = V.CODFORNEC
         WHERE V.CODFILIAL = '9'
           AND V.CODFORNEC IN (7543, 9505)
           AND V.DTEMISSAO = TRUNC(SYSDATE))
 ORDER BY VALOR, CODFILIAL;
