CREATE OR REPLACE VIEW VIEW_BI_PRODUTO AS
    SELECT P.CODPROD,
           P.DESCRICAO AS PRODUTO,
           (
               CASE
                   WHEN P.CODPROD = P.CODPRODMASTER THEN 'PAI'
                   ELSE 'FILHO'
               END
           ) AS TIPO,
           F.CODFORNEC,
           (
               CASE
                   WHEN P.CODMARCA IN (
                       165, 166, 167
                   ) THEN 'DOREL'
                   ELSE COALESCE (M.MARCA, 'SEM MARCA')
               END
           ) AS MARCA,
           D.DESCRICAO AS DEPARTAMENTO,
           S.DESCRICAO AS SECAO,
           C.CATEGORIA,
           COALESCE (L.DESCRICAO, 'SEM LINHA') AS LINHA_PRODUTO,
           P.DTCADASTRO,
           P.DTULTALTCAD
      FROM PCPRODUT P
      LEFT JOIN PCMARCA M ON P.CODMARCA = M.CODMARCA
      LEFT JOIN PCDEPTO D ON P.CODEPTO = D.CODEPTO
      LEFT JOIN PCSECAO S ON P.CODSEC = S.CODSEC
      LEFT JOIN PCCATEGORIA C ON P.CODCATEGORIA = C.CODCATEGORIA
      LEFT JOIN PCLINHAPROD L ON P.CODLINHAPROD = L.CODLINHA
      LEFT JOIN PCFORNEC F ON P.CODFORNEC = F.CODFORNEC;
/