CREATE OR REPLACE VIEW VIEW_JC_PCPRODUT AS
    WITH PRODUTOMASTER AS (
        SELECT T.CODPROD,
               T.DESCRICAO
          FROM PCPRODUT T
          LEFT JOIN PCLINHAPROD L ON T.CODLINHAPROD = L.CODLINHA
         WHERE T.CODPROD = T.CODPRODMASTER
    )
     /*PARA TERMOS A DESCRICAO DO PRODUTO MASTER*/
    SELECT P.CODPROD,
           P.CODPRODMASTER,
           PM.DESCRICAO AS PRODUTO_MASTER,
           P.DESCRICAO AS PRODUTO,
           (
               CASE
                   WHEN P.CODMARCA IN (
                       165, 166, 167
                   ) THEN
     /*AGRUPARMOS A MARCA DOREL*/ 'DOREL'
                   ELSE M.MARCA
               END
           ) AS MARCA,
           D.DESCRICAO AS DEPARTAMENTO,
           S.DESCRICAO AS SECAO,
           C.CATEGORIA,
           L.DESCRICAO AS LINHA_PRODUTO,
           F.CODFORNECPRINC,
           F.FORNECEDOR,
           P.CODAUXILIAR,
           P.REVENDA,
           P.TIPOMERC,
           P.OBS2 AS FORADELINHA,
           P.DTEXCLUSAO
      FROM PCPRODUT P
      LEFT JOIN PCMARCA M ON P.CODMARCA = M.CODMARCA
      LEFT JOIN PCDEPTO D ON P.CODEPTO = D.CODEPTO
      LEFT JOIN PCSECAO S ON P.CODSEC = S.CODSEC
      LEFT JOIN PCCATEGORIA C ON P.CODCATEGORIA = C.CODCATEGORIA
      LEFT JOIN PCLINHAPROD L ON P.CODLINHAPROD = L.CODLINHA
      LEFT JOIN PCFORNEC F ON P.CODFORNEC = F.CODFORNEC
      LEFT JOIN PRODUTOMASTER PM ON P.CODPRODMASTER = PM.CODPROD;