CREATE OR REPLACE VIEW VIEW_BI_LINHAPRODUTO AS
    SELECT P.CODLINHA,
           P.DESCRICAO AS LINHAPRODUTO
      FROM PCLINHAPROD P
    UNION
    SELECT 99 AS CODLINHA,
           'SEM LINHA' AS LINHAPRODUTO
      FROM DUAL;
/