CREATE OR REPLACE VIEW VIEW_JC_LANC_FISCAL AS
WITH PCMOV_NUMTRANSENT AS
--TODAS AS MOVIMENTACOES DA PCMOV
 (SELECT DISTINCT (NUMTRANSENT) FROM PCMOV)
--NOTAS DE SERVICO, COMPRA CONSUMO
SELECT E.CODFILIALNF,
       E.DTEMISSAO,
       E.NUMNOTA,
       B.CODFISCAL,
       E.CODFORNEC,
       ('CNPJ: ' || E.CGC || ' - ' || E.FORNECEDOR) AS FORNECEDOR,
       B.VLCONTABIL,
       B.SITTRIBUT AS CST_ICMS,
       B.VLBASE,
       B.ALIQUOTA AS ALIQ_ICMS,
       B.VLICMS,
       B.VLISENTAS,
       E.VLOUTRAS,
       P.CODTRIBPISCOFINS AS CST_PISCOFINS,
       ROUND(P.VLPIS, 2) AS VLPIS,
       ROUND(P.VLCOFINS, 2) AS VLCOFINS,
       E.NUMTRANSENT
  FROM PCNFENT E
 INNER JOIN PCNFBASE B
    ON E.NUMTRANSENT = B.NUMTRANSENT
 INNER JOIN PCNFENTPISCOFINS P
    ON E.NUMTRANSENT = P.NUMTRANSENT
  LEFT JOIN PCMOV_NUMTRANSENT M
    ON E.NUMTRANSENT = M.NUMTRANSENT
 WHERE E.DTCANCEL IS NULL --NAO TRAZER NOTAS CANCELADAS
   AND M.NUMTRANSENT IS NULL --NAO TRAZER NOTAS COM MOVIMENTACAO NA PCMOV
   AND E.ESPECIE NOT IN ('OE', 'NE', 'TP') --NAO TRAZER NOTAS DE OUTRAS ESPECIES
;/