CREATE OR REPLACE VIEW VIEW_BI_MOVPROD AS
SELECT I.DATA,
       I.CODFILIAL,
       I.CODPROD,
       I.QTCONT AS QT,
       I.PUNITCONT AS VLPROD,
       ROUND(I.CUSTOFINEST,2) AS CUSTO,
       I.VLPRODUTO AS VLVENDA,
       ROUND(((I.QTCONT * I.CUSTOFINEST) + I.VLICMS + I.VLPIS + I.VLCOFINS +
       I.VLICMSPARTILHA),2) AS VLCMV,
       I.VLFRETE,
       I.VLST,
       I.VLOUTRASDESP,
       I.VLCONTABIL AS VLVENDATOTAL,
       NVL(I.CODUSUR,0) AS CODUSUR,
       I.CODFISCAL,
       I.NUMTRANSACAO
  FROM VIEW_JC_ITEM_NOTAFISCAL I
 WHERE I.DTCANCEL IS NULL
   AND I.CODFISCAL IS NOT NULL
   AND I.CODFILIAL NOT IN (3, 4)
   
   AND I.DATA > '08-AUG-2021';
