CREATE OR REPLACE VIEW VIEW_JC_DEVOLUCOES_CLI AS
SELECT E.DTMOV, E.CODIGO, E.CODUSUR, SUM(E.VLTOTALNF) AS VALOR
  FROM VIEW_JC_PCMOV_ENT E
  LEFT JOIN VIEW_JC_VENDEDOR V
    ON E.CODUSUR = V.CODUSUR
 WHERE E.CODFISCAL IN (1202, 1411, 2202, 2411)
   AND V.CODGERENTE IN (1, 8, 9)
 GROUP BY E.DTMOV, E.CODIGO, E.CODUSUR;