CREATE OR REPLACE VIEW VIEW_BI_MOVPROD_VENDAS AS
    WITH CFOP_FILTRADOS AS (
        SELECT CODFISCAL
          FROM VIEW_BI_SAIDA_VENDA_NORMAL
        UNION
        SELECT CODFISCAL
          FROM VIEW_BI_SAIDA_VENDA_TRIANGULAR
        UNION
        SELECT CODFISCAL
          FROM VIEW_BI_SAIDA_REM_ENT_FUT
        UNION
        SELECT CODFISCAL
          FROM VIEW_BI_SAIDA_FAT_CONTA_ORDEM
    )
    SELECT M.*
      FROM VIEW_BI_MOVPROD M
     INNER JOIN CFOP_FILTRADOS F ON M.CODFISCAL = F.CODFISCAL;
/