CREATE OR REPLACE VIEW VIEW_JC_VENDAS_CLI AS
SELECT S.DTMOV, S.CODIGO, S.CODUSUR, SUM(S.VLTOTALNF) AS VALOR
  FROM VIEW_JC_PCMOV_SAID S
  LEFT JOIN VIEW_JC_VENDEDOR V
    ON S.CODUSUR = V.CODUSUR
 WHERE S.CODFISCAL IN (5102,5109,5403,5405,6102,6108,6403)
   AND V.CODGERENTE IN (1, 8, 9)
 GROUP BY S.DTMOV, S.CODIGO, S.CODUSUR;