CREATE OR REPLACE VIEW VIEW_BI_MOVPROD AS
    SELECT I.DATA,
           CAST(I.CODFILIAL AS NUMBER) AS CODFILIAL,
           I.CODPROD,
           I.QTCONT AS QT,
           I.PUNITCONT AS VLPROD,
           ROUND (I.CUSTOFINEST, 4) AS CUSTO,
           I.VLPRODUTO AS VLTOTPROD,
           ROUND (((I.QTCONT * I.CUSTOFINEST) + I.VLICMS + I.VLPIS + I.VLCOFINS + I.VLICMSPARTILHA), 2) AS VLCMV,
           I.VLFRETE,
           I.VLST,
           I.VLOUTRASDESP,
           I.VLCONTABIL AS VLVENDATOTAL,
           NVL (I.CODUSUR, 0) AS CODUSUR,
           I.TIPOMOV,
           CAST(I.CODFISCAL AS VARCHAR2(4)) AS CODFISCAL,
           I.CODFORCLI
      FROM VIEW_JC_ITEM_NOTAFISCAL I
     WHERE I.DTCANCEL IS NULL
       AND I.CODFISCAL IS NOT NULL
       AND I.CODFILIAL NOT IN (
        3, 4
    );
/