CREATE OR REPLACE VIEW VIEW_BI_MOVPROD_COMPRAS AS
    WITH CFOP_FILTRADOS AS (
        SELECT CODFISCAL
          FROM VIEW_BI_ENT_MERCADORIA
        UNION
        SELECT CODFISCAL
          FROM VIEW_BI_ENT_TRIANGULAR
        UNION
        SELECT CODFISCAL
          FROM VIEW_BI_ENT_REM_ENT_FUT
    )
    SELECT M.*
      FROM VIEW_BI_MOVPROD M
     INNER JOIN CFOP_FILTRADOS F ON M.CODFISCAL = F.CODFISCAL;
/