WITH ESTOQUE_ENDERECADO AS
 (SELECT JCENDESTOQUE.PROD_ID,
         SUM(CASE
               WHEN NVL(DEP.TIPO, 'A') = 'A' THEN
                JCENDESTOQUE.QTD
               ELSE
                0
             END) AS QTD_DEPOSITO,
         SUM(CASE
               WHEN NVL(DEP.TIPO, 'A') = 'L' THEN
                JCENDESTOQUE.QTD
               ELSE
                0
             END) QTD_END_LOJA,
         NVL(PCEST.QTFRENTELOJA, 0) AS QTD_LOJA,
         SUM(CASE
               WHEN NVL(DEP.TIPO, 'A') = 'A' THEN
                JCENDESTOQUE.QTD
               ELSE
                0
             END) + NVL(PCEST.QTFRENTELOJA, 0) AS QTD_TOTAL
    FROM JCENDESTOQUE
    JOIN JCENDAPTO
      ON JCENDAPTO.FILIAL_ID = '1'
     AND JCENDAPTO.ID = JCENDESTOQUE.APTO_ID
    LEFT JOIN PCEST
      ON PCEST.CODFILIAL = JCENDAPTO.FILIAL_ID
     AND PCEST.CODPROD = JCENDESTOQUE.PROD_ID
    LEFT JOIN JCENDDEPOSITO DEP
      ON DEP.ID = JCENDAPTO.DEPOSITO_ID
  --WHERE NVL(DEP.TIPO, 'A') = 'A'
   GROUP BY JCENDESTOQUE.PROD_ID, PCEST.QTFRENTELOJA
   ORDER BY JCENDESTOQUE.PROD_ID)
SELECT 'N' AS SELECIONADO,
       PCPRODUT.CODPROD,
       PCPRODUT.DESCRICAO,
       NVL(PCEST.QTESTGER, 0) AS QTD_GERENCIAL,
       NVL(PCEST.QTFRENTELOJA, 0) AS QTD_LOJA,
       NVL(ESTOQUE_ENDERECADO.QTD_END_LOJA, 0) AS QTD_END_LOJA,
       NVL(ESTOQUE_ENDERECADO.QTD_DEPOSITO, 0) AS QTD_DEPOSITO,
       NVL(ESTOQUE_ENDERECADO.QTD_TOTAL, 0) AS QTD_ENDERECADO,
       ABS(NVL(PCEST.QTESTGER, 0) -
           (NVL(ESTOQUE_ENDERECADO.QTD_DEPOSITO, 0) +
            NVL(ESTOQUE_ENDERECADO.QTD_END_LOJA, 0))) AS QTD_DIFERENCA,
       (CASE
         WHEN NVL(PCEST.QTESTGER, 0) = NVL(ESTOQUE_ENDERECADO.QTD_TOTAL, 0) THEN
          'ESTOQUES IGUAIS'
         WHEN NVL(PCEST.QTESTGER, 0) > NVL(ESTOQUE_ENDERECADO.QTD_TOTAL, 0) THEN
          'ESTOQUE GERENCIADO MAIOR'
         ELSE
          'ESTOQUE LOJA + ENDEREÇADO MAIOR'
       END) AS STATUS
  FROM PCPRODUT
  LEFT JOIN PCEST
    ON PCEST.CODFILIAL = '1'
   AND PCEST.CODPROD = PCPRODUT.CODPROD
  LEFT JOIN ESTOQUE_ENDERECADO
    ON ESTOQUE_ENDERECADO.PROD_ID = PCPRODUT.CODPROD
 WHERE (NVL(PCEST.QTESTGER, 0) <> 0 OR
       NVL(ESTOQUE_ENDERECADO.QTD_TOTAL, 0) <> 0)
   AND PCEST.CODFILIAL = '1'