WITH ENDERECAMENTO AS --TABELAS DE ENDEREÇOS
 (SELECT A.FILIAL_ID     AS CODFILIAL,
         A.CODIGO        AS DEP,
         B.CODIGO        AS RUA,
         C.DESCRICAO     AS LADO,
         D.CODIGO        AS PREDIO,
         E.CODIGO        AS NIVEL,
         F.CODIGO        AS APTO,
         F.ID            AS APTO_ID,
         F.TIPO_ENDERECO AS TIPO, -- ADICIONADO O TIPO_ENDEREÇO POIS O ELE É O QUE DEFINE SE É PICKING, AVARIA..
         F.AEREO
    FROM JCENDAPTO F
   INNER JOIN JCENDDEPOSITO A
      ON F.DEPOSITO_ID = A.ID
   INNER JOIN JCENDRUA B
      ON F.RUA_ID = B.ID
   INNER JOIN JCENDLADO C
      ON F.LADO_ID = C.ID
   INNER JOIN JCENDPREDIO D
      ON F.PREDIO_ID = D.ID
   INNER JOIN JCENDNIVEL E
      ON F.NIVEL_ID = E.ID
   WHERE F.ATIVO = 'S'),
ESTOQUE_AVARIADO AS
 (SELECT G.APTO_ID,
         E.AEREO,
         E.CODFILIAL,
         E.DEP,
         E.RUA,
         E.LADO,
         E.PREDIO,
         E.NIVEL,
         E.APTO,
         G.PROD_ID   AS CODPROD,
         P.DESCRICAO,
         G.QTD       AS QT_ENDERECADO
    FROM JCENDESTOQUE G
    LEFT JOIN ENDERECAMENTO E
      ON G.APTO_ID = E.APTO_ID
    LEFT JOIN PCPRODUT P
      ON G.PROD_ID = P.CODPROD
   WHERE E.TIPO = 0) -- ALTERADO PARA TIPO PARA PEGAR A CATEGORIA DO ENDEREÇO CADASTRADO NA 9862 ASSIM NÃO FICA RESTRITO A APENAS O PREDIO 99
SELECT *
  FROM (SELECT A.CODFILIAL,
               A.CODPROD,
               A.DESCRICAO,
               SUM(A.QT_ENDERECADO) AS QT_ENDERECADO,
               E.QTINDENIZ,
               E.QTESTGER,
               NVL(E.QTFRENTELOJA, 0) AS QTLOJA
          FROM ESTOQUE_AVARIADO A
          LEFT JOIN PCEST E
            ON A.CODPROD = E.CODPROD
           AND A.CODFILIAL = E.CODFILIAL
         WHERE A.CODFILIAL IN (1)
         GROUP BY A.CODFILIAL,
                  A.CODPROD,
                  A.DESCRICAO,
                  E.QTINDENIZ,
                  E.QTESTGER,
                  E.QTFRENTELOJA)
 WHERE QT_ENDERECADO <> QTINDENIZ
