SELECT C.FILIAL_ID,
       D.CODIGO,
       D.DESCRICAO,
       A.PROD_ID,
       B.DESCRICAO,
       B.CODAUXILIAR,
       SUM(A.QTD) AS QT_TOTAL
  FROM JCENDESTOQUE A, PCPRODUT B, JCENDAPTO C, JCENDDEPOSITO D
 WHERE A.PROD_ID = B.CODPROD
   AND A.APTO_ID = C.ID
   AND C.DEPOSITO_ID = D.ID
   AND D.CODIGO = 4
   AND C.FILIAL_ID = 1
 GROUP BY C.FILIAL_ID, D.CODIGO, D.DESCRICAO, A.PROD_ID, B.DESCRICAO, B.CODAUXILIAR
