SELECT B.CODPROD,
       P.DESCRICAO,
       E.CODDEVOL CODDEVOL_ATUAL,
       D.MOTIVO MOTIVO_ATUAL,
       (E.QTBLOQUEADA - E.QTINDENIZ) QTBLOQUEADA_ATUAL,
       B.DTDESBLOQUEIO,
       B.QTDESBLOQUEADA,
       B.QTBLOQUEADAANT,
       B.QTBLOQUEADA,
       B.QTDESBLOQUEADAANT,
       B.QTINDENIZ,
       B.QTINDENIZANT,
       B.CODDEVOL,
       B.OBS,
       B.CODFUNCDESBLOQUEIO AS CODFUNC,
       E.NOME_GUERRA,
       B.PROGRAMA
  FROM PCLOGDESBLOQUEIO B
 INNER JOIN PCEST E ON E.CODFILIAL = B.CODFILIAL
   AND E.CODPROD = B.CODPROD
  LEFT JOIN PCPRODUT P ON B.CODPROD = P.CODPROD
  LEFT JOIN PCEMPR E ON B.CODFUNCDESBLOQUEIO = E.MATRICULA
  LEFT JOIN PCTABDEV D ON E.CODDEVOL = D.CODDEVOL
 WHERE TO_DATE (B.DTDESBLOQUEIO, 'DD/MM/YYYY') >= TRUNC (SYSDATE) - 10
   AND (E.QTBLOQUEADA - E.QTINDENIZ) > 0
   AND B.CODDEVOL IN (
    38, 43, 46, 49
)
     /*RESERVAS DE ESTOQUE*/
   AND E.CODDEVOL NOT IN (
    38, 43, 46, 49
)
 ORDER BY DTDESBLOQUEIO DESC