------ ANÁLISE DO SITE CORPORATIVO ------
SELECT F.CODFILIAL,
       P.CODFORNEC,
       N.FORNECEDOR,
       F.CODPROD,
       P.DESCRICAO,
       T.PVENDA,
       DBMS_LOB.SUBSTR(W.DESCRICAOLONGA, 4000, 1) AS DESCRICAOLONGA,
       F.ENVIARFORCAVENDAS,
       P.OBS,
       P.OBS2,
       P.DTEXCLUSAO
  FROM PCPRODFILIAL F, PCPRODUT P, ESTPRODUTOWEB W, PCFORNEC N, PCTABPR T
 WHERE F.CODPROD = P.CODPROD
   AND W.CODPROD = F.CODPROD
   AND N.CODFORNEC = P.CODFORNEC
   AND T.CODPROD = P.CODPROD
   AND T.NUMREGIAO = 6
   AND F.CODFILIAL = 6
   AND F.ENVIARFORCAVENDAS = 'S'
   AND COALESCE(P.OBS, 'X') <> 'PV'
   AND W.NOMEECOMMERCE IS NOT NULL
   AND P.DTEXCLUSAO IS NULL
   ORDER BY N.FORNECEDOR;