/*Análise pedidos corporativos não embrulhados*/
SELECT C.DATA,
       C.NUMPED,
       C.CONDVENDA AS TIPO,
       C.CODCLI,
       T.FANTASIA AS NOME_FANTASIA,
       R.DESCRICAO AS REDE,
       C.VLATEND,
       C.OBSENTREGA1
  FROM PCPEDC C
  LEFT JOIN PCCLIENT T ON C.CODCLI = T.CODCLI
  LEFT JOIN PCREDECLIENTE R ON T.CODREDE = R.CODREDE
 WHERE C.CODUSUR = 14
   AND C.POSICAO NOT IN (
    'F', 'C'
)
   AND NVL (C.ESC_PEDIDOEMBRULHADO, 'N') = 'N'
   AND C.DATA >= TRUNC (SYSDATE) - 90
 ORDER BY T.CODREDE,
          C.DATA;
/