WITH PRODUTO_ESTOQUE AS (
    SELECT E.CODFILIAL,
           F.CODFORNECPRINC,
           P.CODPROD,
           P.IMPORTADO,
           P.CODMARCA,
           M.MARCA,
           E.CUSTOPROXIMACOMPRA
      FROM PCPRODUT P
     INNER JOIN PCPRODFILIAL D ON P.CODPROD = D.CODPROD
      LEFT JOIN PCFORNEC F ON P.CODFORNEC = F.CODFORNEC
      LEFT JOIN PCEST E ON P.CODPROD = E.CODPROD
       AND D.CODFILIAL = E.CODFILIAL
      LEFT JOIN PCMARCA M ON P.CODMARCA = M.CODMARCA
     WHERE D.ENVIARFORCAVENDAS = 'S'
       AND P.CODMARCA NOT IN (
        225
    )
     /*RETIRAR KITS*/
       AND NVL (E.CUSTOPROXIMACOMPRA, 0) <> 0
)
SELECT *
  FROM (
    SELECT P.CODFILIAL,
           P.CODPROD,
           P.DESCRICAO,
           E.IMPORTADO,
           E.CODMARCA,
           E.MARCA,
           P.NUMREGIAO,
           P.REGIAO,
           P.MARGEM AS MIDEAL,
           ROUND (P.MARGEMPRECIFICACAO, 2) AS MPRECO,
           ROUND (E.CUSTOPROXIMACOMPRA, 4) AS CUSTOPROXCOMPRA,
           ROUND (P.CUSTOSELECIONADO, 4) AS CUSTOLIQAPLIC,
           ROUND (P.CUSTOSELECIONADO / (1 - ((P.CODICMTAB + P.MARGEM) / 100)), 4) AS PSUGERIDO,
           ROUND (P.PVENDA, 4) AS PVENDA
      FROM VW_PRECIFICACAO P
     INNER JOIN PRODUTO_ESTOQUE E ON P.CODPROD = E.CODPROD
       AND P.CODFILIAL = E.CODFILIAL
     WHERE P.CODFILIAL = 6
       AND P.NUMREGIAO IN (
        6
    )
     ORDER BY P.CODPROD,
              P.NUMREGIAO
)
 WHERE MIDEAL <> MPRECO
    OR CUSTOPROXCOMPRA <> CUSTOLIQAPLIC
    OR PSUGERIDO <> PVENDA;
/