SELECT TO_DATE(T.DTCADASTRO, 'DD/MM/YY') DTCADASTRO, T.CODCLI, T.CLIENTE
  FROM PCCLIENT T
 WHERE T.DTEXCLUSAO IS NULL
   AND T.CODUSUR1 = 14
   AND (NOT EXISTS (SELECT CODCLI
                      FROM PCTABPRCLI
                     WHERE CODCLI = T.CODCLI
                       AND CODFILIALNF = 5) OR NOT EXISTS
        (SELECT CODCLI
           FROM PCTABPRCLI
          WHERE CODCLI = T.CODCLI
            AND CODFILIALNF = 6))
 ORDER BY DTCADASTRO DESC;
