SELECT C.CODREDE,
       C.CODCLI,
       C.CLIENTE,
       C.FANTASIA,
       C.CGCENT,
       C.ENDERENT END_FATURA,
       C.MUNICENT MUNICIPIO_FATURA,
       C.BAIRROENT BAIRRO_FATURA,
       C.CEPENT CEP_FATURA,
       C.ENDERCOM END_ENTREGA,
       C.MUNICCOM MUNICIPIO_ENTREGA,
       C.BAIRROCOM BAIRRO_ENTREGA,
       C.CEPCOM CEP_ENTREGA
  FROM PCCLIENT C
  WHERE CODREDE = 723;