SELECT C.CODREDE,
       C.CODCLI,
       C.CLIENTE,
       C.FANTASIA,
       C.CGCENT,
       REGEXP_REPLACE(C.CGCENT, '([0-9]{2})([0-9]{3})([0-9]{3})([0-9]{4})', '\1.\2.\3/\4-') AS FORMAT_CGCENT,
       C.ENDERENT END_FATURA,
       C.MUNICENT MUNICIPIO_FATURA,
       C.BAIRROENT BAIRRO_FATURA,
       C.CEPENT CEP_FATURA,
       C.ENDERCOM END_ENTREGA,
       C.MUNICCOM MUNICIPIO_ENTREGA,
       C.BAIRROCOM BAIRRO_ENTREGA,
       C.NUMEROCOM NUMERO_ENTREGA,
       C.COMPLEMENTOCOM COMPLE_ENTREGA,
       C.CEPCOM CEP_ENTREGA
  FROM PCCLIENT C
  WHERE CODREDE = 643;