SELECT C.CODFILIAL,
       C.NUMPED,
       C.NUMNOTA,
       C.POSICAO,
       P.CODREDE,
       R.DESCRICAO AS REDE,
       P.CODCLI,
       P.CLIENTE,
       C.CONDVENDA,
       C.VLTOTAL,
       C.VLATEND
  FROM PCPEDC C,
       PCCLIENT P,
       PCREDECLIENTE R
 WHERE P.CODREDE = R.CODREDE
   AND P.CODCLI = C.CODCLI
   AND R.CODREDE = 917
   AND C.DATA >= TO_DATE ('01/09/2020', 'DD/MM/YYYY')
   AND C.POSICAO NOT IN (
    'C'
);
/