WITH ALTERACAODADOS AS
 (SELECT CODIGO, 
         COUNT(TABELA) AS QT_ALTERACAO,
         MAX(DATA) AS DATA_ALTERACAO
    FROM PCLOGALTERACAODADOS
   WHERE TABELA = 'PCPEDI'
     AND OBSERVACOES NOT LIKE '%Liberação%' --PARA NÃO CONSIDERAR LIBERACAO DE PEDIDO COMO ALTERAÇÃO
   GROUP BY CODIGO)
SELECT A.CODFILIAL,
       A.NUMPED,
       A.CODCLI,
       B.CLIENTE,
       B.CODREDE,
       C.DESCRICAO,
       (CASE
         WHEN D.QT_ALTERACAO > 0 THEN
          'QT ALTERADA'
         ELSE
          NULL
       END) AS ALTERACAO,
       D.DATA_ALTERACAO,
       (CASE
         WHEN (A.DTINICIALCHECKOUT IS NULL AND A.DTFINALCHECKOUT IS NULL) THEN
          'PEDIDO NÃO INICIADO'
         WHEN (A.DTINICIALCHECKOUT IS NOT NULL AND
              A.DTFINALCHECKOUT IS NOT NULL) THEN
          'PEDIDO CONFERIDO'
         WHEN (A.DTINICIALCHECKOUT IS NOT NULL AND A.DTFINALCHECKOUT IS NULL) THEN
          'PEDIDO SENDO CONFERIDO'
         ELSE
          'CHAMAR TI'
       END) AS SITUACAO,
       DECODE(A.POSICAO,
              'F',
              'FATURADO',
              'P',
              'PENDENTE - VER 336',
              'C',
              'CANCELADO',
              'B',
              'BLOQUEADO - VER 336',
              'M',
              'MONTADO',
              'L',
              'LIBERADO') AS POSICAO,
       A.DTINICIALCHECKOUT,
       A.DTFINALCHECKOUT
  FROM PCPEDC A
 INNER JOIN PCCLIENT B
    ON A.CODCLI = B.CODCLI
  LEFT JOIN PCREDECLIENTE C
    ON B.CODREDE = C.CODREDE
  LEFT JOIN ALTERACAODADOS D
    ON A.NUMPED = D.CODIGO
 WHERE A.DATA BETWEEN '01-JAN-2019' AND '31-DEC-2019'
   AND B.CODREDE = 522
  -- AND A.NUMPED = 14005105
  -- AND B.CODCLI = 9590
;