SELECT A.DATA,
       B.CODFILIAL,
       A.NUMPED,
       B.POSICAO,
       B.CONDVENDA,
       A.CODPROD,
       P.DESCRICAO,
       A.CODFILIALRETIRA,
       A.QT,
       A.PVENDA,
       A.CODUSUR
  FROM PCPEDI A,
       PCPEDC B,
       PCPRODUT P,
       PCCLIENT C
 WHERE ((((A.CODFILIALRETIRA IN (
    5, 6
)
    OR (B.CODFILIAL = 1
   AND A.CODFILIALRETIRA NOT IN (
    4
)))
    OR (B.CODFILIAL = 2
   AND A.CODFILIALRETIRA NOT IN (
    3
)))
    OR (B.CODFILIAL = 6
   AND A.CODFILIALRETIRA NOT IN (
    3, 4
)))
    OR (B.CODFILIAL = 5
   AND A.CODFILIALRETIRA NOT IN (
    3, 4
)))
   AND A.NUMPED = B.NUMPED
   AND A.CODPROD = P.CODPROD
   AND B.CONDVENDA <> '7'
   AND A.DATA > TRUNC (SYSDATE) - 10
   AND A.CODUSUR = 14
   AND C.CODCLI = B.CODCLI
 ORDER BY DATA;
/