WITH PEDIDO_VENDA AS (
    SELECT I.NUMPED,
           I.CODPROD,
           SUM (I.QT) AS QT_PEDIDO
      FROM PCPEDI I
     INNER JOIN PCPEDC C ON I.NUMPED = C.NUMPED
     WHERE C.POSICAO NOT IN (
        'F', 'C'
    )
       AND C.CODUSUR = 14
     GROUP BY I.NUMPED,
              I.CODPROD
), PEDIDO_CONFERIDO AS (
    SELECT NUMPED,
           CODPROD,
           SUM (QTCONF) AS QT_CONFERIDO
      FROM PCITEMLOTECONFERIDO
     GROUP BY NUMPED,
              CODPROD
)
SELECT NUMPED,
       CODPROD,
       DESCRICAO,
       QT_PEDIDO,
       QT_CONFERIDO,
       DIF
  FROM (
    SELECT I.NUMPED,
           I.CODPROD,
           P.DESCRICAO,
           I.QT_PEDIDO,
           NVL (C.QT_CONFERIDO, 0) AS QT_CONFERIDO,
           (I.QT_PEDIDO - NVL (C.QT_CONFERIDO, 0)) AS DIF
      FROM PEDIDO_VENDA I
      LEFT JOIN PEDIDO_CONFERIDO C ON I.NUMPED = C.NUMPED
       AND I.CODPROD = C.CODPROD
      LEFT JOIN PCPRODUT P ON I.CODPROD = P.CODPROD
)
 WHERE DIF < 0;