----PRODUTOS BLOQUEADOS SEM PEDIDO DE VENDA - CORPORATIVO

SELECT E.CODFILIAL,
       E.CODPROD,
       P.DESCRICAO,
       E.QTBLOQUEADA,
       E.QTESTGER
  FROM PCEST E
  LEFT JOIN PCPRODUT P ON P.CODPROD = E.CODPROD
  LEFT JOIN PCPEDI I ON I.CODPROD = E.CODPROD
                    AND I.CODFILIALRETIRA = E.CODFILIAL
                    AND I.POSICAO NOT IN ('C', 'F')
                    AND I.CODUSUR = 14
 WHERE E.CODDEVOL = 38
   AND E.QTBLOQUEADA > 0
   AND E.CODFILIAL = '11'
   AND I.CODPROD IS NULL;
