SELECT F.CODFILIAL,
       P.CODPRODMASTER CODPROD_PAI,
       (
           SELECT DESCRICAO
             FROM PCPRODUT
            WHERE CODPROD = P.CODPRODMASTER
       ) DESCRICAO_PAI,
       P.CODPROD,
       P.DESCRICAO,
       F.ENVIARFORCAVENDAS ENVIARFORCAVENDAS_238,
       E.QTESTGER
  FROM PCPRODUT P,
       PCPRODFILIAL F,
       PCEST E
 WHERE P.CODPROD = F.CODPROD
   AND E.CODFILIAL = F.CODFILIAL
   AND E.CODPROD = F.CODPROD
   AND P.CODPROD <> P.CODPRODMASTER
   AND F.CODFILIAL = 6
   AND F.ENVIARFORCAVENDAS = 'S'
 ORDER BY P.CODPRODMASTER;
/