SELECT C.CODCLI,
       C.CLIENTE,
       C.USACRECLIFAT,
       U.NOME VENDEDOR
  FROM PCCLIENT C,
       PCUSUARI U,
       PCSUPERV V
 WHERE C.CODUSUR1 = U.CODUSUR
   AND U.CODSUPERVISOR = V.CODSUPERVISOR
   AND V.CODGERENTE = 2
   AND C.USACRECLIFAT = 'S';