/*---------VERIFICAR SOMATORIA DE PEDIDOS PERTENCENTE A MESMA REDE DE CLIENTE---------*/
SELECT C.CODFILIAL,
       C.CODPLPAG,
       SUM (C.VLTOTAL) VALOR_TOTAL,
       COUNT (C.NUMPED) TOTAL_PEDIDO
  FROM PCPEDC C,
       PCCLIENT P,
       PCREDECLIENTE R
 WHERE P.CODREDE = R.CODREDE
   AND P.CODCLI = C.CODCLI
   AND R.CODREDE = 132
   AND C.DATA >= '01-OCT-2018'
   AND C.POSICAO NOT IN (
    'F', 'C'
)
 /*  AND C.CODPLPAG = 188*/
 GROUP BY C.CODFILIAL,
          C.CODPLPAG;
/

/*---------VERIFICAR SOMATORIA DE ITENS DIGITADOS NOS PEDIDOS PERTENCENTE A MESMA REDE DE CLIENTE---------*/
SELECT C.CODPROD,
       T.DESCRICAO,
       C.CODFILIALRETIRA,
       SUM (C.QT) QT_TOTAL,
       SUM (C.PVENDA * QT) TOTAL_VENDA
  FROM PCCLIENT P,
       PCREDECLIENTE R,
       PCPEDI C,
       PCPRODUT T,
       PCPEDC E
 WHERE P.CODREDE = R.CODREDE
   AND P.CODCLI = C.CODCLI
   AND T.CODPROD = C.CODPROD
   AND E.NUMPED = C.NUMPED
   AND R.CODREDE = 132
   AND C.DATA >= '01-OCT-2018'
   AND C.POSICAO NOT IN (
    'F', 'C'
)
/*   AND E.CODPLPAG = 188*/
 GROUP BY C.CODPROD,
          T.DESCRICAO,
          C.CODFILIALRETIRA;
/

/*---------VERIFICAR SOMATORIA DE ITENS POR CLIENTE DIGITADOS NOS PEDIDOS PERTENCENTE A MESMA REDE DE CLIENTE---------*/
SELECT C.CODCLI,
       P.FANTASIA,
       C.CODPROD,
       T.DESCRICAO,
       C.CODFILIALRETIRA,
       SUM (C.QT) QT_TOTAL,
       SUM (C.PVENDA * QT) TOTAL_VENDA
  FROM PCCLIENT P,
       PCREDECLIENTE R,
       PCPEDI C,
       PCPRODUT T,
       PCPEDC E
 WHERE P.CODREDE = R.CODREDE
   AND P.CODCLI = C.CODCLI
   AND T.CODPROD = C.CODPROD
   AND E.NUMPED = C.NUMPED
   AND R.CODREDE = 132
   AND C.DATA >= '01-OCT-2018'
   AND C.POSICAO NOT IN (
    'F', 'C'
)
/*   AND E.CODPLPAG = 188*/
 GROUP BY C.CODCLI,
          P.FANTASIA,
          C.CODPROD,
          T.DESCRICAO,
          C.CODFILIALRETIRA;
/

 /*---------VERIFICAR VALOR TOTAL PEDIDO POR CLIENTE DIGITADOS NOS PEDIDOS PERTENCENTE A MESMA REDE DE CLIENTE---------*/
SELECT E.CODCLI,
       P.FANTASIA,
       E.NUMPED,
       E.NUMPEDCLI,
       ROUND (SUM (I.QT * (I.PVENDA - I.ST)), 2) PLIQUIDO,
       E.VLTOTAL,
       E.VLATEND
  FROM PCCLIENT P,
       PCREDECLIENTE R,
       PCPEDC E,
       PCPEDI I
 WHERE P.CODREDE = R.CODREDE
   AND P.CODCLI = E.CODCLI
   AND E.NUMPED = I.NUMPED
      /* AND R.CODREDE = 726*/
   AND E.DATA >= '01-OCT-2018'
   AND E.POSICAO NOT IN (
    'F', 'C'
)
/*   AND E.CODPLPAG = 188*/
 GROUP BY E.CODCLI,
          P.FANTASIA,
          E.NUMPED,
          E.NUMPEDCLI,
          E.VLTOTAL,
          E.VLATEND
 ORDER BY E.CODCLI;
/

 /*---------VERIFICAR ITENS DO PEDIDO ---------*/
SELECT I.NUMPED,
       I.DATA,
       I.CODPROD,
       P.DESCRICAO,
       I.QT,
       I.PVENDA,
       I.ST
  FROM PCPEDI I,
       PCPRODUT P
 WHERE I.CODPROD = P.CODPROD
   AND I.NUMPED = 14005241;
/