WITH PEDIDOTV7 AS (
    SELECT I.NUMPED,
           I.CODPROD,
           NVL (SUM (I.QT), 0) AS QT_TV7
      FROM PCPEDI I
     GROUP BY I.NUMPED,
              I.CODPROD
), PEDIDOTV8 AS (
    SELECT C.NUMPEDENTFUT,
           I.CODPROD,
           I.CODFILIALRETIRA AS FILIALRETIRA_TV8,
           NVL (SUM (I.QT), 0) AS QT_TV8
      FROM PCPEDI I
      JOIN PCPEDC C ON I.NUMPED = C.NUMPED
     GROUP BY C.NUMPEDENTFUT,
              I.CODPROD,
              I.CODFILIALRETIRA
)
SELECT C.DATA,
       C.CODFILIAL,
       C.NUMPED, 
       C.CONDVENDA,
       C.CODCLI,
       CT.CLIENTE,
       T.CODPROD,
       P.DESCRICAO,
       T.QT_TV7,
       V.QT_TV8,
       (T.QT_TV7 - V.QT_TV8) AS DIF,
       V.FILIALRETIRA_TV8
  FROM PEDIDOTV7 T
  JOIN PCPRODUT P ON T.CODPROD = P.CODPROD
  JOIN PCPEDC C ON C.NUMPED = T.NUMPED
  JOIN PCCLIENT CT ON CT.CODCLI = C.CODCLI
  LEFT JOIN PEDIDOTV8 V ON T.NUMPED = V.NUMPEDENTFUT
   AND T.CODPROD = V.CODPROD
 WHERE (T.QT_TV7 - V.QT_TV8) <> 0
 AND C.DATA > TO_DATE('01/06/2022', 'DD/MM/YYYY');
