SELECT DISTINCT F.CODFILIAL,
                F.CODPROD,
                ROUND ((NVL (F.CUSTOREP, 0) * ((100 - NVL (F.PERCDESC, 0)) / 100)), 4) PBRUTO_240
  FROM PCPRODFILIAL F
 INNER JOIN PCPRODUT P ON F.CODPROD = P.CODPROD
  LEFT JOIN PCFORNEC R ON P.CODFORNEC = R.CODFORNEC
 WHERE P.CODPROD = P.CODPRODMASTER
   AND P.DTEXCLUSAO IS NULL
   AND F.CODFILIAL = 2
   AND R.CODFORNECPRINC = 2;
/