SELECT DISTINCT E.CODFILIAL,
                E.CODPROD,
                NVL (E.QTESTGER, 0) AS QTGERENCIAL,
                NVL (E.QTPEDIDA, 0) AS QTCOMPRA,
                (NVL (E.QTESTGER, 0) - NVL (E.QTBLOQUEADA, 0)) AS QTDISPONIVEL,
                (NVL (E.QTBLOQUEADA, 0) - NVL (E.QTINDENIZ, 0)) AS QTBLOQ,
                NVL (E.CODDEVOL, 0) AS CODBLOQUEIO
  FROM PCEST E
 INNER JOIN VIEW_JC_PCPRODUT P ON E.CODPROD = P.CODPRODMASTER
 WHERE E.CODFILIAL = 2
   AND P.CODFORNECPRINC = 2;
/