SELECT M.DTMOV,
       M.CODPROD,
       SUM (M.QTCONT) AS QT_TOTAL
  FROM PCMOV M
  LEFT JOIN VIEW_JC_VENDEDOR V ON M.CODUSUR = V.CODUSUR
 WHERE M.CODFISCAL IN (
    1202, 1411, 2202, 2411
)
   AND V.CODGERENTE IN (
    1, 8, 9
)
   AND M.DTCANCEL IS NULL
 GROUP BY M.DTMOV,
          M.CODPROD;
/