SELECT DISTINCT P.CODPRODMASTER AS CODPROD,
                P.CODFAB,
                P.DESCRICAO,
                P.CODAUXILIAR,
                L.DESCRICAO AS LINHA_PRODUTO,
                P.QTUNITCX
  FROM PCPRODUT P
  LEFT JOIN PCLINHAPROD L ON P.CODLINHAPROD = L.CODLINHA
  LEFT JOIN PCFORNEC F ON P.CODFORNEC = F.CODFORNEC
 WHERE F.CODFORNECPRINC = 2
   AND P.DTEXCLUSAO IS NULL
	 AND NVL(P.OBS,'00') NOT IN ('FL')
   AND P.CODPROD = P.CODPRODMASTER;
/
