SELECT T.CODFILIAL,
       T.NUMTRANSENT,
       T.DTMOV,
       T.NUMPED,
       T.CODFORNEC,
       F.FORNECEDOR,
       T.CODPROD,
       P.DESCRICAO,
       T.CODOPER,
       T.NUMNOTA,
       T.QT,
       (I.QTPEDIDA - I.QTENTREGUE) QTPENDENTE
  FROM PCMOVPREENT T
  LEFT JOIN PCPRODUT P ON T.CODPROD = P.CODPROD
  LEFT JOIN PCFORNEC F ON T.CODFORNEC = F.CODFORNEC
  LEFT JOIN PCITEM I ON I.CODPROD = T.CODPROD
   AND I.NUMPED = T.NUMPED
 WHERE F.CODFORNECPRINC = 2
   AND NOT EXISTS (
    SELECT NUMTRANSENT
      FROM PCMOV
     WHERE NUMTRANSENT = T.NUMTRANSENT
);
/