SELECT DISTINCT T.CODFILIAL,
       T.NUMTRANSENT,
       T.DTMOV,
       T.NUMPED,
       T.CODFORNEC,
       F.FORNECEDOR,
       T.CODPROD,
       P.DESCRICAO,
       T.CODOPER,
       T.NUMNOTA,
       T.QT
  FROM PCMOVPREENT T
  LEFT JOIN PCPRODUT P ON T.CODPROD = P.CODPROD
  LEFT JOIN PCFORNEC F ON T.CODFORNEC = F.CODFORNEC
 WHERE F.CODFORNECPRINC = 2
   AND NOT EXISTS (
    SELECT NUMTRANSENT
      FROM PCMOV
     WHERE NUMTRANSENT = T.NUMTRANSENT
);
/
