SELECT *
  FROM (SELECT P.CODPROD,
               P.DESCRICAO,
               (CASE
                 WHEN P.OBS = 'PR' THEN
                  'PROMOCIONAL'
                 ELSE
                  'NORMAL'
               END) AS OBSERVACAO,
               P.CODFAB,
               P.CODAUXILIAR,
               M.MARCA,
               L.DESCRICAO AS LINHA,
               (T.NUMREGIAO || ' - ' || R.REGIAO) AS REGIAO,
               ROUND(T.PVENDA, 4) AS PVENDA
          FROM PCPRODUT P
          LEFT JOIN PCFORNEC O ON O.CODFORNEC = P.CODFORNEC
          LEFT JOIN PCMARCA M ON P.CODMARCA = M.CODMARCA
          LEFT JOIN PCPRODFILIAL F ON P.CODPROD = F.CODPROD
          LEFT JOIN PCLINHAPROD L ON P.CODLINHAPROD = L.CODLINHA
          LEFT JOIN PCTABPR T ON P.CODPROD = T.CODPROD
                             AND T.NUMREGIAO IN (1, 3, 4)
         INNER JOIN PCREGIAO R ON T.NUMREGIAO = R.NUMREGIAO
         WHERE P.DTEXCLUSAO IS NULL
           AND NVL(P.OBS2, '0') NOT IN ('FL')
              /*RETIRAR PRODUTOS FORA DE LINHA*/
           AND F.CODFILIAL = 2
           AND O.CODFORNECPRINC = 2
           AND F.ENVIARFORCAVENDAS = 'S')
PIVOT(SUM(PVENDA)
   FOR REGIAO IN('1 - SP DISTRIBUICAO' AS SPDISTRIBUICAO,
                 '4 - 12% DISTRIBUICAO' AS PRDISTRIBUICAO,
                 '3 - 7% DISTRIBUICAO' AS ESDISTRIBUICAO))
 ORDER BY OBSERVACAO, LINHA;
 /