CREATE OR REPLACE VIEW VIEW_JC_PCPREST_DESDCARTAO AS
/*RETIRAR DESDOBRAMENTO QUE TIVERAM SUA VENDA CANCELADA APOS O DESDOBRAMENTO*/
    WITH PREST_AGRUPADA AS (
        SELECT NUMTRANSVENDA
          FROM PCPREST
         GROUP BY NUMTRANSVENDA
        HAVING MAX (DTCANCEL) IS NULL
    ),
/*PARA TERMOS A INFORMACAO DO CODCONTAB DOS CARTOES/ MKT NA TABELA PCCLIENT*/ 
PCCLIENT_CONTABIL AS (
        SELECT B.CODCOB,
               C.CODCONTAB
          FROM PCCOB B
         INNER JOIN PCCLIENT C ON C.CODCLI = B.CODCLICC
         WHERE B.CARTAO = 'S'
    ),
/*INFORMACOES DOS CODCLI DOS MARKETPLACES E CARTOES PARA DEPOIS DESCONSIDERARMOS ESSAS DUPLICATAS DESDOBRADAS*/ 
CLIENTE_MKTPLACE AS (
        SELECT DISTINCT (CODCLICC) AS CODCLICC
          FROM PCCOB
         WHERE CARTAO = 'S'
    )
    SELECT T.CODFILIAL,
           T.CODCOBORIG,
           T.CODCOB,
           L.CODCONTAB,
           T.DTDESD AS DATA,
           T.NUMTRANSVENDA,
           SUM (T.VALOR) AS VALOR,
           /*PARA TRAZERMOS A INFORMAÇÃO DO CLIENTE DA VENDA ORIGINAL*/
           ('NF ' || T.DUPLIC || ' - ' || C.CLIENTE) AS HISTORICO
      FROM PCPREST T
     INNER JOIN PREST_AGRUPADA G ON T.NUMTRANSVENDA = G.NUMTRANSVENDA
     INNER JOIN PCCLIENT_CONTABIL L ON T.CODCOBORIG = L.CODCOB
      LEFT JOIN PCCLIENT C ON T.CODCLI = C.CODCLI
      LEFT JOIN CLIENTE_MKTPLACE K ON T.CODCLI = K.CODCLICC
     WHERE T.NUMTRANS IS NULL
       AND T.DTDESD IS NOT NULL
       AND T.DTPAG IS NOT NULL
       AND NVL(T.VALORESTORNO,0) = 0 
       --AND T.DTESTORNO IS NULL
        /* NÃO CONSIDERAR DUPLICATAS JÁ DESDOBRADAS PARA O CARTÃO/MRT QUE TENHAM SOFRIDO NOVO DESDOBRAMENTO*/
       AND K.CODCLICC IS NULL
     /*PARA QUE O VALOR DAS PARCELAS SEJA AGRUPADO NA FORMA DE SOMA, DANDO O MESMO VALOR DA NOTA FATURADA SE NÃO HOUVER USO DO CREDITO NA VENDA*/
     GROUP BY T.CODFILIAL,
              T.CODCOBORIG,
              T.CODCOB,
              L.CODCONTAB,
              T.DTDESD,
              T.NUMTRANSVENDA,
              ('NF ' || T.DUPLIC || ' - ' || C.CLIENTE);
/
