CREATE OR REPLACE VIEW VIEW_JC_PREST_COB AS
    SELECT T.CODCOB
      FROM PCCOB T
     WHERE T.CODCOB NOT IN (
        'DESD', 'TR', 'BNF', 'CHI', 'CANC', 'PERD', 'DEVT', 'DEVP', 'ESTR'
    );
    /*NAO TRAZER DESDOBRAMENTO, TROCO, BONIFICACAO, CHEQUE IRREGULAR, CANCELAMENTO, 
    (JUROS NAO DUPLICA NA PCLANC), CONVENIO, PERDAS, DESC*/
/
