CREATE OR REPLACE VIEW VIEW_JC_PREST_BANCOS AS
    SELECT M.NUMTRANS,
           M.CODBANCO
      FROM PCMOVCR M 
   /*PARA NAO TRAZER LANCAMENTO DUPLICADOS OU TRIPILICADOS QUE TENHA SIDO ESTORNADOS NA PCMOVCR*/
     WHERE M.DTESTORNO IS NULL
       AND M.CODBANCO NOT IN (
        17, 20, 35, 50, 52, 53, 54
    );