CREATE OR REPLACE VIEW VIEW_JC_TAXA_CARTAO_LOJA AS
    WITH 
    /*SOMENTE CLIENTES MARCADOS COMO CARTÃO DE LOJA FISICA*/ CLIENTES_CARTAOLOJA AS (
        SELECT DISTINCT (CODCLICC) AS CODCLI
          FROM PCCOB
         WHERE CODCLICC IS NOT NULL
           AND CODCONTACC = 620105
    )
    SELECT T.CODFILIAL,
           T.DATA,
           T.DTVENC,
           T.DTEMISSAO,
           T.NUMNOTA,
           T.CPF_CNPJ,
           NVL(T.VLJUROS,0) VLJUROS,
           NVL(T.VLMULTA,0) VLMULTA,
           NVL(T.VALORDESC,0) VALORDESC,
           T.DUPLICATA,
           T.CODBANCO,
           T.CODCONTABILBANCO,
           T.VALORDESC AS VALOR,
           T.CODCONTAB,
           T.CODCLI,
           T.CODCOB,
           T.CODUSUR,
           T.NUMTRANS,
           T.NUMTRANSVENDA,
           T.CARTORIO,
           T.PROTESTO,
           'T' AS TIPO,
           ('TX CARTAO DUP ' || T.DUPLICATA || ' - ' || TRIM (T.CLIENTE)) AS HISTORICO
      FROM VIEW_JC_BASE_PREST T
     INNER JOIN CLIENTES_CARTAOLOJA L ON T.CODCLI = L.CODCLI
 /*SOMENTE LANCAMENTOS COM DESCONTO*/
     WHERE (T.VALORDESC > 0);
/
