CREATE OR REPLACE VIEW VIEW_JC_PREST_COB AS
    SELECT (T.DUPLIC || '-' || T.PREST || '-' || T.NUMTRANSVENDA) AS CODDUPLIC
      FROM PCPREST T
     WHERE T.CODCOB NOT IN (
        'DESD', 'TR', 'BNF', 'CHI', 'CANC', 'CONV', 'PERD', 'DEVT', 'DEVP', 'ESTR'
    );
/