CREATE OR REPLACE VIEW VIEW_BI_CONTAS_RECEBER_ACC AS
WITH BASE_CONTAS_RECEBER AS
 (SELECT DATA,
         CODCLI,
         SUM(VALOR_EMITIDO) VALOR_EMITIDO,
         SUM(VALOR_PAGO) VALOR_PAGO
    FROM ((SELECT R.DTEMISSAO DATA,
                  R.CODCLI,
                  SUM(R.VALOR) VALOR_EMITIDO,
                  0 VALOR_PAGO
             FROM VIEW_BI_CONTAS_RECEBER R
            GROUP BY R.CODCLI, R.DTEMISSAO) UNION
          (SELECT R.DTPAG DATA,
                  R.CODCLI,
                  0 VALOR_EMITIDO,
                  SUM(R.VALOR) VALOR_PAGO
             FROM VIEW_BI_CONTAS_RECEBER R
            WHERE R.DTPAG IS NOT NULL
            GROUP BY R.CODCLI, R.DTPAG))
   GROUP BY CODCLI, DATA),
CONTAS_RECEBER_ACUMULADO AS
 (SELECT DATA,
         CODCLI,
         VALOR_EMITIDO,
         VALOR_PAGO,
         SUM(VALOR_EMITIDO) OVER(PARTITION BY CODCLI ORDER BY TRUNC(DATA) ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) VALOREMITIDO_ACC,
         SUM(VALOR_PAGO) OVER(PARTITION BY CODCLI ORDER BY TRUNC(DATA) ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) VALORPAG_ACC
    FROM BASE_CONTAS_RECEBER)
SELECT TO_DATE(DATA, 'DD/MM/YYYY') DATA,
       CODCLI,
       VALOR_EMITIDO,
       VALOR_PAGO,
       VALOREMITIDO_ACC,
       VALORPAG_ACC,
       (VALOREMITIDO_ACC - VALORPAG_ACC) SALDO
  FROM CONTAS_RECEBER_ACUMULADO
 ORDER BY CODCLI, DATA;
/
