CREATE OR REPLACE VIEW VIEW_JC_DESC_CONCEDIDOS AS
    WITH 
    /*SOMENTE COBRANÇAS MARCADOS COMO CARTÃO*/ COBRANCAS_CARTAOMKT AS (
        SELECT CODCOB
          FROM PCCOB
         WHERE CODCLICC IS NOT NULL
    ), 
    /*SOMENTE CLIENTES MARCADOS COMO CARTÃO*/ CLIENTES_CARTAOMKT AS (
        SELECT DISTINCT (CODCLICC) AS CODCLI
          FROM PCCOB
         WHERE CODCLICC IS NOT NULL
    )
    SELECT T.CODDUPLIC,
           T.CODFILIAL,
           T.DATA,
           T.DTVENC,
           T.DTEMISSAO,
           T.DUPLICATA,
           T.CODBANCO,
           T.CODCONTABILBANCO,
           T.VALORDESC AS VALOR,
           T.CODCONTAB,
           T.CODCLI,
           T.CODCOB,
           T.CODUSUR,
           T.NUMTRANS,
           T.NUMTRANSVENDA,
           T.CARTORIO,
           T.PROTESTO,
           'D' AS TIPO,
           ('DESC DUP ' || T.DUPLICATA || ' - ' || TRIM (T.CLIENTE)) AS HISTORICO
      FROM VIEW_JC_BASE_PREST T
     INNER JOIN VIEW_JC_PREST_COB C ON T.CODCOB = C.CODCOB
     INNER JOIN VIEW_JC_PREST_BANCOS B ON T.CODBANCO = B.CODBANCO
      LEFT JOIN COBRANCAS_CARTAOMKT L ON T.CODCOB = L.CODCOB
      LEFT JOIN CLIENTES_CARTAOMKT R ON T.CODCLI = R.CODCLI
 /*SOMENTE LANCAMENTOS COM DESCONTO*/
     WHERE (T.VALORDESC > 0)
       AND T.CODCOB NOT IN (
        'JUR', 'DESC', 'CARC', 'CADB'
    )
  /*RETIRAR COBRANCAS E CLIENTES DE MKT E LOJA*/
       AND L.CODCOB IS NULL
       AND R.CODCLI IS NULL;
/