WITH ESTOQUE_F1 AS (
    SELECT E.CODPROD AS CODPROD_F1,
           E.DTULTENT AS DTULTENT_F1,
           ROUND (NVL (E.VALORULTENT, 0), 2) AS VLULTENT_F1,
           (NVL (E.QTESTGER, 0) - NVL (E.QTRESERV, 0) - NVL (E.QTBLOQUEADA, 0)) AS QTDISP_F1
      FROM PCEST E
     WHERE E.CODFILIAL = 1
), ESTOQUE_F8 AS (
    SELECT E.CODPROD AS CODPROD_F8,
           E.DTULTENT AS DTULTENT_F8,
           ROUND (NVL (E.VALORULTENT, 0), 2) AS VLULTENT_F8,
           (NVL (E.QTESTGER, 0) - NVL (E.QTRESERV, 0) - NVL (E.QTBLOQUEADA, 0)) AS QTDISP_F8
      FROM PCEST E
     WHERE E.CODFILIAL = 8
), ESTOQUE_F2 AS (
    SELECT E.CODPROD AS CODPROD_F2,
           ROUND (NVL (E.VALORULTENT, 0), 2) AS VLULTENT_F2,
           (NVL (E.QTESTGER, 0) - NVL (E.QTRESERV, 0) - NVL (E.QTBLOQUEADA, 0)) AS QTDISP_F2
      FROM PCEST E
     WHERE E.CODFILIAL = 2
), ESTOQUE_F7 AS (
    SELECT E.CODFILIAL AS CODFILIAL_F7,
           E.CODPROD AS CODPROD_F7,
           (NVL (E.QTESTGER, 0) - NVL (E.QTRESERV, 0) - NVL (E.QTBLOQUEADA, 0)) AS QTDISP_F7
      FROM PCEST E
     WHERE E.CODFILIAL = 7
), VENDAS_ULT_4MESES AS (
    SELECT *
      FROM (
        SELECT M.CODFILIAL,
               M.CODPROD,
               M.DTMOV,
               SUM (M.QT) AS QTVENDIDA
          FROM PCMOV M
         WHERE M.CODFISCAL IN (
            5102, 5109, 5119, 5120, 5403, 5405, 6102, 6108, 6403, 6119, 6120
        )
           AND M.DTMOV >= TRUNC (SYSDATE) - 120
           AND M.CODFILIAL IN (
            1, 7, 8
        )
         GROUP BY M.CODFILIAL,
                  M.CODPROD,
                  M.DTMOV
    ) PIVOT (
        SUM (QTVENDIDA)
    AS QTVENDIDA, MAX (DTMOV) AS DTULTVENDA
        FOR CODFILIAL
        IN (1 AS "F1", 7 AS "F7", 8 AS "F8")
    )
)
SELECT P.CODPROD,
       P.DESCRICAO,
       O.DTULTENT_F1,
       V.F1_DTULTVENDA AS DTULTVENDA_F1,
       O.VLULTENT_F1,
       O.QTDISP_F1,
       NVL (V.F1_QTVENDIDA, 0) QTVENDIDA_F1,
       B.QTDISP_F8,
       NVL (V.F8_QTVENDIDA, 0) QTVENDIDA_F8,
       A.QTDISP_F2,
       F.QTDISP_F7,
       NVL (V.F7_QTVENDIDA, 0) QTVENDIDA_F7
  FROM PCEST E
 INNER JOIN PCPRODUT P ON E.CODPROD = P.CODPROD
 INNER JOIN ESTOQUE_F7 F ON E.CODPROD = F.CODPROD_F7
   AND E.CODFILIAL = F.CODFILIAL_F7
  LEFT JOIN ESTOQUE_F1 O ON E.CODPROD = O.CODPROD_F1
  LEFT JOIN ESTOQUE_F8 B ON E.CODPROD = B.CODPROD_F8
  LEFT JOIN ESTOQUE_F2 A ON E.CODPROD = A.CODPROD_F2
  LEFT JOIN VENDAS_ULT_4MESES V ON E.CODPROD = V.CODPROD
 WHERE (O.QTDISP_F1 >= 1
    OR B.QTDISP_F8 >= 1)
   AND F.QTDISP_F7 <= 0
   AND A.QTDISP_F2 <= 0
 ORDER BY NVL (V.F7_QTVENDIDA, 0) DESC,
          O.QTDISP_F1 DESC;
/