WITH ESTOQUE_F1 AS (
    SELECT E.CODPROD AS CODPROD_F1,
           E.DTULTENT AS DTULTENT_F1,
           ROUND (NVL (E.VALORULTENT, 0), 2) AS VLULTENT_F1,
           (NVL (E.QTESTGER, 0) - NVL (E.QTRESERV, 0) - NVL (E.QTBLOQUEADA, 0)) AS QTDISP_F1,
           (NVL (E.QTVENDMES, 0) + NVL (E.QTVENDMES1, 0) + NVL (E.QTVENDMES2, 0) + NVL (E.QTVENDMES3, 0)) AS QTVENDIDA_F1
      FROM PCEST E
     WHERE E.CODFILIAL = 1
), ESTOQUE_F8 AS (
    SELECT E.CODPROD AS CODPROD_F8,
           E.DTULTENT AS DTULTENT_F8,
           ROUND (NVL (E.VALORULTENT, 0), 2) AS VLULTENT_F8,
           (NVL (E.QTESTGER, 0) - NVL (E.QTRESERV, 0) - NVL (E.QTBLOQUEADA, 0)) AS QTDISP_F8,
           (NVL (E.QTVENDMES, 0) + NVL (E.QTVENDMES1, 0) + NVL (E.QTVENDMES2, 0) + NVL (E.QTVENDMES3, 0)) AS QTVENDIDA_F8
      FROM PCEST E
     WHERE E.CODFILIAL = 8
), ESTOQUE_F2 AS (
    SELECT E.CODPROD AS CODPROD_F2,
           ROUND (NVL (E.VALORULTENT, 0), 2) AS VLULTENT_F2,
           (NVL (E.QTESTGER, 0) - NVL (E.QTRESERV, 0) - NVL (E.QTBLOQUEADA, 0)) AS QTDISP_F2
      FROM PCEST E
     WHERE E.CODFILIAL = 2
), ESTOQUE_F7 AS (
    SELECT E.CODFILIAL AS CODFILIAL_F7,
           E.CODPROD AS CODPROD_F7,
           (NVL (E.QTESTGER, 0) - NVL (E.QTRESERV, 0) - NVL (E.QTBLOQUEADA, 0)) AS QTDISP_F7,
           (NVL (E.QTVENDMES, 0) + NVL (E.QTVENDMES1, 0) + NVL (E.QTVENDMES2, 0) + NVL (E.QTVENDMES3, 0)) AS QTVENDIDA_F7
      FROM PCEST E
     WHERE E.CODFILIAL = 7
)
SELECT P.CODPROD,
       P.DESCRICAO,
       O.DTULTENT_F1,
       O.VLULTENT_F1,
       O.QTDISP_F1,
       O.QTVENDIDA_F1,
       B.QTDISP_F8,
       B.QTVENDIDA_F8,
       A.QTDISP_F2,
       F.QTDISP_F7,
       F.QTVENDIDA_F7
  FROM PCEST E
 INNER JOIN PCPRODUT P ON E.CODPROD = P.CODPROD
 INNER JOIN ESTOQUE_F7 F ON E.CODPROD = F.CODPROD_F7
   AND E.CODFILIAL = F.CODFILIAL_F7
  LEFT JOIN ESTOQUE_F1 O ON E.CODPROD = O.CODPROD_F1
  LEFT JOIN ESTOQUE_F8 B ON E.CODPROD = B.CODPROD_F8
  LEFT JOIN ESTOQUE_F2 A ON E.CODPROD = A.CODPROD_F2
 WHERE (O.QTDISP_F1 >= 1
    OR B.QTDISP_F8 >= 1)
   AND F.QTDISP_F7 <= 0
   AND A.QTDISP_F2 <= 0
 ORDER BY F.QTVENDIDA_F7 DESC,
          O.QTDISP_F1 DESC;
/