WITH VENDAS_ULT_4MESES AS
 (SELECT M.CODFILIAL,
         M.CODPROD,
         MAX(M.DTMOV) AS DTULTVENDA,
         SUM(M.QT) AS QTVENDIDA
    FROM PCMOV M
   WHERE M.CODFISCAL IN
         (5102, 5109, 5119, 5120, 5403, 5405, 6102, 6108, 6403, 6119, 6120)
     AND M.DTMOV >= TRUNC(SYSDATE) - 120
     AND M.CODFILIAL IN (1, 7, 8, 12, 13)
   GROUP BY M.CODFILIAL, M.CODPROD),
ESTOQUE_F7 AS
 (SELECT E.CODPROD AS CODPROD_F7,
         E.DTULTENT AS DTULTENT_F7,
         MAX(V.DTULTVENDA) AS DTULTVENDA_F7,
         ROUND(NVL(E.VALORULTENT, 0), 2) AS VLULTENT_F7,
         (NVL(E.QTESTGER, 0) - NVL(E.QTRESERV, 0) - NVL(E.QTBLOQUEADA, 0)) AS QTDISP_F7,
         NVL(SUM(V.QTVENDIDA), 0) AS QTVENDIDA_F7
    FROM PCEST E
    LEFT JOIN VENDAS_ULT_4MESES V ON E.CODPROD = V.CODPROD
                                 AND E.CODFILIAL = V.CODFILIAL
   WHERE E.CODFILIAL = 7
     AND (NVL(E.QTESTGER, 0) - NVL(E.QTRESERV, 0) - NVL(E.QTBLOQUEADA, 0)) > 0
   GROUP BY E.CODPROD,
            E.DTULTENT,
            E.VALORULTENT,
            E.QTESTGER,
            E.QTRESERV,
            E.QTBLOQUEADA),
ESTOQUE_F2 AS
 (SELECT E.CODPROD AS CODPROD_F2,
         ROUND(NVL(E.VALORULTENT, 0), 2) AS VLULTENT_F2,
         (NVL(E.QTESTGER, 0) - NVL(E.QTRESERV, 0) - NVL(E.QTBLOQUEADA, 0)) AS QTDISP_F2
    FROM PCEST E
   WHERE E.CODFILIAL = 2
     AND (NVL(E.QTESTGER, 0) - NVL(E.QTRESERV, 0) - NVL(E.QTBLOQUEADA, 0)) > 0),
ESTOQUE_LOJAATUAL AS
 (SELECT E.CODFILIAL AS CODFILIAL_LOJAATUAL,
         E.CODPROD AS CODPROD_LOJAATUAL,
         E.DTULTENT AS DTULTEN_LOJAATUAL,
         V.DTULTVENDA AS DTULTVENDA_LOJAATUAL,
         NVL(E.QTBLOQUEADA, 0) - NVL(E.QTINDENIZ, 0) QTBLOQ_LOJAATUAL,
         (NVL(E.QTESTGER, 0) - NVL(E.QTRESERV, 0) - NVL(E.QTBLOQUEADA, 0)) AS QTDISP_LOJAATUAL,
         NVL(V.QTVENDIDA, 0) AS QTVENDIDA_LOJAATUAL
    FROM PCEST E
    LEFT JOIN VENDAS_ULT_4MESES V ON E.CODPROD = V.CODPROD
                                 AND E.CODFILIAL = V.CODFILIAL
   WHERE E.CODFILIAL = (&CODFILIAL_LOJA_ANALISAR)),
TRANSFERENCIA_PARA_LOJA_ATUAL AS
 (SELECT M.CODPROD, M.QT
    FROM PCMOV M
    LEFT JOIN PCNFENT E ON M.NUMTRANSVENDA = E.NUMTRANSVENDAORIG
   WHERE M.DTCANCEL IS NULL
     AND M.CODOPER = 'ST'
     AND M.STATUS = 'AB'
     AND M.CODFILIAL IN ('7', '2')
        -- AND M.CODCLI IN (&CODCLIENTE_LOJA_ANALISAR) 
     AND M.DTMOV >= '01-OCT-2023'
     AND E.NUMTRANSVENDAORIG IS NULL),
PEDIDO_TRANSF_LOJA_ATUAL AS
 (SELECT I.CODPROD, SUM(I.QT) QT
    FROM PCPEDI I
    LEFT JOIN PCPEDC C ON C.NUMPED = I.NUMPED
   WHERE C.POSICAO NOT IN ('C', 'F')
     AND C.CONDVENDA = 10
     AND C.CODFILIAL IN ('7', '2')
  -- AND C.CODCLI IN (&CODCLIENTE_LOJA_ANALISAR) 
   GROUP BY I.CODPROD)
SELECT P.CODPROD,
       P.DESCRICAO,
       P.CODMARCA,
       M.MARCA,
       F.DTULTEN_LOJAATUAL,
       F.DTULTVENDA_LOJAATUAL,
       (CASE
         WHEN VLULTENT_F7 IS NULL THEN
          VLULTENT_F2
         ELSE
          VLULTENT_F7
       END) VLULTENT_F7_F2,
       (NVL(F.QTBLOQ_LOJAATUAL, 0) + NVL(T.QT, 0) + NVL(P.QT, 0)) QTBLOQ_LOJAATUAL,
       O.QTDISP_F7,
       A.QTDISP_F2,
       F.QTDISP_LOJAATUAL,
       O.QTVENDIDA_F7,
       F.QTVENDIDA_LOJAATUAL
  FROM PCEST E
  JOIN PCPRODUT P ON E.CODPROD = P.CODPROD
  JOIN PCMARCA M ON M.CODMARCA = P.CODMARCA
  JOIN ESTOQUE_LOJAATUAL F ON E.CODPROD = F.CODPROD_LOJAATUAL
                          AND E.CODFILIAL = F.CODFILIAL_LOJAATUAL
  LEFT JOIN ESTOQUE_F7 O ON E.CODPROD = O.CODPROD_F7
  LEFT JOIN ESTOQUE_F2 A ON E.CODPROD = A.CODPROD_F2
  LEFT JOIN TRANSFERENCIA_PARA_LOJA_ATUAL T ON T.CODPROD = E.CODPROD
  LEFT JOIN PEDIDO_TRANSF_LOJA_ATUAL P ON P.CODPROD = E.CODPROD
 WHERE (O.QTDISP_F7 > 0 OR A.QTDISP_F2 > 0)
   AND F.QTDISP_LOJAATUAL <= 0
   AND P.CODEPTO NOT IN (97)
   AND P.CODEPTO NOT IN (&CODDEPARTAMENTO_A_DESCONSIDERAR)
   AND E.CODPROD = 163067 
 ORDER BY F.QTVENDIDA_LOJAATUAL DESC, O.QTDISP_F7 DESC, A.QTDISP_F2 DESC;






/************my audit********************/
WITH VENDAS_ULT_4MESES AS
 (SELECT M.CODFILIAL,
         M.CODPROD,
         MAX(M.DTMOV) AS DTULTVENDA,
         SUM(M.QT) AS QTVENDIDA
    FROM PCMOV M
   WHERE M.CODFISCAL IN
         (5102, 5109, 5119, 5120, 5403, 5405, 6102, 6108, 6403, 6119, 6120)
     AND M.DTMOV >= TRUNC(SYSDATE) - 120
     AND M.CODFILIAL IN (1, 7, 8)
   GROUP BY M.CODFILIAL, M.CODPROD),
ESTOQUE_F7 AS
 (SELECT E.CODPROD AS CODPROD_F7,
         E.DTULTENT AS DTULTENT_F7,
         MAX(V.DTULTVENDA) AS DTULTVENDA_F7,
         ROUND(NVL(E.VALORULTENT, 0), 2) AS VLULTENT_F7,
         (NVL(E.QTESTGER, 0) - NVL(E.QTRESERV, 0) - NVL(E.QTBLOQUEADA, 0)) AS QTDISP_F7,
         NVL(SUM(V.QTVENDIDA), 0) AS QTVENDIDA_F7
    FROM PCEST E
    LEFT JOIN VENDAS_ULT_4MESES V ON E.CODPROD = V.CODPROD
                                 AND E.CODFILIAL = V.CODFILIAL
   WHERE E.CODFILIAL = 7
        /*ADICIONADO POR LUCIANO*/
     AND E.QTBLOQUEADA >= 0
  /**/
   GROUP BY E.CODPROD,
            E.DTULTENT,
            E.VALORULTENT,
            E.QTESTGER,
            E.QTRESERV,
            E.QTBLOQUEADA),
ESTOQUE_OUTRALOJA AS
 (SELECT E.CODPROD AS CODPROD_OUTRALOJA,
         (NVL(E.QTESTGER, 0) - NVL(E.QTRESERV, 0) - NVL(E.QTBLOQUEADA, 0)) AS QTDISP_OUTRALOJA,
         NVL(SUM(V.QTVENDIDA), 0) AS QTVENDIDA_OUTRALOJA
    FROM PCEST E
    LEFT JOIN VENDAS_ULT_4MESES V ON E.CODPROD = V.CODPROD
                                 AND E.CODFILIAL = V.CODFILIAL
   WHERE E.CODFILIAL = 1
   GROUP BY E.CODPROD,
            E.DTULTENT,
            E.VALORULTENT,
            E.QTESTGER,
            E.QTRESERV,
            E.QTBLOQUEADA),
ESTOQUE_F2 AS
 (SELECT E.CODPROD AS CODPROD_F2,
         ROUND(NVL(E.VALORULTENT, 0), 2) AS VLULTENT_F2,
         NVL(E.QTESTGER, 0) - NVL(E.QTRESERV, 0) - NVL(E.QTBLOQUEADA, 0) AS QTDISP_F2
    FROM PCEST E
   WHERE E.CODFILIAL = 2
        /*ADICIONADO POR LUCIANO*/
     AND E.QTBLOQUEADA >= 0
  /**/
  ),
ESTOQUE_LOJAATUAL AS
 (SELECT E.CODFILIAL AS CODFILIAL_LOJAATUAL,
         E.CODPROD AS CODPROD_LOJAATUAL,
         E.DTULTENT AS DTULTEN_LOJAATUAL,
         V.DTULTVENDA AS DTULTVENDA_LOJAATUAL,
         NVL(E.QTBLOQUEADA, 0) - NVL(E.QTINDENIZ, 0) QTBLOQ_LOJAATUAL,
         (NVL(E.QTESTGER, 0) - NVL(E.QTRESERV, 0) - NVL(E.QTBLOQUEADA, 0)) AS QTDISP_LOJAATUAL,
         NVL(V.QTVENDIDA, 0) AS QTVENDIDA_LOJAATUAL
    FROM PCEST E
    LEFT JOIN VENDAS_ULT_4MESES V ON E.CODPROD = V.CODPROD
                                 AND E.CODFILIAL = V.CODFILIAL
   WHERE E.CODFILIAL = 8
  /*GROUP BY E.CODFILIAL,
  E.CODPROD,
  E.DTULTENT,
  E.VALORULTENT,
  E.QTESTGER,
  E.QTRESERV,
  E.QTBLOQUEADA,
  V.DTULTVENDA*/
  )
SELECT P.CODPROD,
       P.DESCRICAO, P.CODFORNEC,
       F.DTULTEN_LOJAATUAL,
       F.DTULTVENDA_LOJAATUAL,
       (CASE
         WHEN VLULTENT_F7 IS NULL THEN
          VLULTENT_F2
         ELSE
          VLULTENT_F7
       END) VLULTENT_F7_F2,
       F.QTBLOQ_LOJAATUAL,
       O.QTDISP_F7,
       A.QTDISP_F2,
       B.QTDISP_OUTRALOJA,
       F.QTDISP_LOJAATUAL,
       O.QTVENDIDA_F7,
       B.QTVENDIDA_OUTRALOJA,
       F.QTVENDIDA_LOJAATUAL
  FROM PCEST E
 INNER JOIN PCPRODUT P ON E.CODPROD = P.CODPROD
 INNER JOIN ESTOQUE_LOJAATUAL F ON E.CODPROD = F.CODPROD_LOJAATUAL
                               AND E.CODFILIAL = F.CODFILIAL_LOJAATUAL
  LEFT JOIN ESTOQUE_F7 O ON E.CODPROD = O.CODPROD_F7
  LEFT JOIN ESTOQUE_OUTRALOJA B ON E.CODPROD = B.CODPROD_OUTRALOJA
  LEFT JOIN ESTOQUE_F2 A ON E.CODPROD = A.CODPROD_F2
 WHERE (O.QTDISP_F7 > 0 OR A.QTDISP_F2 > 0)
   AND F.QTDISP_LOJAATUAL <= 0 
				/*PUERICULTURA PESADA -- para loja do shopping acrescentar puericultura leve */
	AND P.CODCATEGORIA NOT IN
			(4000, 4011, 4012, 4013, 4014, 4015, 4030)
		 /*BOLSAS E MOCHILAS , LANCHEIRAS E ESTOJOS*/
	AND P.CODSEC NOT IN (300, 301)
		 /*MATERIAL EMBALAGENS*/
	AND P.CODEPTO NOT IN (97)
		 /*FORNECEDORES*/
	AND P.CODFORNEC NOT IN (9507,9829,9422,4844,9429,7287,9419,9500,9596,9499,9665,9510,9613,9663,9496,9500,10143,10163,9543)
 ORDER BY F.QTVENDIDA_LOJAATUAL DESC, O.QTDISP_F7 DESC, A.QTDISP_F2 DESC;
/
