WITH VENDAS_ULT_4MESES AS (
    SELECT M.CODFILIAL,
           M.CODPROD,
           MAX (M.DTMOV) AS DTULTVENDA,
           SUM (M.QT) AS QTVENDIDA
      FROM PCMOV M
     WHERE M.CODFISCAL IN (
        5102, 5109, 5119, 5120, 5403, 5405, 6102, 6108, 6403, 6119, 6120
    )
       AND M.DTMOV >= TRUNC (SYSDATE) - 120
       AND M.CODFILIAL IN (
        1, 7, 8
    )
     GROUP BY M.CODFILIAL,
              M.CODPROD
), ESTOQUE_F7 AS (
    SELECT E.CODPROD AS CODPROD_F7,
           E.DTULTENT AS DTULTENT_F7,
           ROUND (NVL (E.VALORULTENT, 0), 2) AS VLULTENT_F7,
           (NVL (E.QTESTGER, 0) - NVL (E.QTRESERV, 0) - NVL (E.QTBLOQUEADA, 0)) AS QTDISP_F7,
           NVL (V.QTVENDIDA, 0) AS QTVENDIDA_F7
      FROM PCEST E
      LEFT JOIN VENDAS_ULT_4MESES V ON E.CODPROD = V.CODPROD
       AND E.CODFILIAL = V.CODFILIAL
     WHERE E.CODFILIAL = 7
), ESTOQUE_OUTRALOJA AS (
    SELECT E.CODPROD AS CODPROD_OUTRALOJA,
           (NVL (E.QTESTGER, 0) - NVL (E.QTRESERV, 0) - NVL (E.QTBLOQUEADA, 0)) AS QTDISP_OUTRALOJA,
           NVL (V.QTVENDIDA, 0) AS QTVENDIDA_OUTRALOJA
      FROM PCEST E
      LEFT JOIN VENDAS_ULT_4MESES V ON E.CODPROD = V.CODPROD
       AND E.CODFILIAL = V.CODFILIAL
     WHERE E.CODFILIAL = 8
), ESTOQUE_F2 AS (
    SELECT E.CODPROD AS CODPROD_F2,
           ROUND (NVL (E.VALORULTENT, 0), 2) AS VLULTENT_F2,
           NVL (E.QTESTGER, 0) - NVL (E.QTRESERV, 0) - NVL (E.QTBLOQUEADA, 0) AS QTDISP_F2
      FROM PCEST E
     WHERE E.CODFILIAL = 2
), ESTOQUE_LOJAATUAL AS (
    SELECT E.CODFILIAL AS CODFILIAL_LOJAATUAL,
           E.CODPROD AS CODPROD_LOJAATUAL,
           (NVL (E.QTESTGER, 0) - NVL (E.QTRESERV, 0) - NVL (E.QTBLOQUEADA, 0)) AS QTDISP_LOJAATUAL,
           NVL (V.QTVENDIDA, 0) AS QTVENDIDA_LOJAATUAL
      FROM PCEST E
      LEFT JOIN VENDAS_ULT_4MESES V ON E.CODPROD = V.CODPROD
       AND E.CODFILIAL = V.CODFILIAL
     WHERE E.CODFILIAL = 1
)
SELECT P.CODPROD,
       P.DESCRICAO,
       O.DTULTENT_F7,
       V.DTULTVENDA,
       (
           CASE
               WHEN VLULTENT_F7 IS NULL THEN VLULTENT_F2
               ELSE VLULTENT_F7
           END
       ) VLULTENT_F7_F2,
       O.QTDISP_F7,
       A.QTDISP_F2,
       B.QTDISP_OUTRALOJA,
       F.QTDISP_LOJAATUAL,
       O.QTVENDIDA_F7,
       B.QTVENDIDA_OUTRALOJA,
       F.QTVENDIDA_LOJAATUAL
  FROM PCEST E
 INNER JOIN PCPRODUT P ON E.CODPROD = P.CODPROD
 INNER JOIN ESTOQUE_LOJAATUAL F ON E.CODPROD = F.CODPROD_LOJAATUAL
   AND E.CODFILIAL = F.CODFILIAL_LOJAATUAL
  LEFT JOIN ESTOQUE_F7 O ON E.CODPROD = O.CODPROD_F7
  LEFT JOIN ESTOQUE_OUTRALOJA B ON E.CODPROD = B.CODPROD_OUTRALOJA
  LEFT JOIN ESTOQUE_F2 A ON E.CODPROD = A.CODPROD_F2
       /*PUERICULTURA PESADA -- para loja do shopping acrescentar puericultura leve */
   AND P.CODCATEGORIA NOT IN (
    4000, 4011, 4012, 4013, 4014, 4015, 4030
)
      /*BOLSAS E MOCHILAS , LANCHEIRAS E ESTOJOS*/
   AND P.CODSEC NOT IN (
    300, 301
)
    /*MATERIAL EMBALAGENS*/
   AND P.CODEPTO NOT IN (
    97
)
    /*FORNECEDORES*/
   AND P.CODFORNEC NOT IN (
    9507, 9829, 9422, 4844, 9429, 7287, 9419, 9500, 9596, 9499, 9665, 9510, 9613
)
 WHERE (O.QTDISP_F7 > 0
    OR A.QTDISP_F2 > 0)
   AND F.QTDISP_LOJAATUAL <= 0
 ORDER BY F.QTVENDIDA_LOJAATUAL DESC,
          O.QTDISP_F7 DESC,
          A.QTDISP_F2 DESC;