/*-----------ANÁLISE DE BLOQUEIO E DESBLOQUEIO DO ITEM - ROTINA E MOTIVO --------------*/
SELECT L.DTDESBLOQUEIO,
       L.PROGRAMA,
       L.CODFILIAL,
       L.CODFUNCDESBLOQUEIO FUNC_DESBL,
       E.NOME_GUERRA FUNCIONARIO,
       L.CODPROD,
       P.DESCRICAO,
       L.QTBLOQUEADAANT QTBLOQ_ANT,
       L.QTBLOQUEADA QTBLOQ,
       L.QTDESBLOQUEADA,
       L.QTDESBLOQUEADAANT QTDESBLOQ_ANT,
       L.CODDEVOL,
       V.MOTIVO,
       V.TIPO,
       L.OBS,
       L.QTINDENIZ,
       L.QTINDENIZANT,
       L.NUMTRANSENT
  FROM PCLOGDESBLOQUEIO L,
       PCEMPR E,
       PCTABDEV V,
       PCPRODUT P
 WHERE E.MATRICULA = L.CODFUNCDESBLOQUEIO
   AND P.CODPROD = L.CODPROD
   AND V.CODDEVOL = L.CODDEVOL
   AND L.DTDESBLOQUEIO BETWEEN TO_DATE ('04/12/2020', 'DD/MM/YYYY') AND TO_DATE ('06/12/2022', 'DD/MM/YYYY')
   AND L.CODFILIAL = 2
   AND L.CODPROD = 811403
 ORDER BY L.DTDESBLOQUEIO DESC,
          L.CODPROD;
/

/*-----------MOVIMENTAÇÃO DE BLOQUEIO E DESBLOQUEIO --------------*/
SELECT CODFILIAL,
       DATA,
       CODPROD,
       QTESTANT,
       QTEST,
       QTESTGERANT,
       QTESTGER,
       QTBLOQUEADAANT,
       QTBLOQUEADA,
       QTINDENIZANT,
       QTINDENIZ,
       PROGRAMA,
       USUARIO,
       MAQUINA
  FROM PCLOGESTOQUE
 WHERE CODFILIAL = 2
   AND CODPROD = 110058 
   AND DATA BETWEEN TO_DATE ('10/09/2022', 'DD/MM/YYYY') AND TO_DATE ('15/09/2022', 'DD/MM/YYYY')
 ORDER BY DATA DESC;
/

/*-----------ENCONTRAR O NÚMERO DO BÔNUS REFERENTE A UMA NOTA--------------*/
SELECT NUMBONUS
  FROM PCNFENT
 WHERE NUMNOTA = 77742;
/

/*-----------ANÁLISE DO BÔNUS--------------*/
SELECT B.CODFILIAL,
       B.NUMBONUS,
       B.DATABONUS,
       B.QTNFS,
       B.CODFUNCRM,
       E.NOME FUNCCRM,
       B.CODFUNCBONUS,
       (
           SELECT NOME
             FROM PCEMPR
            WHERE MATRICULA = B.CODFUNCBONUS
       ) FUNCBONUS,
       B.CODFUNCFECHA,
       (
           SELECT NOME
             FROM PCEMPR
            WHERE MATRICULA = B.CODFUNCFECHA
       ) FUNCFECHA,
       B.DTFECHAMENTO
  FROM PCBONUSC B,
       PCEMPR E
 WHERE E.MATRICULA = B.CODFUNCRM
   AND B.NUMBONUS = 3323;
/

/*-----------ANÁLISE ITENS DO BÔNUS--------------*/
SELECT B.NUMBONUS,
       B.CODPROD,
       P.DESCRICAO,
       B.QTNF,
       B.QTENTRADA,
       B.QTAVARIA
  FROM PCBONUSI B,
       PCPRODUT P
 WHERE P.CODPROD = B.CODPROD
   AND B.NUMBONUS = 3323;
/