WITH ESTOQUE_FILIAL AS (
    SELECT E.CODFILIAL,
           E.CODPROD,
           (NVL (E.QTESTGER, 0) - NVL (E.QTBLOQUEADA, 0) - NVL (E.QTRESERV, 0)) AS QTDISPONIVEL,
           (NVL (E.QTBLOQUEADA, 0) - NVL (E.QTINDENIZ, 0)) AS QTBLOQ,
           NVL (E.CODDEVOL, 0) AS CODBLOQ
      FROM PCEST E
     WHERE E.CODFILIAL IN (
        2
    )
)
SELECT P.CODPROD,
       P.DESCRICAO AS PRODUTO,
       E.QTDISPONIVEL,
       E.QTBLOQ,
       E.CODBLOQ,
       T.MOTIVO
  FROM PCPRODUT P
  LEFT JOIN ESTOQUE_FILIAL E ON P.CODPROD = E.CODPROD
  LEFT JOIN PCTABDEV T ON E.CODBLOQ = T.CODDEVOL
 WHERE QTDISPONIVEL <= 15
   AND CODBLOQ = 49
   AND QTBLOQ > 0;
/