SELECT E.CODFILIAL,
       P.CODFORNEC,
       F.FORNECEDOR,
       E.CODPROD,
       P.DESCRICAO,
       E.QTINDENIZ,
       E.MOTIVOBLOQESTOQUE,
       M.CODFILIAL FILIAL_COMPRA,
       M.NUMNOTA NOTA_COMPRA,
       M.QT QT_COMPRA,
       M.CODFORNEC CODFORNEC_COMPRA,
       F2.FORNECEDOR FORNEC_COMPRA,
       M.DTMOV DATA_COMPRA
  FROM PCEST E,
       PCPRODUT P,
       PCFORNEC F,
       PCMOV M,
       PCFORNEC F2
 WHERE P.CODPROD = E.CODPROD
   AND P.CODFORNEC = F.CODFORNEC
   AND M.CODPROD = E.CODPROD
   AND M.CODFILIAL IN (
    1, 2, 7
)
   AND M.CODOPER IN (
    'E'
)
   AND M.DTCANCEL IS NULL
   AND M.CODFORNEC = F2.CODFORNEC
   AND E.QTINDENIZ > 0
 ORDER BY E.CODFILIAL,
          F.FORNECEDOR,
          E.CODPROD,
          F2.CODFORNEC,
          M.DTMOV DESC,
          M.CODFILIAL;
/