WITH ESTOQUEPROD_PAI AS (
    SELECT E.CODFILIAL AS CODFILIAL_PAI,
           E.DTULTENT AS DTULTENT_PAI,
           P.CODPRODMASTER AS COD_PAI,
           P.DESCRICAO AS PRODUTO_PAI,
           E.QTESTGER AS QTESTGER_PAI,
           E.QTRESERV AS QTRESERV_PAI,
           E.QTBLOQUEADA AS QTBLOQUEADA_PAI,
           (E.QTESTGER + E.QTRESERV - E.QTBLOQUEADA) AS ESTOQUE_PAI
      FROM PCEST E
      LEFT JOIN PCPRODUT P ON E.CODPROD = P.CODPROD
     WHERE P.CODPROD = P.CODPRODMASTER
)
SELECT E.CODFILIAL,
       D.DTULTENT_PAI,
       D.COD_PAI,
       D.PRODUTO_PAI,
       D.QTESTGER_PAI,
       D.QTRESERV_PAI,
       D.QTBLOQUEADA_PAI,
       D.ESTOQUE_PAI,
       E.CODPROD,
       P.DESCRICAO,
       E.QTESTGER,
       E.QTRESERV,
       E.QTBLOQUEADA,
       (E.QTESTGER + E.QTRESERV - E.QTBLOQUEADA) ESTOQUE_FILHO
  FROM PCEST E
  LEFT JOIN PCPRODUT P ON E.CODPROD = P.CODPROD
 INNER JOIN ESTOQUEPROD_PAI D ON P.CODPRODMASTER = D.COD_PAI
   AND E.CODFILIAL = D.CODFILIAL_PAI
 WHERE D.COD_PAI <> P.CODPROD
   AND P.DTEXCLUSAO IS NULL
   AND D.ESTOQUE_PAI > 0
   AND E.CODFILIAL = 7
 ORDER BY D.COD_PAI,
          P.CODPROD;
/