WITH HIST_ESTOQUE AS
 (SELECT H.CODFILIAL,
         F.CGC,
         H.DATA,
         H.CODPROD,
         H.CUSTOCONT,
         NVL(H.QTEST, 0) QTEST,
         ROUND(H.QTEST, 3) * ROUND(H.CUSTOCONT, 3) VLESTOQUE,
         H.TIPOMERC,
         H.TIPOMERCDEPTO
    FROM PCHISTEST H
    LEFT JOIN PCFILIAL F ON F.CODIGO = H.CODFILIAL
   WHERE 0 = 0
     AND NVL(H.TIPOMERCDEPTO, 'X') <> 'IM'
     AND NVL(H.TIPOMERCDEPTO, 'X') <> 'CI'
     AND NVL(H.TIPOMERC, 'X') NOT IN ('MC', 'ME', 'PB')
     AND H.DATA = TO_DATE('31/03/2025', 'DD/MM/YYYY') --AND CODFILIAL = 10
     AND ROUND(H.QTEST, 3) > 0
     AND ROUND(H.CUSTOCONT, 3) > 0)

/*SELECT CODFILIAL,
       CODPROD,
       QTEST,
       CUSTOCONT,
       VLESTOQUE
  FROM HIST_ESTOQUE*/

SELECT CODFILIAL,
       CGC,
       ROUND(SUM(VLESTOQUE),2) VLESTOQUE
  FROM HIST_ESTOQUE
 GROUP BY CODFILIAL,
          CGC
 ORDER BY TO_NUMBER(CODFILIAL)
