WITH FRENTELOJAPREENCHIDO AS (
    SELECT CODPROD
      FROM PCEMBALAGEM
     WHERE QTMINGONDOLA IS NOT NULL
       AND QTMAXGONDOLA IS NOT NULL
       AND CODFILIAL = 1
), GRANDESPRODUTOS AS (
    SELECT CODPROD
      FROM PCPRODUT
     WHERE NUMORIGINAL IS NOT NULL
)
SELECT E.CODFILIAL,
       P.CODFORNEC,
       F.FORNECEDOR,
       T.CODPROD,
       P.DESCRICAO,
       T.CODAUXILIAR,
       (NVL (E.QTESTGER, 0) - NVL (E.QTBLOQUEADA, 0) - NVL (E.QTRESERV, 0)) QTDISPONIVEL,
       NVL (E.QTFRENTELOJA, 0) QTFRENTELOJA,
       (NVL (E.QTESTGER, 0) - NVL (E.QTFRENTELOJA, 0) - NVL (E.QTBLOQUEADA, 0)) QTDEPOSITO,
       T.QTMINGONDOLA,
       T.QTMAXGONDOLA,
       A.PVENDA
  FROM PCEST E
 INNER JOIN PCEMBALAGEM T ON E.CODFILIAL = T.CODFILIAL
   AND E.CODPROD = T.CODPROD
 INNER JOIN PCPRODUT P ON T.CODPROD = P.CODPROD
 INNER JOIN PCFORNEC F ON P.CODFORNEC = F.CODFORNEC
  LEFT JOIN PCTABPR A ON T.CODPROD = A.CODPROD
  LEFT JOIN FRENTELOJAPREENCHIDO D ON T.CODPROD = D.CODPROD
  LEFT JOIN GRANDESPRODUTOS G ON T.CODPROD = G.CODPROD
 WHERE E.CODFILIAL = '1'
   AND (NVL (E.QTESTGER, 0) - NVL (E.QTBLOQUEADA, 0) - NVL (E.QTRESERV, 0)) > 0
   AND (NVL (E.QTESTGER, 0) - NVL (E.QTFRENTELOJA, 0) - NVL (E.QTBLOQUEADA, 0)) > 0
   AND (T.QTMINGONDOLA = 0
    OR T.QTMINGONDOLA IS NULL
    OR T.QTMAXGONDOLA = 0
    OR T.QTMAXGONDOLA IS NULL)
   AND P.REVENDA = 'S'
   AND T.UNIDADE <> 'CX'
   AND A.NUMREGIAO = 100
   AND D.CODPROD IS NULL
     /*PARA NAO TRAZER PRODUTOS QUE TENHAM QTMIN OU QTMAX PREENCHIDO*/
   AND G.CODPROD IS NULL
     /*PARA NÃO TRAZER PRODUTOS GRANDES QUE NAO ESTÃO PREENCHIDOS DE PRPOSITO*/
 ORDER BY F.FORNECEDOR,
          P.DESCRICAO;
/