WITH ESTOQUEPROD_PAI AS (
    SELECT E.CODFILIAL AS FILIAL_PAI,
           E.DTULTENT AS DTENT_FILIAL2,
           P.CODPRODMASTER AS COD_PAI,
           P.DESCRICAO AS PRODUTO_PAI,
           (E.QTESTGER - E.QTRESERV - E.QTBLOQUEADA) AS QTDISP_PAI
      FROM PCEST E
      LEFT JOIN PCPRODUT P ON E.CODPROD = P.CODPROD
     WHERE P.CODPROD = P.CODPRODMASTER
       AND E.CODFILIAL = 2
)
SELECT *
  FROM (
    SELECT D.FILIAL_PAI,
           D.COD_PAI,
           D.PRODUTO_PAI,
           D.DTENT_FILIAL2,
           D.QTDISP_PAI,
           E.CODFILIAL AS FILIAL_FILHO,
           E.CODPROD AS COD_FILHO,
           P.DESCRICAO AS PRODUTO_FILHO,
           E.DTULTENT,
           (E.QTESTGER - E.QTRESERV - E.QTBLOQUEADA) AS QTDISPONIVEL
      FROM PCEST E
      LEFT JOIN PCPRODUT P ON E.CODPROD = P.CODPROD
     INNER JOIN ESTOQUEPROD_PAI D ON P.CODPRODMASTER = D.COD_PAI
     WHERE D.COD_PAI <> P.CODPROD
       AND P.DTEXCLUSAO IS NULL
       AND E.CODFILIAL IN (
        1, 7
    )
)
 WHERE QTDISPONIVEL <= 0
   AND QTDISP_PAI > 0
 ORDER BY COD_PAI,
          COD_FILHO,
          FILIAL_FILHO;
/