/*Produtos estoque loja zerado com estoque no depósito*/
WITH FRENTELOJAPREENCHIDO AS (
    SELECT CODPROD
      FROM PCEMBALAGEM
     WHERE QTMINGONDOLA IS NOT NULL
       AND QTMAXGONDOLA IS NOT NULL
       AND CODFILIAL = 1
), GRANDESPRODUTOS AS (
    SELECT CODPROD
      FROM PCPRODUT
     WHERE NUMORIGINAL IS NOT NULL
), PRODUTOSENDERECADOS AS (
    SELECT E.PROD_ID AS CODPROD,
           SUM (E.QTD) QT_ENDERECADO
      FROM JCENDESTOQUE E
     INNER JOIN JCENDAPTO A ON E.APTO_ID = A.ID
     WHERE FILIAL_ID = '1'
       AND A.ATIVO = 'S'
       AND DEPOSITO_ID NOT IN (
        4
    )
     GROUP BY E.PROD_ID
    HAVING SUM (E.QTD) > 0
)
SELECT E.CODFILIAL,
       P.CODFORNEC,
       F.FORNECEDOR,
       E.CODPROD,
       P.DESCRICAO,
       (E.QTESTGER - E.QTBLOQUEADA - E.QTRESERV) QTDISPONIVEL,
       E.QTFRENTELOJA,
       MAX (T.QTMINGONDOLA) QTMINGONDOLA,
       MAX (T.QTMAXGONDOLA) QTMAXGONDOLA,
       A.PVENDA
  FROM PCEST E
 INNER JOIN PCEMBALAGEM T ON E.CODFILIAL = T.CODFILIAL
   AND E.CODPROD = T.CODPROD
 INNER JOIN PCPRODUT P ON T.CODPROD = P.CODPROD
 INNER JOIN PCFORNEC F ON P.CODFORNEC = F.CODFORNEC
 INNER JOIN FRENTELOJAPREENCHIDO D ON T.CODPROD = D.CODPROD
 INNER JOIN PRODUTOSENDERECADOS C ON T.CODPROD = C.CODPROD
  LEFT JOIN PCTABPR A ON T.CODPROD = A.CODPROD
  LEFT JOIN GRANDESPRODUTOS G ON T.CODPROD = G.CODPROD
 WHERE E.CODFILIAL = '1'
   AND (E.QTESTGER - E.QTBLOQUEADA - E.QTRESERV) > 0
   AND E.QTFRENTELOJA <= 0
   AND T.UNIDADE = 'UN'
   AND A.NUMREGIAO = '100'
   AND (T.QTMINGONDOLA IS NOT NULL
   AND T.QTMAXGONDOLA IS NOT NULL)
 GROUP BY E.CODFILIAL,
          P.CODFORNEC,
          F.FORNECEDOR,
          E.CODPROD,
          P.DESCRICAO,
          E.QTESTGER,
          E.QTBLOQUEADA,
          E.QTRESERV,
          E.QTFRENTELOJA,
          A.PVENDA
 ORDER BY F.FORNECEDOR,
          P.DESCRICAO;
/