WITH QTFRENTELOJA_SOMADO AS (
    SELECT P.NUMORIGINAL,
           SUM (QTFRENTELOJA) QTLOJATOTAL
      FROM PCEST E,
           PCPRODUT P
     WHERE E.CODPROD = P.CODPROD
       AND P.NUMORIGINAL IS NOT NULL
     /*SOMENTE PRODUTOS DE FAMILIA*/
       AND E.CODFILIAL = 1
     /*SOMENTE LOJA  */
     GROUP BY P.NUMORIGINAL
)
SELECT B.CODPROD,
       P.NUMORIGINAL,
       P.CODAUXILIAR CODBARRA_203,
       B.CODAUXILIAR CODBARRA_2014,
       P.DESCRICAO,
       (E.QTESTGER - E.QTINDENIZ - E.QTRESERV) AS QTDISP,
       E.QTFRENTELOJA,
       B.QTMINGONDOLA,
       B.QTMAXGONDOLA
       /*,F.QTLOJATOTAL*/
  FROM PCEMBALAGEM B
 INNER JOIN PCEST E ON B.CODFILIAL = E.CODFILIAL
   AND B.CODPROD = E.CODPROD
 INNER JOIN PCPRODUT P ON B.CODPROD = P.CODPROD
 INNER JOIN QTFRENTELOJA_SOMADO F ON P.NUMORIGINAL = F.NUMORIGINAL
 WHERE B.CODFILIAL = 1
   AND (E.QTESTGER - E.QTINDENIZ - E.QTRESERV) > 0
   AND F.QTLOJATOTAL <= 0
 ORDER BY P.NUMORIGINAL;
/