SELECT *
  FROM (SELECT PCEST.RUA,
               PCEST.MODULO,
               PCEST.APTO,
               PCEST.NUMERO,
               PCMOVLOJA.CODFILIAL,
               PCMOVLOJAITEM.CODMOVLOJA,
               PCMOVLOJAITEM.CODPROD,
               PCPRODUT.CODFAB,
               PCEMBALAGEM.CODAUXILIAR,
               PCPRODUT.DESCRICAO,
               PCMOVLOJAITEM.QTLANCAMENTO,
               PCMOVLOJAITEM.QTREGISTRADA,
               PCMOVLOJAITEM.QTFRENTELOJAANT,
               PCMOVLOJAITEM.QTFRENTELOJAATUAL,
               PCMOVLOJAITEM.MOTIVO,
               PCMOVLOJAITEM.CODFUNCAD,
               PCMOVLOJAITEM.DTCADASTRO,
               PCMOVLOJAITEM.CANCELADO,
               PCMOVLOJAITEM.QTCANCEL,
               PCEMPR.NOME FUNC_SOLICITACAO,
               (ROW_NUMBER() OVER(PARTITION BY PCPRODUT.CODPROD ORDER BY
                                  PCEMBALAGEM.QTUNIT,
                                  PCEMBALAGEM.CODAUXILIAR)) AS RNK
          FROM PCMOVLOJAITEM,
               PCPRODUT,
               PCEMPR,
               PCEMBALAGEM,
               PCMOVLOJA,
               PCEST
         WHERE PCMOVLOJAITEM.CODPROD = PCPRODUT.CODPROD
           AND PCMOVLOJAITEM.CODFUNCAD = PCEMPR.MATRICULA(+)
           AND (PCMOVLOJAITEM.CODMOVLOJA IS NULL OR
               PCMOVLOJAITEM.CODMOVLOJA = 25623)
           AND PCMOVLOJA.CODMOVLOJA = PCMOVLOJAITEM.CODMOVLOJA
           AND PCPRODUT.CODPROD = PCEMBALAGEM.CODPROD
           AND PCEMBALAGEM.CODFILIAL = PCMOVLOJA.CODFILIAL
           AND PCEST.CODFILIAL = PCMOVLOJA.CODFILIAL
           AND PCEST.CODPROD = PCMOVLOJAITEM.CODPROD
         ORDER BY PCEST.RUA, PCEST.MODULO, PCEST.APTO, PCEST.NUMERO)
 WHERE RNK = 1
