---- CONSULTA SE PRODUTO TEM CODAUXILIAR CX MASTER ----
SELECT ROWID, p.CODAUXILIAR, P.CODAUXILIAR2, P.* FROM PCPRODUT P WHERE CODPROD = 803124;


---- CONSULTA SE O CAMPO ESTA COMO 'S' SE SIM O PRODUTO É A CX MASTER -----
SELECT ROWID, P.CODPRODANTUTICAD, P.* FROM PCPRODFILIAL P WHERE CODFILIAL= 7 AND CODPROD = 803124;
