CREATE OR REPLACE VIEW VIEW_JC_CLIENTE AS
SELECT C.CODCLI,
       C.CLIENTE,
       C.MUNICENT,
       C.ESTENT,
       C.CGCENT,
       C.CODUSUR1,
       C.DTCADASTRO,
       C.CODPRACA,
       P.PRACA,
       C.FANTASIA,
       C.TIPOFJ,
       C.CODREDE,
       UPPER(R.DESCRICAO) AS REDE,
       (CASE
         WHEN R.DESCRICAO IS NULL THEN
          ('C - ' || C.CODCLI || ' - ' || C.CLIENTE)
         ELSE
          ('R - ' || C.CODREDE || ' - ' || UPPER(R.DESCRICAO))
       END) AS CLIENTE_REDE,
       C.DTBLOQ,
       C.DTPRIMCOMPRA,
       C.BLOQUEIODEFINITIVO,
       C.DTEXCLUSAO,
       C.CODCONTAB
  FROM PCCLIENT C
  LEFT JOIN PCREDECLIENTE R
    ON C.CODREDE = R.CODREDE
  LEFT JOIN PCPRACA P
    ON C.CODPRACA = P.CODPRACA
 WHERE C.CLIENTE IS NOT NULL
 ;