SELECT DTMOV,
       CODMARCA,
       CODUSUR,
       COUNT (CODPROD) AS PEÇAS,
       SUM (VALOR) AS VALOR
  FROM (
    SELECT M.DTMOV,
           P.CODMARCA,
           S.CODUSUR,
           M.CODPROD,
           ROUND (M.QTCONT * (M.PUNITCONT + NVL (M.VLFRETE, 0) + NVL (M.VLOUTROS, 0)), 2) AS VALOR
      FROM PCMOV M
     INNER JOIN PCNFSAID S ON M.NUMTRANSVENDA = S.NUMTRANSVENDA
     INNER JOIN PCPRODUT P ON M.CODPROD = P.CODPROD
      LEFT JOIN VIEW_JC_VENDEDOR V ON S.CODUSUR = V.CODUSUR
     WHERE M.CODFISCAL IN (
        5102, 5109, 5119, 5120, 5403, 5405, 6102, 6108, 6403, 6119, 6120
    )
       AND V.CODGERENTE IN (
        3
    )
       AND M.DTMOV >= TO_DATE ('01/01/2015', 'DD/MM/YYYY')
       AND M.DTCANCEL IS NULL
)
 GROUP BY DTMOV,
          CODMARCA,
          CODUSUR;
/