CREATE OR REPLACE FUNCTION FN_JF_PRECO_VENDA
(
  pCUSTOLIQ IN NUMBER,
  pMARGEM   IN NUMBER,
  pCMV      IN NUMBER
) RETURN NUMBER IS
  vPVENDA NUMBER;
  INDICE  NUMBER:= 1 - (pMARGEM + pCMV);
BEGIN
  IF INDICE = 0 THEN
    vPVENDA := 0;
  ELSE
    vPVENDA := ROUND((pCUSTOLIQ / INDICE), 4);
  END IF;
  RETURN vPVENDA;

END;
