CREATE OR REPLACE FUNCTION FN_JF_VALOR_ICMS_ST
(
  pVALORCOMPRA IN NUMBER,
  pPERCIPI     IN NUMBER,
  pPERCIVA     IN NUMBER,
  pPERCALIQSTRED IN NUMBER,
  pPERCALIQINT IN NUMBER,
  PPERCALIQEXT IN NUMBER
  
) RETURN NUMBER IS
  v_VALORICMSST NUMBER;

  VALORIPI NUMBER := (pVALORCOMPRA * pPERCIPI);
  BASEICMSST NUMBER := (((pVALORCOMPRA + VALORIPI) * pPERCIVA) + (pVALORCOMPRA + VALORIPI));
BEGIN
  IF pPERCALIQSTRED = 0 THEN 
     v_VALORICMSST := ROUND((BASEICMSST * pPERCALIQINT) - (pVALORCOMPRA * pPERCALIQEXT), 4);
  ELSE
     v_VALORICMSST := ROUND((BASEICMSST * pPERCALIQINT) - (pVALORCOMPRA * pPERCALIQSTRED), 4);
  END IF;
  RETURN v_VALORICMSST;

END;
