CREATE OR REPLACE FUNCTION FN_JF_BASE_ICMS_ST
(
  pVALORCOMPRA IN NUMBER,
  pPERCIPI     IN NUMBER,
  pPERCIVA     IN NUMBER
) RETURN NUMBER IS
  v_BASEICMSST NUMBER;

  VALORIPI NUMBER := (pVALORCOMPRA * pPERCIPI);
BEGIN

  v_BASEICMSST := ROUND(((pVALORCOMPRA + VALORIPI) * pPERCIVA) + (pVALORCOMPRA + VALORIPI),6);
  RETURN v_BASEICMSST;

END;
