CREATE OR REPLACE FUNCTION FN_JF_CUSTO_LIQ
(
  pVALORCOMPRA   IN NUMBER,
  pBASEICMS      IN NUMBER,
  pPERCICMS      IN NUMBER,
  pPERCIPI       IN NUMBER,
  pPERCPIS       IN NUMBER,
  pPERCCOFINS    IN NUMBER,
  pBASEPISCOFINS IN NUMBER,
  pVALORICMSST   IN NUMBER,
  pVALORBRUTO    IN NUMBER
) RETURN NUMBER IS
  v_CUSTOLIQ  NUMBER;
  VALORIPI    NUMBER := (pVALORCOMPRA * pPERCIPI);
  VALORPIS    NUMBER := (pBASEPISCOFINS * pPERCPIS);
  VALORCOFINS NUMBER := (pBASEPISCOFINS * pPERCCOFINS);
  VALORICMS   NUMBER := (pBASEICMS * pPERCICMS);

BEGIN
  IF pVALORICMSST > 0 THEN
    v_CUSTOLIQ := ROUND(pVALORBRUTO - VALORPIS - VALORCOFINS, 4);
  ELSE
    v_CUSTOLIQ := ROUND(pVALORBRUTO + pVALORICMSST - VALORICMS - VALORPIS -
                        VALORCOFINS,
                        4);
  END IF;
  RETURN v_CUSTOLIQ;

END;
