CREATE OR REPLACE FUNCTION FN_JF_SOMADESCONTO
(
  PDESC1  IN NUMBER,
  PDESC2  IN NUMBER,
  PDESC3  IN NUMBER,
  PDESC4  IN NUMBER,
  PDESC5  IN NUMBER,
  PDESC6  IN NUMBER,
  PDESC7  IN NUMBER,
  PDESC8  IN NUMBER,
  PDESC9  IN NUMBER,
  PDESC10 IN NUMBER
) RETURN NUMBER IS
  VDESC_TOTAL NUMBER;
BEGIN
  VDESC_TOTAL := 1 - ((1 - PDESC1 / 100) * (1 - PDESC2 / 100) *
                 (1 - PDESC3 / 100) * (1 - PDESC4 / 100) *
                 (1 - PDESC5 / 100) * (1 - PDESC6 / 100) *
                 (1 - PDESC7 / 100) * (1 - PDESC8 / 100) *
                 (1 - PDESC9 / 100) * (1 - PDESC10 / 100));
  RETURN VDESC_TOTAL;

END;
