CREATE OR REPLACE FUNCTION FN_JF_BASE_ICMS_ST
(
  pVALORCOMPRA IN NUMBER,
  pPERCIPI     IN NUMBER,
  pPERCIVA     IN NUMBER
) RETURN NUMBER IS
  v_BASEICMSST NUMBER;

  VALORIPI NUMBER := (pVALORCOMPRA * pPERCIPI);
BEGIN

  v_BASEICMSST := (((pVALORCOMPRA + VALORIPI) * pPERCIVA) +
                  (pVALORCOMPRA + VALORIPI));
  RETURN v_BASEICMSST;

END;
