CREATE OR REPLACE FUNCTION FN_JF_VALOR_BRUTO
(
  pVALORCOMPRA IN NUMBER,
  pPERCIPI     IN NUMBER,
  pVALORICMSST IN NUMBER
  
) RETURN NUMBER IS
  v_VALORBRUTO NUMBER;

  VALORIPI NUMBER := (pVALORCOMPRA * pPERCIPI);

BEGIN
  v_VALORBRUTO := ROUND((pVALORCOMPRA + VALORIPI + pVALORICMSST), 4);
  RETURN v_VALORBRUTO;

END;
