CREATE OR REPLACE FUNCTION FN_JF_MARGEM_PRECO
(
  pCUSTOLIQ IN NUMBER,
  pPVENDA   IN NUMBER,
  pCMV      IN NUMBER
) RETURN NUMBER IS
  vMARGEM      NUMBER;
  PERCCUSTOLIQ NUMBER;

BEGIN
  IF NVL(pPVENDA, 0) = 0 THEN
    PERCCUSTOLIQ := 0;
  ELSE
    PERCCUSTOLIQ := (pCUSTOLIQ / pPVENDA);
  END IF;
  vMARGEM := ROUND(1 - (PERCCUSTOLIQ + pCMV), 6);
  RETURN vMARGEM;

END;
