CREATE OR REPLACE VIEW VIEW_JC_PEDIDO_PEND_DISTRIBUICAO AS

  SELECT C.CODCLIREDE,
         C.CLIENTEREDE,
         V.CODSUPERVISOR,
         V.SUPERVISOR,
         V.CODUSUR,
         V.VENDEDOR,
         SUM(P.PVENDA) VLPENDENTE
    FROM JEFFERSON.BI_SINC_PEDIDO_VENDA P
    LEFT JOIN JEFFERSON.BI_SINC_VENDEDOR V ON V.CODUSUR = P.CODUSUR
    LEFT JOIN JEFFERSON.BI_SINC_CLIENTE C ON C.CODCLI = P.CODCLI
   WHERE P.POSICAO NOT IN ('F', 'C')
     AND V.CODGERENTE IN (1, 8, 9, 10)
   GROUP BY C.CODCLIREDE,
            C.CLIENTEREDE,
            V.CODSUPERVISOR,
            V.SUPERVISOR,
            V.CODUSUR,
            V.VENDEDOR;
