SELECT S.CODGERENTE,
       G.NOMEGERENTE,
       COUNT(C.NUMPED) PED_FATURADO_HOJE,
       SUM(VLTOTAL) VALOR_FATURADO_HOJE,
       (SELECT COUNT(PCPEDC.NUMPED)
          FROM PCPEDC, PCSUPERV, PCGERENTE
         WHERE PCPEDC.CODSUPERVISOR = PCSUPERV.CODSUPERVISOR
           AND PCSUPERV.CODGERENTE = PCGERENTE.CODGERENTE
           AND PCGERENTE.CODGERENTE = S.CODGERENTE
           AND PCGERENTE.CODGERENTE IN (3, 4)
           AND PCPEDC.POSICAO IN ('B', 'P')) PED_PENDENTES,
       (SELECT SUM(PCPEDC.VLTOTAL)
          FROM PCPEDC, PCSUPERV, PCGERENTE
         WHERE PCPEDC.CODSUPERVISOR = PCSUPERV.CODSUPERVISOR
           AND PCSUPERV.CODGERENTE = PCGERENTE.CODGERENTE
           AND PCGERENTE.CODGERENTE = S.CODGERENTE
           AND PCGERENTE.CODGERENTE IN (3, 4)
           AND PCPEDC.POSICAO IN ('B', 'P')) VALOR_PENDENTE,
       (SELECT COUNT(PCPEDC.NUMPED)
          FROM PCPEDC, PCSUPERV, PCGERENTE
         WHERE PCPEDC.CODSUPERVISOR = PCSUPERV.CODSUPERVISOR
           AND PCSUPERV.CODGERENTE = PCGERENTE.CODGERENTE
           AND PCGERENTE.CODGERENTE = S.CODGERENTE
           AND PCGERENTE.CODGERENTE IN (3, 4)
           AND PCPEDC.POSICAO IN ('L')) PED_LIBERADO,
       (SELECT SUM(PCPEDC.VLTOTAL)
          FROM PCPEDC, PCSUPERV, PCGERENTE
         WHERE PCPEDC.CODSUPERVISOR = PCSUPERV.CODSUPERVISOR
           AND PCSUPERV.CODGERENTE = PCGERENTE.CODGERENTE
           AND PCGERENTE.CODGERENTE = S.CODGERENTE
           AND PCGERENTE.CODGERENTE IN (3, 4)
           AND PCPEDC.POSICAO IN ('L')) VALOR_LIBERADO
  FROM PCPEDC C, PCSUPERV S, PCGERENTE G
WHERE C.CODSUPERVISOR = S.CODSUPERVISOR
   AND G.CODGERENTE = S.CODGERENTE
   AND S.CODGERENTE IN (3, 4)
   AND C.POSICAO = 'F'
   AND DTFAT = TRUNC(SYSDATE)
GROUP BY S.CODGERENTE, G.NOMEGERENTE, C.POSICAO;/


------------ORDEM DOS PEDIDOS PENDENTES---------
SELECT C.CODFILIAL,
       C.CODFORNECFRETE CODFRETE,
       C.NUMPED,
       C.NUMPEDRCA,
       C.NUMPEDCLI,
       C.EMITIUMAPA,
       C.TIPOPRIORIDADEENTREGA PRIORIDADE,
       C.DATA,
       C.DTLIBERA,
       C.CODFUNCLIBERA,
       C.POSICAO,
       C.CONDVENDA,
       C.CODCLI,
       T.CLIENTE,
       C.CODUSUR,
       U.NOME,
       ROUND(C.VLTOTAL, 2) VLTOTAL
  FROM PCPEDC C, PCCLIENT T, PCUSUARI U
WHERE C.CODCLI = T.CODCLI
   AND C.CODUSUR = U.CODUSUR
   AND C.CODSUPERVISOR IN (7, 8)
  -- AND C.EMITIUMAPA IS NULL
   AND C.POSICAO NOT IN ('F', 'C', 'CT')
   AND C.POSICAO = 'L'
   AND C.DATA <= TRUNC(SYSDATE)-1
ORDER BY C.TIPOPRIORIDADEENTREGA, C.DATA, C.HORA, C.MINUTO;/


-------------ALTERACAO PRIORIDADE DO PEDIDO------------
SELECT ROWID, NUMPED, TIPOPRIORIDADEENTREGA FROM PCPEDC WHERE NUMPED = 37067438;


  ------------PEDIDOS COM ALTA PRIORIDADE---------
  SELECT C.CODFILIAL,
         C.NUMPED,
         C.NUMPEDRCA,
         C.EMITIUMAPA,
         C.CODFORNECFRETE CODFRETE,
         C.DATA,
         C.TIPOPRIORIDADEENTREGA PRIORIDADE,
         C.DTLIBERA,
         C.CODFUNCLIBERA,
         C.CODFORNECFRETE,
         C.HORA,
         C.MINUTO,
         C.POSICAO,
         C.CONDVENDA,
         C.CODCLI,
         T.CLIENTE,
         C.CODUSUR,
         U.NOME,
         ROUND(C.VLTOTAL, 2) VLTOTAL
    FROM PCPEDC C, PCCLIENT T, PCUSUARI U
   WHERE C.CODCLI = T.CODCLI
     AND C.CODUSUR = U.CODUSUR
     AND C.CODSUPERVISOR IN (7, 8)
     AND C.POSICAO NOT IN ('F', 'C', 'CT')
     AND C.POSICAO = 'L'
   --  AND C.EMITIUMAPA IS NOT NULL
    -- AND C.EMITIUMAPA IS  NULL
     AND C.TIPOPRIORIDADEENTREGA = 'A'
     AND C.DATA <= TRUNC(SYSDATE)
  -- and C.NUMPED = 37066869
   ORDER BY EMITIUMAPA, C.DATA, C.HORA, C.MINUTO;/


--------CONSULTA ITENS PEDIDO-------------
SELECT I.NUMPED,
       C.NUMPEDRCA,
       C.CODEMITENTE,
       C.EMITIUMAPA,
       C.TIPOPRIORIDADEENTREGA,
       C.POSICAO,
       C.DTFAT,
       I.DATA,
       I.CODPROD,
       T.DESCRICAO,
       I.QT,
       I.PVENDA
  FROM PCPEDI I, PCPRODUT T, PCPEDC C
WHERE I.CODPROD = T.CODPROD
AND C.NUMPED = I.NUMPED
   AND I.NUMPED IN (37231945);/


------------ANALISE DOS ITENS PEDIDO PENDENTE---------
SELECT C.DATA,
       C.CODFILIAL,
       I.NUMPED,
       C.NUMPEDRCA,
       I.POSICAO POS,
       I.CODPROD,
       P.DESCRICAO,
       F.FORNECEDOR,
       I.CODFILIALRETIRA FILIALRETIRA,
       I.QT,
       (E.QTESTGER - E.QTBLOQUEADA - E.QTRESERV) QTDISP,
       E.QTESTGER,
       E.QTBLOQUEADA QTBLOQ,
       E.QTRESERV
  FROM PCPEDC C, PCPEDI I, PCPRODUT P, PCEST E, PCFORNEC F
WHERE C.NUMPED = I.NUMPED
   AND P.CODFORNEC = F.CODFORNEC
   AND P.CODPROD = I.CODPROD
   AND E.CODPROD = P.CODPROD
   AND I.CODFILIALRETIRA = E.CODFILIAL
   AND C.CODSUPERVISOR IN (7, 8)
   AND I.POSICAO IN ('B', 'P')
--AND C.NUMPED = 4500021869
ORDER BY I.DATA, I.NUMPED;/
