WITH VENDEDORES AS
 (SELECT U.CODUSUR, V.CODGERENTE
    FROM PCUSUARI U
    LEFT JOIN PCSUPERV V ON V.CODSUPERVISOR = U.CODSUPERVISOR
    LEFT JOIN PCGERENTE G ON V.CODGERENTE = G.CODGERENTE),
CLIENTES AS
 (SELECT C.CODCLI,
         (CASE
           WHEN R.DESCRICAO IS NULL THEN
            ('C' || C.CODCLI)
           ELSE
            ('R' || C.CODREDE)
         END) AS CODCLIREDE,
         (CASE
           WHEN R.DESCRICAO IS NULL THEN
            ('C' || C.CODCLI || ' - ' || C.CLIENTE)
           ELSE
            ('R' || C.CODREDE || ' - ' || UPPER(R.DESCRICAO))
         END) AS CLIENTE_REDE,
         (C.CODCLI || ' - ' || C.CLIENTE) CLIENTE,
         C.CODUSUR1 AS CODUSUR,
         C.LIMCRED
    FROM PCCLIENT C
    LEFT JOIN PCREDECLIENTE R ON C.CODREDE = R.CODREDE
   INNER JOIN VENDEDORES V ON C.CODUSUR1 = V.CODUSUR
   WHERE V.CODGERENTE IN (1, 8, 9, 10)),
LIMITE_CREDITO AS
 (SELECT CODCLIREDE, SUM(LIMCRED) LIMITE FROM CLIENTES GROUP BY CODCLIREDE),
MAXCODIGOBLOQUEIO AS
 (SELECT MAX(B.CODIGO) CODIGO_MAX, B.NUMPED
    FROM PCBLOQUEIOSPEDIDO B
   INNER JOIN PCPEDC C ON B.NUMPED = C.NUMPED
   WHERE C.POSICAO NOT IN ('F', 'C')
   GROUP BY B.NUMPED),
MOTIVOBLOQUEIO AS
 (SELECT B.NUMPED, B.TIPO, B.MOTIVO
    FROM PCBLOQUEIOSPEDIDO B
   INNER JOIN MAXCODIGOBLOQUEIO M ON B.CODIGO = M.CODIGO_MAX
                                 AND B.NUMPED = M.NUMPED),
TITULOS AS
 (SELECT C.CODCLIREDE, T.DTPAG, T.DTVENC, T.VALOR
    FROM PCPREST T
   INNER JOIN CLIENTES C ON T.CODCLI = C.CODCLI
   INNER JOIN VENDEDORES V ON T.CODUSUR = V.CODUSUR),
TITULOS_ABERTO AS
 (SELECT T.CODCLIREDE, MIN(T.DTVENC) DT_A_VENCER, SUM(T.VALOR) VL_A_VENCER
    FROM TITULOS T
   WHERE T.DTPAG IS NULL
     AND T.DTVENC >= TRUNC(SYSDATE)
   GROUP BY T.CODCLIREDE),
TITULOS_VENCIDOS AS
 (SELECT T.CODCLIREDE, MIN(T.DTVENC) DT_VENCIDO, SUM(T.VALOR) VL_VENCIDO
    FROM TITULOS T
   WHERE T.DTPAG IS NULL
     AND T.DTVENC < TRUNC(SYSDATE)
   GROUP BY T.CODCLIREDE)
SELECT P.CODFILIAL,
       P.DATA,
       P.NUMPED,
       C.CLIENTE_REDE,
       C.CLIENTE,
       P.CODCOB,
       P.VLATEND,
       P.OBS,
       B.MOTIVO AS MOTIVO_BLOQUEIO,
       L.LIMITE,
       (NVL(L.LIMITE,0) - NVL(A.VL_A_VENCER, 0)) SALDO_LIMITE,
       COALESCE(V.DT_VENCIDO, A.DT_A_VENCER) MENOR_DTVENC,
       NVL(V.VL_VENCIDO, 0) VL_VENCIDO,
       NVL(A.VL_A_VENCER, 0) VL_A_VENCER
  FROM PCPEDC P
 INNER JOIN CLIENTES C ON C.CODCLI = P.CODCLI
  LEFT JOIN LIMITE_CREDITO L ON C.CODCLIREDE = L.CODCLIREDE
  LEFT JOIN MOTIVOBLOQUEIO B ON P.NUMPED = B.NUMPED
  LEFT JOIN TITULOS_ABERTO A ON C.CODCLIREDE = A.CODCLIREDE
  LEFT JOIN TITULOS_VENCIDOS V ON C.CODCLIREDE = V.CODCLIREDE
 WHERE P.POSICAO IN ('B')
   AND P.CONDVENDA IN (1, 7)
   AND B.TIPO = 'F'
 ORDER BY P.DATA;
 /