SELECT P.CODFILIAL,
       P.DATA,
       C.CODCLIPRINC,
       P.CODCLI,
       C.CLIENTE,
       P.OBS,
       P.VLATEND AS VLPEDIDO,
       (TRUNC(SYSDATE) - P.DATA) AS DIAS
  FROM PCPEDC P
  LEFT JOIN PCCLIENT C
    ON P.CODCLI = C.CODCLI
  LEFT JOIN PCSUPERV V
   ON P.CODSUPERVISOR = V.CODSUPERVISOR  
 WHERE P.POSICAO IN ('B', 'P')
 AND V.CODGERENTE IN (1,8,9,10)
 AND P.CODFILIAL IN (2)
 AND P.VLATEND < 500
 ORDER BY P.DATA, C.CODCLIPRINC;