SELECT S.CODCLI,
       C.CLIENTE,
       C.CGCENT,
       C.CODREDE,
       C.CODCLIPRINC,
       R.PRACA,
       S.CONDVENDA,
       (CASE S.CONDVENDA
         WHEN 1 THEN
          'VENDA NORMAL'
         WHEN 5 THEN
          'BONIFICADA'
         ELSE
          ''
       END) VENDADESCRICAO,
       M.DTMOV,
       M.NUMNOTA,
       G.DESCRICAO PLANOPAG,
       M.CODPROD,
       P.CODFAB,
       P.DESCRICAO,
       M.QT,
       (CASE
         WHEN M.PUNIT = 0 THEN
          M.PBONIFIC
         ELSE
          M.PUNIT
       END) PVENDA
  FROM PCMOV M, PCPRODUT P, PCNFSAID S, PCCLIENT C, PCPRACA R, PCPLPAG G
 WHERE M.CODPROD = P.CODPROD
   AND M.NUMTRANSVENDA = S.NUMTRANSVENDA
   AND S.CODCLI = C.CODCLI
   AND C.CODPRACA = R.CODPRACA
   AND S.CODPLPAG = G.CODPLPAG
   AND S.CODSUPERVISOR IN (1, 2, 4, 11, 12)
   AND M.DTMOV BETWEEN TO_DATE('01/01/2018', 'DD/MM/YYYY') AND
       TO_DATE('31/03/2019', 'DD/MM/YYYY')
  -- AND M.CODPROD = 800731
      /*AND P.CODFAB = */
  -- AND C.CODREDE = 556
   AND C.CODCLIPRINC = 4891
 ORDER BY C.CLIENTE, M.DTMOV DESC;