WITH MAXCODIGOBLOQUEIO AS (
    SELECT MAX (CODIGO) CODIGO_MAX,
           NUMPED
      FROM PCBLOQUEIOSPEDIDO B
     GROUP BY NUMPED
), MOTIVOBLOQUEIO AS (
    SELECT B.NUMPED,
           B.TIPO,
           B.MOTIVO
      FROM PCBLOQUEIOSPEDIDO B
     INNER JOIN MAXCODIGOBLOQUEIO M ON B.CODIGO = M.CODIGO_MAX
       AND B.NUMPED = M.NUMPED
), VENCIDOS AS (
    SELECT CODCLI,
           SUM (VALOR) VL_VENCIDO
      FROM PCPREST T
     WHERE T.DTPAG IS NULL
       AND T.DTVENC <= TRUNC (SYSDATE) - 1
     GROUP BY CODCLI
)
SELECT C.CODFILIAL,
       C.DATA,
       C.NUMPED,
       T.CODCLIPRINC,
       C.CODCLI,
       T.CLIENTE,
       R.DESCRICAO AS REDE,
       C.CODCOB,
       C.OBS,
       B.MOTIVO AS MOTIVO_BLOQUEIO,
       C.VLATEND,
       V.VL_VENCIDO
  FROM PCPEDC C
  LEFT JOIN MOTIVOBLOQUEIO B ON C.NUMPED = B.NUMPED
  LEFT JOIN PCSUPERV V ON C.CODSUPERVISOR = V.CODSUPERVISOR
  LEFT JOIN PCUSUARI U ON C.CODUSUR = U.CODUSUR
  LEFT JOIN PCCLIENT T ON C.CODCLI = T.CODCLI
  LEFT JOIN PCREDECLIENTE R ON T.CODREDE = R.CODREDE
  LEFT JOIN VENCIDOS V ON C.CODCLI = V.CODCLI
 WHERE C.POSICAO IN (
    'B'
)
   AND V.CODGERENTE IN (
    1, 8, 9, 10
)
   AND C.CONDVENDA IN (
    1, 7
)
   AND B.TIPO = 'F'
 ORDER BY C.DATA;
/