SELECT F.CODFILIAL,
       P.CODPROD,
       P.DESCRICAO,
       P.CODFORNEC,
       N.FORNECEDOR,
       P.CODFUNCULTALTER,
       E.NOME,
       P.DTULTALTER,
       P.ENVIARFORCAVENDAS,
       F.ENVIARFORCAVENDAS
  FROM PCPRODUT P, PCPRODFILIAL F, PCFORNEC N, PCEMPR E
 WHERE P.CODFORNEC = N.CODFORNEC
   AND P.CODPROD = F.CODPROD
   AND E.MATRICULA = P.CODFUNCULTALTER
   AND F.CODFILIAL = '2'
   --AND N.CODFORNEC IN (7561, 305, 9225, 9078, 9167, 9234)
   AND F.ENVIARFORCAVENDAS = 'S'
   AND F.FORALINHA <> 'FL'
 ORDER BY N.FORNECEDOR;