SELECT P.NUMREGIAO,
       P.CODPROD,
       T.DESCRICAO,
       P.DATAALTER,
       P.MATRICULA,
       E.NOME_GUERRA,
       P.ROTINA,
       P.MARGEMIDEALANT,
       P.MARGEMIDEALATUAL,
       P.PTABELAANT,
       P.PTABELA,
       P.PVENDAANT,
       P.PVENDA,
       P.PROGRAMA,
       P.USUARIOREDE,
       P.MAQUINA
  FROM PCPRECO P,
       PCPRODUT T,
       PCEMPR E
 WHERE P.CODPROD = T.CODPROD
   AND E.MATRICULA = P.MATRICULA
   AND T.CODPROD = 803898
   AND P.NUMREGIAO = 1
 ORDER BY P.DATAALTER DESC;
/