WITH PRODUTO_ACABADO AS
 (SELECT CODPROD, DESCRICAO FROM PCPRODUT),
TABELA_PRECO AS
 (SELECT CODPROD, ROUND(PVENDA,2) AS PVENDA FROM PCTABPR WHERE NUMREGIAO = 6),
PESQUISA_PRODUTOMP AS
 (SELECT DISTINCT (CODPRODACAB) FROM PCFORMPROD WHERE CODPRODMP IN (799052))
SELECT F.CODPRODACAB AS CODPROD_KIT,
       A.DESCRICAO   AS PRODUTO_KIT,
       F.CODPRODMP,
       P.DESCRICAO   AS PRODUTO_MP,
       F.QTPRODMP    AS QT,
       T.PVENDA
  FROM PCFORMPROD F
 INNER JOIN PESQUISA_PRODUTOMP M
    ON F.CODPRODACAB = M.CODPRODACAB
  LEFT JOIN PCPRODUT P
    ON F.CODPRODMP = P.CODPROD
  LEFT JOIN PRODUTO_ACABADO A
    ON F.CODPRODACAB = A.CODPROD
  LEFT JOIN TABELA_PRECO T
    ON F.CODPRODMP = T.CODPROD
 WHERE P.DTEXCLUSAO IS NULL
   AND F.CODPRODACAB = 810559
 ORDER BY F.CODPRODACAB, F.CODPRODMP