WITH PRODUTO_ACABADO AS (
    SELECT CODPROD,
           DESCRICAO
      FROM PCPRODUT
),PESQUISA_PRODUTOMP AS (
    SELECT DISTINCT (CODPRODACAB)
      FROM PCFORMPROD
     WHERE CODPRODMP IN ( 799052 )
)
SELECT F.CODPRODACAB AS CODPROD_KIT,
       A.DESCRICAO AS PRODUTO_KIT,
       F.CODPRODMP,
       P.DESCRICAO AS PRODUTO_MP,
       F.QTPRODMP AS QT,
       L.ENVIARFORCAVENDAS AS ATIVO,
       ROUND (T.PVENDA, 2) AS PVENDA
  FROM PCFORMPROD F
 INNER JOIN PESQUISA_PRODUTOMP M ON F.CODPRODACAB = M.CODPRODACAB
  LEFT JOIN PCPRODUT P ON F.CODPRODMP = P.CODPROD
  LEFT JOIN PCPRODFILIAL L ON F.CODPRODACAB = L.CODPROD AND L.CODFILIAL = 6
  LEFT JOIN PRODUTO_ACABADO A ON F.CODPRODACAB = A.CODPROD
  LEFT JOIN PCTABPR T ON F.CODPRODMP = T.CODPROD AND T.NUMREGIAO = 6
 WHERE P.DTEXCLUSAO IS NULL
   AND F.CODPRODACAB IN ( 810559 )
 ORDER BY F.CODPRODACAB,    
          F.CODPRODMP