SELECT F.CODFILIAL,
       P.CODPRODMASTER CODPROD_PAI,
       (SELECT DESCRICAO FROM PCPRODUT WHERE CODPROD = P.CODPRODMASTER) DESCRICAO_PAI,
       P.CODPROD,
       P.DESCRICAO,
       F.ENVIARFORCAVENDAS ENVIARFORCAVENDAS_238,
       B.ENVIAFV ENVIAFV_2014,
       B.CODAUXILIAR CODAUXILIAR_2014,
       E.QTESTGER
  FROM PCPRODUT P, PCPRODFILIAL F, PCEMBALAGEM B, PCFORNEC C, PCEST E
 WHERE P.CODPROD = F.CODPROD    
   AND P.CODPROD = B.CODPROD
   AND F.CODFILIAL = B.CODFILIAL
   AND P.CODFORNEC = C.CODFORNEC
   AND E.CODFILIAL = F.CODFILIAL
   AND E.CODPROD = F.CODPROD
   AND C.CODFORNECPRINC IN (2, 305)
   AND P.CODPROD <> P.CODPRODMASTER
   AND F.CODFILIAL = 2
   AND (F.ENVIARFORCAVENDAS = 'S' OR B.ENVIAFV = 'S' OR E.QTESTGER > 0)
 ORDER BY P.CODPRODMASTER;