WITH PRODUTOS_DISPONIVEIS AS (
    SELECT E.CODFILIAL,
           P.DTCADASTRO,
           P.NUMORIGINAL,
           P.CODFAB,
           P.CODAUXILIAR,
           P.CODPROD,
           P.DESCRICAO,
           E.QTESTGER
      FROM PCPRODUT P
      LEFT JOIN PCEST E ON P.CODPROD = E.CODPROD
     WHERE P.CODPROD = P.CODPRODMASTER
)
SELECT E.CODFILIAL,
       P.DTCADASTRO,
       P.CODFAB,
       P.CODAUXILIAR,
       P.CODPROD,
       P.DESCRICAO,
       E.QTESTGER,
       D.CODFILIAL CODFILIAL_DISP,
       D.DTCADASTRO CADASTRO_DISP,
       D.CODFAB CODFAB_DISP,
       D.CODAUXILIAR EAN_DISP,
       D.CODPROD CODPROD_DISP,
       D.DESCRICAO DESCRICAO_DISP,
       D.QTESTGER QT_DISP
  FROM PCPRODUT P
  LEFT JOIN PCEST E ON P.CODPROD = E.CODPROD
 INNER JOIN PRODUTOS_DISPONIVEIS D ON P.CODPROD = D.NUMORIGINAL
   AND E.CODFILIAL = D.CODFILIAL
 WHERE P.CODPROD <> P.CODPRODMASTER
   AND E.QTEST = 0
   AND E.CODFILIAL IN (
    1, 2, 7
)
 ORDER BY E.CODFILIAL,
          P.CODPRODMASTER
/