SELECT A.CODPROD,
       A.DESCRICAO,
       A.CODEPTO,
       B.DESCRICAO DEPTO,
       A.CODSEC,
       C.DESCRICAO SECAO,
       A.CODCATEGORIA,
       E.CATEGORIA,
       A.CODFORNEC,
       D.FORNECEDOR
  FROM PCPRODUT A,
       PCDEPTO B,
       PCSECAO C,
       PCFORNEC D,
       PCCATEGORIA E
 WHERE A.CODEPTO = B.CODEPTO
   AND A.CODSEC = C.CODSEC
   AND A.CODFORNEC = D.CODFORNEC
   AND A.CODCATEGORIA = E.CODCATEGORIA(+)
   AND A.CODEPTO NOT IN (10, 20, 30, 40, 50, 96, 97, 98, 99)
 ORDER BY A.CODEPTO;