SELECT P.DTCADASTRO,
       P.CODFUNCCADASTRO COD_FUNC,
       (SELECT NOME FROM PCEMPR WHERE P.CODFUNCCADASTRO = MATRICULA) FUNC_CADASTRO,
       P.DTULTALTCAD,
       P.CODFUNCULTALTCAD FUNC_CADASTRO,
       (SELECT NOME FROM PCEMPR WHERE P.CODFUNCULTALTCAD = MATRICULA)FUNC_ULT_ALT,
       P.CODPROD,
       P.DESCRICAO,
       P.QTUNIT,
       P.QTUNITCX,
       P.MULTIPLO   MULT_PRODUT,
       F.MULTIPLO   MULT_PRODFILIAL_2
  FROM PCPRODUT P, PCPRODFILIAL F
 WHERE F.CODPROD = P.CODPROD  
   AND P. QTUNIT > 1
   AND F.CODFILIAL = 2;