SELECT A.CODPROD,
       A.CODPRODMASTER,
       A.DESCRICAO,
       A.EMBALAGEM,
       B.MARCA,
       A.CODFAB,
       A.UNIDADEMASTER UNIDADE_COMPRA,
       A.UNIDADE       UNIDADE_VENDA,
       A.NBM,
       A.CODAUXILIAR
  FROM PCPRODUT A, PCMARCA B
 WHERE A.CODMARCA = B.CODMARCA
   AND A.DTEXCLUSAO IS NULL
 ORDER BY CODPROD DESC;