--ALTERACAO PRECO DE VENDA TV8 IGUAL AO TV7 - DISTRIBUICAO
WITH ITENS_PEDIDO_TV8 AS
 (SELECT C.NUMPEDENTFUT NUMPED_TV7,
         C.NUMPED NUMPED_TV8,
				 C.POSICAO POSICAO_TV8,
         I.CODCLI CODCLI_TV8,
         I.CODPROD,
         I.QT QT_TV8,
         I.PVENDA PVENDA_TV8,
         ROUND(I.QT * I.PVENDA, 2) VLTOTAL_TV8
    FROM PCPEDI I
    JOIN PCPEDC C ON C.NUMPED = I.NUMPED
   WHERE I.NUMPED = &NUMPED_TV8)

SELECT C.NUMPED_TV7,
       C.NUMPED_TV8,
       I.CODCLI CODCLI_TV7,
       C.CODCLI_TV8,
       I.CODPROD,
       I.QT QT_TV7,
       C.QT_TV8,
       I.PVENDA PVENDA_TV7,
       C.PVENDA_TV8,
       ROUND(I.QT * I.PVENDA, 2) VLTOTAL_TV7,
       C.VLTOTAL_TV8
  FROM PCPEDI I
  JOIN ITENS_PEDIDO_TV8 C ON C.NUMPED_TV7 = I.NUMPED
                         AND C.CODPROD = I.CODPROD
 WHERE C.POSICAO_TV8 NOT IN ('C', 'F')
   AND I.QT = C.QT_TV8
	 ;

------UPDATE DO PVENDA DO TV8 PARA FICAR IGUAL AO TV7--------

/**------------------------------------------------------------------------------------//
***  DEPOIS RODAR ROTINA 507 - OPÇÃO 18 - RECALCULO DO CABEÇALHO DO PEDIDO DE VENDA   ***
**------------------------------------------------------------------------------------**/

MERGE INTO PCPEDI I
USING (
  WITH ITENS_PEDIDO_TV8 AS
   (SELECT C.NUMPEDENTFUT NUMPED_TV7,
           C.NUMPED NUMPED_TV8,
           C.POSICAO POSICAO_TV8,
					 I.CODCLI CODCLI_TV8,
           I.CODPROD,
           I.QT QT_TV8,
           I.PVENDA PVENDA_TV8,
           ROUND(I.QT * I.PVENDA, 2) VLTOTAL_TV8
      FROM PCPEDI I
      JOIN PCPEDC C ON C.NUMPED = I.NUMPED
     WHERE I.NUMPED = &NUMPED_TV8)
  
  SELECT C.NUMPED_TV7,
         C.NUMPED_TV8,
         I.CODPROD,
         I.QT QT_TV7,
         C.QT_TV8,
         I.PVENDA PVENDA_TV7,
         C.PVENDA_TV8
    FROM PCPEDI I
    JOIN ITENS_PEDIDO_TV8 C ON C.NUMPED_TV7 = I.NUMPED
                           AND C.CODPROD = I.CODPROD
   WHERE C.POSICAO_TV8 NOT IN ('C', 'F')
     AND I.QT = C.QT_TV8) X ON (I.NUMPED = X.NUMPED_TV8 AND I.CODPROD = X.CODPROD)
		 WHEN MATCHED THEN
			 UPDATE SET I.PVENDA = X.PVENDA_TV7;
