------ANALISE DE PRODUTO FORA DA MARGEM - PVENDA X PCOMPRA X PESTOQUE
SELECT P.CODFILIAL,
       P.NUMREGIAO,
       P.CODPROD,
       P.DESCRICAO,
       P.MARGEM,
       P.PVENDA,
       P.CUSTOSELECIONADO,
       C.PCOMPRA,
       C.PLIQUIDO,
       E.CUSTOREP,
       E.CUSTOFIN,
       E.VALORULTENT
  FROM VW_PRECIFICACAO P
  LEFT JOIN VIEW_JC_CUSTOLIQ_240 C ON C.CODPROD = P.CODPROD
                                  AND C.CODFILIAL = P.CODFILIAL
  LEFT JOIN PCEST E ON E.CODPROD = P.CODPROD
                   AND E.CODFILIAL = P.CODFILIAL
 WHERE P.CODFILIAL = '11'
   AND P.NUMREGIAO = 4
   AND P.CODPROD IN (815163);


---CORRECAO NA PCEST
SELECT ROWID,
       E.CODPROD,
       E.VALORULTENT,
       E.CUSTOREP,
       E.CUSTOFIN,
       E.CUSTOREAL
  FROM PCEST E
 WHERE E.CODFILIAL = '11'
   AND E.CODPROD = 815163;
	 
	----RODAR RECLACULO NA 507
