/*-----------SCRIPT PARA IDENTIFICAR PROBLEMAS NA MARGEM QUANDO JÁ TEMOS O PEDIDO / PRODUTO INFORMADO--------------*/
SELECT S.DATA,
       P.CODFILIAL,
       S.NUMPED,
       S.CODCLI,
       C.CLIENTE,
       S.CODPROD,
       T.DESCRICAO,
       S.QT,
       S.PTABELA,
       ROUND(S.PERDESC,2) PERDESC,
       S.PVENDA,
       S.VLCUSTOFIN,
       (S.PVENDA - (S.CUSTOFINEST + (S.PVENDA * (S.CODICMTAB / 100)))) LUCRO,
       ROUND (((S.PVENDA - (S.CUSTOFINEST + (S.PVENDA * (S.CODICMTAB / 100)))) / S.PVENDA * 100), 2) PER_LUCRO,
       S.CUSTOFINEST,
       S.CODICMTAB,
       (S.PVENDA * (S.CODICMTAB / 100)) VLIMPOSTOS,
       S.PERCOM,
       S.PVENDA * (S.PERCOM / 100) VLCOMISSAO,
       S.VLVERBACMV,
       E.VALORULTENT VLULTENT_1103,
       E.CUSTOFIN CUSTOFIN_1103,
       E.CUSTOULTENT CUSTOULT_1103,
       E.CUSTOCONT CUSTOCONT_1103,
       E.CUSTOREP CUSTOREP_1103
  FROM PCPEDI S,
       PCCLIENT C,
       PCPRODUT T,
       PCEST E,
       PCPEDC P
 WHERE C.CODCLI = S.CODCLI
   AND T.CODPROD = S.CODPROD
   AND E.CODPROD = S.CODPROD
   AND P.NUMPED = S.NUMPED
   AND P.CODFILIAL = E.CODFILIAL
   AND S.NUMPED IN ( 5000000377, 15004295 )
   --AND P.CODFILIAL = 8
   AND S.CODPROD IN ( 810379 )
   ;
/
/*-----------SCRIPT PARA ENCONTRAR PRODUTOS ABAIXO DA MARGEM ESTIPULADA--------------*/
SELECT *
  FROM (
    SELECT S.DATA,
           P.CODFILIAL,
           S.NUMPED,
           S.CODCLI,
           C.CLIENTE,
           S.CODPROD,
           T.DESCRICAO,
           S.QT,
           S.PTABELA,
           S.PERDESC,
           S.PVENDA,
           S.VLCUSTOFIN,
           (S.PVENDA - S.VLCUSTOFIN) LUCRO,
           ROUND (((S.PVENDA - S.VLCUSTOFIN) / S.PVENDA * 100), 2) PER_LUCRO,
           S.CUSTOFINEST,
           S.CODICMTAB,
           S.PVENDA * (S.CODICMTAB / 100) VLIMPOSTOS,
           S.PERCOM,
           S.PVENDA * (S.PERCOM / 100) VLCOMISSAO,
           S.VLVERBACMV,
           E.VALORULTENT VLULTENT_1103,
           E.CUSTOFIN CUSTOFIN_1103,
           E.CUSTOULTENT CUSTOULT_1103,
           E.CUSTOCONT CUSTOCONT_1103,
           E.CUSTOREP CUSTOREP_1103
      FROM PCPEDI S,
           PCCLIENT C,
           PCPRODUT T,
           PCEST E,
           PCPEDC P
     WHERE C.CODCLI = S.CODCLI
       AND T.CODPROD = S.CODPROD
       AND E.CODPROD = S.CODPROD
       AND P.NUMPED = S.NUMPED
       AND P.CODFILIAL = E.CODFILIAL
)
 WHERE CODCLI NOT IN (
    4, 7543, 82215, 18633, 17427
)
   AND PER_LUCRO < 20
   AND DATA > TRUNC (SYSDATE) - 3;
/