/*--- ANÁLISE CUSTOS PCEST PRODUTO PAI E FILHO --------*/
SELECT E.CODFILIAL,
       (
           SELECT PCPRODUT.CODPROD
             FROM PCPRODUT,
                  PCPRODFILIAL
            WHERE P.CODPRODMASTER = PCPRODUT.CODPROD
              AND F.CODFILIAL = PCPRODFILIAL.CODFILIAL
              AND PCPRODFILIAL.CODPROD = PCPRODUT.CODPROD
       ) COD_PAI,
       (
           SELECT PCPRODUT.DESCRICAO
             FROM PCPRODUT
            WHERE P.CODPRODMASTER = PCPRODUT.CODPROD
       ) PRODUTO_PAI,
       (
           SELECT PCEST.DTULTENT
             FROM PCEST
            WHERE PCEST.CODPROD = P.CODPRODMASTER
              AND PCEST.CODFILIAL = 7
       ) DTULTENT_PAI,
       (
           SELECT PCEST.QTESTGER
             FROM PCEST
            WHERE PCEST.CODPROD = P.CODPRODMASTER
              AND PCEST.CODFILIAL = 7
       ) QTESTGER_PAI,
       (
           SELECT PCEST.VALORULTENT
             FROM PCEST
            WHERE PCEST.CODPROD = P.CODPRODMASTER
              AND PCEST.CODFILIAL = 7
       ) VALORULTENT_PAI,
       (
           SELECT PCEST.CUSTOULTENT
             FROM PCEST
            WHERE PCEST.CODPROD = P.CODPRODMASTER
              AND PCEST.CODFILIAL = 7
       ) CUSTOULTENT_PAI,
       (
           SELECT PCEST.CUSTOCONT
             FROM PCEST
            WHERE PCEST.CODPROD = P.CODPRODMASTER
              AND PCEST.CODFILIAL = 7
       ) CUSTOCONT_PAI,
       (
           SELECT PCEST.CUSTOREAL
             FROM PCEST
            WHERE PCEST.CODPROD = P.CODPRODMASTER
              AND PCEST.CODFILIAL = 7
       ) CUSTOREAL_PAI,
       (
           SELECT PCEST.CUSTOFIN
             FROM PCEST
            WHERE PCEST.CODPROD = P.CODPRODMASTER
              AND PCEST.CODFILIAL = 7
       ) CUSTOFIN_PAI,
       (
           SELECT PCEST.CUSTOREP
             FROM PCEST
            WHERE PCEST.CODPROD = P.CODPRODMASTER
              AND PCEST.CODFILIAL = 7
       ) CUSTOREP_PAI,
       /*   P.CODFORNEC,*/
       E.CODPROD COD_FILHO,
       P.DESCRICAO PRODUTO_FILHO,
       E.DTULTENT,
       E.QTESTGER,
       E.VALORULTENT,
       E.CUSTOULTENT,
       E.CUSTOCONT,
       E.CUSTOREAL,
       E.CUSTOFIN,
       E.CUSTOREP
  FROM PCPRODUT P,
       PCEST E,
       PCPRODFILIAL F
 WHERE E.CODPROD = P.CODPROD
   AND E.CODPROD = F.CODPROD
   AND E.CODFILIAL = F.CODFILIAL
   AND E.CODFILIAL NOT IN (
    2, 3, 4, 5, 6
)
   AND P.CODPROD = 804459
 ORDER BY P.CODPRODMASTER,
          E.CODPROD,
          E.CODFILIAL;
/



/*--- BUSCA PELO CÓDIGO MASTER DO PRODUTO --------*/
SELECT CODPRODMASTER
  FROM PCPRODUT
 WHERE CODPROD = 800815;
/


/*--- BUSCA PELO FILHOS ATRAVÉS DO PAI --------*/
SELECT CODPROD,
       DESCRICAO
  FROM PCPRODUT
 WHERE CODPRODMASTER = 801931
 ORDER BY CODPROD;
/

/*--- ANÁLISE CUSTOS PCMOV X PCEST NAS FILIAIS --------*/
SELECT M.CODFILIAL FILIAL,
       M.DTMOV,
       M.CODFORNEC,
       M.CODPROD,
       P.DESCRICAO,
       M.QTESTANT,
       M.QT,
       M.VALORULTENTANT VLULTENTANT_M,
       M.VALORULTENT VLULTENT_M,
       M.CUSTOULTENTANT C_ULTENTANT_M,
       M.CUSTOULTENT C_ULTENT_M,
       M.CUSTOFINANT C_FINANT_M,
       M.CUSTOFIN C_FIN_M,
       M.CUSTOCONTANT C_CONTANT_M,
       M.CUSTOCONT C_CONT_M,
       E.VALORULTENT VLULTENT_E,
       E.CUSTOULTENT C_ULTENT_E,
       E.CUSTOFIN C_FIN_E,
       E.QTESTGER EST_ATUAL,
       M.STATUS,
       M.NUMNOTA,
       M.CODOPER
  FROM PCMOV M,
       PCPRODUT P,
       PCEST E
 WHERE M.CODPROD = P.CODPROD
   AND E.CODPROD = M.CODPROD
   AND E.CODFILIAL = M.CODFILIAL
   AND (((((CODOPER = 'E'
    OR CODOPER = 'ET')
    OR (CODOPER = 'EP'))
    OR (CODOPER = 'EB'))
    OR (CODOPER = 'ER'))
    OR (CODOPER = 'ED'))
   AND M.CODFILIAL IN (
    1, 2, 7
)
   AND M.CODPROD IN (
    798926
)
   AND M.DTCANCEL IS NULL
   AND M.DTMOV > TO_DATE ('20/01/2015', 'DD/MM/YYYY')
 ORDER BY M.DTMOV DESC;
/


 /*--- FORNECEDOR --------*/
SELECT CODFORNEC,
       FORNECEDOR,
       ESTADO,
       TIPOFORNEC
  FROM PCFORNEC F
 WHERE CODFORNEC = 7079;
/

/*--- ANÁLISE REBAIXA NO PRODUTO --------*/
SELECT DTAPLIC,
       CODFILIAL,
       NUMVERBA,
       CODPROD,
       QTESTGER,
       CUSTOFINANT,
       CUSTOFINATUAL,
       CUSTOULTENTANT,
       CUSTOULTENTATUAL,
       CUSTOREPANT,
       CUSTOREPATUAL
  FROM PCAPLICVERBAI
 WHERE CODPROD = 798118
 ORDER BY DTAPLIC DESC;
/

 /*--- NOVO PREÇO DE COMPRA APÓS REBAIXA NO PRODUTO --------*/
SELECT F.CODFILIAL,
       F.CODPROD,
       F.CUSTOREP,
       E.CUSTOPROXIMACOMPRA,
       ROUND ((E.CUSTOPROXIMACOMPRA / (1 - (0.0925 + 0.18))), 2) VLULTENTCALC
  FROM PCPRODFILIAL F,
       PCEST E
 WHERE F.CODFILIAL = E.CODFILIAL
   AND F.CODPROD = E.CODPROD
   AND F.CODPROD = 804329;
/