SELECT A.CODCLI,
       A.CLIENTE,
       A.FANTASIA,
       A.CGCENT,
       A.IEENT,
       A.ESTCOM,
       A.CODREDE,
       B.DESCRICAO
  FROM PCCLIENT A,
       PCREDECLIENTE B
 WHERE A.CODREDE = B.CODREDE (+)
   AND A.CODUSUR1 NOT IN (
    14, 37
)
 ORDER BY CODCLI;
/