WITH R(DT) AS
 (SELECT TO_DATE('01/05/2019', 'DD/MM/YYYY') DT
    FROM DUAL
  UNION ALL
  SELECT TRUNC(R.DT) + 1
    FROM R
   WHERE R.DT < TO_DATE('19/08/2022', 'DD/MM/YYYY'))

SELECT DISTINCT R.DT,
                MAX(P.DATAALTER) OVER(PARTITION BY P.CODPROD ORDER BY R.DT) MAIOR_DATA,
                P.CODPROD,
                LAST_VALUE(P.PVENDA) OVER(PARTITION BY P.CODPROD ORDER BY R.DT) PTABELA
  FROM PCPRECO P
  JOIN R ON P.DATAALTER <= R.DT
 WHERE P.NUMREGIAO = 1
   AND P.ROTINA = '201'
   AND P.CODPROD = 162887
 ORDER BY R.DT