WITH R(DT) AS
 (SELECT TO_DATE('01/05/2019', 'DD/MM/YYYY') DT
    FROM DUAL
  UNION ALL
  SELECT TRUNC(R.DT) + 1
    FROM R
   WHERE R.DT < TO_DATE('19/08/2022', 'DD/MM/YYYY'))

SELECT DISTINCT R.DT,
                MAX(P.DATAALTER) OVER(PARTITION BY P.CODPROD ORDER BY R.DT) MAIOR_DATA,
                P.CODPROD,
                LAST_VALUE(P.PVENDA) OVER(PARTITION BY P.CODPROD ORDER BY R.DT) PTABELA
  FROM PCPRECO P
  JOIN R ON P.DATAALTER <= R.DT
 WHERE P.NUMREGIAO = 1
   AND P.ROTINA = '201'
   AND P.CODPROD = 162887
 ORDER BY R.DT;
 /
 
 
 ------APLICACAO-------
 WITH R(DT) AS
 (SELECT TO_DATE('01/05/2019', 'DD/MM/YYYY') DT
    FROM DUAL
  UNION ALL
  SELECT TRUNC(R.DT) + 1
    FROM R
   WHERE R.DT < TO_DATE('19/08/2022', 'DD/MM/YYYY')),
PRECO_TABELA AS
 (SELECT DISTINCT R.DT,
                  --MAX(P.DATAALTER) OVER (PARTITION BY P.CODPROD ORDER BY R.DT) MAIOR_DATA,
                  P.CODPROD,
                  LAST_VALUE(P.PVENDA) OVER(PARTITION BY P.CODPROD ORDER BY R.DT) PTABELA
    FROM PCPRECO P
    JOIN R ON TO_DATE(P.DATAALTER, 'DD/MM/YYYY') <= R.DT
   WHERE P.NUMREGIAO = 1
     AND P.ROTINA = '201')
SELECT M.DTMOV,
       S.CODCLI,
       C.CLIENTE,
       S.NUMNOTA,
       S.CODPLPAG,
       L.DESCRICAO PLANOPAG,
       M.CODPROD,
       M.DESCRICAO,
       M.QT,
       M.PUNIT,
       T.PTABELA,
       ROUND(1 - (M.PUNIT / T.PTABELA), 4) DESCONTO
  FROM PCMOV M
  JOIN PCNFSAID S ON S.NUMTRANSVENDA = M.NUMTRANSVENDA
  JOIN PCCLIENT C ON S.CODCLI = C.CODCLI
  JOIN PCPLPAG L ON L.CODPLPAG = S.CODPLPAG
  LEFT JOIN PRECO_TABELA T ON T.CODPROD = M.CODPROD
                          AND T.DT = M.DTMOV
 WHERE M.DTCANCEL IS NULL
   AND M.CODFISCAL IN (5102, 5405, 6102, 6403)
   AND S.CODCLI = 142570
 ORDER BY M.DTMOV, S.NUMNOTA;