WITH TRANSACAO_VENDA AS (
    SELECT NUMTRANSENT,
           MAX(M.NUMTRANSDEV) AS NUMTRANSVENDA
      FROM PCMOV M
     WHERE NUMTRANSDEV IS NOT NULL AND NUMTRANSENT IS NOT NULL
     GROUP BY NUMTRANSENT
    HAVING MAX(M.NUMTRANSDEV) > 0
), VENDA AS (
    SELECT T.NUMTRANSENT,
           S.DTSAIDA DTVENDA,
           S.NUMNOTA NOTAVENDA,
           ( S.CODCLI || '-' || S.CLIENTE ) CLIENTE,
           S.VLTOTGER VLVENDA,
           ( S.CODUSUR || '-' || U.USURDIRFV ) VENDEDOR
      FROM PCNFSAID S
      JOIN TRANSACAO_VENDA T ON T.NUMTRANSVENDA = S.NUMTRANSVENDA
      JOIN PCUSUARI U ON U.CODUSUR = S.CODUSUR
     WHERE U.CODSUPERVISOR IN ( 5, 13 )
)
SELECT ( M.DTMOV - V.DTVENDA ) DIAS_VENDA,
       ( E.CODFUNCLANC || '-' || R.NOME_GUERRA ) FUNCIONARIO,
       M.CODFILIAL,
       M.DTMOV DTDEV,
       M.NUMNOTA NOTADEV,
       ( M.CODPROD || '-' || M.DESCRICAO ) PRODUTO,
       M.QT QTDEV,
       M.PUNIT,
       V.DTVENDA,
       V.NOTAVENDA,
       V.CLIENTE,
       V.VLVENDA,
       V.VENDEDOR
  FROM PCMOV M
  JOIN VENDA V ON V.NUMTRANSENT = M.NUMTRANSENT
  JOIN PCNFENT E ON E.NUMTRANSENT = M.NUMTRANSENT
  LEFT JOIN PCEMPR R ON R.MATRICULA = E.CODFUNCLANC
 WHERE M.CODFILIAL IN ( '1', '8' ) AND ( M.DTMOV - V.DTVENDA ) > 30 AND M.DTMOV > TRUNC(SYSDATE) - 60