/*--- ANÁLISE PRODUTOS DEVOLVIDOS ------*/
SELECT DEV.DIAS_VENDA,
       DEV.CODFUNC,
       DEV.FUNCIONARIO,
       M.DTMOV,
       DEV.NOTA_DEV,
       M.NUMTRANSENT,
       M.CODPROD,
       P.DESCRICAO,
       M.CODOPER,
       M.QT,
       M.PUNIT,
       DEV.DT_VENDA,
       DEV.NOTA_VENDA,
       DEV.CODCLI,
       DEV.CLIENTE,
       DEV.VL_VENDA,
       DEV.CODUSUR
  FROM PCMOV M,
       PCPRODUT P,
       (
           SELECT (E.DTEMISSAO - F.DTSAIDA) DIAS_VENDA,
                  E.CODFUNCLANC CODFUNC,
                  R.NOME_GUERRA FUNCIONARIO,
                  E.DTEMISSAO DT_DEVOL,
                  E.NUMNOTA NOTA_DEV,
                  E.NUMTRANSENT,
                  E.CODFORNEC,
                  E.FORNECEDOR,
                  E.VLTOTAL VL_DEV,
                  E.CODUSURDEVOL VENDEDOR_DEV,
                  E.NUMTRANSVENDAORIG NUMTRANSVENDA,
                  F.DTSAIDA DT_VENDA,
                  F.NUMNOTA NOTA_VENDA,
                  F.CODCLI,
                  F.CLIENTE,
                  F.VLTOTGER VL_VENDA,
                  F.CODUSUR
             FROM PCNFENT E,
                  PCUSUARI U,
                  PCSUPERV S,
                  PCEMPR R,
                  PCNFSAID F
            WHERE E.CODUSURDEVOL = U.CODUSUR
              AND S.CODSUPERVISOR = U.CODSUPERVISOR
              AND E.CODFUNCLANC = R.MATRICULA
              AND E.NUMTRANSVENDAORIG = F.NUMTRANSVENDA
              AND U.CODSUPERVISOR = 5
              AND E.TIPODESCARGA = '6'
              AND E.DTEMISSAO > TRUNC (SYSDATE) - 3
              AND E.DTEMISSAO - F.DTSAIDA >= 30
            ORDER BY E.DTEMISSAO
       ) DEV
 WHERE M.NUMTRANSENT = DEV.NUMTRANSENT
   AND P.CODPROD = M.CODPROD;
/

/*--- ANÁLISE DA DEVOLUÇÃO REALIZADA -----*/
SELECT (E.DTEMISSAO - F.DTSAIDA) DIAS_VENDA,
       E.CODFUNCLANC CODFUNC,
       R.NOME FUNCIONARIO,
       E.DTEMISSAO DT_DEVOL,
       E.NUMNOTA NOTA_DEV,
       E.CODFORNEC,
       E.FORNECEDOR,
       E.VLTOTAL VL_DEV,
       E.CODUSURDEVOL VENDEDOR_DEV,
       E.NUMTRANSVENDAORIG NUMTRANSVENDA,
       F.DTSAIDA DT_VENDA,
       F.NUMNOTA NOTA_VENDA,
       F.CODCLI,
       F.CLIENTE,
       F.VLTOTGER VL_VENDA,
       F.CODUSUR
  FROM PCNFENT E,
       PCUSUARI U,
       PCSUPERV S,
       PCEMPR R,
       PCNFSAID F
 WHERE E.CODUSURDEVOL = U.CODUSUR
   AND S.CODSUPERVISOR = U.CODSUPERVISOR
   AND E.CODFUNCLANC = R.MATRICULA
   AND E.NUMTRANSVENDAORIG = F.NUMTRANSVENDA
   AND U.CODSUPERVISOR = 5
   AND E.TIPODESCARGA = '6'
   AND E.DTEMISSAO > TRUNC (SYSDATE) - 30
   AND E.DTEMISSAO - F.DTSAIDA >= 30
 ORDER BY E.DTEMISSAO;
/