SELECT I.NUMPED,
       I.DATA,
       P.CODMARCA,
       M.MARCA,
       I.CODPROD,
       P.DESCRICAO,
       P.CODFAB,
       P.CODAUXILIAR,
       I.QT
  FROM PCPEDI I,
       PCPRODUT P,
       PCMARCA M
 WHERE I.CODPROD = P.CODPROD
   AND P.CODMARCA = M.CODMARCA
   AND I.NUMPED = 27002081
 ORDER BY M.MARCA;