SELECT NVL(C.TIPOPRIORIDADEENTREGA, 0) PRIORIDADE,
       COUNT(C.NUMPED) PED_FATURADO_HOJE,
       SUM(VLTOTAL) VALOR_FATURADO_HOJE,
       (SELECT COUNT(PCPEDC.NUMPED)
          FROM PCPEDC, PCSUPERV, PCGERENTE
         WHERE PCPEDC.CODSUPERVISOR = PCSUPERV.CODSUPERVISOR
           AND PCSUPERV.CODGERENTE = PCGERENTE.CODGERENTE
           AND NVL(PCPEDC.TIPOPRIORIDADEENTREGA, 0) =
               NVL(C.TIPOPRIORIDADEENTREGA, 0)
           AND PCGERENTE.CODGERENTE IN (4)
           AND PCPEDC.POSICAO IN ('L')) PED_LIBERADO,
       (SELECT NVL(SUM(PCPEDC.VLTOTAL), 0)
          FROM PCPEDC, PCSUPERV, PCGERENTE
         WHERE PCPEDC.CODSUPERVISOR = PCSUPERV.CODSUPERVISOR
           AND PCSUPERV.CODGERENTE = PCGERENTE.CODGERENTE
           AND NVL(PCPEDC.TIPOPRIORIDADEENTREGA, 0) =
               NVL(C.TIPOPRIORIDADEENTREGA, 0)
           AND PCGERENTE.CODGERENTE IN (4)
           AND PCPEDC.POSICAO IN ('L')) VALOR_LIBERADO
  FROM PCPEDC C, PCSUPERV S, PCGERENTE G
 WHERE C.CODSUPERVISOR = S.CODSUPERVISOR
   AND G.CODGERENTE = S.CODGERENTE
   AND S.CODGERENTE IN (4)
   AND C.POSICAO = 'F'
   AND DTFAT = TRUNC(SYSDATE)
 GROUP BY C.TIPOPRIORIDADEENTREGA;