SELECT P.DTFAT,
       P.DATA,
       P.NUMPED,
       P.NUMPEDRCA,
       P.CODCLI,
       C.CLIENTE,
       C.CGCENT CPF,
       C.EMAIL,
       P.NUMVOLUME,
       P.CODUSUR,
       U.NOME
  FROM PCPEDC P,
       PCCLIENT C,
       PCUSUARI U
 WHERE P.CODCLI = C.CODCLI
   AND P.CODUSUR = U.CODUSUR
   AND P.CODSUPERVISOR IN (
    7, 8
)
   AND P.NUMVOLUME > 1
   AND P.POSICAO = 'F'
   AND P.DTFAT > TRUNC (SYSDATE) - 2
  /* AND P.DTFAT BETWEEN TO_DATE('01-09-2018', 'DD/MM/YYYY') AND TO_DATE('01-12-2018', 'DD/MM/YYYY')*/
 ORDER BY P.DTFAT;
/
SELECT COUNT (NUMPED)
  FROM PCPEDC P
 WHERE P.CODSUPERVISOR IN (
    7, 8
)
   AND P.NUMVOLUME > 1
   AND P.POSICAO = 'F'
   AND P.DTFAT >= '01-FEB-2019';
/
SELECT COUNT (NUMPED)
  FROM PCPEDC P
 WHERE P.CODSUPERVISOR IN (
    7, 8
)
   AND P.POSICAO = 'F'
   AND P.DTFAT BETWEEN '01-JUL-2018' AND '31-DEC-2018';
/
SELECT F.CODFILIAL,
       F.DTSAIDA,
       F.NUMPED,
       C.NUMPEDWEB,
       F.NUMTRANSVENDA,
       F.NUMNOTA,
       F.NUMVOLUME,
       F.CODUSUR,
       I.NOME
  FROM PCNFSAID F,
       PCPEDC C,
       PCUSUARI I
 WHERE F.CODSUPERVISOR IN (
    7, 8
)
   AND F.NUMVOLUME > 1
   AND C.NUMTRANSVENDA = F.NUMTRANSVENDA
   AND I.CODUSUR = F.CODUSUR
   AND F.DTCANCEL IS NULL
   AND F.DTSAIDA BETWEEN TO_DATE ('04/10/2018', 'DD/MM/YYYY') AND TO_DATE ('10/10/2018', 'DD/MM/YYYY')
 ORDER BY F.DTSAIDA DESC;
/