WITH PRODUTOS AS (
SELECT C.CODFILIAL FILIAL,
       C.DATA,
       C.NUMPED,
       NVL(U.USURDIRFV, U.NOME) VENDEDOR,
       (C.CODCLI ||'-'|| T.CLIENTE) CLIENTE,
       A.RAMO,
       (P.CODPROD ||'-'|| P.DESCRICAO) PRODUTO,
       M.MARCA,
       (I.PVENDA * I.QT) VLPEDIDO,
       ROUND((I.VLCUSTOFIN * I.QT), 2) VLCMV,
       ROUND(I.CUSTOFINEST,2) CUSTO_1103,
       ROUND((((I.PVENDA - I.VLCUSTOFIN) / DECODE(NVL(I.PVENDA, 0), 0, 1, I.PVENDA)) * 100),2) MREAL,
       NVL(R.MARGEM, 0) MPREV,
       (E.QTESTGER - E.QTRESERV - E.QTINDENIZ) QTDISP          
  FROM PCPEDC C
  JOIN PCPEDI I ON I.NUMPED = C.NUMPED
  JOIN PCCLIENT T ON T.CODCLI = C.CODCLI
  JOIN PCPRODUT P ON P.CODPROD = I.CODPROD
  LEFT JOIN PCMARCA M ON M.CODMARCA = P.CODMARCA
  LEFT JOIN PCPRACA PR ON PR.CODPRACA = C.CODPRACA
  LEFT JOIN PCTABPR R ON R.NUMREGIAO = PR.NUMREGIAO AND R.CODPROD = P.CODPROD
  LEFT JOIN PCEST E ON E.CODFILIAL = C.CODFILIAL AND E.CODPROD = P.CODPROD
  LEFT JOIN PCATIVI A ON A.CODATIV = T.CODATV1
  LEFT JOIN PCUSUARI U ON U.CODUSUR = C.CODUSUR
 WHERE 1 = 1
   AND C.POSICAO NOT IN ('C')
   AND C.CONDVENDA IN (1)
   AND P.CODMARCA NOT IN (179) --SULAMERICANA
   AND C.CODCOB NOT IN ('CONV', 'C') --SEM VENDAS DIRETORIA E FUNCIONARIO
   AND (I.PVENDA * I.QT) > 1 --RETIRAR BRINDES
   AND C.DATA >= TRUNC(SYSDATE) - 7 --PARAMETRO
   AND ((C.CODFILIAL IN (1, 7, 8, 12, 13, 14)) OR ('99' IN (1, 7, 8, 12, 13, 14))) --PARAMETRO
)
  SELECT *
    FROM PRODUTOS
   WHERE MREAL < 25 --PARAMETRO
   ORDER BY DATA DESC, MREAL;


------MYAUDIT
WITH PRODUTOS AS
 (SELECT C.CODFILIAL FILIAL,
         C.DATA,
         C.NUMPED,
         NVL(U.USURDIRFV, U.NOME) VENDEDOR,
         (C.CODCLI || '-' || T.CLIENTE) CLIENTE,
         A.RAMO,
         (P.CODPROD || '-' || P.DESCRICAO) PRODUTO,
         M.MARCA,
         (I.PVENDA * I.QT) VLPEDIDO,
         ROUND((I.VLCUSTOFIN * I.QT), 2) VLCMV,
         ROUND(I.CUSTOFINEST, 2) CUSTO_1103,
         ROUND((((I.PVENDA - I.VLCUSTOFIN) /
               DECODE(NVL(I.PVENDA, 0), 0, 1, I.PVENDA)) * 100),
               2) MREAL,
         NVL(R.MARGEM, 0) MPREV,
         (E.QTESTGER - E.QTRESERV - E.QTINDENIZ) QTDISP          
    FROM PCPEDC C
    JOIN PCPEDI I ON I.NUMPED = C.NUMPED
    JOIN PCCLIENT T ON T.CODCLI = C.CODCLI
    JOIN PCPRODUT P ON P.CODPROD = I.CODPROD
    LEFT JOIN PCMARCA M ON M.CODMARCA = P.CODMARCA
    LEFT JOIN PCPRACA PR ON PR.CODPRACA = C.CODPRACA
    LEFT JOIN PCTABPR R ON R.NUMREGIAO = PR.NUMREGIAO AND R.CODPROD = P.CODPROD
    LEFT JOIN PCEST E ON E.CODFILIAL = C.CODFILIAL AND E.CODPROD = P.CODPROD
    LEFT JOIN PCATIVI A ON A.CODATIV = T.CODATV1
    LEFT JOIN PCUSUARI U ON U.CODUSUR = C.CODUSUR
   WHERE 1 = 1
     AND C.POSICAO NOT IN ('C')
     AND C.CONDVENDA IN (1)
     AND P.CODMARCA NOT IN ([RETIRAR_CODMARCA])
     AND C.CODCOB NOT IN ('CONV', 'C')
     AND (I.PVENDA * I.QT) > 1
     AND C.DATA >= TRUNC(SYSDATE) - [DIAS]
     AND ((C.CODFILIAL IN ([CODFILIAL])) OR ('99' IN ([CODFILIAL]))))
SELECT *
  FROM PRODUTOS
 WHERE MREAL < [MARGEM]
 ORDER BY DATA DESC, MREAL;
