SELECT DISTINCT F.CODFILIAL,
                (F.ESPECIE || ' ' || F.NUMNOTA) NUMNOTA,
                F.DTSAIDA,
                (F.CODCLI || ' - ' || F.CLIENTE) CLIENTE,
                F.VLTOTGER,
                F.CAIXA NUM_CAIXA,
                (F.CODEMITENTE || ' - ' || E.NOME) FUNC_CAIXA,
                (F.CODUSUR || ' - ' || U.NOME) VENDEDOR,
                LISTAGG(M.DESCRICAO, ' | ') WITHIN GROUP(ORDER BY M.DESCRICAO) OVER(PARTITION BY F.NUMNOTA) PRODUTOS
  FROM PCMOV M
  JOIN PCNFSAID F ON M.NUMTRANSVENDA = F.NUMTRANSVENDA
  LEFT JOIN PCUSUARI U ON F.CODUSUR = U.CODUSUR
  LEFT JOIN PCEMPR E ON F.CODEMITENTE = E.MATRICULA
  LEFT JOIN PCPLPAG P ON F.CODPLPAG = P.CODPLPAG
 WHERE F.CODPLPAG = 126
   AND F.DTSAIDA > TRUNC(SYSDATE) - 30
 ORDER BY F.DTSAIDA;
