SELECT F.CODFILIAL,
       F.ESPECIE,
       F.SERIE,
       F.DTSAIDA,
       F.CODCLI,
       C.CLIENTE,
       F.NUMNOTA,
       F.VLTOTGER,
       F.CODPLPAG,
       P.DESCRICAO PLANO,
       F.CAIXA NUM_CAIXA,
       F.CODEMITENTE,
       E.NOME FUNC_CAIXA,
       F.CODUSUR,
       U.NOME VENDEDOR
  FROM PCNFSAID F,
       PCCLIENT C,
       PCUSUARI U,
       PCEMPR E,
       PCPLPAG P
 WHERE F.CODCLI = C.CODCLI
   AND F.CODUSUR = U.CODUSUR
   AND F.CODEMITENTE = E.MATRICULA
   AND F.CODPLPAG = P.CODPLPAG
   AND F.CODPLPAG = 126
   AND DTSAIDA > TRUNC (SYSDATE) - 30
 ORDER BY F.DTSAIDA;
/