WITH PEDIDOS_MESMO_CLIENTE AS (
    SELECT C.CGCENT
      FROM PCPEDC P
     INNER JOIN PCCLIENT C ON P.CODCLI = C.CODCLI
     WHERE P.DATA >= TRUNC (SYSDATE) - 2
       AND P.CODSUPERVISOR IN (
        7, 8
    )
       AND P.POSICAO NOT IN (
        'C'
    )
     GROUP BY C.CGCENT
    HAVING COUNT (C.CGCENT) > 1
)
SELECT P.DATA,
       P.NUMPEDRCA,
       P.NUMPED,
       P.NUMPEDCLI,
       P.CODCLI,
       C.CLIENTE,
       C.CGCENT AS CPF,
       E.NOME AS EMITENTE,
       U.NOME AS CANAL_VENDA,
       P.VLTOTAL
  FROM PCPEDC P
 INNER JOIN PCCLIENT C ON P.CODCLI = C.CODCLI
 INNER JOIN PEDIDOS_MESMO_CLIENTE M ON C.CGCENT = M.CGCENT
  LEFT JOIN PCEMPR E ON P.CODEMITENTE = E.MATRICULA
  LEFT JOIN PCUSUARI U ON P.CODUSUR = U.CODUSUR
 WHERE P.DATA >= TRUNC (SYSDATE) - 2
   AND P.CODSUPERVISOR IN (
    7, 8
)
   AND P.POSICAO NOT IN (
    'C'
)
 ORDER BY C.CGCENT,
          P.DATA DESC;
/