SELECT A.DTSAIDA,
       A.CODUSUR,
       B.NOME,
       B.CODSUPERVISOR,
       C.NOME,
       A.ESPECIE,
       A.NUMNOTA,
       A.CODCLI,
       A.CLIENTE,
       A.UFCODIGO,
       A.VLTOTAL,
       D.CODFORNEC,
       A.TRANSPORTADORA
  FROM PCNFSAID A, PCUSUARI B, PCSUPERV C, PCFORNEC D
 WHERE D.FORNECEDOR = A.TRANSPORTADORA
   AND B.CODSUPERVISOR = C.CODSUPERVISOR
   AND B.CODUSUR = A.CODUSUR
   AND A.CGCFRETE = D.CGC
   AND A.DTSAIDA BETWEEN '01-DEC-2016' AND '30-APR-2017'
   AND B.CODSUPERVISOR NOT IN (5, 7)
   AND A.CODCLI NOT IN (4, 7543)
 ORDER BY DTSAIDA;