SELECT *
  FROM PCLOGALTERACAODADOS
 WHERE OBSERVACOES LIKE '%797510%'
    OR OBSERVACOES2 LIKE '%797510%'
    OR CODIGO LIKE '%797510%'
 ORDER BY DATA DESC;

SELECT *
  FROM PCLOGALTERACAODADOS
 WHERE CODIGO = 6900000185
   AND TABELA = 'PCPEDC'
   --AND OBSERVACOES NOT LIKE '%Liberação%'
 ORDER BY DATA DESC;

SELECT DATA,
       CODIGO,
       CODFUNC,
       OSUSER,
       CODROTINA,
       TABELA,
       COLUNA,
       VALORALFA,
       OBSERVACOES
  FROM PCLOGALTERACAODADOS
 WHERE CODIGO = 4004203
   AND TABELA = 'PCPEDI'
--AND VALORALFA LIKE '%162887%'
 ORDER BY DATA DESC;


