SELECT *
  FROM PCLOGROTINA
 WHERE CODAUXILIAR = 7896027543889
 ORDER BY DATAINICIO DESC;
/
SELECT C.DATAALTER,
       C.CODPROD,
       P.DESCRICAO,
       C.ROTINA,
       C.NUMREGIAO,
       R.REGIAO,
       C.PTABELAANT,
       C.PTABELA,
       C.PVENDAANT,
       C.PVENDA,
       C.MARGEMIDEALANT,
       C.MARGEMIDEALATUAL,
       C.MATRICULA AS CODFUNC,
       E.NOME_GUERRA AS FUNCIONARIO
  FROM PCPRECO C
  LEFT JOIN PCPRODUT P ON C.CODPROD = P.CODPROD
  LEFT JOIN PCREGIAO R ON C.NUMREGIAO = R.NUMREGIAO
  LEFT JOIN PCEMPR E ON C.MATRICULA = E.MATRICULA
 WHERE C.CODPROD = 163066
 ORDER BY C.NUMREGIAO,
          C.DATAALTER DESC;
/
