SELECT DISTINCT COLUMN_NAME, TABLE_NAME
  FROM ALL_TAB_COLUMNS C --, ALL_OBJECTS O
 WHERE C.COLUMN_NAME = 'PERCTXADMINCC'
 ORDER BY TABLE_NAME;
 
 SELECT *
  FROM  ALL_OBJECTS O
 WHERE O.OBJECT_NAME = 'T_PC_CREDITOCLIENTE';
 --ORDER BY TABLE_NAME;
