  BEGIN
    FOR REC IN (
        SELECT OBJECT_NAME
        FROM USER_OBJECTS
        WHERE OBJECT_TYPE = 'TABLE'
    ) LOOP
        EXECUTE IMMEDIATE 'GRANT SELECT ON ' || REC.OBJECT_NAME || ' TO CONSULTA';
        EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE ON ' || REC.OBJECT_NAME || ' TO BROKER';
        EXECUTE IMMEDIATE 'GRANT SELECT ON ' || REC.OBJECT_NAME || ' TO BIJC';
    END LOOP;
  END;
