/*******************************************************************
 --REALIZADOS
 0.GERAR TABELA DE BACKUP COM AS INFORMAÇÕES QUE SERÃO ALTERADAS
 1.INFORMAR OS NUMTRANSVENDA DAS NOTAS DE SAIDA DE TRANSFERENCIA
 2.ALTERAR NA PCNFENT: DTENT, DTSELOFISCAL
 3.ALTERAR NA PCMOV: DTMOV, DTMOVLOG (DATETIME), DATAESTOQUE (DATETIME)
 4.ALTERAR NA PCMOVCOMPLE: DTREGISTRO (DATETIME)
 
 --NÃO REALIZADOS
 5.RECALCULAR NA PCHISTEST: DATA
 6.RECALCULAR NA PCLOGESTOQUE: DATA (DATETIME)
 
 --RODAR LIVROS FISCAIS
*******************************************************************/

/****************TABELAS DE BACKUP********************/
--PCNFENT
CREATE TABLE BKP_PCNFENT_PARCIAL_10_07_2024 AS 
   SELECT E.* FROM PCNFENT E WHERE E.NUMTRANSVENDAORIG IN (22097905, 22098039, 22097506);

--PCMOV
CREATE TABLE BKP_PCMOV_PARCIAL_10_07_2024 AS
  WITH NUMTRANSENT_NOTAS AS
 (SELECT E.NUMTRANSENT
    FROM PCNFENT E
   WHERE E.NUMTRANSVENDAORIG IN (22097905, 22098039, 22097506)) 
  SELECT M.DESCRICAO, M.NUMTRANSENT, M.*
    FROM PCMOV M
    JOIN NUMTRANSENT_NOTAS E ON E.NUMTRANSENT = M.NUMTRANSENT
   WHERE M.CODOPER = 'ET';

--PCMOVCOMPLE
CREATE TABLE BKP_PCMOVCOMPLE_PARCIAL_10_07_2024 AS 
  WITH NUMTRANSENT_NOTAS AS
  (SELECT E.NUMTRANSENT,
         E.DTENT,
         E.DTSELOFISCAL
    FROM PCNFENT E
   WHERE E.NUMTRANSVENDAORIG IN (22097905, 22098039, 22097506)),
 NUMTRANSITEM_PRODUTOS AS
  (SELECT M.DTMOV,
         M.NUMTRANSITEM,
         M.CODPROD,
         M.CODFILIAL
    FROM PCMOV M
    JOIN NUMTRANSENT_NOTAS E ON E.NUMTRANSENT = M.NUMTRANSENT
   WHERE M.CODOPER = 'ET')
 SELECT M.*
    FROM PCMOVCOMPLE M
    JOIN NUMTRANSITEM_PRODUTOS P ON P.NUMTRANSITEM = M.NUMTRANSITEM;

/****************FIM BACKUP********************/

/****************UPDATES NAS TABELAS********************/
--PCNFENT 
--3 REGISTROS
UPDATE PCNFENT
   SET DTENT        = TO_DATE('30/06/2024', 'DD/MM/YYYY'),
       DTSELOFISCAL = TO_DATE('30/06/2024', 'DD/MM/YYYY')
 WHERE NUMTRANSVENDAORIG IN (22097905, 22098039, 22097506);

--PCMOV 
--52 REGISTROS
UPDATE PCMOV
   SET DTMOV       = TO_DATE('30/06/2024', 'DD/MM/YYYY'),
       DTMOVLOG    = TO_DATE('30/06/2024', 'DD/MM/YYYY'),
       DATAESTOQUE = TO_DATE('30/06/2024', 'DD/MM/YYYY')
 WHERE NUMTRANSENT IN
       (SELECT E.NUMTRANSENT
          FROM PCNFENT E
         WHERE E.NUMTRANSVENDAORIG IN (22097905, 22098039, 22097506));

--PCMOVCOMPLE
--52 REGISTROS
UPDATE PCMOVCOMPLE
   SET DTREGISTRO = TO_DATE('30/06/2024', 'DD/MM/YYYY')
 WHERE NUMTRANSITEM IN
       (SELECT M.NUMTRANSITEM
          FROM PCMOV M
          JOIN PCNFENT E ON E.NUMTRANSENT = M.NUMTRANSENT
         WHERE E.NUMTRANSVENDAORIG IN (22097905, 22098039, 22097506)
           AND M.CODOPER = 'ET');

/****************FIM UPDATES********************/

/****************CONSULTAS BASE********************/
WITH NUMTRANSENT_NOTAS AS
 (SELECT E.NUMTRANSENT,
         E.DTENT,
         E.DTSELOFISCAL
    FROM PCNFENT E
   WHERE E.NUMTRANSVENDAORIG IN (22097905, 22098039, 22097506)),
NUMTRANSITEM_PRODUTOS AS
 (SELECT M.DTMOV,
         M.DTMOVLOG,
         M.DATAESTOQUE,
         M.NUMTRANSITEM,
         M.CODPROD,
         M.CODFILIAL
    FROM PCMOV M
    JOIN NUMTRANSENT_NOTAS E ON E.NUMTRANSENT = M.NUMTRANSENT
   WHERE M.CODOPER = 'ET'),
DTREGISTRO_PRODUTOS AS
 (SELECT M.*
    FROM PCMOVCOMPLE M
    JOIN NUMTRANSITEM_PRODUTOS P ON P.NUMTRANSITEM = M.NUMTRANSITEM)

SELECT * FROM NUMTRANSENT_NOTAS;

/***************************************************/
