----BUSCAR O NUMTRANSENT DA DEVOLUCAO
SELECT E.CODFILIAL,
       E.NUMTRANSENT,
       E.*
  FROM PCNFENT E
 WHERE E.CODFORNEC IN (530526, 562366); --1760535

----BUSCAR UM CODIGO QUE NAO FOI USADO AINDA NA PCCRECLI
SELECT CODIGO FROM PCCRECLI C WHERE ROWNUM <= 500 ORDER BY CODIGO DESC;

----VALIDAR O CODIGO ENCONTRADO
SELECT * FROM PCCRECLI C WHERE C.CODIGO = 257438;

----RODAR A PROCEDURE INFORMANDO O PCNFENT.NUMTRANSENT E PCCRECLI.CODIGO
BEGIN
    PRC_INSERE_CREDITO_CLIENTE();
END;
-----------EXCLUIR LANCAMENTO GERADO COMO RECEITA NA PCLANC 
SELECT ROWID,
       L.*
  FROM PCLANC L
 WHERE L.NUMNOTA IN (55957, 68829)
   AND CODFILIAL = '9';

SELECT * FROM PCRATEIOCENTROCUSTO R WHERE R.RECNUM = 6800234;

/***********************************************************************/

------------PROCEDURE CRIADA---------------------
CREATE OR REPLACE PROCEDURE PRC_INSERE_CREDITO_CLIENTE
(
  pNUMTRANSENT IN NUMBER,
  pCODIGO IN NUMBER
) IS

  -----VARIAVEIS PARA RECEBER A INFORMAÇÃO DA PCMOV
  vCODCLI          PCCRECLI.CODCLI%TYPE;
  vDTLANC          PCCRECLI.DTLANC%TYPE;
  vCODFILIAL       PCCRECLI.CODFILIAL%TYPE;
  vNUMNOTA         PCCRECLI.NUMNOTA%TYPE;
  vSERIE           PCCRECLI.SERIE%TYPE;
  vVALOR           PCCRECLI.VALOR%TYPE;
  vCODFUNC         PCCRECLI.CODFUNC%TYPE;
  vHORA            PCCRECLI.HORA %TYPE;
  vMINUTO          PCCRECLI.MINUTO %TYPE;
  vDTEMISSAOTITULO PCCRECLI.DTEMISSAOTITULO%TYPE;

BEGIN

  SELECT E.CODFORNEC,
         E.DTEMISSAO,
         E.CODFILIAL,
         E.NUMNOTA,
         E.SERIE,
         E.VLTOTAL,
         E.CODFUNCLANC,
         E.HORALANC,
         E.MINUTOLANC,
         E.DTEMISSAO
    INTO vCODCLI,
         vDTLANC,
         vCODFILIAL,
         vNUMNOTA,
         vSERIE,
         vVALOR,
         vCODFUNC,
         vHORA,
         vMINUTO,
         vDTEMISSAOTITULO
    FROM PCNFENT E
   WHERE E.NUMTRANSENT = pNUMTRANSENT;

  ---INSERCAO DOS DADOS
  INSERT INTO PCCRECLI
    (CODCLI,
     DTLANC,
     CODFILIAL,
     NUMNOTA,
     NUMTRANSVENDA,
     SERIE,
     VALOR,
     DTDESCONTO,
     CODFILIALDESC,
     NUMNOTADESC,
     SERIEDESC,
     CODFUNC,
     HORA,
     MINUTO,
     ORIGEM,
     NUMTRANSVENDADESC,
     NUMTRANSENTDEVCLI,
     HISTORICO,
     CODFUNCLANC,
     NUMPED,
     NUMERARIO,
     CODMOVIMENTO,
     NUMLANCBAIXA,
     NUMTRANSBAIXA,
     NUMLANC,
     NUMTRANS,
     SITUACAO,
     NUMINDENIZ,
     CODROTINA,
     PRESTRESTCLI,
     NUMPEDECF,
     NUMCAIXA,
     CODFUNCCX,
     NUMSERIEEQUIP,
     CODIGO,
     VALORESTORNOLIBERADO,
     OBS,
     CODADMCARTAO,
     NUMCUPOM,
     NSUTEF,
     BIN,
     CODCLIORIG,
     NUMGIFTCARD,
     DTEMISSAOTITULO,
     NUMCRED,
     DTESTORNO,
     ROTINAINSERT,
     ROTINAULTIMAALTERACAO,
     ROTINAESTORNO,
     ROTINABAIXA,
     DTVENC,
     PRESTORIG,
     ESC_DTREFERENCIA,
     STATUS,
     CODPLPAG,
     OBSLIBERADO,
     DTCANCEL)
  VALUES
    (vCODCLI,
     vDTLANC,
     vCODFILIAL,
     vNUMNOTA,
     NULL,
     vSERIE,
     vVALOR,
     NULL,
     NULL,
     NULL,
     NULL,
     vCODFUNC,
     vHORA,
     vMINUTO,
     NULL,
     NULL,
     pNUMTRANSENT,
     'DEVOLUCAO',
     vCODFUNC,
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     1346,
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     pCODIGO,
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     vDTEMISSAOTITULO,
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     NULL);

  COMMIT;

END;
