WITH DATAS AS
 (SELECT (TO_DATE('01/01/2010', 'DD/MM/YYYY') + LEVEL - 1) DT, TRUNC(SYSDATE) DTHOJE
    FROM DUAL
  CONNECT BY LEVEL <= (TO_DATE('31/01/2027', 'DD/MM/YYYY') -
             TO_DATE('01/01/2010', 'DD/MM/YYYY')) + 1)

SELECT DT AS DATA,
       EXTRACT(DAY FROM DT) DIA,
       EXTRACT(YEAR FROM DT) ANO,
       EXTRACT(MONTH FROM DT) NUM_MES,
       INITCAP(TO_CHAR(DT, 'MONTH', 'NLS_DATE_LANGUAGE=PORTUGUESE')) NOME_MES,
       INITCAP(TO_CHAR(DT, 'MON', 'NLS_DATE_LANGUAGE=PORTUGUESE')) NOME_MES_ABREV,
       (EXTRACT(YEAR FROM DT) * 100) + EXTRACT(MONTH FROM DT) NUM_MES_ANO,
       (EXTRACT(YEAR FROM DT) * 12) + (EXTRACT(MONTH FROM DT) - 1) NUM_MES_ANO_SEQ,
       INITCAP(TO_CHAR(DT, 'MON', 'NLS_DATE_LANGUAGE=PORTUGUESE')) || '/' ||
       TO_CHAR(DT, 'YYYY') MES_ANO,
       CEIL(EXTRACT(MONTH FROM DT) / 3) NUM_TRIMESTRE,
       CEIL(EXTRACT(MONTH FROM DT) / 3) || 'º ' || 'Trimestre' NOME_TRIMESTRE,
       CEIL(EXTRACT(MONTH FROM DT) / 3) || 'º ' || 'Tri' NOME_TRIMESTRE_ABREV,
       (EXTRACT(YEAR FROM DT) * 100) + CEIL(EXTRACT(MONTH FROM DT) / 3) NUM_TRIMESTRE_ANO,
       CEIL(EXTRACT(MONTH FROM DT) / 3) || 'º ' || 'Tri/' ||EXTRACT(YEAR FROM DT) NOME_TRIMESTRE_ANO,
       TO_NUMBER(TO_CHAR(DT, 'W')) NUM_SEMANA_MES,
       TO_NUMBER(TO_CHAR(DT, 'W')) || 'º ' || 'Semana' SEMANA_MES,
       TO_NUMBER(TO_CHAR(DT, 'WW')) NUM_SEMANA_ANO,
       TO_NUMBER(TO_CHAR(DT, 'WW')) || 'º ' || 'Sem. Ano' SEMANA_ANO,
       TO_NUMBER(TO_CHAR(DT, 'D')) NUM_DIA_SEMANA,
       INITCAP(TO_CHAR(DT, 'DAY', 'NLS_DATE_LANGUAGE=PORTUGUESE')) NOME_DIA_SEMANA,
       INITCAP(TO_CHAR(DT, 'DY', 'NLS_DATE_LANGUAGE=PORTUGUESE')) NOME_ABREV_DIA_SEMANA,
       (EXTRACT(YEAR FROM DT) - EXTRACT(YEAR FROM DTHOJE)) * 12 + EXTRACT(MONTH FROM DT) - EXTRACT(MONTH FROM DTHOJE) CALCULO_MES_ATUAL,
       (EXTRACT(YEAR FROM DT) - EXTRACT(YEAR FROM DTHOJE)) * 4 + CEIL(EXTRACT(MONTH FROM DT)/3) - CEIL(EXTRACT(MONTH FROM DTHOJE)/3) CALCULO_TRIMESTRE_ATUAL,
       (EXTRACT(YEAR FROM DT) - EXTRACT(YEAR FROM DTHOJE)) CALCULO_ANO_ATUAL
  FROM DATAS
