WITH DATAS AS
 (SELECT (TO_DATE('01/01/2010', 'DD/MM/YYYY') + LEVEL - 1) DT, TRUNC(SYSDATE) vDTHOJE
    FROM DUAL
  CONNECT BY LEVEL <= (TO_DATE('31/01/2027', 'DD/MM/YYYY') -
             TO_DATE('01/01/2010', 'DD/MM/YYYY')) + 1),

    CALENDARIO AS
     (SELECT DT AS DATA,
             EXTRACT(DAY FROM DT) DIA,
             EXTRACT(YEAR FROM DT) ANO,
             EXTRACT(MONTH FROM DT) NUM_MES,
             INITCAP(TO_CHAR(DT, 'MONTH', 'NLS_DATE_LANGUAGE=PORTUGUESE')) NOME_MES,
             INITCAP(TO_CHAR(DT, 'MON', 'NLS_DATE_LANGUAGE=PORTUGUESE')) NOME_MES_ABREV,
             (EXTRACT(YEAR FROM DT) * 100) + EXTRACT(MONTH FROM DT) NUM_MES_ANO,
             (EXTRACT(YEAR FROM DT) * 12) + (EXTRACT(MONTH FROM DT) - 1) NUM_MES_ANO_SEQ,
             INITCAP(TO_CHAR(DT, 'MON', 'NLS_DATE_LANGUAGE=PORTUGUESE')) || '/' ||
             TO_CHAR(DT, 'YYYY') MES_ANO,
             TO_NUMBER(TO_CHAR(DT, 'DDD')) NUM_DIA_ANO,
             CEIL(EXTRACT(MONTH FROM DT) / 3) NUM_TRIMESTRE,
             CEIL(EXTRACT(MONTH FROM DT) / 3) || 'º ' || 'Trimestre' NOME_TRIMESTRE,
             CEIL(EXTRACT(MONTH FROM DT) / 3) || 'º ' || 'Tri' NOME_TRIMESTRE_ABREV,
             (EXTRACT(YEAR FROM DT) * 100) +
             CEIL(EXTRACT(MONTH FROM DT) / 3) NUM_TRIMESTRE_ANO,
             CEIL(EXTRACT(MONTH FROM DT) / 3) || 'º ' || 'Tri/' ||
             EXTRACT(YEAR FROM DT) NOME_TRIMESTRE_ANO,
             (CASE
               WHEN (CEIL(EXTRACT(MONTH FROM DT) / 3) = 4 AND
                    EXTRACT(MONTH FROM DT) = 10 AND
                    EXTRACT(DAY FROM DT) <= 12) THEN
                3
               ELSE
                CEIL(EXTRACT(MONTH FROM DT) / 3)
             END) NUM_TRIMESTRE_JC,
             TO_NUMBER(TO_CHAR(DT, 'W')) NUM_SEMANA_MES,
             TO_NUMBER(TO_CHAR(DT, 'W')) || 'º ' || 'Semana' NOME_SEMANA_MES,
             TO_NUMBER(TO_CHAR(DT, 'WW')) NUM_SEMANA_ANO,
             TO_NUMBER(TO_CHAR(DT, 'WW')) || 'º ' || 'Sem. Ano' NOME_SEMANA_ANO,
             TO_NUMBER(TO_CHAR(DT, 'D')) NUM_DIA_SEMANA,
             INITCAP(TO_CHAR(DT, 'DAY', 'NLS_DATE_LANGUAGE=PORTUGUESE')) NOME_DIA_SEMANA,
             INITCAP(TO_CHAR(DT, 'DY', 'NLS_DATE_LANGUAGE=PORTUGUESE')) NOME_DIA_SEMANA_ABREV,
             (EXTRACT(YEAR FROM DT) - EXTRACT(YEAR FROM vDTHOJE)) * 12 +
             EXTRACT(MONTH FROM DT) - EXTRACT(MONTH FROM vDTHOJE) CALCULO_MES_ATUAL,
             (EXTRACT(YEAR FROM DT) - EXTRACT(YEAR FROM vDTHOJE)) * 4 +
             CEIL(EXTRACT(MONTH FROM DT) / 3) -
             CEIL(EXTRACT(MONTH FROM vDTHOJE) / 3) CALCULO_TRIMESTRE_ATUAL,
             (EXTRACT(YEAR FROM DT) - EXTRACT(YEAR FROM vDTHOJE)) CALCULO_ANO_ATUAL,
             (FN_BI_DIA_UTIL_FINANCEIRO(DT)) DIA_UTIL_FINANCEIRO
        FROM DATAS)
    
    SELECT C.DATA,
           C.DIA,
           C.ANO,
           C.NUM_MES,
           C.NOME_MES,
           C.NOME_MES_ABREV,
           C.NUM_DIA_ANO,
           C.NUM_MES_ANO,
           C.NUM_MES_ANO_SEQ,
           C.MES_ANO,
           C.NUM_TRIMESTRE,
           C.NOME_TRIMESTRE,
           C.NOME_TRIMESTRE_ABREV,
           C.NUM_TRIMESTRE_ANO,
           C.NOME_TRIMESTRE_ANO,
           C.NUM_TRIMESTRE_JC,
           (C.NUM_TRIMESTRE_JC || 'º ' || 'Trimestre') NOME_TRIMESTRE_JC,
           (C.NUM_TRIMESTRE_JC || 'º ' || 'Tri') NOME_TRIMESTRE_ABREV_JC,
           ((C.ANO * 100) + C.NUM_TRIMESTRE_JC) NUM_TRIMESTRE_ANO_JC,
           C.NUM_TRIMESTRE_JC || 'º ' || 'Tri/' || C.ANO NOME_TRIMESTRE_ANO_JC,
           C.NUM_SEMANA_MES,
           C.NOME_SEMANA_MES,
           C.NUM_SEMANA_ANO,
           C.NOME_SEMANA_ANO,
           C.NUM_DIA_SEMANA,
           C.NOME_DIA_SEMANA,
           C.NOME_DIA_SEMANA_ABREV,
           C.CALCULO_MES_ATUAL,
           C.CALCULO_TRIMESTRE_ATUAL,
           C.CALCULO_ANO_ATUAL,
           C.DIA_UTIL_FINANCEIRO
      FROM CALENDARIO C
