SELECT M.DTCADASTRO,
       P.CODPROD,
       P.DESCRICAO,
       P.CODAUXILIAR,
       M.QTREGISTRADA,
       T.PVENDA,
       A.NUMREGIAO,
       A.PRECOFIXO,
       A.DTFIMVIGENCIA,
       CASE
         WHEN M.DTCADASTRO <= A.DTFIMVIGENCIA THEN
          A.PRECOFIXO
         ELSE
          T.PVENDA
       END PCERTO
  FROM PCMOVLOJAITEM M,
       PCPRODUT P,
       PCTABPR T,
       PCPRECOPROM A,
       (SELECT LEVEL AS LVL
          FROM DUAL
        CONNECT BY LEVEL <= (SELECT MAX(QTREGISTRADA)
                               FROM PCMOVLOJAITEM
                              WHERE CODMOVLOJA = 23876)) AUX
 WHERE P.CODPROD = M.CODPROD
   AND P.CODPROD = T.CODPROD
   AND T.CODPROD = A.CODPROD(+)
   AND T.NUMREGIAO = A.NUMREGIAO(+)
   AND AUX.LVL BETWEEN 1 AND M.QTREGISTRADA
   AND M.CODMOVLOJA = 23876
   AND T.NUMREGIAO = '100'
 ORDER BY P.CODPROD;