SELECT A.CODIGO,
       A.ROTINA,
       A.NOMEROTINA,
       A.VERSAOCOMPLETA,
       (NVL(A.QTUTILIZACAO, 0)) QTD
  FROM PCROTINA A
 WHERE A.QTUTILIZACAO IS NOT NULL
   AND A.VERSAOCOMPLETA NOT LIKE '29%'
 ORDER BY A.QTUTILIZACAO DESC;