/******
        PRIMEIRO DEVEMOS PEGAR QUAIS SÃO OS REGISTROS A SEREM REPLICADOS PARA AS DEMAIS FILIAIS
        DEPOIS EXPORTAR O ARQUIVO PARA EXCEL
*******/
SELECT CODPROD,
       NUMREGIAO,
       PRECOFIXO,
       DTINICIOVIGENCIA,
       DTFIMVIGENCIA,
       CODFILIAL,
       CODPRECOPROM
  FROM PCPRECOPROM P
 WHERE /*P.DTINICIOVIGENCIA = '19/01/2024'
   AND */ p.dtfimvigencia >= TRUNC(SYSDATE)
	 AND P.NUMREGIAO = 100
   AND P.CODFILIAL = '12'
   --AND P.CODFUNCULTALTER = 3;
;
/******
        VERIFICAR QUAL O ULTIMO CODPRECOPROM ENTRANDO NA SEQUENCE DFSEQ_PCPRECOPROM
				E PEGANDO O VALOR DO CAMPO NEXT NUMBER 
*******/


/******
        NO EXCEL, TROCAR A VIRGULA POR PONTO, ALTERAR A FILIAL E A SEQUENCIA DE CODPRECOPROM
        
        CHAMAR A PROCEDURE PCR_REPLICA_PRECO_PROM PASSANDO OS CAMPOS COMO ARGUMENTO, MUDANDO
        APENAS A FILIAL A SER REPLICADA, CONFORME EXEMPLO ABAIXO
*******/

BEGIN
	PRC_REPLICA_PRECO_PROM(822106, 100, 39.99, TO_DATE('19/01/2024', 'DD/MM/YYYY'), TO_DATE('01/01/2050', 'DD/MM/YYYY'), '8', 49247);
  DBMS_OUTPUT.PUT_LINE('Procedimento executada com sucesso');
END;  
	

/******
        VERIFICAR MAIOR VALOR DA COLUNA CODPRECOPROM E ATUALIZAR O SEQUENCE PARA O CODPRECOPROM 
				SEGUINTE AO ULTIMO VALOR UTILIZADO APOS RODAR A INSERÇÃO DOS NOVOS DADOS
*******/

SELECT MAX(CODPRECOPROM) ULTIMO_CODPRECOPROM FROM PCPRECOPROM;

