/*- DELETAR TUDO DA FILIAL (DESTINO-NOVA)---*/
DELETE FROM PCPARAMFILIAL
 WHERE CODFILIAL = (DESTINO - NOVA);
/

/*- CRIAR UMA TABELA TEMPORÁRIA----*/
CREATE TABLE TEMP
    AS
        SELECT *
          FROM PCPARAMFILIAL
         WHERE CODFILIAL = (FILIAL - ORIGEM);
/
/*ATUALIZAR TABELA TEMPORÁRIA COM A NOVA */
UPDATE TEMP
   SET
    CODFILIAL = (DESTINO - NOVA);
/

/*--INSERIR INFORAMAÇÕES DA TABELA TEMPORÁRIA NA TABELA DA 132----*/
    INSERT INTO PCPARAMFILIAL
        SELECT *
          FROM TEMP;
/