CREATE TABLE BROKERCONTABIL (
    CODFILIAL   NUMBER (2),
    CODFORNEC   NUMBER (6),
    CODCONTAB   NUMBER (6)
);
/
ALTER TABLE BROKERCONTABIL MODIFY
    CODCONTAB NUMBER (6);
/
INSERT INTO BROKERCONTABIL (
    CODFILIAL,
    CODFORNEC,
    CODCONTAB
) VALUES (
    1, 1, 1103
);
/
SELECT *
  FROM BROKERCONTABIL
 WHERE CODFILIAL = 5
 ORDER BY CODFILIAL;
/
SELECT COUNT (CODFORNEC),
       CODCONTAB
  FROM BROKERCONTABIL
 WHERE CODFILIAL = 1
 GROUP BY CODCONTAB
HAVING COUNT (CODFORNEC) > 1;
/
SELECT B.CODFILIAL,
       B.CODFORNEC,
       F.FORNECEDOR,
       F.CGC,
       F.ESTADO,
       B.CODCONTAB
  FROM BROKERCONTABIL B
  LEFT JOIN PCFORNEC F ON B.CODFORNEC = F.CODFORNEC
 WHERE B.CODCONTAB IN (
    1077
)
 ORDER BY B.CODFORNEC,
          B.CODFILIAL;
/