CREATE OR REPLACE TRIGGER TRG_GRANT_SELECT
AFTER CREATE ON SCHEMA
BEGIN
    FOR REC IN (
        SELECT OBJECT_NAME
        FROM USER_OBJECTS
        WHERE OBJECT_TYPE = 'TABLE'
        AND CREATED > SYSDATE - INTERVAL '1' SECOND
    ) LOOP
        EXECUTE IMMEDIATE 'GRANT SELECT ON ' || REC.OBJECT_NAME || ' TO CONSULTA';
        EXECUTE IMMEDIATE 'GRANT SELECT ON ' || REC.OBJECT_NAME || ' TO BROKER';
        EXECUTE IMMEDIATE 'GRANT SELECT ON ' || REC.OBJECT_NAME || ' TO BIJC';
    END LOOP;
END;
