SELECT *
  FROM (
    SELECT CODFILIAL,
           CODPROD,
           (QTESTGER - (PCEST.QTRESERV - PCEST.QTBLOQUEADA)) AS DISPONIVEL
      FROM PCEST
     WHERE CODFILIAL IN (
        2, 7
    )
       AND PCEST.CODPROD = 162887
) PIVOT (
    AVG (DISPONIVEL)
    FOR CODFILIAL
    IN (7, 2)
);
/
SELECT *
  FROM (
    SELECT M.CODPROD,
           C.CODREDE,
           QT
      FROM PCMOV M,
           PCNFSAID S,
           PCCLIENT C
     WHERE M.NUMTRANSVENDA = S.NUMTRANSVENDA
       AND C.CODCLI = S.CODCLI
       AND S.CONDVENDA = 1
       AND M.CODPROD IN (
        803135, 803134, 797381, 806615, 801919
    )
) PIVOT (
    SUM (QT)
    FOR CODREDE
    IN (272, 254, 459, 471, 415)
)
 ORDER BY CODPROD;
/