/***********************************************************
SCRIPT PARA FAZER A TROCA DO VENDEDOR 37 DOS CLIENTES 
ECOMMERCE QUE COMPRARAM SOMENTE EM MARKETPLACE
************************************************************/
WITH CLIENTE_VTEX AS
 (SELECT P.CODCLI,
         MAX(P.CODUSUR) CODUSUR
    FROM PCPEDC P
    JOIN PCUSUARI U ON U.CODUSUR = P.CODUSUR
    LEFT JOIN PCSUPERV V ON V.CODSUPERVISOR = U.CODSUPERVISOR
   WHERE (P.CODUSUR = 37 OR V.CODGERENTE = 3)
   GROUP BY P.CODCLI),
CLIENTES_PARA_MODIFICAR AS
 (SELECT C.CODCLI,
         C.CLIENTE,
         C.EMAIL
    FROM PCCLIENT C
    LEFT JOIN CLIENTE_VTEX V ON V.CODCLI = C.CODCLI
   WHERE C.CODUSUR1 = 37
     AND LENGTH(REGEXP_REPLACE(C.CGCENT, '[^0-9]', '')) = 11
     AND V.CODCLI IS NULL),
NOVO_VENDEDOR AS
 (SELECT P.CODCLI,
         C.CLIENTE,
         C.EMAIL,
         MAX(P.CODUSUR) NOVO_CODUSUR
    FROM PCPEDC P
    JOIN CLIENTES_PARA_MODIFICAR C ON C.CODCLI = P.CODCLI
    LEFT JOIN PCUSUARI U ON U.CODUSUR = P.CODUSUR
   GROUP BY P.CODCLI,
            C.CLIENTE,
            C.EMAIL
   ORDER BY P.CODCLI)
SELECT * FROM NOVO_VENDEDOR ; 

MERGE INTO PCCLIENT C
USING (
  WITH CLIENTE_VTEX AS
   (SELECT P.CODCLI,
           MAX(P.CODUSUR) CODUSUR
      FROM PCPEDC P
      JOIN PCUSUARI U ON U.CODUSUR = P.CODUSUR
      LEFT JOIN PCSUPERV V ON V.CODSUPERVISOR = U.CODSUPERVISOR
     WHERE (P.CODUSUR = 37 OR V.CODGERENTE = 3)
     GROUP BY P.CODCLI),
  CLIENTES_PARA_MODIFICAR AS
   (SELECT C.CODCLI,
           C.CLIENTE
      FROM PCCLIENT C
      LEFT JOIN CLIENTE_VTEX V ON V.CODCLI = C.CODCLI
     WHERE C.CODUSUR1 = 37
       AND LENGTH(REGEXP_REPLACE(C.CGCENT, '[^0-9]', '')) = 11
       AND V.CODCLI IS NULL)
  SELECT P.CODCLI,
         MAX(P.CODUSUR) NOVO_CODUSUR
    FROM PCPEDC P
    JOIN CLIENTES_PARA_MODIFICAR C ON C.CODCLI = P.CODCLI
    LEFT JOIN PCUSUARI U ON U.CODUSUR = P.CODUSUR
   GROUP BY P.CODCLI) X 
   ON (C.CODCLI = X.CODCLI) 
   WHEN MATCHED THEN
    UPDATE SET C.CODUSUR1 = X.NOVO_CODUSUR;

--SELECT COUNT(*) FROM NOVO_VENDEDOR --411872
--SELECT COUNT(*) FROM CLIENTES_PARA_MODIFICAR --459298
SELECT U.NOME,
       C.*
  FROM PCPEDC C
  JOIN PCUSUARI U ON U.CODUSUR = C.CODUSUR
 WHERE C.CODCLI = 559987;
