-----SCRIPT DE CONSULTA-----
SELECT C.CODREDE,
       R.DESCRICAO,
       C.CODCLI,
       C.CLIENTE,
       C.CONDVENDA1,
       C.CONDVENDA7,
       C.CONDVENDA8
  FROM PCCLIENT C, PCREDECLIENTE R
 WHERE C.CODREDE = R.CODREDE
   AND C.CODREDE = 726
   AND (C.CONDVENDA7 = 'N' OR C.CONDVENDA8 = 'N');


-----SCRIPT DE ATUALIZAÇÃO-----
UPDATE PCCLIENT
   SET CONDVENDA7 = 'S', CONDVENDA8 = 'S'
 WHERE CODREDE = 726
   AND (CONDVENDA7 = 'N' OR CONDVENDA8 = 'N');
