-----SCRIPT DE CONSULTA-----
SELECT C.NUMPED,
       C.CODCLI,
       T.CLIENTE,
       T.BLOQUEIO,
       T.DTDESBLOQUEIO,
       T.CODFUNCULTALTER1203,
       C.CONDVENDA,
       C.CODCOB,
       C.POSICAO
  FROM PCPEDC C, PCCLIENT T
 WHERE C.CODCLI = T.CODCLI
   AND C.CODCOB = 'SENT'
   AND T.BLOQUEIO = 'S'
   AND C.POSICAO IN ('B', 'M', 'P');


-----SCRIPT DE ATUALIZAÇÃO-----
UPDATE PCCLIENT
   SET BLOQUEIO = 'N',
       DTDESBLOQUEIO = TRUNC(SYSDATE),
       CODFUNCULTALTER1203 = 45
 WHERE CODCLI IN (25589,25590)
