-----------ENCONTRAR OS CODCLI QUE IREMOS UTILIZAR---------
SELECT CODREDE, CODCLI, CLIENTE FROM PCCLIENT WHERE CODREDE = 47;


-----------VERIFICAR REGISTRO NA TABELA PCTABPRCLI---------
SELECT * FROM PCTABPRCLI WHERE CODCLI = 4486;


-----------INSERÇÃO NA TABELA PCTABPRCLI DIZENDO A FILIAL E A REGIAO-------
INSERT INTO PCTABPRCLI (CODCLI, CODFILIALNF, NUMREGIAO) VALUES ( 'CODIGO CLIENTE' , 'CODIGO FILIAL' , 'REGIAO' ) ;
