WITH CLIENTES_MKT AS
 (SELECT DISTINCT B.CODCLICC, C.CLIENTE CLIENTE_MKT
    FROM PCCOB B
    JOIN PCCLIENT C ON B.CODCLICC = C.CODCLI
   WHERE B.CODCLICC IS NOT NULL),
TOTAL_PREST AS
 (SELECT P.CODCLI,
         P.NUMTRANSVENDA,
         SUM(P.VALOR) TOTPREST,
         LISTAGG('PREST ' || P.PREST || ' ' || P.CODCOB || ' VLPAG: ' ||
                 NVL(P.VPAGO, 0) || ' DTPAG: ' || P.DTPAG,
                 ' || ') WITHIN GROUP(ORDER BY TO_NUMBER(P.PREST)) COMPLEMENTO
    FROM PCPREST P
   WHERE P.CODCOB NOT IN ('DESD')
   GROUP BY P.CODCLI, P.NUMTRANSVENDA)
SELECT DISTINCT C.CODFILIAL,
                T.CODCLIPRINC,
                M.CLIENTE_MKT,
                C.CODCLI,
                T.CLIENTE,
                C.DTLANC,
                P.NUMNOTA,
                C.VALOR,
                COALESCE(P.NUMPEDCLI, TP.NUMPEDCLI) NUMPEDCLI,
                M.NUMTRANSDEV,
                L.TOTPREST,
                L.COMPLEMENTO
  FROM PCCRECLI C
  LEFT JOIN PCCLIENT T ON C.CODCLI = T.CODCLI
  JOIN CLIENTES_MKT M ON M.CODCLICC = T.CODCLIPRINC
  LEFT JOIN PCMOV M ON M.NUMTRANSENT = C.NUMTRANSENTDEVCLI
  LEFT JOIN PCPEDC P ON P.NUMTRANSVENDA = M.NUMTRANSDEV
  LEFT JOIN PCPEDCTEMP TP ON TP.NUMPED = P.NUMPED
  LEFT JOIN TOTAL_PREST L ON L.NUMTRANSVENDA = M.NUMTRANSDEV
                         AND L.CODCLI = M.CODCLICC
 WHERE C.DTDESCONTO IS NULL
   AND P.NUMNOTA IS NOT NULL
	 AND C.CODFILIAL = '9' AND T.CODCLIPRINC = 63722
 ORDER BY TO_NUMBER(C.CODFILIAL), T.CODCLIPRINC, C.DTLANC;
