-------ENCONTRANDO O NUMTRANSENT A PARTIR DO NUMTRANSVENDA------
SELECT * FROM PCESTCOM WHERE NUMTRANSVENDA = 10104160;

-------ANÁLISE VALOR DA NOTA DE DEVOLUÇÃO----------
SELECT * FROM PCNFENT WHERE NUMTRANSENT = 43371;

-------ANÁLISE DOS ITENS DA NOTA-----
SELECT M.DTMOV,
       M.CODFILIAL,
       M.CODPROD,
       T.DESCRICAO,
       M.NUMNOTA,
       M.CODOPER,
       M.QT,
       M.PUNIT,
       (ROUND((M.QT*M.PUNIT),2)) VLPRODUTO,
       M.VLFRETE,
       (ROUND((M.QT*M.PUNIT)+(M.QT*M.VLFRETE),2)) VLTOTAL
  FROM PCMOV M, PCPRODUT T
WHERE M.CODPROD = T.CODPROD
   AND M.NUMTRANSENT = 80080
   AND M.NUMTRANSVENDA = 10187675
   ;
-------ANÁLISE MOVIMENTAÇÃO DO CRÉDITO----------
SELECT * FROM PCCRECLI WHERE CODCLI = 75294;
SELECT CODFILIAL,
       NUMCRED,
       DTLANC,
       HORA,
       NUMTRANSVENDA,
       NUMNOTA,
       NUMTRANSVENDADESC,
       NUMTRANSENTDEVCLI,
       VALOR,
       DTDESCONTO,
       CODFUNC,
       CODROTINA,
       HISTORICO
  FROM PCCRECLI
WHERE NUMTRANSVENDA = 10187675
ORDER BY DTLANC, DTDESCONTO;


-------MOVIMENTAÇÃO DUPLICATAS----------
SELECT T.CODFILIALNF FILIAL,
       T.NUMTRANSVENDA NUMTRANS,
       T.DTEMISSAO,
       T.ROTINAINSERT,
       T.DTULTALTER,
       T.CODFUNCULTALTER,
       T.CODCLI,
       C.CLIENTE,
       T.DUPLIC,
       TO_CHAR(T.PREST, '99') PREST,
       T.VALORORIG,
       T.VALOR,
       T.VALORDESC,
       T.TXPERM,
       T.VPAGO,
       T.CODCOBORIG,
       T.CODCOB,
       T.CODBAIXA,
       T.DTBAIXA,
       T.DTPAG,
       T.ROTINALANCULTALT,
       T.FUNCLANC,
       T.ROTINALANC,
       T.ROTINAPAG,
       T.CODFUNCFECHA,
       T.ROTINAFECHA,
       T.ROTINADESD,
       T.CODFUNCDESD,
       T.DTDESD,
       T.DTBAIXACRED,
       T.DTVENCORIG,
       T.DTVENC
  FROM PCPREST T, PCCLIENT C
 WHERE T.CODCLI = C.CODCLI
   AND T.NUMTRANSVENDA = 10104160
 ORDER BY PREST;
 
-------PARA SABER QUAL NOME FUNC PELO CODFUNC----------
SELECT * FROM PCEMPR WHERE MATRICULA = 78;
