WITH TRANSACAO_VENDA AS
 (SELECT NUMTRANSENT, MAX(M.NUMTRANSDEV) AS NUMTRANSVENDA
    FROM PCMOV M
   WHERE NUMTRANSDEV IS NOT NULL
     AND NUMTRANSENT IS NOT NULL
   GROUP BY NUMTRANSENT)
SELECT C.*,
       (SELECT SUM(P.VALOR)
          FROM PCPREST P
         WHERE P.CODCLI = C.CODCLI
           AND P.DTPAG IS NULL) TOTAL_RECEBER_CLIENTE,
       (SELECT SUM(P.VALOR)
          FROM PCPREST P
         WHERE P.CODCLI = C.CODCLIPRINC
           AND P.DTPAG IS NULL) TOTAL_RECEBER_PRINCIPAL
  FROM (SELECT B.CODCLIPRINC,
               (SELECT CLIENTE FROM PCCLIENT WHERE CODCLI = B.CODCLIPRINC) CLIENTE_PRINCIPAL,
               S.CODSUPERVISOR CODSUPERV,
               S.NOME SUPERVISOR,
               B.CODCLI,
               B.CLIENTE,
               A.NUMNOTA NOTA_DEV,
               A.VALOR VL_CREDITOS,
               D.NUMNOTA NOTA_VENDA,
               D.VLTOTGER VL_VENDA,
               D.CODCOB,
               T.CODCLICC,
               (SELECT CLIENTE FROM PCCLIENT WHERE CODCLI = T.CODCLICC) CLIENTE_COBRANCA
          FROM PCCLIENT        B,
               PCCRECLI        A,
               PCSUPERV        S,
               PCUSUARI        I,
               PCNFSAID        D,
               PCCOB           T,
               TRANSACAO_VENDA TV
         WHERE B.CODCLI = D.CODCLI
           AND I.CODUSUR = B.CODUSUR1
           AND I.CODSUPERVISOR = S.CODSUPERVISOR
           AND D.NUMTRANSVENDA = TV.NUMTRANSVENDA
           AND A.NUMTRANSENTDEVCLI = TV.NUMTRANSENT
           AND T.CODCOB = D.CODCOB
           AND NVL(A.VALOR, 0) <> 0
           AND A.DTDESCONTO IS NULL
           AND A.DTESTORNO IS NULL
           AND A.DTLANC <= TRUNC(SYSDATE) - 1
           AND EXISTS (SELECT P.CODCLI
                  FROM PCPREST P
                 WHERE P.CODCLI = B.CODCLIPRINC
                   AND P.DTPAG IS NULL)) C
 ORDER BY CODCLICC, VL_CREDITOS DESC;