 WITH CREDITO AS
  (SELECT CODCLI, SUM(VALOR) AS VALOR_CREDITO
     FROM PCCRECLI
    WHERE DTDESCONTO IS NULL
    GROUP BY CODCLI),
 DUPLICATA AS
  (SELECT CODCLI, SUM(VALOR) AS VALOR_PREST
     FROM PCPREST T
    WHERE T.DTPAG IS NULL
    GROUP BY CODCLI)
 SELECT C.CODCLI, T.CLIENTE, C.VALOR_CREDITO, D.VALOR_PREST
   FROM CREDITO C
  INNER JOIN DUPLICATA D
     ON C.CODCLI = D.CODCLI
  INNER JOIN PCCLIENT T
     ON C.CODCLI = T.CODCLI   
  WHERE C.VALOR_CREDITO > 0
    AND C.CODCLI IN (17427,18633);
