/*VERIFICAR PEDIDO TV 7 ---*/
/*IDENTIFICAR O CODREDE DO CLIENTE E INSERIR CONTA E ORDEM = 'S'--*/
SELECT T.CODREDE,
       C.CONDVENDA,
       C.CONTAORDEM,
       C.POSICAO,
       C.*
  FROM PCPEDC C
  LEFT JOIN PCCLIENT T ON C.CODCLI = T.CODCLI
 WHERE C.CONDVENDA = 7
   AND C.NUMPED = 14006030;
/

/*IDENTIFICAR PEDIDOS TV8--*/
/*INFORMAR CODREDE--*/
SELECT C.CONDVENDA,
       C.CONTAORDEM,
       C.NUMPEDENTFUT,
       C.POSICAO,
       C.*
  FROM PCPEDC C
  LEFT JOIN PCCLIENT T ON C.CODCLI = T.CODCLI
 WHERE C.POSICAO NOT IN (
    'F', 'C'
)
   AND C.CODCOB = 'SENT'
   AND (C.CONTAORDEM IS NULL
    OR NUMPEDENTFUT IS NULL
    OR CONTAORDEM = 'N')
   AND T.CODREDE = 704;
/

/*REALIZAR UPDATE--*/
UPDATE PCPEDC
   SET CONDVENDA = 8,
       CONTAORDEM = 'S',
       NUMPEDENTFUT = 14006030
 WHERE EXISTS (
    SELECT C.CONDVENDA,
           C.CONTAORDEM,
           C.NUMPEDENTFUT
      FROM PCPEDC C
      LEFT JOIN PCCLIENT T ON C.CODCLI = T.CODCLI
     WHERE C.POSICAO NOT IN (
        'F', 'C'
    )
       AND C.CODCOB = 'SENT'
       AND (C.CONTAORDEM IS NULL
        OR NUMPEDENTFUT IS NULL
        OR CONTAORDEM = 'N')
       AND T.CODREDE = 704
       AND C.NUMPED = PCPEDC.NUMPED
);
/

/*VERIFICAR DADOS ALTERADOS--*/
SELECT C.CONDVENDA,
       C.CONTAORDEM,
       C.NUMPEDENTFUT,
       C.POSICAO,
       C.*
  FROM PCPEDC C
  LEFT JOIN PCCLIENT T ON C.CODCLI = T.CODCLI
 WHERE C.POSICAO NOT IN (
    'F', 'C'
)
   AND C.CODCOB = 'SENT'
   AND C.CONDVENDA = 8
   AND T.CODREDE = 704;
/