CREATE OR REPLACE VIEW VIEW_JC_PREST_REDECARD AS

WITH NUMERO_RESUMO AS
 (SELECT DISTINCT P.NUMTRANSVENDA, P.NUMRESUMO, P.PRESTTEF, P.VALOR, P.PERDESC
    FROM PCPREST P
   WHERE P.NUMRESUMO IS NOT NULL)
SELECT P.CODFILIAL,
       P.DTEMISSAO,
       P.DTVENC,
       COALESCE(P.NUMRESUMO, R.NUMRESUMO) NUMRESUMO,
       COALESCE(P.NSUHOST, P.NSUTEF) NSUHOSTTEF,
       P.NUMTRANSVENDA,
       P.PREST,
       P.PRESTTEF,
       P.VALOR,
       (P.VALOR - P.VALORDESC) VLLIQ
  FROM PCPREST P
  JOIN NUMERO_RESUMO R ON R.NUMTRANSVENDA = P.NUMTRANSVENDA AND R.PRESTTEF = P.PRESTTEF AND R.VALOR = P.VALOR AND R.PERDESC = P.PERDESC
 WHERE P.DTPAG IS NULL;
