CREATE OR REPLACE VIEW VIEW_JC_FRETES AS
    SELECT E.CODFILIAL,
           E.DTEMISSAO DTCTE,
           (
               CASE
                   WHEN S.NUMTRANSVENDA IS NOT NULL THEN
                       'S'
                   WHEN E2.NUMTRANSENT IS NOT NULL THEN
                       'E'
                   ELSE
                       'CT'
               END
           ) TIPO,
           E.NUMNOTA NUMNOTA_CTE,
           E.CODFORNEC,
           T.FORNECEDOR,
           COALESCE(S.NUMTRANSVENDA, E2.NUMTRANSENT, 0) NUMTRANSACAO,
           COALESCE(S.CODCLI, E2.CODFORNEC, 10) CODCLI,
           ROUND((E.VLTOTAL / COUNT(E.NUMTRANSENT)
                              OVER(PARTITION BY E.NUMTRANSENT)),
                 2) VLCTE
      FROM PCNFENT E
      JOIN PCFORNEC T ON T.CODFORNEC = E.CODFORNEC
      LEFT JOIN PCCONHECIMENTOFRETEI F ON F.NUMTRANSCONHEC = E.NUMTRANSENT
      LEFT JOIN PCNFSAID S ON S.CHAVENFE = F.CHAVENFE
      LEFT JOIN PCNFENT E2 ON E2.CHAVENFE = F.CHAVENFE
     WHERE E.ESPECIE = 'CT' AND E.DTCANCEL IS NULL;