CREATE OR REPLACE VIEW VIEW_JC_LOGISTICA AS
WITH ITEM_SEPARADO AS
 (SELECT S.NUMPED, SUM(S.QTSEPARADA) QTSEPARADA
    FROM JCITEMSEPARACAO S
   GROUP BY S.NUMPED),
ITENS_PEDIDO AS
 (SELECT I.NUMPED, SUM(I.QT) QTPEDIDO FROM PCPEDI I GROUP BY I.NUMPED),
DATAINICIO_SEP AS
 (SELECT I.PEDIDO_ID NUMPED, MIN(DT_CONF_ORIGEM) DTINICIOSEP
    FROM JCENDOSITEM I
   GROUP BY I.PEDIDO_ID),
DATAFIM_SEP AS
 (SELECT I.PEDIDO_ID NUMPED, MAX(C.DT_FIM) DTFIMSEP
    FROM JCENDOS C
    JOIN JCENDOSITEM I ON C.ID = I.OS_ID
   WHERE C.TIPO_OS = 6
   GROUP BY I.PEDIDO_ID),
SEPARACAO AS
 (SELECT NUMPED,
       DTINICIOSEP,
       QTSEPARADA,
       QTPEDIDO,
       (CASE
         WHEN PERCSEP < 1 THEN
          NULL
         ELSE
          DTFIMSEP
       END) DTFIMSEP,
       PERCSEP
  FROM (SELECT C.NUMPED,
               DI.DTINICIOSEP,
               S.QTSEPARADA,
               I.QTPEDIDO,
               DFS.DTFIMSEP,
               (CASE
                 WHEN NVL(I.QTPEDIDO, 0) = 0 THEN
                  0
                 ELSE
                  ROUND((NVL(S.QTSEPARADA, 0) / I.QTPEDIDO), 2)
               END) PERCSEP
          FROM PCPEDC C
          JOIN ITENS_PEDIDO I ON I.NUMPED = C.NUMPED
          LEFT JOIN ITEM_SEPARADO S ON S.NUMPED = C.NUMPED
          LEFT JOIN DATAINICIO_SEP DI ON DI.NUMPED = C.NUMPED
          LEFT JOIN DATAFIM_SEP DFS ON DFS.NUMPED = C.NUMPED)),
QTITENS_CONFERIDOS AS
 (SELECT C.NUMPED, MIN(C.DATACONF) DTINICIOCONF, SUM(C.QTCONF) QTCONF
    FROM PCITEMLOTECONFERIDO C
   GROUP BY C.NUMPED),
NUMVOL_CONFERIDOS AS
 (SELECT C.NUMPED, MAX(NUMCAIXA) NUMVOLUME
    FROM JCCONFERENCIACAIXA C
   GROUP BY C.NUMPED),
CONFERENCIA AS
 (SELECT C.NUMPED,
       Q.DTINICIOCONF,
       V.NUMVOLUME,
       Q.QTCONF,
       I.QTPEDIDO,
       (CASE WHEN NVL(I.QTPEDIDO,0)= 0 THEN 0 ELSE ROUND((NVL(Q.QTCONF, 0) / I.QTPEDIDO), 2) END) PERCCONF
  FROM PCPEDC C
  JOIN ITENS_PEDIDO I ON I.NUMPED = C.NUMPED
  LEFT JOIN QTITENS_CONFERIDOS Q ON Q.NUMPED = C.NUMPED
  LEFT JOIN NUMVOL_CONFERIDOS V ON V.NUMPED = C.NUMPED),
FATURAMENTO AS
 (SELECT A.NUMPED,
         A.NUMNOTA,
         DTHORAAUTORIZACAOSEFAZ AS DTFAT,
         A.TRANSPORTADORA
    FROM PCNFSAID A),
ROMANEIO_ITEM AS
 (SELECT B.ROMANEIO_ID, B.PEDIDO_ID NUMPED, MIN(B.DT_CONF) DTINICIOEXP
    FROM JCROMANEIOPEDVOL B
   GROUP BY B.PEDIDO_ID, B.ROMANEIO_ID),
EXPEDICAO AS
 (SELECT I.NUMPED,
       I.DTINICIOEXP,
       C.DT_FIM DTFIMEXP,
       (CASE WHEN C.DT_FIM IS NULL THEN NULL ELSE 
       ('PLACA: ' || C.PLACA || ' - ' || 'MOTORISTA: ' || C.MOTORISTA_NOME ||
       ' - ' || 'DOC: ' || NVL(C.MOTORISTA_CPF, C.MOTORISTA_RG)) END) OBSCOLETA
  FROM JCROMANEIOC C
  JOIN ROMANEIO_ITEM I ON I.ROMANEIO_ID = C.ID
 WHERE C.DT_FIM IS NOT NULL AND C.DT_CANCEL IS NULL)
SELECT P.NUMPED,
       S.DTINICIOSEP,
       S.QTSEPARADA,
       S.QTPEDIDO,
       S.DTFIMSEP,
       S.PERCSEP,
       C.DTINICIOCONF,
       C.QTCONF,
       P.DTFINALCHECKOUT DTFIMCONF,
       C.PERCCONF,
       C.NUMVOLUME,
       F.NUMNOTA,
       F.DTFAT,
       F.TRANSPORTADORA,
       E.DTINICIOEXP,
       E.DTFIMEXP,
       E.OBSCOLETA
  FROM PCPEDC P
  LEFT JOIN SEPARACAO S ON P.NUMPED = S.NUMPED
  LEFT JOIN CONFERENCIA C ON P.NUMPED = C.NUMPED
  LEFT JOIN FATURAMENTO F ON P.NUMPED = F.NUMPED
  LEFT JOIN EXPEDICAO E ON P.NUMPED = E.NUMPED
  WHERE P.CONDVENDA IN (1, 5, 8, 9, 10)
    AND P.DATA >= TO_DATE('01/01/2021', 'DD/MM/YYYY');
 /
