CREATE MATERIALIZED VIEW MV_JC_ACOMPANHA_LOG_CORP
REFRESH FORCE ON DEMAND
--ATUALIZACAO COM FREQUENCIA DE 2 MIN
START WITH SYSDATE NEXT SYSDATE + 2/1152 AS

--CREATE OR REPLACE VIEW MV_JC_ACOMPANHA_LOG_CORP AS
WITH ITEM_SEPARADO AS
 (SELECT S.NUMPED, SUM(S.QTSEPARADA) QTSEPARADA
    FROM JCITEMSEPARACAO S
   GROUP BY S.NUMPED),
ITENS_PEDIDO AS
 (SELECT I.NUMPED, SUM(I.QT) QTPEDIDO FROM PCPEDI I GROUP BY I.NUMPED),
DATAINICIO_SEP AS
 (SELECT I.PEDIDO_ID NUMPED, MIN(DT_CONF_ORIGEM) DTINICIOSEP
    FROM JCENDOSITEM I
   GROUP BY I.PEDIDO_ID),
DATAFIM_SEP AS
 (SELECT I.PEDIDO_ID NUMPED, MAX(C.DT_FIM) DTFIMSEP
    FROM JCENDOS C
    JOIN JCENDOSITEM I ON C.ID = I.OS_ID
   WHERE C.TIPO_OS = 6
   GROUP BY I.PEDIDO_ID),
SEPARACAO AS
 (SELECT NUMPED,
         DTINICIOSEP,
         QTSEPARADA,
         QTPEDIDO,
         (CASE
           WHEN PERCSEP < 1 THEN
            NULL
           ELSE
            DTFIMSEP
         END) DTFIMSEP,
         PERCSEP
    FROM (SELECT C.NUMPED,
                 DI.DTINICIOSEP,
                 S.QTSEPARADA,
                 I.QTPEDIDO,
                 DFS.DTFIMSEP,
                 (CASE
                   WHEN NVL(I.QTPEDIDO, 0) = 0 THEN
                    0
                   ELSE
                    ROUND((NVL(S.QTSEPARADA, 0) / I.QTPEDIDO), 2)
                 END) PERCSEP
            FROM PCPEDC C
            JOIN ITENS_PEDIDO I ON I.NUMPED = C.NUMPED
            LEFT JOIN ITEM_SEPARADO S ON S.NUMPED = C.NUMPED
            LEFT JOIN DATAINICIO_SEP DI ON DI.NUMPED = C.NUMPED
            LEFT JOIN DATAFIM_SEP DFS ON DFS.NUMPED = C.NUMPED)),
QTITENS_CONFERIDOS AS
 (SELECT C.NUMPED, MIN(C.DATACONF) DTINICIOCONF, SUM(C.QTCONF) QTCONF
    FROM PCITEMLOTECONFERIDO C
   GROUP BY C.NUMPED),
NUMVOL_CONFERIDOS AS
 (SELECT C.NUMPED, MAX(NUMCAIXA) NUMVOLUME
    FROM JCCONFERENCIACAIXA C
   GROUP BY C.NUMPED),
CONFERENCIA AS
 (SELECT C.NUMPED,
         Q.DTINICIOCONF,
         V.NUMVOLUME,
         Q.QTCONF,
         I.QTPEDIDO,
         (CASE
           WHEN NVL(I.QTPEDIDO, 0) = 0 THEN
            0
           ELSE
            ROUND((NVL(Q.QTCONF, 0) / I.QTPEDIDO), 2)
         END) PERCCONF
    FROM PCPEDC C
    JOIN ITENS_PEDIDO I ON I.NUMPED = C.NUMPED
    LEFT JOIN QTITENS_CONFERIDOS Q ON Q.NUMPED = C.NUMPED
    LEFT JOIN NUMVOL_CONFERIDOS V ON V.NUMPED = C.NUMPED),
FATURAMENTO AS
 (SELECT A.NUMPED,
         A.NUMNOTA,
         DTHORAAUTORIZACAOSEFAZ AS DTFAT,
         A.TRANSPORTADORA
    FROM PCNFSAID A),
ROMANEIO_ITEM AS
 (SELECT B.ROMANEIO_ID, B.PEDIDO_ID NUMPED, MIN(B.DT_CONF) DTINICIOEXP
    FROM JCROMANEIOPEDVOL B
   WHERE DT_CONF IS NOT NULL
   GROUP BY B.PEDIDO_ID, B.ROMANEIO_ID),
EXPEDICAO AS
 (SELECT I.NUMPED,
         I.DTINICIOEXP,
         C.DT_FIM DTFIMEXP,
         (CASE
           WHEN C.DT_FIM IS NULL THEN
            NULL
           ELSE
            ('PLACA: ' || C.PLACA || ' - ' || 'MOTORISTA: ' ||
            C.MOTORISTA_NOME || ' - ' || 'DOC: ' ||
            NVL(C.MOTORISTA_CPF, C.MOTORISTA_RG))
         END) OBSCOLETA
    FROM JCROMANEIOC C
    JOIN ROMANEIO_ITEM I ON I.ROMANEIO_ID = C.ID
   WHERE C.DT_CANCEL IS NULL),
ITENS AS
 (SELECT I.NUMPED, ROUND(SUM(I.QT * (I.PVENDA - I.ST)), 4) VLPEDIDO
    FROM PCPEDI I
   GROUP BY I.NUMPED
  HAVING SUM(I.ST) > 0),
GUIAS AS
 (SELECT L.CODFILIAL, L.NUMNOTA, L.VALOR, L.DTPAGTO
    FROM PCLANC L
   WHERE L.CODCONTA = 140104
     AND L.DTESTORNOBAIXA IS NULL),
ETIQUETAPERSONALIZADA AS
 (SELECT NUMPED FROM BROKER.JCETIQUETAPEDIDOCORP GROUP BY NUMPED),
FILIALRETIRA AS
 (SELECT NUMPED, MAX(I.CODFILIALRETIRA) FILIALRETIRA
    FROM PCPEDI I
   GROUP BY NUMPED)
SELECT P.NUMPED,
       P.DATA,
       P.DTCANCEL,
       (CASE P.CONDVENDA
         WHEN 1 THEN
          'VENDA'
         WHEN 5 THEN
          'BONIFICADO'
         WHEN 7 THEN
          'NOTA MÃE'
         WHEN 8 THEN
          'NOTA FILHA'
         WHEN 9 THEN
          'AMOSTRAS'
         ELSE
          'NOVO TIPO'
       END) TIPO,
       (T.CODREDE || ' - ' || R.DESCRICAO) REDE,
       T.CODCLI,
       T.CLIENTE,
       T.FANTASIA,
       REGEXP_REPLACE(T.CGCENT,
                      '([0-9]{2})([0-9]{3})([0-9]{3})([0-9]{4})',
                      '\1.\2.\3/\4-') CNPJ,
       T.IEENT,
       T.ESTENT UF,
       (CASE WHEN T.MUNICCOM = 'SAO PAULO' THEN (T.MUNICCOM || ' - ' || T.BAIRROCOM) ELSE T.MUNICCOM END) CIDADE,
       T.CEPCOM CEP,
       P.CODFILIAL FILIAL,
       FR.FILIALRETIRA,
       P.NUMPEDCLI,
       NVL(I.VLPEDIDO, P.VLATEND) VLPEDIDO,
       ROUND(P.VLATEND, 2) VLTOTAL,
       (CASE
         WHEN P.CONDVENDA <> 8 AND
              (P.VLATEND - NVL(I.VLPEDIDO, P.VLATEND)) > 0 THEN
          'SIM'
         ELSE
          '-'
       END) GNRE,
       G.VALOR VLGUIA,
       G.DTPAGTO DTPAG,
       (CASE
         WHEN ET.NUMPED IS NOT NULL THEN
          'SIM + PERSONALIZADO'
         ELSE
          DECODE(NVL(P.ESC_PEDIDOEMBRULHADO, 'N'), 'N', 'NÃO', 'SIM')
       END) EMBRULHADO,
       P.OBSENTREGA1 OBSLOGISTICA,
       (P.OBSENTREGA2 || ' ' || P.OBSENTREGA3 || ' ' || P.OBSENTREGA4) OBSENTREGA,
       IP.QTPEDIDO,
       S.DTINICIOSEP,
       S.QTSEPARADA,
       S.DTFIMSEP,
       S.PERCSEP,
       SP.DT_LIMITE DTLIMITE,
       C.DTINICIOCONF,
       C.QTCONF,
       P.DTFINALCHECKOUT DTFIMCONF,
       C.PERCCONF,
       C.NUMVOLUME,
       F.NUMNOTA,
       F.DTFAT,
       F.TRANSPORTADORA,
       E.DTINICIOEXP,
       E.DTFIMEXP,
       E.OBSCOLETA,
       (SYSDATE) DTATUALIZA
  FROM PCPEDC P
  JOIN PCCLIENT T ON T.CODCLI = P.CODCLI
  JOIN FILIALRETIRA FR ON FR.NUMPED = P.NUMPED
  LEFT JOIN PCREDECLIENTE R ON R.CODREDE = T.CODREDE
  LEFT JOIN JCPRIORIDADESEPARACAO SP ON SP.NUMPED = P.NUMPED
  LEFT JOIN SEPARACAO S ON P.NUMPED = S.NUMPED
  LEFT JOIN CONFERENCIA C ON P.NUMPED = C.NUMPED
  LEFT JOIN FATURAMENTO F ON P.NUMPED = F.NUMPED
  LEFT JOIN EXPEDICAO E ON P.NUMPED = E.NUMPED
  LEFT JOIN ITENS_PEDIDO IP ON IP.NUMPED = P.NUMPED
  LEFT JOIN ITENS I ON I.NUMPED = P.NUMPED
  LEFT JOIN GUIAS G ON G.CODFILIAL = P.CODFILIAL
                   AND G.NUMNOTA = F.NUMNOTA
  LEFT JOIN ETIQUETAPERSONALIZADA ET ON ET.NUMPED = P.NUMPED
 WHERE P.CODUSUR = 14
   AND P.DATA >= TO_DATE('01/01/2023', 'DD/MM/YYYY')
 ORDER BY P.DATA;