WITH ITENS AS
 (SELECT I.NUMPED, ROUND(SUM(I.QT * (I.PVENDA - I.ST)), 4) VLPEDIDO
    FROM PCPEDI I
   GROUP BY I.NUMPED
  HAVING SUM(I.ST) > 0),
GUIAS AS
 (SELECT L.CODFILIAL, L.NUMNOTA, L.VALOR, L.DTPAGTO
    FROM PCLANC L
   WHERE L.CODCONTA = 140104),
ETIQUETAPERSONALIZADA AS
 (SELECT NUMPED FROM BROKER.JCETIQUETAPEDIDOCORP GROUP BY NUMPED)
SELECT P.NUMPED,
       P.DATA,
       (CASE P.CONDVENDA
         WHEN 1 THEN
          'VENDA'
         WHEN 5 THEN
          'BONIFICADO'
         WHEN 7 THEN
          'NOTA MÃE'
         WHEN 8 THEN
          'NOTA FILHA'
         WHEN 9 THEN
          'AMOSTRAS'
         ELSE
          'NOVO TIPO'
       END) TIPO,
       (C.CODREDE || ' - ' || R.DESCRICAO) REDE,
       C.CODCLI,
       C.CLIENTE,
       C.FANTASIA,
       REGEXP_REPLACE(C.CGCENT,
                      '([0-9]{2})([0-9]{3})([0-9]{3})([0-9]{4})',
                      '\1.\2.\3/\4-') CNPJ,
       C.IEENT,
       C.ESTENT UF,
       (C.MUNICENT || ' - ' || C.BAIRROENT) CIDADE,
       C.CEPENT CEP,
       P.CODFILIAL FILIAL,
       (SELECT MAX(I.CODFILIALRETIRA) FILIALRETIRA
          FROM PCPEDI I
         WHERE I.NUMPED = P.NUMPED) FILIALRETIRA,     
       P.NUMPEDCLI,
       NVL(I.VLPEDIDO, P.VLATEND) VLPEDIDO,
       ROUND(P.VLATEND, 2) VLTOTAL,
       (CASE
         WHEN (P.VLATEND - NVL(I.VLPEDIDO, P.VLATEND)) > 0 THEN
          'SIM'
         ELSE
          '-'
       END) GNRE,
       G.VALOR VLGUIA,
       G.DTPAGTO DTPAG,
       (CASE
         WHEN E.NUMPED IS NOT NULL THEN
          'SIM + PERSONALIZADO'
         ELSE
          DECODE(NVL(P.ESC_PEDIDOEMBRULHADO, 'N'), 'N', 'NÃO', 'SIM')
       END) EMBRULHADO,
       L.PERCSEP,
       L.DTINICIOSEP,
       L.DTFIMSEP,
       --COLOCAR DATA LIMITE DA ROTINA 9869
       L.PERCCONF,
       L.DTINICIOCONF,
       L.DTFIMCONF,
       L.NUMVOLUME, --QUANTIDADE DE VOLUMES ANTES DE FATURAR
       L.NUMNOTA,
       L.DTFAT,      
       L.TRANSPORTADORA,
       L.DTEXPED, --CORRIGIR PARA DATA FIM DO ROMAIEO DE EXPEDICAO
       L.VOLCONF,
       L.PERCEXP
  FROM PCPEDC P
  JOIN PCCLIENT C ON C.CODCLI = P.CODCLI
  LEFT JOIN PCREDECLIENTE R ON R.CODREDE = C.CODREDE
  LEFT JOIN VIEW_JC_LOGISTICA L ON L.NUMPED = P.NUMPED
  LEFT JOIN ITENS I ON I.NUMPED = P.NUMPED
  LEFT JOIN GUIAS G ON G.CODFILIAL = P.CODFILIAL
                   AND G.NUMNOTA = L.NUMNOTA
  LEFT JOIN ETIQUETAPERSONALIZADA E ON E.NUMPED = P.NUMPED
 WHERE P.CODUSUR = 14
      --AND P.NUMPED = 14009016
   AND P.DATA >= TO_DATE('01/01/2022', 'DD/MM/YYYY')
 ORDER BY P.DATA;
