/*WITH CUSTO_FILIAL_3 AS
(SELECT CODPROD,
        PLIQCOMPRA AS PRECOLIQ,
        PBRUTO AS PRECOBRUTO,
        PLIQUIDO AS CUSTOLIQUIDO,
        PERPIS AS PIS,
        PERCOFINS AS COFINS,
        PERIPI AS IPI,
        PERCICM AS ICMS,
        PERCICMRED AS REDUCAOICMS,
        PERCIVA AS IVA,
        PERCALIQEXT AS ICMSEXTERNO,
        PERCALIQINT AS ICMSINTERNO,
        ROUND(REDBASEALIQEXT,4) AS REDBASEST,
        ROUND(PERCALIQSTRED,2) AS ALIQREDST
        
   FROM VIEW_JC_CUSTOLIQ_240 V
  WHERE CODFILIAL = 3)*/
SELECT P.CODFAB,
       P.CODPROD,
       P.DESCRICAO AS PRODUTO,
       M.MARCA,
       P.NBM AS NCM,
       P.IMPORTADO,
       F3.PLIQCOMPRA AS PRECOLIQ,
       F3.PBRUTO AS PRECOBRUTO,
       F3.PLIQUIDO AS CUSTOLIQUIDO,
       F3.PERPIS AS PIS,
       F3.PERCOFINS AS COFINS,
       F3.PERIPI AS IPI,
       F3.PERCICM AS ICMS,
       F3.PERCICMRED AS REDUCAOICMS,
       F3.PERCIVA AS IVA,
       F3.PERCALIQEXT AS ICMSEXTERNO,
       F3.PERCALIQINT AS ICMSINTERNO,
       ROUND(F3.REDBASEALIQEXT, 4) AS REDBASEST,
       ROUND(F3.PERCALIQSTRED, 2) AS ALIQREDST
  FROM PCPRODUT P
  LEFT JOIN PCMARCA M ON P.CODMARCA = M.CODMARCA
  LEFT JOIN PCPRODFILIAL F ON P.CODPROD = F.CODPROD
  LEFT JOIN VIEW_JC_CUSTOLIQ_240 F3 ON P.CODPROD = F3.CODPROD
                                   AND F.CODFILIAL = F3.CODFILIAL
 WHERE F.CODFILIAL = 3
      
   AND P.CODPROD = 796062