CREATE OR REPLACE VIEW VIEW_JC_CUSTOLIQ_240 AS 
WITH TRIBUTACAO_ENTRADA AS (
    SELECT F.CODFIGURA,
           (NVL (F.PERPIS, 0) + NVL (F.PERCOFINS, 0)) / 100 AS PERPISCOFINS,
           NVL (F.PERCICMRED, 0) / 100 AS PERCICMRED,
           NVL (F.PERCICM, 0) / 100 AS PERCICM,
           NVL (F.PERCREDICMS, 0) / 100 AS PERCREDICMS,
           NVL (F.PERIPI, 0) / 100 AS PERIPI,
           NVL (F.PERCIVA, 0) / 100 AS PERCIVA,
           NVL (F.PERCALIQEXTGUIA, 0) / 100 AS PERCALIQEXTGUIA,
           NVL (F.PERCALIQEXT, 0) / 100 AS PERCALIQEXT,
           NVL (F.PERCALIQINT, 0) / 100 AS PERCALIQINT,
           NVL (F.REDBASEALIQEXT, 0) / 100 AS REDBASEALIQEXT,
           (
               CASE
                   WHEN F.PERCICMRED = 0 THEN F.PERCICM / 100
                   ELSE F.PERCICMRED / 100
               END
           ) AS PRECICMS_ESCOLHIDO,
           (
               CASE
                   WHEN F.PERCICMRED = 0 THEN F.PERCREDICMS / 100
                   ELSE F.PERCICMRED / 100
               END
           ) AS PRECCREDICMS_ESCOLHIDO
      FROM PCTRIBFIGURA F
), CUSTO_COMPRA AS (
    SELECT P.CODFILIAL,
           P.CODPROD,
           NVL (ROUND ((NVL (P.CUSTOREP, 0) * ((100 - P.PERCDESC) / 100)), 4), 0) AS PLIQCOMPRA
      FROM PCPRODFILIAL P
), CALCULOS_CUSTO AS (
    SELECT E.CODFILIAL,
           P.CODPROD,
           P.CODFORNEC,
           P.CODNCMEX,
           F.TIPOFORNEC,
           F.ESTADO,
           E.CODFIGURA,
           C.PLIQCOMPRA,
           (C.PLIQCOMPRA * PERIPI) AS VLIPI,
           (C.PLIQCOMPRA * (1 - T.PRECICMS_ESCOLHIDO) + (C.PLIQCOMPRA * PERIPI)) AS BASEPISCOFINS,
           (C.PLIQCOMPRA * T.PRECCREDICMS_ESCOLHIDO) AS VLCREDICMS,
           PRECICMS_ESCOLHIDO,
           PRECCREDICMS_ESCOLHIDO,
           T.PERPISCOFINS,
           T.PERCICM,
           T.PERCICMRED,
           T.PERCREDICMS,
           T.PERIPI,
           T.PERCIVA,
           T.PERCALIQEXT,
           T.PERCALIQINT,
           T.PERCALIQEXTGUIA,
           T.REDBASEALIQEXT,
           (T.PERCALIQINT * T.REDBASEALIQEXT) AS PERCALIQSTRED
      FROM PCPRODUT P
     INNER JOIN PCFORNEC F ON P.CODFORNEC = F.CODFORNEC
     INNER JOIN PCTRIBENTRADA E ON P.CODNCMEX = E.NCM
       AND F.TIPOFORNEC = E.TIPOFORNEC
       AND F.ESTADO = E.UFORIGEM
      LEFT JOIN TRIBUTACAO_ENTRADA T ON E.CODFIGURA = T.CODFIGURA
      LEFT JOIN CUSTO_COMPRA C ON P.CODPROD = C.CODPROD
       AND E.CODFILIAL = C.CODFILIAL
     WHERE F.TIPOFORNEC NOT IN (
        'C', 'O'
    )
), VALORPISCOFINS AS (
    SELECT (C.BASEPISCOFINS * C.PERPISCOFINS) AS VLCREDPISCOFINS,
           C.*
      FROM CALCULOS_CUSTO C
), BASEICMSST AS (
    SELECT (((C.PLIQCOMPRA + C.VLIPI) * C.PERCIVA) + (C.PLIQCOMPRA + C.VLIPI)) AS BASEICMSST,
           C.*
      FROM VALORPISCOFINS C
), VALORICMSST AS (
    SELECT (
        CASE
            WHEN C.PERCALIQSTRED = 0 THEN ((C.BASEICMSST * C.PERCALIQINT) - (C.PLIQCOMPRA * C.PERCALIQEXT))
            ELSE ((C.BASEICMSST * C.PERCALIQINT) - (C.PLIQCOMPRA * C.PERCALIQSTRED))
        END
    ) VLICMSST,
           C.*
      FROM BASEICMSST C
), PRECOBRUTO AS (
    SELECT (
        CASE
            WHEN PERCALIQEXTGUIA = 0 THEN (C.PLIQCOMPRA + C.VLIPI + C.VLICMSST)
            ELSE (C.PLIQCOMPRA + C.VLIPI)
        END
    ) AS PBRUTO,
           C.*
      FROM VALORICMSST C
)
SELECT (
    CASE
        WHEN C.PERCALIQEXTGUIA = 0 THEN ROUND ((C.PBRUTO - C.VLCREDPISCOFINS - C.VLCREDICMS), 4)
        ELSE ROUND ((C.PBRUTO + C.VLICMSST - C.VLCREDPISCOFINS - C.VLCREDICMS), 4)
    END
) AS PLIQUIDO,
       C.*
  FROM PRECOBRUTO C
        /* WHERE C.CODFILIAL = 7*/
      /* AND C.CODPROD IN( 796177, 803349)*/
  ;
/