CREATE OR REPLACE VIEW VIEW_JC_FRETES AS 
   SELECT E.CODFILIAL,
          E.NUMTRANSENT,
          NVL(S.DTSAIDA, E2.DTENT) DTMOV,
          NVL(S.CODCLI, E2.CODFORNEC) CODCLI,
          NVL(S.NUMNOTA, E2.NUMNOTA) AS NUMNOTAVENDA,
          NVL(S.VLTOTAL, E2.VLTOTAL) VLVENDA,
          ROUND((E.VLTOTAL / COUNT(E.NUMTRANSENT)
                 OVER(PARTITION BY E.NUMTRANSENT)),
                2) VLCTE,
          E.DTEMISSAO,
          E.NUMNOTA AS NUMNOTA_CTE,
          E.CODFORNEC,
          T.FORNECEDOR
     FROM PCNFENT E
     JOIN PCFORNEC T ON T.CODFORNEC = E.CODFORNEC
     LEFT JOIN PCCONHECIMENTOFRETEI F ON F.NUMTRANSCONHEC = E.NUMTRANSENT
     LEFT JOIN PCNFSAID S ON S.CHAVENFE = F.CHAVENFE
     LEFT JOIN PCNFENT E2 ON E2.CHAVENFE = F.CHAVENFE
    WHERE E.ESPECIE = 'CT'
      AND E.DTCANCEL IS NULL
    ORDER BY DTEMISSAO DESC;
   /
