WITH TRIBUTACAO_ENTRADA AS
 (SELECT F.CODFIGURA,
         (NVL(F.PERPIS, 0) + NVL(F.PERCOFINS, 0)) / 100 PERPISCOFINS,
         NVL(F.PERCICMRED, 0) / 100 PERCICMRED,
         NVL(F.PERCREDICMS, 0) / 100 PERCREDICMS,
         NVL(F.PERIPI, 0) / 100 PERIPI,
         NVL(F.PERCIVA, 0) / 100 PERCIVA,
         NVL(F.PERCALIQEXT, 0) / 100 PERCALIQEXT,
         NVL(F.PERCALIQINT, 0) / 100 PERCALIQINT,
         NVL(F.REDBASEALIQEXT, 0) / 100 REDBASEALIQEXT
    FROM PCTRIBFIGURA F
    ), TRIBUTACAO_PRODUTO AS
    (
SELECT E.CODFILIAL,
       P.CODPROD,
       P.CODFORNEC,
       P.CODNCMEX,
       F.TIPOFORNEC,
       F.ESTADO,
       E.CODFIGURA,
       T.PERPISCOFINS,
       T.PERCICMRED,
       T.PERCREDICMS,
       T.PERIPI,
       T.PERCIVA,
       T.PERCALIQEXT,
       T.PERCALIQINT,
       T.REDBASEALIQEXT
  FROM PCPRODUT P
 INNER JOIN PCFORNEC F
    ON P.CODFORNEC = F.CODFORNEC
 INNER JOIN PCTRIBENTRADA E
    ON P.CODNCMEX = E.NCM
   AND F.TIPOFORNEC = E.TIPOFORNEC
   AND F.ESTADO = E.UFORIGEM
  LEFT JOIN TRIBUTACAO_ENTRADA T
    ON E.CODFIGURA = T.CODFIGURA
 WHERE F.TIPOFORNEC NOT IN ('C', 'O')
)
