WITH ITENS_OS AS (
    SELECT OS_ID,
           COUNT (PROD_ID) QTITENS
      FROM (
        SELECT DISTINCT I.OS_ID,
                        I.PROD_ID
          FROM JCENDOSITEM I
    )
     GROUP BY OS_ID
), ABASTECIMENTOS AS (
    SELECT C.ID,
           C.USUARIO_ID AS CODFUNC,
           E.NOME_GUERRA AS FUNCIONARIO,
           COUNT (C.USUARIO_ID) AS CONTAR
      FROM JCENDOS C
      LEFT JOIN PCEMPR E ON C.USUARIO_ID = E.MATRICULA
     WHERE C.TIPO_MOV = 'H'
       AND C.TIPO_OS = 3
       AND C.DT_CANCEL IS NULL
     /*RETIRAR 'OS' CANCELADAS*/
       AND C.DT_FIM IS NOT NULL
     /*PEGAR APENAR 'OS' FINALIZADAS*/
       AND DT_INICIO BETWEEN TO_DATE ('01/11/2020', 'DD/MM/YYYY') AND TO_DATE ('11/12/2020', 'DD/MM/YYYY')
     GROUP BY C.ID,
              C.USUARIO_ID,
              E.NOME_GUERRA
)
SELECT A.CODFUNC,
       A.FUNCIONARIO,
     /*SUM( A.CONTAR) AS QTABASTECIMENTOS,*/
       I.QTITENS
  FROM ABASTECIMENTOS A
 INNER JOIN ITENS_OS I ON A.ID = I.OS_ID
 GROUP BY A.CODFUNC,
          A.FUNCIONARIO,
          I.QTITENS