SELECT A.DTSAIDA DATA,
       /*A.CODFILIAL,*/
       A.NUMNOTA NOTAFISCAL,
       'FCX3255' AS PLACA,
       /*C.CODCLI,*/
       C.ENDERCOM AS ENDERECODESTINO,
       C.BAIRROCOM AS BAIRRODESTINO,
       D.NOMECIDADE CIDADEDESTINO,
       A.VLTOTAL VALOR,
       F.ENDERECO
  FROM PCNFSAID A
  LEFT JOIN PCCLIENT C ON A.CODCLI = C.CODCLI
  LEFT JOIN PCCIDADE D ON C.CODCIDADE = D.CODCIDADE
  LEFT JOIN PCFILIAL F ON A.CODFILIAL = F.CODIGO
 WHERE A.DTCANCEL IS NULL
   AND A.CODFILIAL IN (
    1, 2, 7
)
   AND C.CODCLI NOT IN (
    18633, 17427
)
     /*RETIRAR VENDA ENTRE EMPRESAS*/
   AND NOT (A.CODFILIAL = 2
   AND C.CODCLI = 82215)
     /*RETIRAR TRANSFERENCIA DA FILIAL 2 PARA FILIAL 7*/
   AND NOT (A.CODFILIAL = 7
   AND C.CODCLI = 7543)
     /*RETIRAR TRANSFERENCIA DA FILIAL 7 PARA FILIAL 2*/
   AND A.DTSAIDA BETWEEN TO_DATE ('01/11/2020', 'DD/MM/YYYY') AND TO_DATE ('30/11/2020', 'DD/MM/YYYY')
   AND A.CODFORNECFRETE IN (
    8598
)
 ORDER BY A.DTSAIDA;
/