SELECT A.DTSAIDA DATA,
       A.CODFILIAL,
       A.NUMNOTA NOTAFISCAL,
       'FCX3255' AS PLACA,
       C.CODCLI,
       C.ENDERCOM AS ENDERECODESTINO,
       C.BAIRROCOM AS BAIRRODESTINO,
       D.NOMECIDADE CIDADEDESTINO,
       A.VLTOTAL VALOR,
       F.ENDERECO
  FROM PCNFSAID A
  LEFT JOIN PCCLIENT C ON A.CODCLI = C.CODCLI
  LEFT JOIN PCCIDADE D ON C.CODCIDADE = D.CODCIDADE
  LEFT JOIN PCFILIAL F ON A.CODFILIAL = F.CODIGO
 WHERE A.DTCANCEL IS NULL
   AND A.CODFILIAL IN (
    1, 2, 5, 6, 7, 8
)
  /* AND A.CODFILIAL IN (:CODFILIAL)*/
   AND C.CODCLI NOT IN (
    18633, 17427, 8630
)
     /*RETIRAR VENDA ENTRE EMPRESAS E DIRETORIA*/
   AND D.UF = 'SP'
   AND A.CONDVENDA NOT IN (
    7, 8, 10
)
     /*RETIRAR VENDA DE REMESSA E TRANSFERENCIA*/
   AND A.CODFORNECFRETE IN (
    8598
)
   AND A.DTSAIDA BETWEEN TO_DATE ('01/11/2021', 'DD/MM/YYYY') AND TO_DATE ('30/11/2021', 'DD/MM/YYYY')
  /* AND A.DTSAIDA BETWEEN TO_DATE(:DTINI, 'DD/MM/YYYY') AND TO_DATE(:DTFIM, 'DD/MM/YYYY')*/
 ORDER BY A.DTSAIDA;