/**********************************************************
Trazer clientes que são:
1. De vendedores que estão na VIEW DITO_VENDEDORES
2. Apenas clientes que sejam pessoa física (CPF com 11 digitos)
3. Clientes que não estajam como excluidos

Tratamento dos campos:
1. Trazer o NOME da JCCLIENTCLUB, caso nulo, trazer primeiro nome da PCCLIENT.CLIENTE
1. Trazer o SOBRENOME da JCCLIENTCLUB, caso nulo, trazer demais nomes da PCCLIENT.CLIENTE
**********************************************************/
WITH CLIENTES AS
 (SELECT C.CODCLI CODIGO_CLIENTE,
         REGEXP_REPLACE(C.CGCENT, '[^0-9]', '') CPF_CNPJ,
         TO_CHAR(C.DTCADASTRO, 'DD/MM/YYYY HH24:MI:SS') DATA_CADASTRO,
         TO_CHAR(NVL(C.DTULTALTER, C.DTCADASTRO), 'DD/MM/YYYY HH24:MI:SS') DATA_UPDATE,
         DECODE(C.TIPOFJ, 'J', 'Jurídica', 'F', 'Física', 'Física') TIPO_PESSOA,
         C.CLIENTE,
         (CASE
           WHEN INSTR(TRIM(C.CLIENTE), ' ') > 0 THEN
            UPPER(SUBSTR(TRIM(C.CLIENTE), 1, INSTR(TRIM(C.CLIENTE), ' ') - 1))
           ELSE
            UPPER(TRIM(C.CLIENTE))
         END) PRIMEIRO_NOME_PCCLIENT,
         CASE
           WHEN INSTR(TRIM(C.CLIENTE), ' ') > 0 THEN
            UPPER(TRIM(SUBSTR(TRIM(C.CLIENTE),
                              INSTR(TRIM(C.CLIENTE), ' ') + 1)))
           ELSE
            NULL
         END AS SOBRENOME_PCCLIENT,
         TRIM(B.NOME) NOME_JCCLIENTCLUB,
         TRIM(B.SOBRENOME) SOBRENOME_JCCLIENTCLUB,
         LOWER(C.EMAIL) EMAIL,
         REGEXP_REPLACE(C.TELENT, '[^0-9]', '') CELULAR,
         C.DTEXCLUSAO
    FROM PCCLIENT C
    JOIN DITO_VENDEDORES V ON V.CODIGO_VENDEDOR = C.CODUSUR1
    LEFT JOIN JCCLIENTCLUB B ON B.CODCLI = C.CODCLI)
SELECT CODIGO_CLIENTE,
       CPF_CNPJ,
       DATA_CADASTRO,
       DATA_UPDATE,
       TIPO_PESSOA,
       /*       CLIENTE,
       PRIMEIRO_NOME_PCCLIENT,
       SOBRENOME_PCCLIENT,
       NOME_JCCLIENTCLUB,
       SOBRENOME_JCCLIENTCLUB,*/
       NVL(NOME_JCCLIENTCLUB, PRIMEIRO_NOME_PCCLIENT) NOME,
       NVL(SOBRENOME_JCCLIENTCLUB, SOBRENOME_PCCLIENT) SOBRENOME,
       EMAIL,
       CELULAR,
       LENGTH(CELULAR) TAMNHO_CEL
  FROM CLIENTES
 WHERE LENGTH(CPF_CNPJ) = 11
   AND DTEXCLUSAO IS NULL
      --AND CODIGO_CLIENTE = 555392
   AND SOBRENOME_JCCLIENTCLUB IS NOT NULL
   AND ROWNUM <= 3000;

/****************************************************************
SELECT * FROM JCCLUBCLIENTE WHERE CADASTRADO = 'N' AND CPF IS NOT NULL AND EMAIL IS NOT NULL;
SELECT * FROM JCCLUB;
SELECT J.* FROM JCCLIENTCLUB J;
 SELECT CODCLI, COUNT(*)  FROM JCCLIENTCLUB J GROUP BY CODCLI;



SELECT C.CODCLI CODIGO_CLIENTE,
       C.CGCENT CPF_CNPJ,
       LENGTH(C.CGCENT) TAMANHO,
       C.*
FROM PCCLIENT C
JOIN DITO_VENDEDORES V ON V.CODIGO_VENDEDOR = C.CODUSUR1
WHERE LENGTH(C.CGCENT) = 9
--LEFT JOIN JCCLIENTCLUB B ON B.CODCLI = C.CODCLI

;


SELECT * FROM PCCLIENT C WHERE C.CODCLI = 149623;


SELECT SOBRENOME, COUNT(codcli) FROM JCCLIENTCLUB GROUP BY SOBRENOME;

SELECT ROWID, j.* FROM JCCLIENTCLUB j WHERE CODCLI IN (
557070,
557086,
557108,
557138,
557143,
556791,
556836);


SELECT c.dtcadastro, B.SOBRENOME,
       C.*
  FROM PCCLIENT C
  LEFT JOIN JCCLIENTCLUB B ON C.CODCLI = B.CODCLI
 WHERE C.CODATV1 = 25
   AND c.dtcadastro IS NOT NULL
   AND INSTR(C.CLIENTE, 'CADASTRO') > 0
 ORDER BY c.dtcadastro DESC;
 
 **********/
