--CREATE OR REPLACE VIEW BROKER.DITO_BASE_MOV_PRODUTO AS
WITH CLIENTES_MAIS_CONSUMIDOR_FINAL AS
 (SELECT C.CODIGO_CLIENTE,
         C.CPF_CNPJ
    FROM BROKER.DITO_CLIENTES C
  UNION
  SELECT C.CODCLI CODIGO_CLIENTE,
         REGEXP_REPLACE(C.CGCENT, '[^0-9]', '') CPF_CNPJ
    FROM PCCLIENT C
   WHERE C.CODCLI = 1),

CFOP_VENDAS AS
 (SELECT F.CODFISCAL
    FROM PCCFO F
   WHERE F.CODFISCAL IN
         (5115, 6115, 5102, 5109, 5403, 5405, 6102, 6108, 6403, 5120, 6120)),

CFOP_DEVOLUCAO AS
 (SELECT F.CODFISCAL
    FROM PCCFO F
   WHERE F.CODFISCAL IN (1202, 1411, 2202, 2411)),

CFOP_TRANSACAO AS
 (SELECT CODFISCAL
    FROM CFOP_VENDAS
  UNION
  SELECT CODFISCAL
    FROM CFOP_DEVOLUCAO)

SELECT C.CODIGO_CLIENTE,
       C.CPF_CNPJ,
       M.DTMOV DATA_COMPRA,
       NVL(M.NUMTRANSVENDA, M.NUMTRANSENT) ID_TRANSACAO,
       M.CODPROD ID_PRODUTO,
       M.DESCRICAO NOME_PRODUTO,
       (CASE
         WHEN M.CODFISCAL IN (SELECT CODFISCAL FROM CFOP_DEVOLUCAO D) THEN
          M.QTCONT * -1
         ELSE
          M.QTCONT
       END) QUANTIDADE,
       ROUND(M.QTCONT * (M.PUNITCONT - NVL(M.ST, 0) - NVL(M.VLIPI, 0) -
             NVL(M.VLFRETE, 0)),
             2) PRECO_PRODUTO,
       ROUND(M.QTCONT * (M.PUNITCONT - NVL(M.ST, 0) - NVL(M.VLIPI, 0) -
             NVL(M.VLFRETE, 0)),
             2) VALOR_UNITARIO,
       ROUND(M.QTCONT * NVL(M.VLDESCONTO, 0), 2) TOTAL_DESCONTO,
       ROUND(M.QTCONT * NVL(M.VLFRETE, 0), 2) TOTAL_FRETE,
       (CASE
         WHEN M.CODFISCAL IN (SELECT CODFISCAL FROM CFOP_DEVOLUCAO D) THEN
          'Devolução'
         ELSE
          'Compra'
       END) OPERACAO_PRODUTO
  FROM PCMOV M
  JOIN CLIENTES_MAIS_CONSUMIDOR_FINAL C ON C.CODIGO_CLIENTE = M.CODCLI
  JOIN CFOP_TRANSACAO T ON T.CODFISCAL = M.CODFISCAL
 WHERE M.DTCANCEL IS NULL
   AND M.DTMOV >= TO_DATE('01/01/2022', 'DD/MM/YYYY');
