--CREATE OR REPLACE VIEW BROKER.DITO_TRANSACOES AS
/**********************************************************
Trazer vendas que são:
1. 
2. 
3. 
4. 
5. 
6. 
7. 

Tratamento dos campos:
1. 
2. 
3. 
4. 
5. 

CODIGO_CLIENTE,
CPF_CNPJ,
DATA_COMPRA,
ID_TRANSACAO,
NOME_LOJA,
ID_LOJA,
NOME_VENDEDOR,
CODIGO_VENDEDOR,
METODO_PAGAMENTO,
TOTAL,
TIPO_LOJA,
QUANTIDADE_PRODUTOS,
TOTAL_DESCONTO,
TOTAL_FRETE,
CUPOM,
CLASSIFICACAO_LOJA

**********************************************************/

WITH BASE_MOV_PROD_CONSOLIDADA AS
 (SELECT M.ID_TRANSACAO,
         M.OPERACAO_PRODUTO,
         MAX(M.CODIGO_CLIENTE) CODIGO_CLIENTE,
         MAX(M.CPF_CNPJ) CPF_CNPJ,
         MAX(M.DATA_COMPRA) DATA_COMPRA,
         MAX(M.ID_LOJA) ID_LOJA,
         MAX(M.CODIGO_VENDEDOR) CODIGO_VENDEDOR,
         (CASE
           WHEN M.OPERACAO_PRODUTO = 'Devolucao' THEN
            SUM(M.PRECO_PRODUTO) * -1
           ELSE
            SUM(M.PRECO_PRODUTO)
         END) TOTAL,
         COUNT(M.ID_PRODUTO) QUANTIDADE_PRODUTO,
         SUM(M.TOTAL_DESCONTO) TOTAL_DESCONTO,
         SUM(M.TOTAL_FRETE) TOTAL_FRETE
    FROM BROKER.DITO_BASE_MOV_PRODUTO M
   GROUP BY M.ID_TRANSACAO,
            M.OPERACAO_PRODUTO),

FILIAIS AS
 (SELECT F.CODIGO,
         F.FANTASIA
    FROM PCFILIAL F)

SELECT M.CODIGO_CLIENTE,
       M.CPF_CNPJ,
       M.DATA_COMPRA,
       M.ID_TRANSACAO,
       F.FANTASIA NOME_LOJA,
       M.ID_LOJA,
       V.NOME_VENDEDOR,
       M.CODIGO_VENDEDOR,
       '' METODO_PAGAMENTO,
       M.TOTAL,
       (CASE
         WHEN M.ID_LOJA IN
              (SELECT F1.CODIGO
                 FROM PCFILIAL F1
                WHERE INSTR(F1.FANTASIA, 'LOJA') > 0) THEN
          'OFFLINE'
         ELSE
          'ONLINE'
       END) TIPO_LOJA,
       M.QUANTIDADE_PRODUTO,
       M.TOTAL_DESCONTO,
       M.TOTAL_FRETE,
       '' CUPOM,
       'Própria' CLASSIFICACAO_LOJA
  FROM BASE_MOV_PROD_CONSOLIDADA M
  JOIN BROKER.DITO_VENDEDORES V ON V.CODIGO_VENDEDOR = M.CODIGO_VENDEDOR
	LEFT JOIN PCFILIAL F ON F.CODIGO = M.ID_LOJA
