CREATE OR REPLACE VIEW BROKER.DITO_PRODUTOS AS

SELECT M.CODIGO_CLIENTE,
       M.CPF_CNPJ,
       M.DATA_COMPRA,
       M.ID_TRANSACAO,
       M.ID_PRODUTO,
       INITCAP(M.NOME_PRODUTO) NOME_PRODUTO,
       M.QUANTIDADE,
       M.PRECO_PRODUTO,
       M.VALOR_UNITARIO,
       M.OPERACAO_PRODUTO,
       INITCAP(D.DESCRICAO) DEPARTAMENTO,
       INITCAP(S.DESCRICAO) CATEGORIA,
       INITCAP(C.CATEGORIA) SUB_CATEGORIA,
       J.VALUE FAIXA_ETARIA
  FROM BROKER.DITO_BASE_MOV_PRODUTO M
  LEFT JOIN PCPRODUT P ON P.CODPROD = M.ID_PRODUTO
  LEFT JOIN PCDEPTO D ON D.CODEPTO = P.CODEPTO
  LEFT JOIN PCSECAO S ON S.CODSEC = P.CODSEC
  LEFT JOIN PCCATEGORIA C ON C.CODCATEGORIA = P.CODCATEGORIA
  LEFT JOIN JCWEBPRODVTEXTAGS J ON J.CODPROD = M.ID_PRODUTO AND J.FIELD_ID = 33
