--CREATE OR REPLACE VIEW BROKER.DITO_PRODUTOS AS
/**********************************************************
Trazer clientes que são:
1. 
2. 
3. 
4. 
5. 
6. 
7. 

Tratamento dos campos:
1. 
2. 
3. 
4. 
5. 

CODIGO_CLIENTE,
CPF_CNPJ,
DATA_COMPRA,
ID_TRANSACAO,
ID_PRODUTO,
NOME_PRODUTO,
QUANTIDADE,
PRECO_PRODUTO,
VALOR_UNITARIO,
OPERACAO_PRODUTO,
DEPARTAMENTO,
CATEGORIA,
SUB_CATEGORIA,
COLECAO,
COR,
TAMANHO,
IDADE_SUGERIDA

JCWEBPRODVTEXTAGS WHERE FIELD_ID = 33

**********************************************************/

SELECT M.CODIGO_CLIENTE,
       M.CPF_CNPJ,
       M.DATA_COMPRA,
       M.ID_TRANSACAO,
       M.ID_PRODUTO,
       M.NOME_PRODUTO,
       M.QUANTIDADE,
       M.PRECO_PRODUTO,
       M.VALOR_UNITARIO,
       M.OPERACAO_PRODUTO,
  FROM BROKER.DITO_BASE_MOV_PRODUTO M
	LEFT JOIN PCPRODUT P ON P.CODPROD = M.ID_PRODUTO
