CREATE OR REPLACE VIEW VIEW_JC_VENDEDOR AS
    SELECT U.CODUSUR,
           U.USURDIRFV AS VENDEDOR,
           U.BLOQUEIO,
           U.CODSUPERVISOR,
           V.NOME AS SUPERVISOR,
           V.CODGERENTE,
           G.NOMEGERENTE AS GERENTE
      FROM PCUSUARI U
      LEFT JOIN PCSUPERV V ON V.CODSUPERVISOR = U.CODSUPERVISOR
      LEFT JOIN PCGERENTE G ON V.CODGERENTE = G.CODGERENTE;/