--ALTERAR PRODUTOS PARA NÃO CONSIGNADOS ANTES DE SUBIR O XML DA NOTA NA 1301
UPDATE PCPRODUT SET COMPRACONSIGNADO = 'N' WHERE COMPRACONSIGNADO = 'S' AND CODFORNEC = 10260;

--ALTEARAR PRODUTOS PARA NÃO CONSIGNADOS ANTES DE SUBIR O XML DA NOTA NA 1301
UPDATE PCPRODUT SET COMPRACONSIGNADO = 'S' WHERE COMPRACONSIGNADO = 'N' AND CODFORNEC = 10260;

--ALTERAR PRE-ENTRADA DE 1 PARA A ANTES DE VINCULAR PEDIDO
SELECT ROWID, TIPODESCARGA, E.* FROM PCNFENTPREENT E WHERE E.NUMTRANSENT = 564364;

--ALTERAR CODFISCAL DOS ITENS PARA 1917
SELECT CODFISCAL, M.* FROM PCMOVPREENT M WHERE M.NUMTRANSENT = 564364;
UPDATE PCMOVPREENT SET CODFISCAL = 1917 WHERE NUMTRANSENT = 564364;

--VINCULAR PEDIDO NA 1309
--DAR ENTRADA NA 1301
