CREATE OR REPLACE PROCEDURE JC_CRIA_TABELAS_TRIB_SAIDA AS

  v_table_exists NUMBER;
  v_index_exists NUMBER;

BEGIN
  ----JC_TIPO_EMPRESA
  SELECT COUNT(*) INTO v_table_exists FROM user_tables WHERE table_name = 'JC_TIPO_EMPRESA';
  IF v_table_exists = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE JC_TIPO_EMPRESA
  (
     CODTIPOEMPRESA  NUMBER(2),
     TIPOEMPRESA     VARCHAR2(25),
     CONSTRAINT PK_JC_TIPO_EMPRESA PRIMARY KEY (CODTIPOEMPRESA)
  )';
  END IF;

  ----JC_TIPO_EMPRESA_FILIAL
  SELECT COUNT(*) INTO v_table_exists FROM user_tables WHERE table_name = 'JC_TIPO_EMPRESA_FILIAL';
  IF v_table_exists = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE JC_TIPO_EMPRESA_FILIAL
  (
     CODTIPOEMPRESA  NUMBER(2),
     CODFILIAL       VARCHAR2(2),
     CONSTRAINT PK_JC_TIPO_EMPRESA_FILIAL PRIMARY KEY (CODTIPOEMPRESA, CODFILIAL)
  )';
  END IF;

  ----JC_CONFIGURA_TRIB_SAIDA
  SELECT COUNT(*) INTO v_table_exists FROM user_tables WHERE table_name = 'JC_CONFIGURA_TRIB_SAIDA';
  IF v_table_exists = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE JC_CONFIGURA_TRIB_SAIDA
  (
     CODTIPOEMPRESA  NUMBER(2),
     CODNCMEX        VARCHAR2(20),
     UF              VARCHAR2(2),
     IMPORTADO       VARCHAR2(1),
     REGIMEST        VARCHAR2(1),
     CODST           NUMBER(4),
     CODPISCOFINS    NUMBER(4),
     CONSTRAINT PK_JC_CONFIGURA_TRIB_SAIDA PRIMARY KEY (CODTIPOEMPRESA, CODNCMEX, UF, IMPORTADO, REGIMEST)
  )';
  END IF;

END;
