CREATE OR REPLACE VIEW VIEW_JC_PROD_TRIBUTADOS_SEM_CONFIG AS 

    WITH TRIBUTACOES_EXISTENTES AS
     (SELECT E.CODTIPOEMPRESA,
             P.CODNCMEX
        FROM PCTABTRIB T
        LEFT JOIN PCPRODUT P ON P.CODPROD = T.CODPROD
        LEFT JOIN JC_TIPO_EMPRESA_FILIAL E ON E.CODFILIAL = T.CODFILIALNF
       WHERE T.CODFILIALNF NOT IN ('3', '4', '5', '6', '9', '10', '15')
         AND E.CODTIPOEMPRESA IS NOT NULL
       GROUP BY E.CODTIPOEMPRESA,
                P.CODNCMEX),
    
    TAB_IMPORTADO AS
     (SELECT 'N' IMPORTADO FROM DUAL UNION SELECT 'S' IMPORTADO FROM DUAL)
    
    SELECT T.CODTIPOEMPRESA,
           T.CODNCMEX,
           E.UF,
           I.IMPORTADO
      FROM TRIBUTACOES_EXISTENTES T
     CROSS JOIN PCESTADO E
     CROSS JOIN TAB_IMPORTADO I
      LEFT JOIN JC_CONFIGURA_TRIB_SAIDA J ON J.CODTIPOEMPRESA = T.CODTIPOEMPRESA
                                         AND J.CODNCMEX = T.CODNCMEX
                                         AND J.UF = E.UF
                                         AND J.IMPORTADO = I.IMPORTADO
    
     WHERE J.CODTIPOEMPRESA IS NULL
     ORDER BY T.CODNCMEX,
              T.CODTIPOEMPRESA,
              I.IMPORTADO,
              E.UF;
