CREATE OR REPLACE PROCEDURE PRC_JC_UPSERT_CONFIG_TRIB_SAIDA
(
  pCODTIPOEMPRESA NUMBER,
  pCODNCMEX       VARCHAR2,
  pUF             VARCHAR2,
  pIMPORTADO      VARCHAR2,
  pREGIMEST       VARCHAR2,
  pCODST          NUMBER,
  pCODPISCOFINS   NUMBER
) AS

BEGIN
  UPDATE JC_CONFIGURA_TRIB_SAIDA
     SET CODST        = pCODST,
         CODPISCOFINS = pCODPISCOFINS
   WHERE CODTIPOEMPRESA = pCODTIPOEMPRESA
     AND CODNCMEX = pCODNCMEX
     AND UF = pUF
     AND IMPORTADO = pIMPORTADO
     AND REGIMEST = pREGIMEST;

  IF SQL%NOTFOUND THEN
    INSERT INTO JC_CONFIGURA_TRIB_SAIDA
      (CODTIPOEMPRESA,
       CODNCMEX,
       UF,
       IMPORTADO,
       REGIMEST,
       CODST,
       CODPISCOFINS)
    VALUES
      (pCODTIPOEMPRESA,
       pCODNCMEX,
       pUF,
       pIMPORTADO,
       pREGIMEST,
       pCODST,
       pCODPISCOFINS);
  END IF;

EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Erro encontrado: ' || SQLERRM);
    RAISE_APPLICATION_ERROR(-20000, 'Erro durante a insercao na tabela: ' || SQLERRM);
  
    COMMIT;
  
END;
