CREATE OR REPLACE VIEW VIEW_JC_PRODUTO_TRIB_SAIDA AS

      WITH CONFIG_TRIBUT_FILIAL_PRODUTO AS
       (SELECT F.CODFILIAL,
               P.CODPROD,
               P.DESCRICAO,
               T.CODTIPOEMPRESA,
               E.TIPOEMPRESA,
               T.CODNCMEX,
               T.UF,
               P.IMPORTADO,
               T.REGIMEST,
               T.CODST,
               T.CODPISCOFINS
          FROM PCPRODUT P
          LEFT JOIN JC_CONFIGURA_TRIB_SAIDA T ON T.CODNCMEX = P.CODNCMEX
                                             AND T.IMPORTADO = P.IMPORTADO
          JOIN JC_TIPO_EMPRESA E ON E.CODTIPOEMPRESA = T.CODTIPOEMPRESA
          LEFT JOIN JC_TIPO_EMPRESA_FILIAL F ON F.CODTIPOEMPRESA = T.CODTIPOEMPRESA
          LEFT JOIN PCFILIAL L ON L.CODIGO = F.CODFILIAL
         WHERE P.DTEXCLUSAO IS NULL
           AND L.DTEXCLUSAO IS NULL)
      
      SELECT C.CODTIPOEMPRESA,
             C.TIPOEMPRESA,
             T.CODFILIALNF,
             C.CODNCMEX,
             T.CODPROD,
             C.DESCRICAO,
             C.IMPORTADO,
             C.REGIMEST,
             T.UFDESTINO,
             T.CODST CODST_ATUAL,
             B.MENSAGEM FIGURA_ATUAL,
             T.CODTRIBPISCOFINS CODPC_ATUAL,
             P.DESCRICAOTRIBPISCOFINS PISCOFINS_ATUAL,
             C.CODST CODST_CONFIG,
             BC.MENSAGEM FIGURA_CONFIG,
             C.CODPISCOFINS CODPC_CONFIG,
             PC.DESCRICAOTRIBPISCOFINS PISCOFINS_CONFIG
        FROM PCTABTRIB T
        JOIN PCTRIBUT B ON B.CODST = T.CODST
        JOIN PCTRIBPISCOFINS P ON P.CODTRIBPISCOFINS = T.CODTRIBPISCOFINS
        LEFT JOIN CONFIG_TRIBUT_FILIAL_PRODUTO C ON C.CODFILIAL = T.CODFILIALNF
                                                AND C.CODPROD = T.CODPROD
                                                AND C.UF = T.UFDESTINO
        LEFT JOIN PCTRIBUT BC ON BC.CODST = C.CODST
        LEFT JOIN PCTRIBPISCOFINS PC ON PC.CODTRIBPISCOFINS = C.CODPISCOFINS
       /*ORDER BY C.CODTIPOEMPRESA,
                TO_NUMBER(C.CODFILIAL),
                C.CODNCMEX,
                C.CODPROD*/
