--VERIFICAR PRODUTOS SEM REGISTRO NA PCTABTRIB
SELECT * FROM VIEW_JC_PRODUTO_SEM_TRIB_SAIDA_VISUAL;

--FAZER A INSERÇÃO DESSES PRODUTOS NA PCTABTRIB
BEGIN
	  PRC_JC_INSERT_NOVOS_PRODUTOS_PCTABTRIB;
END;

--VERIFICAR SE EXISTE ALGUMA CONFIGURAÇÃO A FAZER
SELECT * FROM VIEW_JC_PROD_TRIBUTADOS_SEM_CONFIG;

--VERIFICAR UPSERT
SELECT P.*
  FROM VIEW_JC_PRODUTO_TRIB_SAIDA P
 WHERE P.CODST_ATUAL <> P.CODST_CONFIG
    OR P.CODPC_ATUAL <> P.CODPC_CONFIG;
		
--FAZER O UPSERT DESSES PRODUTOS NA PCTABTRIB
BEGIN
	  PRC_JC_UPDATE_ATUALIZA_PCTABPTRIB;
END;

---CORRIGIR ARQUIVO DE CONFIGURAÇÃO
SELECT ROWID, J. * FROM JC_CONFIGURA_TRIB_SAIDA J WHERE J.CODNCMEX = '56079010.';
