SELECT F.CODFILIAL,
       F.CODPROD,
       ROUND ((NVL (F.CUSTOREP, 0) * ((100 - NVL (F.PERCDESC, 0)) / 100)), 4) PBRUTO_240
  FROM PCPRODFILIAL F
 INNER JOIN PCPRODUT P ON F.CODPROD = P.CODPROD
 WHERE P.DTEXCLUSAO IS NULL
   AND F.CODFILIAL = 7;
/