SELECT E.CODFILIAL,
       E.CODPROD,
       NVL (E.QTESTGER, 0) AS QTGERENCIAL,
       NVL (E.QTPEDIDA, 0) AS QTCOMPRA,
       (NVL (E.QTESTGER, 0) - NVL (E.QTBLOQUEADA, 0) - NVL (E.QTRESERV, 0)) AS QTDISPONIVEL,
       NVL (E.QTINDENIZ, 0) AS QTAVARIA,
       NVL (E.QTFRENTELOJA, 0) AS QTGONDOLA
  FROM PCEST E
 INNER JOIN PCPRODUT P ON E.CODPROD = P.CODPROD
 WHERE P.DTEXCLUSAO IS NULL
   AND E.CODFILIAL IN (
    1, 2, 7
);
/