SELECT MAX (CODPRECOPROM) AS CODPRECOPROM,
       P.CODPROD,
       P.PRECOFIXO
  FROM PCPRECOPROM P
 INNER JOIN PCEST E ON P.CODPROD = E.CODPROD
 WHERE P.NUMREGIAO = 102
   AND TRUNC (SYSDATE) <= P.DTFIMVIGENCIA
   AND E.QTESTGER > 0
   AND E.CODFILIAL = 7
 GROUP BY P.CODPROD,
          P.PRECOFIXO;
/