WITH PRODUTOPAI AS (
    SELECT P.CODPROD AS COD_PAI,
           P.DESCRICAO AS PRODUTO_PAI
      FROM PCPRODUT P
     WHERE P.CODPROD = P.CODPRODMASTER
       AND P.DTEXCLUSAO IS NULL
)
SELECT P.CODPROD,
       P.CODFAB,
       P.DESCRICAO AS PRODUTO,
       PP.COD_PAI,
       PP.PRODUTO_PAI,
       P.QTUNITCX,
       F.FORNECEDOR,
       D.DESCRICAO AS DEPARTAMENTO,
       S.DESCRICAO AS SECAO,
       M.MARCA
  FROM PCPRODUT P
  LEFT JOIN PCFORNEC F ON P.CODFORNEC = F.CODFORNEC
  LEFT JOIN PCDEPTO D ON P.CODEPTO = D.CODEPTO
  LEFT JOIN PCSECAO S ON P.CODSEC = S.CODSEC
  LEFT JOIN PCMARCA M ON P.CODMARCA = M.CODMARCA
  LEFT JOIN PRODUTOPAI PP ON P.CODPRODMASTER = PP.COD_PAI
 WHERE P.DTEXCLUSAO IS NULL;
/