SELECT PCMOVCRFOR.NUMVERBA,
       PCMOVCRFOR.NUMTRANSCRFOR,
       PCMOVCRFOR.DTPAGO AS DT_REB_VERBA,
       PCMOVCRFOR.TIPOVERBA,
       PCMOVCRFOR.VALOR AS VALOR_VERBA,
       PCMOVCRFOR.HISTORICO1 AS HIST_VERBA,
       PCMOVCRFOR.HISTORICO2,
       PCMOVCRFOR.DTCONCIL,
       A.DTPAGTO AS DTPAGTO_DUPLIC,
       B.CODFORNEC,
       B.FORNECEDOR,
       B.CGC,
       E.NUMNOTA AS NOTA_DEV,
       E.DTSAIDA,
       E.VLTOTAL AS VL_NOTA_DEV,
       E.CODFILIAL AS CODFILIAL_DEV,
       E.OBS,
       E.NFFORNEC AS NUM_NOTA_COMPRA,
       A.CODCONTA,
       C.CONTA,
       A.HISTORICO,
       A.CODFILIAL AS CODFILIAL_PAGTO,
       A.NUMNOTA AS NOTA_VENDA,
       A.DUPLIC,
       A.VALOR,
       A.VPAGOBORDERO,
       A.RECNUM,
       PCMOVCRFOR.NUMLANC,
       PCMOVCRFOR.ROTINALANC,
       A.RECNUMBAIXA,
       A.CODROTINABAIXA,
       PCFILIAL.RAZAOSOCIAL,
       PCFILIAL.CGC AS CNPJ_FILIAL
  FROM PCLANC A,
       PCFORNEC B,
       PCCONTA C,
       PCMOVCRFOR,
       PCNFSAID E,
       PCVERBA F,
       PCFILIAL
 WHERE PCMOVCRFOR.NUMLANC = A.RECNUM
   AND A.CODFORNEC = B.CODFORNEC
   AND A.CODCONTA = C.CODCONTA
   AND PCMOVCRFOR.NUMVERBA = F.NUMVERBA
   AND E.NUMNOTA = F.NUMNOTA
   AND PCFILIAL.CODIGO = A.CODFILIAL
   AND PCMOVCRFOR.DTPAGO IS NOT NULL
   AND A.DTPAGTO IS NULL
   AND PCMOVCRFOR.DTPAGO BETWEEN '01-JAN-2017' AND '05-MAY-2017'
 ORDER BY B.FORNECEDOR,
          CODFILIAL_PAGTO,
          DT_REB_VERBA