------MOVIMENTAÇÃO DA VERBA-------
SELECT ROTINALANC, PCMOVCRFOR.*
  FROM PCMOVCRFOR
 WHERE NUMVERBA = 1485  
ORDER BY NUMTRANSCRFOR;

------ANÁLISE ENTRADA DA NOTA-------
SELECT NUMTRANSENT, PCNFENT.* FROM PCNFENT WHERE NUMNOTA = 143935;

------ANÁLISE DO ITEM NA ENTRADA DA NOTA-------
SELECT DTMOVLOG, PUNITCONT, PLIQPED, QT
  FROM PCMOV
 WHERE NUMTRANSENT = 51297;

------ANÁLISE DO ITEM NO PEDIDO DE COMPRA-------
SELECT PCOMPRA + VLIPI, QTPEDIDA FROM PCITEM WHERE NUMPED = 4244;

------ANÁLISE DE ALTERAÇÕES DO ITEM NO PEDIDO DE COMPRA-------
SELECT PERIPI, L. * FROM PCITEMLOG L WHERE NUMPED = 4244;

------ANÁLISE DO SALDO EM ABERTO NA MOVIMENTAÇÃO DE VERBAS-------
SELECT ROTINALANC, NUMVERBA, PCMOVCRFOR.*
  FROM PCMOVCRFOR
 WHERE VALOR = '60.50'
   AND NUMVERBA = 0;
