SELECT D.NUMVERBA,
       D.NUMTRANSCRFOR,
       D.DTPAGO AS DT_REB_VERBA,
       D.TIPOVERBA,
       D.VALOR AS VALOR_VERBA,
       D.HISTORICO1 AS HIST_VERBA,
       D.HISTORICO2,
       D.DTCONCIL,
       A.DTPAGTO AS PAGTO_DUPLIC,
       B.CODFORNEC,
       B.FORNECEDOR,
       B.CGC,
       E.NUMNOTA AS NOTA_DEV,
       E.DTSAIDA,
       E.VLTOTAL AS VL_NOTA_DEV,
       E.CODFILIAL AS CODFILIAL_DEV,
       E.OBS,
       E.NFFORNEC AS NUM_NOTA_COMPRA,
       A.CODCONTA,
       C.CONTA,
       A.CODFILIAL AS FILIAL_PAGTO,
       A.HISTORICO,
       A.NUMNOTA AS NOTA_VENDA,
       A.DUPLIC,
       A.VALOR,
       A.VPAGOBORDERO,
       A.RECNUM,
       D.NUMLANC,
       D.ROTINALANC,
       A.RECNUMBAIXA,
       A.CODROTINABAIXA,
       G.RAZAOSOCIAL,
       G.CGC
  FROM PCLANC A,
       PCFORNEC B,
       PCCONTA C,
       PCMOVCRFOR D,
       PCNFSAID E,
       PCVERBA F,
       PCFILIAL G
 WHERE D.NUMLANC = A.RECNUM
   AND A.CODFORNEC = B.CODFORNEC
   AND A.CODCONTA = C.CODCONTA
   AND D.NUMVERBA = F.NUMVERBA
   AND E.NUMNOTA = F.NUMNOTA
   AND G.CODIGO = A.CODFILIAL
   AND D.DTPAGO IS NOT NULL
   AND A.DTPAGTO BETWEEN '01-JAN-2017' AND '30-APR-2017'
     /*AND D.DTPAGO BETWEEN '01-JAN-2017' AND '30-APR-2017'*/
 ORDER BY B.FORNECEDOR,
          A.CODFILIAL,
          A.DTPAGTO