/*Verba - Crédito / Débito / Saldo*/
SELECT M.*,
       (NVL (DEBITO, 0) - NVL (CREDITO, 0)) SALDO
  FROM (
    SELECT ROUND (SUM (NVL (V.VALOR, 0)), 4) DEBITO,
           T.CREDITO
      FROM PCMOVCRFOR V,
           (
               SELECT NUMVERBA,
                      ROUND (SUM (NVL (VALOR, 0)), 4) CREDITO
                 FROM PCMOVCRFOR
                WHERE TIPO = 'C'
                GROUP BY NUMVERBA
           ) T
     WHERE T.NUMVERBA (+) = V.NUMVERBA
       AND V.TIPO = 'D'
       AND V.NUMVERBA IN (10979)
     GROUP BY T.CREDITO
) M;

-------

SELECT
  --ROWID,
  A.CODFORNEC,
  A.CODFORNECPRINC,
  A.CONCILIACAO,
  CASE 
    WHEN A.TIPO = 'C' THEN ROUND(A.VALOR, 2)
    ELSE 0
  END AS VALOR_CREDITO,
 
  CASE 
    WHEN A.TIPO = 'D' THEN ROUND(A.VALOR, 2)
    ELSE 0
  END AS VALOR_DEBITO,
  A.TIPO,
  A.NUMVERBA
FROM PCMOVCRFOR A
WHERE A.NUMVERBA IN (10979 ) ;
