--VALOR TOTAL DO PENDENTE---
SELECT ROUND( SUM(C.VLATEND),2 ) AS VLTOTAL
  FROM PCPEDC C
  LEFT JOIN PCSUPERV V
    ON C.CODSUPERVISOR = V.CODSUPERVISOR
 WHERE C.POSICAO NOT IN ('F', 'C') 
   AND V.CODGERENTE IN (1,8,9)
   AND C.CONDVENDA IN (1,7);/

--VALOR TOTAL DO PENDENTE POSICAO BLOQUADO COMERCIAL---  
WITH MAXCODIGOBLOQUEIO AS
 (SELECT MAX(CODIGO) CODIGO_MAX, NUMPED
    FROM PCBLOQUEIOSPEDIDO B
   GROUP BY NUMPED),
MOTIVOBLOQUEIO AS
(SELECT B.NUMPED, B.TIPO
  FROM PCBLOQUEIOSPEDIDO B
 INNER JOIN MAXCODIGOBLOQUEIO M
    ON B.CODIGO = M.CODIGO_MAX
    AND B.NUMPED = M.NUMPED)
SELECT ROUND( SUM(C.VLATEND),2 ) AS VLTOTAL
  FROM PCPEDC C
  LEFT JOIN MOTIVOBLOQUEIO B
  ON C.NUMPED = B.NUMPED
  LEFT JOIN PCSUPERV V
    ON C.CODSUPERVISOR = V.CODSUPERVISOR
 WHERE C.POSICAO IN ('B') 
   AND V.CODGERENTE IN (1,8,9)
   AND C.CONDVENDA IN (1,7)
   AND ( TRIM(C.OBS) NOT LIKE '%FATURAR%' OR C.OBS IS NULL)
   AND B.TIPO = 'C';/
   
--VALOR TOTAL DO PENDENTE POSICAO BLOQUADO FINANCEIRO---  
WITH MAXCODIGOBLOQUEIO AS
 (SELECT MAX(CODIGO) CODIGO_MAX, NUMPED
    FROM PCBLOQUEIOSPEDIDO B
   GROUP BY NUMPED),
MOTIVOBLOQUEIO AS
(SELECT B.NUMPED, B.TIPO
  FROM PCBLOQUEIOSPEDIDO B
 INNER JOIN MAXCODIGOBLOQUEIO M
    ON B.CODIGO = M.CODIGO_MAX
   AND B.NUMPED = M.NUMPED)
SELECT ROUND( SUM(C.VLATEND),2 ) AS VLTOTAL
  FROM PCPEDC C
  LEFT JOIN MOTIVOBLOQUEIO B
  ON C.NUMPED = B.NUMPED
  LEFT JOIN PCSUPERV V
    ON C.CODSUPERVISOR = V.CODSUPERVISOR
 WHERE C.POSICAO IN ('B') 
   AND V.CODGERENTE IN (1,8,9)
   AND C.CONDVENDA IN (1,7)
   AND B.TIPO = 'F';/
   
   
--VALOR TOTAL DO PENDENTE POSICAO PENDENTE---
SELECT ROUND( SUM(C.VLATEND),2 ) AS VLTOTAL
  FROM PCPEDC C
  LEFT JOIN PCSUPERV V
    ON C.CODSUPERVISOR = V.CODSUPERVISOR
 WHERE C.POSICAO IN ('P')
   AND ( TRIM(C.OBS) NOT LIKE '%FATURAR%' OR C.OBS IS NULL)     
   AND V.CODGERENTE IN (1,8,9)
   AND C.CONDVENDA IN (1,7);/
   

----VALOR TOTAL DO PENDENTE POSICAO PENDENTE E BLOQUEADO COM. DATA PROGRAMADA---
WITH MAXCODIGOBLOQUEIO AS
 (SELECT MAX(CODIGO) CODIGO_MAX, NUMPED
    FROM PCBLOQUEIOSPEDIDO B
   GROUP BY NUMPED),
MOTIVOBLOQUEIO AS
(SELECT B.NUMPED, B.TIPO
  FROM PCBLOQUEIOSPEDIDO B
 INNER JOIN MAXCODIGOBLOQUEIO M
    ON B.CODIGO = M.CODIGO_MAX)
SELECT ROUND( SUM(C.VLATEND),2 ) AS VLTOTAL
  FROM PCPEDC C
  LEFT JOIN MOTIVOBLOQUEIO B
  ON C.NUMPED = B.NUMPED
  LEFT JOIN PCSUPERV V
    ON C.CODSUPERVISOR = V.CODSUPERVISOR
 WHERE TRIM(C.OBS) LIKE '%FATURAR%'     
   AND V.CODGERENTE IN (1,8,9)
   AND C.CONDVENDA IN (1,7)
   AND ( (B.TIPO = 'C' AND C.POSICAO = ('B') ) OR C.POSICAO IN ('P') );/   
   
--VALOR TOTAL DO PENDENTE POSICAO LIBERADO ANTECIPADO---
SELECT ROUND( SUM(C.VLATEND),2 ) AS VLTOTAL
  FROM PCPEDC C
  LEFT JOIN PCSUPERV V
    ON C.CODSUPERVISOR = V.CODSUPERVISOR
 WHERE C.POSICAO IN ('L') 
   AND V.CODGERENTE IN (1,8,9)
   AND C.CONDVENDA IN (1,7)
   AND C.CODCOB = 'ANTE';/     
   
--VALOR TOTAL DO PENDENTE POSICAO LIBERADO SEM ANTECIPADO---
SELECT ROUND( SUM(C.VLATEND),2 ) AS VLTOTAL
  FROM PCPEDC C
  LEFT JOIN PCSUPERV V
    ON C.CODSUPERVISOR = V.CODSUPERVISOR
 WHERE C.POSICAO IN ('L') 
   AND V.CODGERENTE IN (1,8,9)
   AND C.CONDVENDA IN (1,7)
   AND C.CODCOB <> 'ANTE';/      
   
--VALOR TOTAL DO PENDENTE POSICAO MONTADO---
SELECT ROUND( NVL( SUM(C.VLATEND), 0) , 2 ) AS VLTOTAL
  FROM PCPEDC C
  LEFT JOIN PCSUPERV V
    ON C.CODSUPERVISOR = V.CODSUPERVISOR
 WHERE C.POSICAO IN ('M') 
   AND V.CODGERENTE IN (1,8,9)
   AND C.CONDVENDA IN (1,7); /