/*ABAIXO DE 500,00---*/
SELECT COUNT (*) AS CONTAGEM
  FROM PCPEDC P
  LEFT JOIN PCCLIENT C ON P.CODCLI = C.CODCLI
  LEFT JOIN PCSUPERV V ON P.CODSUPERVISOR = V.CODSUPERVISOR
 WHERE P.POSICAO IN (
    'B', 'P'
)
   AND V.CODGERENTE IN (
    1, 8, 9, 10
)
   AND P.CODFILIAL IN (
    2
)
   AND P.VLATEND < 500
   AND P.CONDVENDA IN (
    1, 7
)
 ORDER BY P.DATA,
          C.CODCLIPRINC;
/


/*ENTRE 500 E 1000----*/
SELECT COUNT (*) AS CONTAGEM
  FROM PCPEDC P
  LEFT JOIN PCCLIENT C ON P.CODCLI = C.CODCLI
  LEFT JOIN PCSUPERV V ON P.CODSUPERVISOR = V.CODSUPERVISOR
 WHERE P.POSICAO IN (
    'B', 'P'
)
   AND V.CODGERENTE IN (
    1, 8, 9, 10
)
   AND P.CODFILIAL IN (
    2
)
   AND P.CONDVENDA IN (
    1, 7
)
   AND P.VLATEND BETWEEN 500 AND 999.99
 ORDER BY P.DATA,
          C.CODCLIPRINC;
/