SELECT COUNT (*) AS "#VENCIDOS"
  FROM PCLANC L
 WHERE L.DTCANCEL IS NULL
   AND L.DTPAGTO IS NULL
   AND L.DTVENC <= TRUNC (SYSDATE)
   AND L.CODFILIAL IN (
    1, 2, 7
)
   AND L.CODROTINACAD NOT IN (
    'Integradora.Servico.exe'
);
/
SELECT COUNT (*) AS "#VENCIDOS"
  FROM PCLANC L
 WHERE L.DTCANCEL IS NULL
   AND L.DTPAGTO IS NULL
   AND L.DTVENC <= TRUNC (SYSDATE)
   AND L.CODFILIAL IN (
    5
);
/
SELECT COUNT (*) AS "#VENCIDOS"
  FROM PCLANC L
 WHERE L.DTCANCEL IS NULL
   AND L.DTPAGTO IS NULL
   AND L.DTVENC <= TRUNC (SYSDATE)
   AND L.CODFILIAL IN (
    6
);
/
SELECT COUNT (*) AS "#VENCIDOS"
  FROM PCLANC L
 WHERE L.DTCANCEL IS NULL
   AND L.DTPAGTO IS NULL
   AND L.DTVENC <= TRUNC (SYSDATE)
   AND L.CODFILIAL IN (
    1, 2, 7
)
   AND L.CODROTINACAD IN (
    'Integradora.Servico.exe'
);
/