--VALOR TOTAL A SER LIBERADO---
WITH PEDIDOS_VLATENDPREV AS
 (SELECT NUMPED,
         SUM((CASE
               WHEN QTATENDPREV >= 0 THEN
                VALOR
               ELSE
                QTDISPONIVEL * PVENDA
             END)) VLATENDPREV
    FROM (SELECT I.NUMPED,
                 I.PVENDA,
                 ROUND((I.QT * I.PVENDA), 2) VALOR,
                 (E.QTESTGER - E.QTRESERV - E.QTBLOQUEADA) QTDISPONIVEL,
                 (E.QTESTGER - E.QTRESERV - E.QTBLOQUEADA - QT) QTATENDPREV
            FROM PCPEDI I
           INNER JOIN PCEST E
              ON I.CODPROD = E.CODPROD
             AND I.CODFILIALRETIRA = E.CODFILIAL
           INNER JOIN PCPEDC C
              ON I.NUMPED = C.NUMPED
            LEFT JOIN PCSUPERV V
              ON C.CODSUPERVISOR = V.CODSUPERVISOR
           WHERE V.CODGERENTE IN (1, 8, 9)
             AND I.POSICAO IN ('P', 'B'))
   GROUP BY NUMPED),
MAXCODIGOBLOQUEIO AS
 (SELECT MAX(CODIGO) CODIGO_MAX, NUMPED
    FROM PCBLOQUEIOSPEDIDO B
   GROUP BY NUMPED),
MOTIVOBLOQUEIO AS
 (SELECT B.NUMPED, B.TIPO
    FROM PCBLOQUEIOSPEDIDO B
    LEFT JOIN MAXCODIGOBLOQUEIO M
      ON B.CODIGO = M.CODIGO_MAX)
SELECT ROUND(SUM(VLTOTAL), 2) AS VLTOTAL
  FROM PCPEDC C
 INNER JOIN MOTIVOBLOQUEIO B
    ON C.NUMPED = B.NUMPED
 INNER JOIN PEDIDOS_VLATENDPREV P
    ON C.NUMPED = P.NUMPED
  LEFT JOIN PCSUPERV V
    ON C.CODSUPERVISOR = V.CODSUPERVISOR
 WHERE V.CODGERENTE IN (1, 8, 9)
   AND C.CONDVENDA IN (1, 7)
   AND C.CODCOB NOT IN ('ANTE')
   AND (C.POSICAO IN ('P') OR (C.POSICAO = 'B' AND B.TIPO = 'C'))
   AND ( TRIM(C.OBS) NOT LIKE '%FATURAR%' OR C.OBS IS NULL)
   AND P.VLATENDPREV > 1000;/