SELECT T.CODST,
       T.MENSAGEM,
       T.SITTRIBUT,
       T.SITTRIBUTTV7,
       T.SITTRIBUTTV8,
       T.SITTRIBUTTV7ORDEM,
       T.SITTRIBUTTV8ORDEM,
       T.SITTRIBUTTRIANG,
       T.CODFISCALVENDAENTFUT,
       T.CODFISCALVENDAENTFUTINTER,
       T.CODFISCALSIMPENTFUT,
       T.CODFISCALSIMPENTFUTINTER,
       T.CODFISCALCONTAORDEM,
       T.CODFISCALCONTAORDEMINTER,
       T.CODFISCALCONTAORDEMSIMPENT,
       T.CODFISCALCONTAORDEMSIMPENTINTE,
       T.CODFISCALTRIANGULAR,
       T.CODFISCALTRIANGULARINTER,
       T.CODFISCALTRIANGULARPF,
       T.CODFISCALTRIANGULARINTERPF
  FROM PCTRIBUT T
 WHERE MENSAGEM NOT LIKE '*INATIVO%'
   AND MENSAGEM NOT LIKE 'ICMS PARTILHA%';
/