CREATE OR REPLACE VIEW VIEW_JC_PCEST AS
SELECT E.CODFILIAL,
       E.CODPROD,
       NVL(E.QTEST, 0) AS QTCONTABIL,
       NVL(E.QTESTGER, 0) AS QTGERENCIAL,
       NVL(E.QTPEDIDA,0) AS QTCOMPRA,
       (NVL(E.QTESTGER, 0) - NVL(E.QTBLOQUEADA, 0) - NVL(E.QTRESERV, 0)) AS QTDISPONIVEL,
       NVL(E.QTBLOQUEADA, 0) AS QTBLOQUEADA,
       NVL(E.QTRESERV, 0) AS QTRESERVADA,
       NVL(E.QTINDENIZ, 0) AS QTAVARIADA,
       NVL(E.QTFRENTELOJA, 0) AS QTFRENTELOJA,
       NVL(E.VALORULTENT, 0) AS VALORULTENT,
       NVL(E.CUSTOULTENT, 0) AS CUSTOULTENT,
       NVL(E.CUSTOFIN, 0) AS CUSTOFINANCEIRO,
       NVL(E.CUSTOCONT, 0) AS CUSTOCONTABIL,
       NVL(E.CUSTOREP, 0) AS CUSTOREPOSICAO,
       E.CODDEVOL AS CODBLOQUEIO
  FROM PCEST E;
