CREATE OR REPLACE VIEW VIEW_JC_GRUPOCONTAS AS
SELECT C.GRUPOCONTA,
       (C.GRUPOCONTA || ' - ' || G.GRUPO) GRUPO,
       C.CODCONTA,
       (C.CODCONTA || ' - ' || C.CONTA) CONTA,
       C.CONTACONTABIL
  FROM PCCONTA C
  LEFT JOIN PCGRUPO G
    ON C.GRUPOCONTA = G.CODGRUPO;
