SELECT L.*
  FROM PCCONTROLELIVROFISCAL L
 WHERE CODFILIAL = 5
   AND ANO = 2019;

SELECT L.*
  FROM PCCONTROLEITEMLIVROFISCAL L
 WHERE CODFILIAL = 5
   AND ANO = 2019
   AND MES = 10;

UPDATE PCCONTROLELIVROFISCAL
   SET ENCERRADO = 'N'
 WHERE CODFILIAL = 5
   AND ANO = 2019
   AND MES = 10;

UPDATE PCCONTROLEITEMLIVROFISCAL
   SET ENCERRADO = 'N'
 WHERE CODFILIAL = 5
   AND ANO = 2019
   AND MES = 10;

UPDATE PCCONTROLELIVROFISCAL
   SET ENCERRADO = 'S'
 WHERE CODFILIAL = 5
   AND ANO = 2019
   AND MES = 10;

UPDATE PCCONTROLEITEMLIVROFISCAL
   SET ENCERRADO = 'S'
 WHERE CODFILIAL = 5
   AND ANO = 2019
   AND MES = 10;



SELECT L.*
  FROM PCCONTROLELIVROFISCAL L
 WHERE ENCERRADO = 'N'
   AND MES < 5
   ORDER BY ANO DESC, MES DESC, CODFILIAL;

SELECT L.*
  FROM PCCONTROLEITEMLIVROFISCAL L
 WHERE ENCERRADO = 'N'
   ORDER BY ANO DESC, MES DESC, DIA DESC, CODFILIAL;