SELECT L.*
  FROM PCCONTROLELIVROFISCAL L
 WHERE CODFILIAL = 7
   AND ANO = 2023;

SELECT L.*
  FROM PCCONTROLEITEMLIVROFISCAL L
 WHERE CODFILIAL = 7
   AND ANO = 2023
   AND MES = 3;

UPDATE PCCONTROLELIVROFISCAL
   SET ENCERRADO = 'N'
 WHERE CODFILIAL = 7
   AND ANO = 2023
   AND MES = 3;

UPDATE PCCONTROLEITEMLIVROFISCAL
   SET ENCERRADO = 'N'
 WHERE CODFILIAL = 7
   AND ANO = 2023
   AND MES = 3;

UPDATE PCCONTROLELIVROFISCAL
   SET ENCERRADO = 'S'
 WHERE CODFILIAL = 7
   AND ANO = 2023
   AND MES = 3;

UPDATE PCCONTROLEITEMLIVROFISCAL
   SET ENCERRADO = 'S'
 WHERE CODFILIAL = 7
   AND ANO = 2023
   AND MES = 3;



SELECT L.ROWID, L.*
  FROM PCCONTROLELIVROFISCAL L
 WHERE CODFILIAL = '1' AND ANO = 2025 AND MES = 1
   ORDER BY ANO DESC, MES DESC, CODFILIAL;

SELECT L.ROWID, L.*
  FROM PCCONTROLEITEMLIVROFISCAL L
 WHERE CODFILIAL = '1' AND ANO = 2025 AND MES = 1 AND DIA = 31
   ORDER BY ANO DESC, MES DESC, DIA DESC, CODFILIAL;
