/*-----VERIFICAR CFOP------*/
SELECT CODST,
       MENSAGEM,
       CODFISCALCONTAORDEM,
       CODFISCALCONTAORDEMINTER
  FROM PCTRIBUT
 WHERE CODST IN (
    3, 90, 91
);
/

/*--ALTERAR CFOP PARA REALIZAR A VENDA TRIANGULAR-----*/
UPDATE PCTRIBUT
   SET CODFISCALCONTAORDEM = 5120,
       CODFISCALCONTAORDEMINTER = 6120
 WHERE CODST IN (
    3, 90, 91
);
/

/*---RETORNAR O CFOP CORRETO PARA VENDA CONTA E ORDEM---- */
UPDATE PCTRIBUT
   SET CODFISCALCONTAORDEM = 5119,
       CODFISCALCONTAORDEMINTER = 6119
 WHERE CODST IN (
    3, 90, 91
);
/