/*----IDENTIFICAR AS FIGURAS TRIBUTARIAS----------*/
SELECT CODFISCALSIMPENTFUT,
       CODFISCALSIMPENTFUTINTER,
       PCTRIBUT.*
  FROM PCTRIBUT
 WHERE (CODFISCALSIMPENTFUT = 5117
    OR CODFISCALSIMPENTFUTINTER = 6117);
/

/*----ATUALIZAR COM O CFOP DE VENDA CONTA E ORDEM------------*/
UPDATE PCTRIBUT
   SET CODFISCALSIMPENTFUT = '5923',
       CODFISCALSIMPENTFUTINTER = '6923'
 WHERE (CODFISCALSIMPENTFUT = 5117
    OR CODFISCALSIMPENTFUTINTER = 6117);
/

/*----VERIFICAR PEDIDOS QUE SÃO TV8 COMO VENDA FUTURA--------*/
SELECT CONTAORDEM,
       PCPEDC.*
  FROM PCPEDC
 WHERE POSICAO NOT IN (
    'F', 'C'
)
   AND CODFILIAL = '1'
   AND CODUSUR = '14'
   AND CODCOB = 'SENT'
   AND CONDVENDA = '8'; /    
/*---ATUALIZAR CAMPO CONTAORDEM PARA NÃO------   */
UPDATE PCPEDC
   SET
    CONTAORDEM = 'N'
 WHERE POSICAO NOT IN (
    'F', 'C'
)
   AND CODFILIAL = '1'
   AND CODUSUR = '14'
   AND CODCOB = 'SENT'
   AND CONDVENDA = '8';
/
