SELECT M.ROWID,
       M.VLBASEPISCOFINSBKP,
       M.VLCREDPISBKP,
       M.VLCREDCOFINSBKP,
       P.VLBASEPISCOFINS,
       P.VLCREDPIS,
       P.VLCREDCOFINS,
       M.PERPISBKP,
			 M.PERCOFINSBKP,
			 (M.VLBASEPISCOFINSBKP * M.PERPISBKP / 100) VLCREDPIS_CALC,
			 (M.VLBASEPISCOFINSBKP * M.PERCOFINSBKP / 100) VLCREDCOFINS_CALC,
       M.*
  FROM PCMOVCOMPLE M
 INNER JOIN PCMOV P ON M.NUMTRANSITEM = P.NUMTRANSITEM
 WHERE 1=1 
 AND P.NUMTRANSENT IN (1863442)
   --AND P.NUMTRANSVENDA IN (22433912)
   -- AND M.NUMTRANSITEM IN ( 104936794, 104936795)
   --AND P.CODPROD IN (825931)
	 ;

