--CORRIGIR CODST, CODICMTAB, PERCICM SUBSTITUINDO PELOS VALORES CORRETOS
--PARA RECALCULO DO ICMS PARTILHA SÓ REPROCESSAR A NOTA
SELECT F.ROWID,
       F.CODFILIALNF,
       F.CODPROD,
       F.DESCRICAO AS PRODUTO,
       F.CODST,
       F.CODICMTAB,
       F.PERCICM,
       B.CODST AS CODST_CORRETO,
       T.CODICMTAB AS CODICMTAB_CORRETO,
       T.CODICM AS PERCICM_CORRETO
  FROM PCMOVPREFAT F
  LEFT JOIN PCNFSAIDPREFAT S ON F.NUMTRANSVENDA = S.NUMTRANSVENDA
  LEFT JOIN PCTABTRIB B ON F.CODPROD = B.CODPROD AND F.CODFILIALNF = B.CODFILIALNF
  LEFT JOIN PCTRIBUT T ON B.CODST = T.CODST
 WHERE S.UF = B.UFDESTINO
 AND F.NUMTRANSVENDA = 21980118;
