--CORRIGIR CODST, PERCICM, CODICMTAB
--PARA RECALCULO DO ICMS PARTILHA SÓ REPROCESSAR A NOTA
SELECT ROWID,
       F.CODST,
       F.ALIQICMSVIGENTE,
       F.BASEICMS,
       F.CODICMTAB,
       F.PERCICM,
       F.VLBASEPISCOFINS,
       F.*
  FROM PCMOVPREFAT F
 WHERE NUMTRANSVENDA = 10566620;
