--CORRIGIR CODST, ALIQICMS, CODICMTAB, BASEICMS SE NECESSARIO
--CORRIGIR O VALOR DE ICMS NA 1008 ANTES DE REPROCESSAR A NOTA
--PARA RECALCULO DO ICMS PARTILHA SÓ REPROCESSAR A NOTA
SELECT ROWID,
       F.CODST,
       F.ALIQICMSVIGENTE,
       F.BASEICMS,
       F.CODICMTAB,
       F.PERCICM,
       F.VLBASEPISCOFINS,
       F.*
  FROM PCMOVPREFAT F
 WHERE NUMTRANSVENDA = 10566620;
