/*-----CORREÇÃO DOS CREDITO DE ICMS---------*/
--NOVO
SELECT ROWID,
       M.BASEICMS,
       M.PERCICM,
       M.PERCREDICMS,
       M.VLCREDICMS,
       CASE
         WHEN M.GERAICMSLIVROFISCAL = 'S' THEN
          M.BASEICMS * M.PERCICM / 100
         ELSE
          0
       END VLICMSCALC,
       M.GERAICMSLIVROFISCAL,
       M.*
  FROM PCMOV M
 WHERE M.NUMTRANSENT = 1843167
   AND M.CODPROD IN (818073)
   AND M.GERAICMSLIVROFISCAL = 'S'
 ORDER BY CODPROD;
 
--ANTIGO
SELECT ROWID,
       PERCREDICMS,
       VLCREDICMS,
       PERCICMRED,
       PERCICM,
       SITTRIBUT,
       CUSTOCONT,
       CUSTOFIN,
       CUSTOULTENT,
       CUSTOREAL,
       CODST,
       ((PUNIT - NVL (VLIPI, 0)) * PERCICM / 100) VLCRED_CORRETO,
       M.*
  FROM PCMOV M
 WHERE NUMTRANSENT = 323547
      /*NUMTRANSVENDA = 10372610*/
   AND CODPROD IN (
    1514
);

/*--ANÁLISE DA ENTRADA DO PRODUTO PELO FORNECEDOR----*/
SELECT NUMTRANSENT,
       NUMTRANSVENDA,
       M.*
  FROM PCMOV M
 WHERE M.CODPROD = 802926
   AND M.CODOPER LIKE 'ST%'
 ORDER BY DTMOV;

/*-VER NCM DO PRODUTO---*/
SELECT CODPROD,
       DESCRICAO,
       CODNCMEX,
       CODFORNEC
  FROM PCPRODUT
 WHERE CODPROD = 808089;

/*---VER TIPO DE FORNECEDOR E UF---*/
SELECT CODFORNEC,
       FORNECEDOR,
       TIPOFORNEC,
       ESTADO
  FROM PCFORNEC
 WHERE CODFORNEC = 9642;

/*--ANÁLISE DA TRIBUTAÇÃO DE ENTRADA----*/
SELECT *
  FROM PCTRIBENTRADA
 WHERE NCM = 90049090.;
SELECT CODFIGURA,
       DESCRICAO
  FROM PCTRIBFIGURA
 WHERE CODFIGURA = 76;

/*--ANÁLISE DA TRIBUTAÇÃO DE SAÍDA ----*/
SELECT *
  FROM PCTABTRIB
 WHERE CODPROD = 802926
   AND UFDESTINO = 'SP';
SELECT CODST,
       MENSAGEM
  FROM PCTRIBUT
 WHERE CODST IN (
    61
);

/*---------ANALISE DOS CUSTOS DO PRODUTO NA FILIAL--------*/
SELECT ROWID,
       E.CODFILIAL,
       E.CODPROD,
       E.VALORULTENT,
       E.CUSTOULTENT,
       E.CUSTOCONT,
       E.CUSTOREAL,
       E.CUSTOFIN,
       E.CUSTOREP
  FROM PCEST E
 WHERE CODPROD = 808021
   AND CODFILIAL IN (
    1, 7
);
