---------------LIMPAR O NUMPEDCLI E MANDAR RODAR A NOTA NOVAMENTE-------------------
SELECT ROWID,
       PCNFSAID.NUMPEDCLI,
       PCNFSAID.NUMPED,
       SITUACAONFE,
       AMBIENTENFE,
       CHAVENFE,
       PROTOCOLONFE,
       PCNFSAID.*
  FROM PCNFSAID
 WHERE NUMTRANSVENDA IN (10245212);/

SELECT NUM_PEDIDO_CLI, LENGTH(NUM_PEDIDO_CLI), NUM_TRANSACAO
  FROM SQL_NFE_CABECALHO_SAIDA
 WHERE NUM_TRANSACAO IN (10245212);/

SELECT ROWID, A.NUMPEDCLI, A.*
  FROM PCPEDCTEMP A
 WHERE A.NUMPED = 4500028246;/

SELECT COUNT(C.NUMPED)
  FROM PCPEDC C
 WHERE C.POSICAO = 'L'
   AND C.CODSUPERVISOR IN (7, 8)
   AND C.CODFILIAL = 7;/
