WITH TRANSFERENCIA AS
 (SELECT NUMNOTA,
         CODPROD,
         MOVIMENTO,
         VLICMS
    FROM BI_SINC_MOV_PRODUTO M
   WHERE M.TIPOMOV IN ('ENTRADA TRANSFERENCIA', 'SAIDA TRANSFERENCIA')),

ANALISE_ENT_SAIDA AS
 (SELECT * FROM TRANSFERENCIA PIVOT(SUM(VLICMS) FOR MOVIMENTO IN('E' ENTRADA, 'S' SAIDA)))

SELECT * FROM ANALISE_ENT_SAIDA WHERE ENTRADA <> SAIDA
