SELECT DISTINCT F.CODCONTAB,
                L.CODFORNEC,
                F.FORNECEDOR
  FROM PCFORNEC F
 INNER JOIN PCLANC L ON F.CODFORNEC = L.CODFORNEC
   AND L.TIPOPARCEIRO = 'F'
   AND L.CODCONTA IN (
    410104, 420102, 620106, 620109
)
 WHERE (F.FORNECEDOR LIKE '%AMERICANAS%'
    OR F.FORNECEDOR LIKE '%B2W%'
    OR F.FORNECEDOR LIKE '%AMAZON%'
    OR F.FORNECEDOR LIKE '%MERCADO LIVRE%'
    OR F.FORNECEDOR LIKE '%MERCADO PAGO%'
    OR F.FORNECEDOR LIKE '%MERCADO ENVIO%'
    OR F.FORNECEDOR LIKE '%EBAZAR%'
    OR F.FORNECEDOR LIKE '%CARREFOUR%'
    OR F.FORNECEDOR LIKE '%VIA VAREJO%'
    OR F.FORNECEDOR LIKE 'VIA%'
    OR F.FORNECEDOR LIKE '%CNOVA%'
    OR F.FORNECEDOR LIKE '%RI HAPPY%'
    OR F.FORNECEDOR LIKE '%PAYMEE%'
    OR F.FORNECEDOR LIKE '%WMB%'
    OR F.FORNECEDOR LIKE '%WALMART%'
    OR F.FORNECEDOR LIKE '%PAGAR.ME%')
   AND F.CODCONTAB IS NULL
 ORDER BY F.FORNECEDOR;