WITH PRODUTOS_DEVOLVIDOS AS
 (SELECT M.CODPROD,
         SUM(M.QT) QT_DEV,
         (SUM(M.QT) * AVG(M.VALORULTENT)) CUSTO_DEV
    FROM PCMOV M
   WHERE M.DTCANCEL IS NULL
     AND M.CODFILIAL = '11'
     AND M.CODFISCAL IN (1202, 2202, 1411, 2411)
     AND M.DTMOV BETWEEN TO_DATE('07/09/2025', 'DD/MM/YYYY') AND TO_DATE('30/09/2025', 'DD/MM/YYYY')
   GROUP BY M.CODPROD),

PRODUTOS_COMPRADO_F11 AS
 (SELECT M.CODFILIAL,
         M.CODPROD,
         P.CODFAB,
         P.DESCRICAO,
         SUM(M.QT) QT_COMPRADO,
         MAX(DTMOV) ULTIMA_COMPRA
    FROM PCMOV M
    JOIN PRODUTOS_DEVOLVIDOS D ON D.CODPROD = M.CODPROD
    LEFT JOIN PCPRODUT P ON P.CODPROD = M.CODPROD
   WHERE M.DTCANCEL IS NULL
     AND M.CODFILIAL IN ('11')
     AND M.CODFISCAL IN (1102, 2102, 1403, 1405, 2403)
   GROUP BY M.CODFILIAL,
            M.CODPROD,
            P.CODFAB,
            P.DESCRICAO),

PRODUTOS_COMPRADO_F02 AS
 (SELECT M.CODFILIAL,
         M.CODPROD,
         P.CODFAB,
         P.DESCRICAO,
         SUM(M.QT) QT_COMPRADO,
         MAX(DTMOV) ULTIMA_COMPRA
    FROM PCMOV M
    JOIN PRODUTOS_DEVOLVIDOS D ON D.CODPROD = M.CODPROD
    LEFT JOIN PCPRODUT P ON P.CODPROD = M.CODPROD
    LEFT JOIN PRODUTOS_COMPRADO_F11 F ON F.CODPROD = M.CODPROD
   WHERE M.DTCANCEL IS NULL
     AND M.CODFILIAL IN ('2')
     AND M.CODFISCAL IN (1102, 2102, 1403, 1405, 2403)
     AND F.CODPROD IS NULL
   GROUP BY M.CODFILIAL,
            M.CODPROD,
            P.CODFAB,
            P.DESCRICAO)

SELECT M.CODFILIAL,
       M.CODPROD,
       M.CODFAB,
       M.DESCRICAO,
       M.QT_COMPRADO,
       M.ULTIMA_COMPRA,
       D.QT_DEV,
       ROUND(D.CUSTO_DEV, 2) CUSTO_DEV
  FROM (SELECT * FROM PRODUTOS_COMPRADO_F02 UNION SELECT * FROM PRODUTOS_COMPRADO_F11) M
  JOIN PRODUTOS_DEVOLVIDOS D ON D.CODPROD = M.CODPROD
 ORDER BY TO_NUMBER(CODFILIAL)
