/*CORREÇÃO DE NUMERO DE NOTA LANÇADA*/
SELECT ROWID,
       NUMNOTA,
       L.*
  FROM PCLANC L
 WHERE NUMTRANS = 125410;
/
 /*CORRIGIR NA PCMOVCR TAMBEM*/
SELECT ROWID,
       NUMCARR,
       M.*
  FROM PCMOVCR M
 WHERE NUMTRANS = 125410;