------PRIMEIRO DEVEMOS ESTORNAR A TRANSFERENICA DE NUMERÁRIOS NA 639-------

------LANCAR CRÉDITO NA ROTINA 618 E DEPOIS ALTERAR O DTLANC PARA DATA QUE REALMENTE O DINHEIRO ENTROU NA CONTA------
SELECT ROWID, DTLANC, C.* FROM PCCRECLI C WHERE CODCLI = 17841;

------CORRIGIR A DATA DO LANÇAMENTO PARA O DIA QUE O CREDITO ENTROU NA CONTA E REALIZAR DEVIDA CONCILIAÇÃO------
SELECT ROWID, C.* FROM PCMOVCR C WHERE NUMTRANS = 93474;
