--LANCAMENTOS SEM CONTA INFORMADA
SELECT L.*
  FROM PCLANC L
 WHERE L.CODCONTA = 0
   AND CODROTINACAD = 'ESJCB9876.exe'
 ORDER BY DTLANC DESC;
 
--UPDATE CORREÇAO CODCONTA ZERADO
UPDATE PCLANC
   SET CODCONTA = 620108
 WHERE CODCONTA = 0
   AND CODROTINACAD = 'ESJCB9876.exe';

--LANCAMENTO COM DESCONTO NA CONTA INCORRETA
SELECT L. *
  FROM PCLANC L
 WHERE L.CODCONTA = 620103
   AND CODROTINABAIXA IN (1209, 1207)
   AND CODFILIAL IN ('7', '9', '10')
   AND CODFORNEC NOT IN (8630)
 ORDER BY DTLANC DESC;
 
--UPDATE CORREÇAO CODCONTA ERRADA
UPDATE PCLANC
   SET CODCONTA = 620108
 WHERE CODCONTA = 620103
   AND CODROTINABAIXA IN (1209, 1207)
   AND CODFILIAL IN ('7', '9', '10')
   AND CODFORNEC NOT IN (8630);
