SELECT L.CODROTINAALT, L.CODROTINABAIXA, L.*
  FROM PCLANC L
 WHERE NVL(L.CODCONTA, 0) = 0
   AND L.INDICE = 'A'
   AND NVL(L.CODFORNEC, 0) <> 0;

--UPDATE
UPDATE PCLANC L
   SET L.CODCONTA = 620108
 WHERE NVL(L.CODCONTA, 0) = 0
   AND L.INDICE = 'A'
   AND NVL(CODFORNEC, 0) <> 0;


  SELECT L.CODROTINAALT, L.CODROTINABAIXA, L.*
    FROM PCLANC L
   WHERE L.CODCONTA = 620108
     AND L.DTLANC = TRUNC(SYSDATE)
     AND L.CODROTINABAIXA = 9876;

/
