WITH VENDEDOR AS
 (SELECT U.CODUSUR, U.USURDIRFV VENDEDOR, V.CODGERENTE
    FROM PCUSUARI U
    JOIN PCSUPERV V ON V.CODSUPERVISOR = U.CODSUPERVISOR
    JOIN PCGERENTE G ON V.CODGERENTE = G.CODGERENTE),
FILTRO_CLIENTE AS
 (SELECT C.CODCLI,
         (CASE
           WHEN R.DESCRICAO IS NULL THEN
            ('C' || C.CODCLI)
           ELSE
            ('R' || C.CODREDE)
         END) AS CODCLIREDE,
         (CASE
           WHEN R.DESCRICAO IS NULL THEN
            ('C' || C.CODCLI || ' - ' || UPPER(C.CLIENTE))
           ELSE
            ('R' || C.CODREDE || ' - ' || UPPER(R.DESCRICAO))
         END) AS CLIENTE_REDE,
         C.CODCLIPRINC,
         V.VENDEDOR
    FROM PCCLIENT C
    JOIN VENDEDOR V ON C.CODUSUR1 = V.CODUSUR
    LEFT JOIN PCREDECLIENTE R ON C.CODREDE = R.CODREDE
   WHERE V.CODGERENTE IN (1, 8, 9, 10)
     AND C.DTEXCLUSAO IS NULL
     AND C.CODCOB NOT IN ('ANTE')
     AND C.BLOQUEIODEFINITIVO = 'N'
     AND ((C.CODCLI = C.CODCLIPRINC AND C.LIMCRED = 0) OR
         (C.CODCLI <> C.CODCLIPRINC AND C.LIMCRED > 0)))
SELECT DISTINCT C.DTCADASTRO,
       C.BLOQUEIODEFINITIVO AS BLOQUEADO,
       C.BLOQUEIO AS BLOQ_ATUAL,
       C.CODCOB,
       F.CODCLIREDE,
       C.CODCLI,
       C.CODCLIPRINC,
       F.CLIENTE_REDE,
       F.VENDEDOR,
       C.CLIENTE,
       C.LIMCRED,
       CASE
         WHEN C.CODCLI = F.CODCLIPRINC THEN
          'S'
         ELSE
          'N'
       END PRINCIPAL
  FROM PCCLIENT C
  JOIN FILTRO_CLIENTE F ON C.CODCLIPRINC = F.CODCLIPRINC
 ORDER BY C.CODCLIPRINC, C.CODCLI;
 /