---PRIMEIRO TRAZER OS CLIENTES PRINCIPAIS DE REDES DA DISTRIBUIÇÃO
WITH VENDEDOR AS
 (SELECT U.CODUSUR, U.USURDIRFV VENDEDOR, V.CODGERENTE
    FROM PCUSUARI U
    JOIN PCSUPERV V ON V.CODSUPERVISOR = U.CODSUPERVISOR
    JOIN PCGERENTE G ON V.CODGERENTE = G.CODGERENTE),
CLIENTES_DISTRIBUICAO AS
 (SELECT C.CODCLI,
         C.CODCLIPRINC,
         C.CLIENTE,
         V.CODUSUR,
         V.VENDEDOR,
         V.CODGERENTE
    FROM PCCLIENT C
    JOIN VENDEDOR V ON C.CODUSUR1 = V.CODUSUR
    JOIN PCREDECLIENTE R ON C.CODREDE = R.CODREDE
   WHERE V.CODGERENTE IN (1, 8, 9, 10)),
CLI_PRINCIPAIS_DISTRIBUICAO AS
 (SELECT DISTINCT CODCLIPRINC FROM CLIENTES_DISTRIBUICAO),

--SEGUNDO DENTRE ESSES CLIENTES PRINCIPAIS TRAZER AQUELES QUE POSSUEM VENDEDORES DIFERENTE DA DISTRIBUIÇÃO
CLIENTES_VENDEDOR_ERRADO AS
 (SELECT C.CODCLI,
         C.CODCLIPRINC,
         C.CLIENTE,
         C.CODREDE,
         V.CODUSUR,
         V.VENDEDOR,
         V.CODGERENTE
    FROM PCCLIENT C
    JOIN CLI_PRINCIPAIS_DISTRIBUICAO CD ON CD.CODCLIPRINC = C.CODCLIPRINC
    JOIN VENDEDOR V ON C.CODUSUR1 = V.CODUSUR
   WHERE V.CODGERENTE NOT IN (1, 8, 9, 10)),
CLI_PRINCIPAL_VENDA_ERRADO AS
 (SELECT DISTINCT CODCLIPRINC FROM CLIENTES_VENDEDOR_ERRADO),

--TERCEIRO TRAZER APENAS ESSES CLIENTES PRINCIPAIS SEM FILTRO DE VENDEDOR
VENDEDOR_CORRETO AS
 (SELECT C.CODCLIPRINC, MAX(C.CODUSUR1) CODUSUR_CORRETO
    FROM PCCLIENT C
    JOIN CLI_PRINCIPAL_VENDA_ERRADO CD ON CD.CODCLIPRINC = C.CODCLIPRINC
    JOIN VENDEDOR V ON C.CODUSUR1 = V.CODUSUR
   WHERE V.CODGERENTE IN (1, 8, 9, 10)
   GROUP BY C.CODCLIPRINC)
SELECT C.DTCADASTRO,
       C.BLOQUEIODEFINITIVO AS BLOQUEADO,
       C.BLOQUEIO AS BLOQ_ATUAL,
       C.CODCOB,
       C.CODREDE,
       R.DESCRICAO AS REDE,
       C.CODCLI,
       C.CODCLIPRINC,
       C.CLIENTE,
       VC.CODUSUR_CORRETO,
       V.CODUSUR,
       V.VENDEDOR,
       V.CODGERENTE,
       C.LIMCRED,
       CASE
         WHEN C.CODCLI = CD.CODCLIPRINC THEN
          'S'
         ELSE
          'N'
       END PRINCIPAL
  FROM PCCLIENT C
  JOIN CLI_PRINCIPAL_VENDA_ERRADO CD ON CD.CODCLIPRINC = C.CODCLIPRINC
  JOIN VENDEDOR V ON C.CODUSUR1 = V.CODUSUR
  LEFT JOIN PCREDECLIENTE R ON C.CODREDE = R.CODREDE
  LEFT JOIN VENDEDOR_CORRETO VC ON VC.CODCLIPRINC = C.CODCLIPRINC
 ORDER BY C.CODCLIPRINC, C.CODCLI;
/