WITH CONTAGEMREDE AS
 (SELECT CODREDE, COUNT(CODREDE) AS CONT_REDE
    FROM PCCLIENT
   WHERE TIPOFJ = 'J'
   GROUP BY CODREDE),
CONTAGEMCLIPRINCIPAL AS
 (SELECT CODCLIPRINC, COUNT(CODCLIPRINC) AS CONT_CLIPRINC
    FROM PCCLIENT
   WHERE TIPOFJ = 'J'
   GROUP BY CODCLIPRINC)
SELECT C.CODREDE,
       R.DESCRICAO REDE,
       C.CODCLIPRINC,
       C.CODCLI,
       (SELECT MIN(PCCLIENT.CODCLI)
          FROM PCCLIENT
         WHERE PCCLIENT.CODREDE = C.CODREDE) NOVO_CLIPRINC,
       C.CLIENTE,
       C.CODUSUR1 VENDEDOR,
       CR.CONT_REDE,
       CP.CONT_CLIPRINC
  FROM PCCLIENT C
  LEFT JOIN PCREDECLIENTE R ON C.CODREDE = R.CODREDE
  LEFT JOIN CONTAGEMREDE CR ON C.CODREDE = CR.CODREDE
  LEFT JOIN CONTAGEMCLIPRINCIPAL CP ON C.CODCLIPRINC = CP.CODCLIPRINC
 WHERE C.TIPOFJ = 'J'
   AND NVL(C.CODREDE,0) <> 0
   AND CR.CONT_REDE <> CP.CONT_CLIPRINC
 ORDER BY C.CODREDE DESC, C.CODCLI;