SELECT CODCLI AS CODIGO,
       CLIENTE AS DESCRICAO,
       CGCENT,
       IEENT,
       CODUSUR1,
       CODATV1,
       CODCIDADE,
       DTCADASTRO,
       CODPRACA,
       ENDERENT,
       BAIRROENT,
       CEPENT,
       CEPCOB,
       CEPCOM,
       EMITEDUP,
       CONSUMIDORFINAL,
       CLIENTPROTESTO,
       ENDERCOM,
       ENDERCOB,
       PISCOFINSCUMULATIVO
  FROM PCCLIENT
 WHERE (CODUSUR1 IS NULL
    OR CODCLI IS NULL
    OR CLIENTE IS NULL
    OR TIPOFJ IS NULL
    OR CGCENT IS NULL
    OR IEENT IS NULL
    OR CODATV1 IS NULL
    OR CODCIDADE IS NULL
    OR DTCADASTRO IS NULL
    OR CODPRACA IS NULL
    OR ENDERENT IS NULL
    OR BAIRROENT IS NULL
    OR CEPENT IS NULL
    OR CEPCOB IS NULL
    OR CEPCOM IS NULL
    OR EMITEDUP IS NULL
    OR CONSUMIDORFINAL IS NULL
    OR CLIENTPROTESTO IS NULL
    OR ENDERCOM IS NULL
    OR ENDERCOB IS NULL
    OR PISCOFINSCUMULATIVO IS NULL)
   AND DTEXCLUSAO IS NULL
   AND DTEXCLUSAO IS NULL
   AND CODCLI NOT IN (
    1, 2, 3
);