SELECT P.CODCLIPRINC,
       P.CODCLI,
       P.CLIENTE,
       P.CODCOB,
       P.CODPLPAG,
       P.CODUSUR1,
       P.CODATV1,
       P.CODPRACA
  FROM PCCLIENT P, PCUSUARI S
 WHERE P.CODUSUR1 = S.CODUSUR
   AND S.CODSUPERVISOR = 5
   AND (((((P.CODCOB <> 'CONV' OR P.CODPLPAG <> 10) OR P.CODUSUR1 <> 18) OR
       P.CODCLIPRINC <> 1) OR P.CODPRACA <> 9) OR P.CODATV1 <> 11)
   AND P.CODCLI NOT IN (1, 8630)
 ORDER BY P.CLIENTE;