--Títulos não recebidos para análise
WITH TRANSACAO_VENDA_DEVOLVIDA AS
 (SELECT NUMTRANSENT, MAX(M.NUMTRANSDEV) AS NUMTRANSVENDA
    FROM PCMOV M
   WHERE NVL(NUMTRANSDEV, 0) <> 0
     AND NVL(NUMTRANSDEV, 0) <> 0
   GROUP BY NUMTRANSENT),
CREDITOS_ABERTOS AS
 (SELECT (C.CODCLI || '-' || T.CLIENTE) CLIENTE,
         C.VALOR AS VALOR_CREDITO,
         C.DTLANC DTLANC_CRED,
         D.NUMTRANSVENDA
    FROM PCCRECLI C
   INNER JOIN TRANSACAO_VENDA_DEVOLVIDA D ON C.NUMTRANSENTDEVCLI =
                                             D.NUMTRANSENT
   INNER JOIN PCCLIENT T ON C.CODCLI = T.CODCLI
   WHERE C.DTDESCONTO IS NULL)
SELECT P.CODFILIAL,
       P.DTEMISSAO,
       W.NUMPEDRCA,
       W.NUMPED,
       COALESCE(W.NUMPEDCLI, CT.NUMPEDCLI) NUMPEDCLI,
       (SELECT (P1.CODCLI || ' - ' || C1.CLIENTE)
          FROM PCPREST P1
          LEFT JOIN PCCLIENT C1 ON C1.CODCLI = P1.CODCLI
         WHERE P1.NUMTRANSVENDA = S.NUMTRANSVENDA
           AND P1.PREST = '1') CLIENTE,
       P.CODCLI || ' - ' || C.CLIENTE CLIENTE_MKT,
       P.NUMTRANSVENDA,
       P.CODCOBORIG,
       P.CODCOB,
       P.CODUSUR,
       (P.DUPLIC || '-' || P.PREST) DUPLICATA,
       P.VALOR,
       (P.VALOR - NVL(P.VALORDESC, 0)) VALORLIQ,
       P.DTVENC,
       P.OBSTITULO,
       TO_DATE(LPAD(P.OBSTITULO, 10), 'DD/MM/YYYY') DTOBS,
       A.CLIENTE CLIENTE_CRED,
       A.VALOR_CREDITO,
       A.DTLANC_CRED
  FROM PCPREST P
  JOIN PCNFSAID S ON P.NUMTRANSVENDA = S.NUMTRANSVENDA
  LEFT JOIN PCCLIENT C ON P.CODCLI = C.CODCLI
  LEFT JOIN PCPEDC W ON S.NUMPED = W.NUMPED
  LEFT JOIN PCPEDCTEMP CT ON W.NUMPEDWEB = CT.NUMPEDWEB
                         AND CT.CODCLI = S.CODCLI
  LEFT JOIN CREDITOS_ABERTOS A ON S.NUMTRANSVENDA = A.NUMTRANSVENDA
 WHERE P.DTPAG IS NULL
   AND (P.CODFILIAL IN ('1', '7', '9') OR
       (P.CODFILIAL = '2' AND C.CODCLI = 8998))
   AND P.OBSTITULO IS NOT NULL
 ORDER BY P.CODUSUR, DTOBS DESC, P.DUPLIC, TO_NUMBER(P.PREST);
