SELECT (
    CASE
        WHEN V.CODSUPERVISOR IN (
            12
        ) THEN 12
        ELSE V.CODGERENTE
    END
) AS CODGERENTE,
       SUM (C.VLATEND) VALOR
  FROM PCPEDC C
  LEFT JOIN VIEW_JC_VENDEDOR V ON C.CODUSUR = V.CODUSUR
 WHERE C.POSICAO NOT IN (
    'F', 'C'
)
 GROUP BY V.CODSUPERVISOR,
          V.CODGERENTE