CREATE MATERIALIZED VIEW MV_JF_VENDA_PRODUTO_DISTR
REFRESH FORCE ON DEMAND
START WITH SYSDATE NEXT SYSDATE + 90/1152
AS
WITH PRODUTOS_ESTRELA AS --PRODUTOS ESTRELA
 (SELECT DISTINCT P.CODPRODMASTER AS CODPROD, P.DESCRICAO PRODUTO
    FROM PCPRODUT P
    LEFT JOIN PCLINHAPROD L ON P.CODLINHAPROD = L.CODLINHA
    LEFT JOIN PCFORNEC F ON P.CODFORNEC = F.CODFORNEC
   WHERE F.CODFORNECPRINC = 2
     AND P.DTEXCLUSAO IS NULL
     AND NVL(P.OBS, '00') NOT IN ('FL')
     AND P.CODPROD = P.CODPRODMASTER),
PRODUTOS_VENDIDOS AS
 (SELECT M.DTMOV, M.CODPROD, SUM(M.QTCONT) AS QTVENDA
    FROM PCMOV M
    JOIN PRODUTOS_ESTRELA P ON P.CODPROD = M.CODPROD
    JOIN PCUSUARI U ON M.CODUSUR = U.CODUSUR
    JOIN PCSUPERV V ON V.CODSUPERVISOR = U.CODSUPERVISOR
   WHERE M.CODFISCAL IN
         (5102, 5109, 5119, 5120, 5403, 5405, 6102, 6108, 6403, 6119, 6120)
     AND V.CODGERENTE IN (1, 8, 9, 10)
     AND M.DTCANCEL IS NULL
     AND M.DTMOV >= '01/01/2020'
     AND M.CODFILIAL IN ('2', '11')
   GROUP BY M.DTMOV, M.CODPROD),
PRODUTOS_DEVOLVIDOS AS
 (SELECT M.DTMOV, M.CODPROD, SUM(M.QTCONT) AS QTDEV
    FROM PCMOV M
    JOIN PRODUTOS_ESTRELA P ON P.CODPROD = M.CODPROD
    JOIN PCUSUARI U ON M.CODUSUR = U.CODUSUR
    JOIN PCSUPERV V ON V.CODSUPERVISOR = U.CODSUPERVISOR
   WHERE M.CODFISCAL IN (1202, 1411, 2202, 2411)
     AND V.CODGERENTE IN (1, 8, 9, 10)
     AND M.DTCANCEL IS NULL
     AND M.DTMOV >= '01/01/2020'
     AND M.CODFILIAL IN ('2', '11')
   GROUP BY M.DTMOV, M.CODPROD)

SELECT COALESCE(V.DTMOV, D.DTMOV) DTMOV,
       P.CODPROD,
       P.PRODUTO,
       (NVL(V.QTVENDA, 0) - NVL(D.QTDEV, 0)) QT
  FROM PRODUTOS_ESTRELA P
  JOIN PRODUTOS_VENDIDOS V ON V.CODPROD = P.CODPROD
  JOIN PRODUTOS_DEVOLVIDOS D ON D.CODPROD = P.CODPROD
	WHERE (NVL(V.QTVENDA, 0) - NVL(D.QTDEV, 0)) <> 0


