CREATE MATERIALIZED VIEW MV_JF_CUSTOS_ENTRADA
REFRESH FORCE ON DEMAND
START WITH SYSDATE NEXT SYSDATE + 5/1152
AS
WITH TRIBUTACAO_ENTRADA AS
 (SELECT F.CODFIGURA,
         FN_JF_TRANSFORMA_EM_PERCENTUAL(F.PERPIS) PERPIS,
         FN_JF_TRANSFORMA_EM_PERCENTUAL(F.PERCOFINS) PERCOFINS,
         FN_JF_TRANSFORMA_EM_PERCENTUAL(F.PERCICMRED) PERCICMRED,
         FN_JF_TRANSFORMA_EM_PERCENTUAL(F.PERCICM) PERCICM,
         FN_JF_TRANSFORMA_EM_PERCENTUAL(F.PERCREDICMS) PERCREDICMS,
         FN_JF_TRANSFORMA_EM_PERCENTUAL(F.PERIPI) PERCIPI,
         FN_JF_TRANSFORMA_EM_PERCENTUAL(F.PERCIVA) PERCIVA,
         FN_JF_TRANSFORMA_EM_PERCENTUAL(F.PERCALIQEXTGUIA) PERCALIQEXTGUIA,
         FN_JF_TRANSFORMA_EM_PERCENTUAL(F.PERCALIQEXT) PERCALIQEXT,
         FN_JF_TRANSFORMA_EM_PERCENTUAL(F.PERCALIQINT) PERCALIQINT,
         FN_JF_TRANSFORMA_EM_PERCENTUAL(F.REDBASEALIQEXT) REDBASEALIQEXT
    FROM PCTRIBFIGURA F),
CUSTO_COMPRA AS
 (SELECT P.CODFILIAL,
         P.CODPROD,
         ROUND(NVL((P.CUSTOREP * (1 - P.PERCDESC)), 0), 4) AS PCOMPRA
    FROM (SELECT P.CODFILIAL,
                 P.CODPROD,
                 P.CUSTOREP,
                 FN_JF_SOMADESCONTO(P.PERCDESC1,
                                    P.PERCDESC2,
                                    P.PERCDESC3,
                                    P.PERCDESC4,
                                    P.PERCDESC5,
                                    P.PERCDESC6,
                                    P.PERCDESC7,
                                    P.PERCDESC8,
                                    P.PERCDESC9,
                                    P.PERCDESC10) PERCDESC
            FROM PCPRODFILIAL P) P),
BASE_FINAL_LC AS
 (SELECT E.CODFILIAL,
         P.CODPROD,
         P.CODFORNEC,
         F.EQUIPINDUSTRIA,
         P.CODNCMEX,
         F.TIPOFORNEC,
         F.ESTADO,
         E.CODFIGURA,
         C.PCOMPRA,
         FN_JF_BASE_ENT_ICMS(C.PCOMPRA, T.PERCICMRED, T.PERCICM) BASEICMS,
         T.PERPIS,
         T.PERCOFINS,
         T.PERCICM,
         T.PERCICMRED,
         T.PERCREDICMS,
         (CASE
           WHEN (F.EQUIPINDUSTRIA = 'N' AND F.TIPOFORNEC = 'D') THEN
            0
           ELSE
            T.PERCIPI
         END) AS PERCIPI,
         T.PERCIVA,
         T.PERCALIQEXT,
         T.PERCALIQINT,
         T.PERCALIQEXTGUIA,
         T.REDBASEALIQEXT,
         (T.PERCALIQINT * T.REDBASEALIQEXT) AS PERCALIQSTRED
    FROM PCPRODUT P
    JOIN PCFORNEC F ON P.CODFORNEC = F.CODFORNEC
    JOIN PCTRIBENTRADA E ON P.CODNCMEX = E.NCM
                        AND F.TIPOFORNEC = E.TIPOFORNEC
                        AND F.ESTADO = E.UFORIGEM
    LEFT JOIN TRIBUTACAO_ENTRADA T ON E.CODFIGURA = T.CODFIGURA
    LEFT JOIN CUSTO_COMPRA C ON P.CODPROD = C.CODPROD
                            AND E.CODFILIAL = C.CODFILIAL
   WHERE F.TIPOFORNEC NOT IN ('C', 'O')),
BASE_FINAL_SN AS
 (SELECT E.CODFILIAL,
         P.CODPROD,
         P.CODFORNEC,
         F.EQUIPINDUSTRIA,
         P.CODNCMEX,
         F.TIPOFORNEC,
         F.ESTADO,
         E.CODFIGURA,
         C.PCOMPRA,
         FN_JF_BASE_ENT_ICMS(C.PCOMPRA, T.PERCICMRED, T.PERCICM) BASEICMS,
         T.PERPIS,
         T.PERCOFINS,
         T.PERCICM,
         T.PERCICMRED,
         T.PERCREDICMS,
         (CASE
           WHEN (F.EQUIPINDUSTRIA = 'N' AND F.TIPOFORNEC = 'D') THEN
            0
           ELSE
            T.PERCIPI
         END) AS PERCIPI,
         T.PERCIVA,
         T.PERCALIQEXT,
         T.PERCALIQINT,
         T.PERCALIQEXTGUIA,
         T.REDBASEALIQEXT,
         (T.PERCALIQINT * T.REDBASEALIQEXT) AS PERCALIQSTRED
    FROM PCPRODUT P
    JOIN PCFORNEC F ON F.CODFORNEC = 1
    JOIN PCTRIBENTRADA E ON P.CODNCMEX = E.NCM
                        AND F.TIPOFORNEC = E.TIPOFORNEC
                        AND F.ESTADO = E.UFORIGEM
    LEFT JOIN TRIBUTACAO_ENTRADA T ON E.CODFIGURA = T.CODFIGURA
    LEFT JOIN CUSTO_COMPRA C ON P.CODPROD = C.CODPROD
                            AND E.CODFILIAL = C.CODFILIAL
   WHERE F.TIPOFORNEC NOT IN ('C', 'O')
   AND E.CODFILIAL IN ('5', '6', '9', '10'))
SELECT T.CODFILIAL,
       T.CODPROD,
       T.CODFORNEC,
       T.CODNCMEX,
       T.ESTADO,
       T.PCOMPRA,
       ROUND(T.PCOMPRA * T.PERCIPI, 4) VLIPI,
       FN_JF_VALOR_ICMS_ST(T.PCOMPRA, T.PERCIPI, T.PERCIVA, T.PERCALIQSTRED, T.PERCALIQINT, T.PERCALIQEXT) VLICMSST,
       FN_JF_VALOR_BRUTO(
            T.PCOMPRA, 
            T.PERCIPI, 
            FN_JF_VALOR_ICMS_ST(T.PCOMPRA, T.PERCIPI, T.PERCIVA, T.PERCALIQSTRED, T.PERCALIQINT, T.PERCALIQEXT)) PBRUTO,
       ROUND(T.BASEICMS * T.PERCREDICMS, 4) VLCREDICMS,
       ROUND(FN_JF_BASE_ENT_PIS_COFINS(T.PCOMPRA,T.BASEICMS,T.PERCREDICMS,T.PERCIPI) * PERPIS,4) VLPIS,
       ROUND(FN_JF_BASE_ENT_PIS_COFINS(T.PCOMPRA,T.BASEICMS,T.PERCREDICMS,T.PERCIPI) * PERCOFINS,4) VLCOFINS,
       FN_JF_CUSTO_LIQ(
            T.PCOMPRA, 
            T.BASEICMS,
            T.PERCREDICMS,
            T.PERCIPI,
            T.PERPIS, 
            T.PERCOFINS, 
            FN_JF_BASE_ENT_PIS_COFINS(T.PCOMPRA, T.BASEICMS, T.PERCREDICMS, T.PERCIPI), 
            FN_JF_VALOR_ICMS_ST(T.PCOMPRA, T.PERCIPI, T.PERCIVA, T.PERCALIQSTRED, T.PERCALIQINT, T.PERCALIQEXT),
            FN_JF_VALOR_BRUTO(T.PCOMPRA, T.PERCIPI, FN_JF_VALOR_ICMS_ST(T.PCOMPRA, T.PERCIPI, T.PERCIVA, T.PERCALIQSTRED, T.PERCALIQINT, T.PERCALIQEXT))) CUSTOLIQ,
       T.BASEICMS,
       FN_JF_BASE_ICMS_ST(T.PCOMPRA, T.PERCIPI, T.PERCIVA) BASEICMSST,
       FN_JF_BASE_ENT_PIS_COFINS(T.PCOMPRA,T.BASEICMS, T.PERCREDICMS, T.PERCIPI) BASEPISCOFINS,
       T.PERPIS,
       T.PERCOFINS,
       T.PERCIPI,
       T.PERCICM,
       T.PERCICMRED,
       T.PERCREDICMS,
       T.PERCIVA,
       T.PERCALIQEXT,
       T.PERCALIQINT,
       T.PERCALIQEXTGUIA,
       T.REDBASEALIQEXT,
       T.PERCALIQSTRED
  FROM (SELECT * FROM BASE_FINAL_LC UNION SELECT * FROM BASE_FINAL_SN) T
