CREATE OR REPLACE VIEW MV_JC_PCMOV_ENT AS
SELECT S.DATA DTMOV,
       S.CODFILIAL,
       S.CFOP CODFISCAL,
       M.CODOPER,
       'NC' TIPOPROCESSO,
       NVL(E.NUMTRANSVENDAORIG, 0) AS NUMTRANSVENDAORIG,
       S.MOVIMENTO TIPOCONTABIL,
       DECODE(S.CODCLI,0, S.CODFORNEC, S.CODCLI) CODIGO,
       ('NF' || ' ' || E.NUMNOTA || ' - ' || E.FORNECEDOR) CLIENTE_FORNECEDOR,
       E.NUMNOTA,
       S.CODPROD,
       M.DESCRICAO PRODUTO,
       M.NBM NCM,
       S.QT QTCONT,
       S.PUNIT PUNITCONT,
       S.CUSTOCONTABIL CUSTOCONT,
       S.CUSTOCONTABIL VLTOTALCUSTOCONT,
       S.VLPRODUTO VLTOTALPROD,
       S.VLFRETE VLTOTALFRETE,
       S.VLIPI VLTOTALIPI,
       S.VLDESCONTO VLTOTALDESCONTO,
       S.VLCONTABIL VLTOTALNF,
       S.CST_ICMS,
       S.VLBASEICMS BASEICMS_NF,
       S.PERCICMS ALIQ_ICMS,
       S.VLICMS VLTOTALCREDICMSNF,
       0 VLOUTRAS_NF,
       0 VLTOTALOUTRASDESP,
       0 VLTOTALBASEOUTROS,
       S.VLST VLTOTALST,
       S.VLSTGUIA VLTOTALSTFORANF,
       S.CST_PISCOFINS,
       S.VLBASEPISCOFINS,
       S.VLPIS VLTOTALPIS,
       S.VLCOFINS VLTOTALCOFINS,
       0 VLTOTALICMSPART,
       S.VLICMSDIFAL VLTOTALICMSPARTDEST,
       0 VLTOTALFCPPART,
       S.CODUSUR,
       S.NUMTRANSACAO,
       S.NUMTRANSITEM
 FROM BI_SINC_MOV_PRODUTO S
 JOIN PCMOV M ON M.NUMTRANSITEM = S.NUMTRANSITEM
 LEFT JOIN PCNFENT E ON E.NUMTRANSENT = S.NUMTRANSACAO
WHERE S.MOVIMENTO = 'E'
AND E.ESPECIE NOT IN ('OE')
AND M.DTCANCEL IS NULL
AND S.DATA >= TO_DATE('01/01/2023', 'DD/MM/YYYY')
