SELECT ROWID, CODFILIAL, L.*
  FROM PCLANC L
 WHERE CODFILIAL = 7
   AND CODCONTA = 680102
   --AND RECNUM = 664163
   ;


---ALTERAR FUNDO DE RESERVA ENTRE FILIAIS---
SELECT ROWID,
       CODFILIAL,
       RECNUM,
       DTLANC,
       CODCONTA,
       CODFORNEC,
       HISTORICO,
       NUMNOTA,
       VALOR
  FROM PCLANC L
 WHERE L.CODCONTA = 680102
   AND L.CODFILIAL = 2
   AND VALOR < 0
	 AND L.DTLANC >= '01/01/2024'
	 AND L.HISTORICO = 'FUNDO DE RESERVA'
 ORDER BY DTLANC;
