------- A ROTINA VALIDA O CODCONTA ENTÃO DEVEMOS ALTERAR PARA 680105--------
SELECT ROWID,
       DTAPURACAO,
       CODFILIAL,
       NUMVERBA,
       TIPO,
       FORMAPGTO,
       CODCONTA,
       ORIGEM,
       DTVENC,
       VALOR,
       REFERENCIA,
       REFERENCIA1
  FROM PCVERBA
 WHERE NUMVERBA = 1615;


------- PARA DEIXAR A MOVIMENTAÇÃO CORRETA DEVEMOS ALTERAR PARA 680105--------
SELECT ROWID, CODCONTA, C. * FROM PCMOVCRFOR C WHERE NUMVERBA = 1615;
