--CREDITO GERADO COM BAIXA TOTAL EM DUPLICATAS 
SELECT C.NUMCRED, C.CODIGO, C.NUMTRANS, C.CODROTINA, C.NUMTRANSVENDADESC, C.NUMLANCBAIXA, C.ROTINAINSERT, C.ROTINAESTORNO, C.ROTINABAIXA, C.NUMTRANSBAIXA, C.NUMERARIO, C.* FROM PCCRECLI C WHERE NUMCRED IN ( 458830 ) OR NUMTRANS IN ( 183731 ) ORDER BY C.CODIGO;

--CREDITO GERADO COM BAIXA PARCIAL EM DUPLICATAS DIFERENTES
SELECT C.NUMCRED, C.CODIGO, C.NUMTRANS, C.CODROTINA, C.NUMTRANSVENDADESC, C.NUMLANCBAIXA, C.ROTINAINSERT, C.ROTINAESTORNO, C.ROTINABAIXA, C.NUMTRANSBAIXA, C.NUMERARIO, C.* FROM PCCRECLI C WHERE NUMCRED IN ( 678680 ) OR NUMTRANS IN ( 269959 ) ORDER BY C.CODIGO;

--CREDITO DE ADIANTAMENTO CLIENTE DISTRIBUIÇÃO PEDIDO ANTECIPADO COM SALDO EM ABERTO E BAIXA EM DUPLICATA DIFERENTES
SELECT C.NUMCRED, C.CODIGO, C.NUMTRANS, C.CODROTINA, C.NUMTRANSVENDADESC, C.NUMLANCBAIXA, C.ROTINAINSERT, C.ROTINAESTORNO, C.ROTINABAIXA, C.NUMTRANSBAIXA, C.NUMERARIO, C.* FROM PCCRECLI C WHERE NUMCRED IN ( 561977 ) OR NUMTRANS IN ( 208601 ) ORDER BY C.CODIGO;

--CREDITO DE ADIANTAMENTO CLIENTE DISTRIBUIÇÃO PEDIDO ANTECIPADO COM SALDO EM ABERTO E BAIXA EM DUPLICATA DIFERENTES
SELECT C.NUMCRED, C.CODIGO, C.NUMTRANS, C.CODROTINA, C.NUMTRANSVENDADESC, C.NUMLANCBAIXA, C.ROTINAINSERT, C.ROTINAESTORNO, C.ROTINABAIXA, C.NUMTRANSBAIXA, C.NUMERARIO, C.* FROM PCCRECLI C WHERE NUMCRED IN ( 661357 ) OR NUMTRANS IN ( 263642 ) ORDER BY C.CODIGO;

--CREDITO DE ADIANTAMENTO CLIENTE DISTRIBUIÇÃO PEDIDO ANTECIPADO COM SALDO EM ABERTO E BAIXA EM DUPLICATA
SELECT C.NUMCRED, C.CODIGO, C.NUMTRANS, C.CODROTINA, C.NUMTRANSVENDADESC, C.NUMLANCBAIXA, C.ROTINAINSERT, C.ROTINAESTORNO, C.ROTINABAIXA, C.NUMTRANSBAIXA, C.NUMERARIO, C.* FROM PCCRECLI C WHERE NUMCRED IN ( 678678 ) OR NUMTRANS IN ( 269930 ) ORDER BY C.CODIGO;

--CREDITO GERADO E BAIXADO COMO RECEITA 100% (ESSE NÃO APARECE NO RELATÓRIO)
SELECT C.NUMCRED, C.CODIGO, C.NUMTRANS, C.CODROTINA, C.NUMTRANSVENDADESC, C.NUMLANCBAIXA, C.ROTINAINSERT, C.ROTINAESTORNO, C.ROTINABAIXA, C.NUMTRANSBAIXA, C.NUMERARIO, C.* FROM PCCRECLI C WHERE NUMCRED IN ( 674229 ) OR NUMTRANS IN ( 266443 ) ORDER BY C.CODIGO;

--CREDITO GERADO E BAIXADO PARCIALMENTE EM VARIAS DUPLICATAS E COM SALDO BAIXADO COMO RECEITA
SELECT C.NUMCRED, C.CODIGO, C.NUMTRANS, C.CODROTINA, C.NUMTRANSVENDADESC, C.NUMLANCBAIXA, C.ROTINAINSERT, C.ROTINAESTORNO, C.ROTINABAIXA, C.NUMTRANSBAIXA, C.NUMERARIO, C.* FROM PCCRECLI C WHERE NUMCRED IN ( 681113 ) OR NUMTRANS IN ( 271247 ) ORDER BY C.CODIGO;

--CREDITO GERADO PARA ECOMMERCE QUANDO NÃO HOUVE FATURAMENTO, DEVOLUAÇÃO PARCIAL E POSTERIORMENTE BAIXADO EM DUPLICATA (numcred diferente)
SELECT C.NUMCRED, C.CODIGO, C.NUMTRANS, C.CODROTINA, C.DTESTORNO, C.NUMTRANSVENDADESC, C.NUMLANCBAIXA, C.ROTINAINSERT, C.ROTINAESTORNO, C.ROTINABAIXA, C.NUMTRANSBAIXA, C.NUMERARIO, C.* FROM PCCRECLI C WHERE NUMCRED IN ( 295661 ) OR NUMTRANS IN ( 150237 ) ORDER BY C.CODIGO;

--CREDITO GERADO PARA ECOMMERCE QUANDO NÃO HOUVE FATURAMENTO, POSTERIORMENTE BAIXADO EM DUPLICATA (numcred diferente)
SELECT C.NUMCRED, C.CODIGO, C.NUMTRANS, C.CODROTINA, C.NUMTRANSVENDADESC, C.NUMLANCBAIXA, C.ROTINAINSERT, C.ROTINAESTORNO, C.ROTINABAIXA, C.NUMTRANSBAIXA, C.NUMERARIO, C.* FROM PCCRECLI C WHERE NUMCRED IN ( 426874,426960 ) OR NUMTRANS IN ( 150237 ) ORDER BY C.CODIGO;

--CREDITO GERADO PARA ECOMMERCE QUANDO NÃO HOUVE FATURAMENTO, POSTERIORMENTE BAIXADO EM DUPLICATA E DEPOIS DEVOLUCAO DO ADIANTAMENTO (numcred diferente)
SELECT C.NUMCRED, C.CODIGO, C.NUMTRANS, C.CODROTINA, C.DTESTORNO, C.NUMTRANSVENDADESC, C.NUMLANCBAIXA, C.ROTINAINSERT, C.ROTINAESTORNO, C.ROTINABAIXA, C.NUMTRANSBAIXA, C.NUMERARIO, C.* FROM PCCRECLI C WHERE NUMCRED IN ( 326058,519865 ) OR NUMTRANS IN ( 152286 ) ORDER BY C.CODIGO;

--CREDITO GERADO PARA ECOMMERCE QUANDO NÃO HOUVE FATURAMENTO, POSTERIORMENTE BAIXADO EM DUPLICATA E DEPOIS DEVOLUCAO DO ADIANTAMENTO (numcred diferente)
SELECT C.NUMCRED, C.CODIGO, C.NUMTRANS, C.CODROTINA, C.NUMTRANSVENDADESC, C.NUMLANCBAIXA, C.ROTINAINSERT, C.ROTINAESTORNO, C.ROTINABAIXA, C.NUMTRANSBAIXA, C.NUMERARIO, C.* FROM PCCRECLI C WHERE NUMCRED IN ( 426906,519853,316919 ) OR NUMTRANS IN ( 152282 ) ORDER BY C.CODIGO;

--CREDITO GERADO PARA LOJA E USADO NA HORA DA VENDA
SELECT C.NUMCRED, C.CODIGO, C.NUMTRANS, C.CODROTINA, C.NUMTRANSVENDADESC, C.NUMLANCBAIXA, C.ROTINAINSERT, C.ROTINAESTORNO, C.ROTINABAIXA, C.NUMTRANSBAIXA, C.NUMERARIO, C.* FROM PCCRECLI C WHERE NUMCRED IN ( 454244 ) OR NUMTRANS IN ( 183280 ) ORDER BY C.CODIGO;

--CREDITO GERADO PARA CORPORATIVO E BAIXADO 100% NA DUPLICATA
SELECT C.NUMCRED, C.CODIGO, C.NUMTRANS, C.CODROTINA, C.NUMTRANSVENDADESC, C.NUMLANCBAIXA, C.ROTINAINSERT, C.ROTINAESTORNO, C.ROTINABAIXA, C.NUMTRANSBAIXA, C.NUMERARIO, C.* FROM PCCRECLI C WHERE NUMCRED IN ( 673580 ) OR NUMTRANS IN ( 266372 ) ORDER BY C.CODIGO;

--CREDITO GERADO PARA DISTRIBUICAO E BAIXADO PARCIAL EM DUAS DUPLICATAS DIFERENTES
SELECT C.NUMCRED, C.CODIGO, C.NUMTRANS, C.CODROTINA, C.NUMTRANSVENDADESC, C.NUMLANCBAIXA, C.ROTINAINSERT, C.ROTINAESTORNO, C.ROTINABAIXA, C.NUMTRANSBAIXA, C.NUMERARIO, C.* FROM PCCRECLI C WHERE NUMCRED IN ( 549900 ) OR NUMTRANS IN ( 203350 ) ORDER BY C.CODIGO;

--CREDITO GERADO PARA ECOMMERCE QUANDO NÃO HOUVE FATURAMENTO, POSTERIORMENTE DEVOLVIDO PARCIAL E SALDO EM ABERTO (numcred igual)
SELECT C.NUMCRED, C.CODIGO, C.NUMTRANS, C.CODROTINA, C.NUMTRANSVENDADESC, C.NUMLANCBAIXA, C.ROTINAINSERT, C.ROTINAESTORNO, C.ROTINABAIXA, C.NUMTRANSBAIXA, C.NUMERARIO, C.* FROM PCCRECLI C WHERE NUMCRED IN ( 548154 ) OR NUMTRANS IN ( 202728 ) ORDER BY C.CODIGO;

--CREDITO GERADO E DEPOIS BAIXADO 100% COMO RECEITA
SELECT C.NUMCRED, C.CODIGO, C.NUMTRANS, C.CODROTINA, C.NUMTRANSVENDADESC, C.NUMLANCBAIXA, C.ROTINAINSERT, C.ROTINAESTORNO, C.ROTINABAIXA, C.NUMTRANSBAIXA, C.NUMERARIO, C.* FROM PCCRECLI C WHERE NUMCRED IN ( 673048 ) OR NUMTRANS IN ( 266200 ) ORDER BY C.CODIGO;

--CREDITO GERADO PARA ECOMMERCE COM 100% DE DEVOLUÇÃO
SELECT C.NUMCRED, C.CODIGO, C.NUMTRANS, C.CODROTINA, C.NUMTRANSVENDADESC, C.NUMLANCBAIXA, C.ROTINAINSERT, C.ROTINAESTORNO, C.ROTINABAIXA, C.NUMTRANSBAIXA, C.NUMERARIO, C.* FROM PCCRECLI C WHERE NUMCRED IN ( 674889 ) OR NUMTRANS IN ( 267414 ) ORDER BY C.CODIGO;

--CREDITO GERADO PARA ECOMMERCE COM 100% DE DEVOLUÇÃO
SELECT C.NUMCRED, C.CODIGO, C.NUMTRANS, C.CODROTINA, C.NUMTRANSVENDADESC, C.NUMLANCBAIXA, C.ROTINAINSERT, C.ROTINAESTORNO, C.ROTINABAIXA, C.NUMTRANSBAIXA, C.NUMERARIO, C.* FROM PCCRECLI C WHERE NUMCRED IN ( 679647 ) OR NUMTRANS IN ( 270951 ) ORDER BY C.CODIGO;

--CREDITO GERADO PARA ECOMMERCE COM DEVOLUÇÃO PARCIAL E FEITO DEVOLUÇÃO INTEGRAL DO VALOR RESTANTE (numcred diferente)
SELECT C.NUMCRED, C.CODIGO, C.NUMTRANS, C.CODROTINA, C.NUMTRANSVENDADESC, C.NUMLANCBAIXA, C.ROTINAINSERT, C.ROTINAESTORNO, C.ROTINABAIXA, C.NUMTRANSBAIXA, C.NUMERARIO, C.* FROM PCCRECLI C WHERE NUMCRED IN ( 354974,356994 ) OR NUMTRANS IN ( 155387 ) ORDER BY C.CODIGO;

--CREDITO GERADO COM DEVOLUÇÃO PARCIAL E FEITO BAIXA INTEGRAL DO VALOR RESTANTE (numcred diferente)
SELECT C.NUMCRED, C.CODIGO, C.NUMTRANS, C.CODROTINA, C.NUMTRANSVENDADESC, C.NUMLANCBAIXA, C.ROTINAINSERT, C.ROTINAESTORNO, C.ROTINABAIXA, C.NUMTRANSBAIXA, C.NUMERARIO, C.* FROM PCCRECLI C WHERE NUMCRED IN ( 601544,613338 ) OR NUMTRANS IN ( 252381 ) ORDER BY C.CODIGO;

--CREDITO GERADO COM BAIXA PARCIAL EM DUPLICATAS E FEITO BAIXA INTEGRAL DO VALOR RESTANTE (numcred diferente)
SELECT C.NUMCRED, C.CODIGO, C.NUMTRANS, C.CODROTINA, C.NUMTRANSVENDADESC, C.NUMLANCBAIXA, C.ROTINAINSERT, C.ROTINAESTORNO, C.ROTINABAIXA, C.NUMTRANSBAIXA, C.NUMERARIO, C.* FROM PCCRECLI C WHERE NUMCRED IN ( 578520,563559 ) OR NUMTRANS IN ( 204902 ) ORDER BY C.CODIGO;

--CREDITO GERADO COM DEVOLUÇÃO PARCIAL E DEPOIS FEITO OUTRO DESDOBRAMENTO PARA BAIXA EM DUPLICATA, DEPOIS ESTORNO, DEPOIS BAIXA EM DUPLICATA OUTRO VALOR
SELECT C.NUMCRED, C.CODIGO, C.NUMTRANS, C.CODROTINA, C.DTESTORNO, C.NUMTRANSVENDADESC, C.NUMLANCBAIXA, C.ROTINAINSERT, C.ROTINAESTORNO, C.ROTINABAIXA, C.NUMTRANSBAIXA, C.NUMERARIO, C.* FROM PCCRECLI C WHERE NUMCRED IN ( 387216,383701 ) OR NUMTRANS IN ( 158031 ) ORDER BY C.CODIGO;

--CREDITO GERADO COM DEVOLUÇÃO PARCIAL E SALDO EM ABERTO AINDA
SELECT C.NUMCRED, C.CODIGO, C.NUMTRANS, C.CODROTINA, C.NUMTRANSVENDADESC, C.NUMLANCBAIXA, C.ROTINAINSERT, C.ROTINAESTORNO, C.ROTINABAIXA, C.NUMTRANSBAIXA, C.NUMERARIO, C.* FROM PCCRECLI C WHERE NUMCRED IN ( 686591 ) OR NUMTRANS IN ( 270988 ) ORDER BY C.CODIGO;

--CREDITO GERADO, BAIXA EM DUPLICATA PELA 1286 E DEPOIS ESTORNADO 1209 E DEPOIS BAIXADO NOVAMENTE 1286
SELECT C.NUMCRED, C.CODIGO, C.NUMTRANS, C.CODROTINA, C.DTESTORNO, C.NUMTRANSVENDADESC, C.NUMLANCBAIXA, C.ROTINAINSERT, C.ROTINAESTORNO, C.ROTINABAIXA, C.NUMTRANSBAIXA, C.NUMERARIO, C.* FROM PCCRECLI C WHERE NUMCRED IN ( 678602 ) OR NUMTRANS IN ( 268225 ) ORDER BY C.CODIGO;

--CREDITO GERADO USADO NO FATURAMENTO E O SALDO DEVOLVIDO
SELECT C.NUMCRED, C.CODIGO, C.NUMTRANS, C.CODROTINA, C.NUMTRANSVENDADESC, C.NUMLANCBAIXA, C.ROTINAINSERT, C.ROTINAESTORNO, C.ROTINABAIXA, C.NUMTRANSBAIXA, C.NUMERARIO, C.* FROM PCCRECLI C WHERE NUMCRED IN ( 523134  ) OR NUMTRANS IN ( 189561 ) ORDER BY C.CODIGO;

--CREDITO GERADO USADO NO FATURAMENTO E O SALDO DEVOLVIDO
SELECT C.NUMCRED, C.CODIGO, C.NUMTRANS, C.CODROTINA, C.NUMTRANSVENDADESC, C.NUMLANCBAIXA, C.ROTINAINSERT, C.ROTINAESTORNO, C.ROTINABAIXA, C.NUMTRANSBAIXA, C.NUMERARIO, C.* FROM PCCRECLI C WHERE NUMCRED IN ( 695168 ) OR NUMTRANS IN ( 275663 ) ORDER BY C.CODIGO;

--CREDITO GERADO. BAIXADO PARCIAL EM DUPLICATA, E SALDO BAIXADO COMO RECEITA
SELECT C.NUMCRED, C.CODIGO, C.NUMTRANS, C.CODROTINA, C.NUMTRANSVENDADESC, C.NUMLANCBAIXA, C.ROTINAINSERT, C.ROTINAESTORNO, C.ROTINABAIXA, C.NUMTRANSBAIXA, C.NUMERARIO, C.* FROM PCCRECLI C WHERE NUMCRED IN ( 426917 ) OR NUMTRANS IN ( 147215 ) ORDER BY C.CODIGO;

--CREDITO GERADO, BAIXADO TOTAL EM DUPLICATA E DEPOIS ESTORNADO 
SELECT C.NUMCRED, C.CODIGO, C.NUMTRANS, C.CODROTINA, C.DTESTORNO, C.NUMTRANSVENDADESC, C.NUMLANCBAIXA, C.ROTINAINSERT, C.ROTINAESTORNO, C.ROTINABAIXA, C.NUMTRANSBAIXA, C.NUMERARIO, C.* FROM PCCRECLI C WHERE /*NUMCRED IN ( 698187 ) OR*/ NUMTRANS IN ( 167096 ) ORDER BY C.CODIGO;

--CREDITO GERADO, BAIXADO TOTAL EM DUPLICATA E DEPOIS ESTORNADO 
SELECT C.NUMCRED, C.CODIGO, C.NUMTRANS, C.CODROTINA, C.DTESTORNO, C.NUMTRANSVENDADESC, C.NUMLANCBAIXA, C.ROTINAINSERT, C.ROTINAESTORNO, C.ROTINABAIXA, C.NUMTRANSBAIXA, C.NUMERARIO, C.* FROM PCCRECLI C WHERE /*NUMCRED IN ( 698187 ) OR*/ NUMTRANS IN ( 148329 ) ORDER BY C.CODIGO;

--CREDITO GERADO. BAIXADO PARCIAL EM DUPLICATA, E SALDO BAIXADO COMO RECEITA
SELECT C.NUMCRED, C.CODIGO, C.NUMTRANS, C.CODROTINA, C.NUMTRANSVENDADESC, C.NUMLANCBAIXA, C.ROTINAINSERT, C.ROTINAESTORNO, C.ROTINABAIXA, C.NUMTRANSBAIXA, C.NUMERARIO, C.* FROM PCCRECLI C WHERE NUMCRED IN ( 140420,163683 ) OR NUMTRANS IN ( 97459 ) ORDER BY C.CODIGO;

--CREDITO GERADO. BAIXADO TOTAL, ESTORNADO TOTAL, BAIXADO TOTAL NOVAMENTE E ESTORNADO TOTAL NOVAMENTE, E ABERTO
SELECT C.NUMCRED, C.CODIGO, C.NUMTRANS, C.CODROTINA, C.DTESTORNO, C.NUMTRANSVENDADESC, C.NUMLANCBAIXA, C.ROTINAINSERT, C.ROTINAESTORNO, C.ROTINABAIXA, C.NUMTRANSBAIXA, C.NUMERARIO, C.* FROM PCCRECLI C WHERE NUMCRED IN ( 699848,699847 ) OR NUMTRANS IN ( 244475,244474 ) ORDER BY C.CODIGO;