CREATE OR REPLACE VIEW VIEW_JC_BASE_ADIANT_DESD_TWICE AS 
SELECT C.CODFILIAL,
         C.DTLANC,
         C.DTDESCONTO,
         C.NUMCRED,
         C.CODIGO AS CODCRED,
         C.NUMTRANS,
         C.NUMTRANSBAIXA,
         C.NUMTRANSVENDADESC,
         C.NUMNOTADESC,
         C.NUMLANCBAIXA,
         C.CODMOVIMENTO,
         C.CODCLI,
         C.VALOR
    FROM PCCRECLI C
   INNER JOIN VIEW_JC_BASE_ADIANT_DESDOBRE V ON C.NUMTRANS = V.NUMTRANS
   WHERE C.CODROTINA = 1286
   AND C.VALOR > 0;
/