CREATE OR REPLACE VIEW VIEW_JC_ADIANTAMENTO_CLIENTE AS
    SELECT CODFILIAL,
           NUMNOTA,
           CPF_CNPJ,
           DATA,
           CODCRED,
           CODCONTAB,
           TO_CHAR (CODCONTABILBANCO) AS CODCONTABILBANCO,
           NUMTRANSACAO,
           VALOR,
           TIPO,
           HISTORICO
      FROM (
        SELECT *
          FROM VIEW_JC_ADIANT_CLIENT_RECEBIDO
        UNION ALL
        SELECT *
          FROM VIEW_JC_ADIANT_DEV_SIMPLES
        UNION ALL
        SELECT *
          FROM VIEW_JC_ADIANT_DEV_DESDOBRADO
        UNION ALL
        SELECT *
          FROM VIEW_JC_ADIANT_RECEITA_SIMPLES
        UNION ALL
        SELECT *
          FROM VIEW_JC_ADIANT_RECEITA_DESD
        UNION ALL
        SELECT *
          FROM VIEW_JC_ADIANT_RECEITA_DESD_TW
        UNION ALL
        SELECT *
          FROM VIEW_JC_ADIANT_DEV_DESD_TW
        UNION ALL
        SELECT *
          FROM VIEW_JC_ADIANT_BAIXA_DUPLICATA
        UNION ALL
        SELECT *
          FROM VIEW_JC_ADIANT_DES_DUP_RECEITA
        UNION ALL
        SELECT *
          FROM VIEW_JC_ADIANT_DEV_DESD_FAT
        UNION ALL
        SELECT *
          FROM VIEW_JC_ADIANT_RECEITA_DESDFAT
          UNION ALL
        SELECT *
          FROM VIEW_JC_ADIANT_DEV_DESD_1209
          UNION ALL
        SELECT *
          FROM VIEW_JC_ADIANT_DEV_DESD_1409
    );
/