CREATE OR REPLACE VIEW VIEW_JC_ADIANT_CLIENT_RECEBIDO AS
 SELECT C.CODFILIAL,
         (
               CASE
                   WHEN B.CODBACEN IS NOT NULL THEN C.DTLANC
                     WHEN M.DTCOMPENSACAO IS NULL THEN C.DTLANC
                   ELSE M.DTCOMPENSACAO
               END
           ) AS DATA,
         C.CODIGO AS CODCRED,
         C.NUMCRED,
         '' AS CODCONTAB,
         B.CODCONTABIL AS CODCONTABILBANCO,
         C.NUMTRANS AS NUMTRANSACAO,
         C.NUMTRANS,
         (CASE
           WHEN C.VALOR < 0 THEN
            C.VALOR * -1
           ELSE
            C.VALOR
         END) AS VALOR,
         'A' AS TIPO,
         ('Nº TRANS. ' || C.NUMTRANS || ' - ADIANT. CLIENTE - ' || T.CLIENTE) AS HISTORICO
    FROM PCCRECLI C
    LEFT JOIN PCCLIENT T ON C.CODCLI = T.CODCLI
   INNER JOIN PCMOVCR M ON C.NUMTRANS = M.NUMTRANS
                       AND C.CODMOVIMENTO = M.CODBANCO
    LEFT JOIN PCBANCO B ON M.CODBANCO = B.CODBANCO
   WHERE M.DTESTORNO IS NULL
     AND M.CODBANCO NOT IN (17, 20, 35, 50, 52, 53, 54)
     AND C.NUMERARIO = 'S'
     AND C.NUMTRANS IS NOT NULL
     AND C.CODROTINA = 618
     AND C.VALOR > 0;
/