CREATE OR REPLACE VIEW VIEW_JC_PCPREST_BAIXA_CRED AS
WITH CREDITOUSADO AS
 (SELECT C.CODIGO
    FROM PCCRECLI C
   INNER JOIN VIEW_JC_ADIANT_CLIENTE V
      ON C.NUMTRANS = V.NUMTRANS
   WHERE C.DTESTORNO IS NULL), --RELACAO DOS ADIANTAMENTOS FEITOS COM OS CODIGOS UNICOS QUE SÃO GERADOS
CREDITOABERTO AS
 (SELECT C.NUMCRED
    FROM PCCRECLI C
   INNER JOIN VIEW_JC_ADIANT_CLIENTE V
      ON C.NUMTRANS = V.NUMTRANS
   WHERE C.NUMTRANSVENDADESC IS NULL
     AND C.NUMCRED IS NOT NULL) --RELACAO ENTRE OS ADIANTAMENTOS FEITOS COM OS NUMEROS DE CRÉDITOS QUE SÃO GERADOS
/*--Conciliação do adiantamento Baixando duplicata--*/
SELECT C.CODFILIAL,
       C.DTDESCONTO AS DATA,
       C.CODIGO,
       C.NUMCRED,
       C.NUMTRANS,
       C.NUMLANCBAIXA,
       T.CODCONTAB,
       C.VALOR,
       'D' AS TIPO,       ('BAIXA NF ' || C.NUMNOTADESC || ' - ' || T.CLIENTE) AS HISTORICO
  FROM PCCRECLI C
 INNER JOIN CREDITOUSADO A
    ON C.CODIGO = A.CODIGO
  LEFT JOIN PCCLIENT T
    ON C.CODCLI = T.CODCLI
 WHERE C.DTDESCONTO IS NOT NULL
UNION ALL
/*--Baixa do adiantamento como receita--*/
SELECT C.CODFILIAL,
       C.DTDESCONTO AS DATA,
       C.CODIGO,
       C.NUMCRED,
       C.NUMTRANS,
       C.NUMLANCBAIXA,
       T.CODCONTAB,
       (C.VALOR * -1) AS VALOR,
       'R' AS TIPO,       ('RECEITA CRED ' || C.NUMCRED || ' - ' || T.CLIENTE) AS HISTORICO
  FROM PCCRECLI C
 INNER JOIN CREDITOABERTO A
    ON C.NUMCRED = A.NUMCRED
  LEFT JOIN PCCLIENT T
    ON C.CODCLI = T.CODCLI
 WHERE C.NUMLANCBAIXA IS NOT NULL
   AND C.CODMOVIMENTO NOT IN (620108) --PARA RETIRAR LANCAMENTOS QUE REALMENTE FORAM FEITO ERRADO
;