CREATE OR REPLACE VIEW VIEW_JC_ADIANT_DEV_DESD_FAT AS
WITH BASE_DEVOLUCAO_ADIANTAMENTO AS
(SELECT C.CODFILIAL,
         C.DTLANC,
         C.NUMCRED,
         C.CODIGO AS CODCRED,
         C.NUMTRANSBAIXA,
         C.NUMTRANS,
         C.CODMOVIMENTO,
         C.CODCLI,  
         C.VALOR
FROM PCCRECLI C
INNER JOIN VIEW_JC_BASE_ADIANT_DESD_FAT D ON C.NUMCRED = D.NUMCRED
WHERE C.NUMTRANSBAIXA IS NOT NULL),
DEVOLUCAO_PARCIAL AS
 (SELECT C.NUMTRANSBAIXA, COUNT(C.NUMTRANSBAIXA) CONTAGEM
    FROM BASE_DEVOLUCAO_ADIANTAMENTO C
   WHERE C.NUMTRANSBAIXA IS NOT NULL
   GROUP BY C.NUMTRANSBAIXA
  HAVING COUNT(C.NUMTRANSBAIXA) > 1),
REGISTROS_DESDOBRADOS AS
 (SELECT C.CODCRED, C.NUMTRANSBAIXA
    FROM BASE_DEVOLUCAO_ADIANTAMENTO C
   INNER JOIN DEVOLUCAO_PARCIAL E ON C.NUMTRANSBAIXA = E.NUMTRANSBAIXA
   WHERE C.VALOR < 0)
SELECT C.CODFILIAL,
       (CASE
         WHEN B.CODBACEN IS NOT NULL THEN
          C.DTLANC
         ELSE
          M.DTCOMPENSACAO
       END) AS DATA,
       C.CODCRED,
       C.NUMCRED,
       '' AS CODCONTAB,
       B.CODCONTABIL AS CODCONTABILBANCO,
       C.NUMTRANSBAIXA AS NUMTRANSACAO,
       C.NUMTRANS,
       (CASE
         WHEN C.VALOR < 0 THEN
          C.VALOR * -1
         ELSE
          C.VALOR
       END) AS VALOR,
       'DDF' AS TIPO,
       ('Nº TRANS DEV. ' || C.NUMTRANSBAIXA || ' - DEV ADIANT. CLIENTE - ' || T.CLIENTE) AS HISTORICO
  FROM BASE_DEVOLUCAO_ADIANTAMENTO C
  LEFT JOIN PCCLIENT T ON C.CODCLI = T.CODCLI
 INNER JOIN PCMOVCR M ON C.NUMTRANSBAIXA = M.NUMTRANS
                     AND C.CODMOVIMENTO = M.CODBANCO
  LEFT JOIN PCBANCO B ON M.CODBANCO = B.CODBANCO
  LEFT JOIN REGISTROS_DESDOBRADOS P ON C.CODCRED = P.CODCRED
  LEFT JOIN VIEW_JC_ADIANT_DEV_SIMPLES S ON C.CODCRED = S.CODCRED
  LEFT JOIN VIEW_JC_ADIANT_DEV_DESDOBRADO D ON C.CODCRED = D.CODCRED
  LEFT JOIN VIEW_JC_ADIANT_DEV_DESD_TW W ON C.CODCRED = W.CODCRED
 WHERE M.DTESTORNO IS NULL
   AND M.CODBANCO NOT IN (17, 20, 35, 50, 52, 53, 54)
   --RETIRAR REGISTROS DESDOBRADOS E MANTER APENAS REGISTROS DE DEVOLUCAO
   AND P.CODCRED IS NULL
   --RETIRAR REGISTROS JÁ LANÇADOS NAS DEMAIS VIEWS DE DEVOLUCAO
   AND S.CODCRED IS NULL
   AND D.CODCRED IS NULL
   AND W.CODCRED IS NULL;