CREATE OR REPLACE VIEW VIEW_JC_PCPREST_BAIXA_CRED AS
    WITH ADIANTAMENTOS_BAIXADOS AS
  /*RELACAO DOS ADIANTAMENTOS FEITOS COM OS CODIGOS UNICOS QUE SÃO GERADOS*/ (
        SELECT C.CODIGO,
               TO_NUMBER (TO_CHAR (C.DTDESCONTO, 'YYYY') || TO_CHAR (C.DTDESCONTO, 'MM')) AS MES_DTDESCONTO,
               TO_NUMBER (TO_CHAR (C.DTESTORNO, 'YYYY') || TO_CHAR (C.DTESTORNO, 'MM')) AS MES_DTESTORNO,
               TO_NUMBER (TO_CHAR (C.DTLANC, 'YYYY') || TO_CHAR (C.DTLANC, 'MM')) AS MES_DTLANC
          FROM PCCRECLI C
         INNER JOIN VIEW_JC_ADIANT_CLIENTE V ON C.NUMTRANS = V.NUMTRANS
         WHERE C.HISTORICO NOT LIKE 'DESDOBRAMENTO EM BAIXA%'
     /*RETIRAR LANÇAMENTOS DE DESDOBRAMENTO*/
    ), VER_DTLANC_DTDESC_BAIXA_DUPLIC AS (
        SELECT CODIGO,
               (
                   CASE
                       WHEN ((L.MES_DTDESCONTO <> L.MES_DTLANC)
                          AND L.MES_DTESTORNO IS NOT NULL) THEN 1
                       ELSE 0
                   END
               ) AS VERIFICAR_DATA
          FROM ADIANTAMENTOS_BAIXADOS L
    ), PCCRECLI_BASE AS (
        SELECT C.CODFILIAL,
               C.DTLANC,
               C.DTDESCONTO,
               C.CODROTINA,
               C.ROTINABAIXA,
               C.CODIGO,
               C.NUMCRED,
               C.NUMTRANS,
               C.NUMLANCBAIXA,
               C.NUMTRANSBAIXA,
               C.CODMOVIMENTO,
               T.CODCONTAB,
               B.CODCONTABIL AS CODCONTABILBANCO,
               C.VALOR AS VALOR_ORIG,
               (
                   CASE
                       WHEN C.VALOR < 0 THEN (C.VALOR * - 1)
                       ELSE C.VALOR
                   END
               ) AS VALOR,
               C.NUMNOTADESC,
               T.CLIENTE
          FROM PCCRECLI C
         INNER JOIN ADIANTAMENTOS_BAIXADOS A ON C.CODIGO = A.CODIGO
          LEFT JOIN PCCLIENT T ON C.CODCLI = T.CODCLI
          LEFT JOIN PCMOVCR M ON C.NUMTRANS = M.NUMTRANS
           AND M.DTESTORNO IS NULL
          LEFT JOIN PCBANCO B ON M.CODBANCO = B.CODBANCO
    )
/*--CONCILIAÇÃO DO ADIANTAMENTO EM DUPLICATA--*/
    SELECT B.CODFILIAL,
           (
               CASE
                   WHEN V.VERIFICAR_DATA = 1 THEN B.DTLANC
                   ELSE B.DTDESCONTO
               END
           ) AS DATA,
           B.CODIGO,
           B.NUMCRED,
           B.NUMTRANS,
           B.NUMLANCBAIXA,
           B.CODCONTAB,
           B.CODCONTABILBANCO,
           B.VALOR,
           'C' AS TIPO,
           ('BAIXA NF ' || B.NUMNOTADESC || ' - ' || B.CLIENTE) AS HISTORICO
      FROM PCCRECLI_BASE B
      LEFT JOIN VER_DTLANC_DTDESC_BAIXA_DUPLIC V ON B.CODIGO = V.CODIGO
      LEFT JOIN VIEW_JC_ADIANT_CLIENTE A ON B.CODIGO = A.CODCRED
     WHERE B.VALOR_ORIG > 0
       AND B.ROTINABAIXA NOT LIKE '%619%'
       AND B.NUMTRANSBAIXA IS NULL
       AND A.CODCRED IS NULL
    UNION ALL
/*--BAIXA DO ADIANTAMENTO COMO RECEITA--*/
    SELECT B.CODFILIAL,
           (
               CASE
                   WHEN V.VERIFICAR_DATA = 1 THEN B.DTLANC
                   ELSE B.DTDESCONTO
               END
           ) AS DATA,
           B.CODIGO,
           B.NUMCRED,
           B.NUMTRANS,
           B.NUMLANCBAIXA,
           B.CODCONTAB,
           B.CODCONTABILBANCO,
           B.VALOR,
           'R' AS TIPO,
           ('RECEITA CRED ' || B.NUMCRED || ' - ' || B.CLIENTE) AS HISTORICO
      FROM PCCRECLI_BASE B
      LEFT JOIN VER_DTLANC_DTDESC_BAIXA_DUPLIC V ON B.CODIGO = V.CODIGO
     WHERE (B.CODROTINA IN (
        1400
    )
       AND B.ROTINABAIXA LIKE '%619%')
       AND B.NUMTRANS IS NOT NULL
       /*SOMENTE LANÇAMENTOS QUE MOVIMENTARAM CONTA GERENCIAL*/
       AND B.CODMOVIMENTO IS NOT NULL
    UNION ALL
 /*--ESTORNOS REALIZADOS---*/
    SELECT B.CODFILIAL,
           B.DTDESCONTO AS DATA,
           B.CODIGO,
           B.NUMCRED,
           B.NUMTRANS,
           B.NUMLANCBAIXA,
           B.CODCONTAB,
           B.CODCONTABILBANCO,
           B.VALOR,
           'E' AS TIPO,
           ('ESTORNO BAIXA CRED NFD ' || B.NUMCRED || ' - ' || B.CLIENTE) AS HISTORICO
      FROM PCCRECLI_BASE B
      LEFT JOIN VIEW_JC_ADIANT_CLIENTE A ON B.CODIGO = A.CODCRED
     WHERE (B.CODROTINA = 1209
       AND B.ROTINABAIXA LIKE '%1209%')
       AND B.VALOR_ORIG < 0
       AND A.CODCRED IS NULL;
/