CREATE OR REPLACE VIEW VIEW_JC_ADIANT_CLIENTE AS
SELECT C.CODFILIAL,
       --C.DTLANC,
       --M.DTCOMPENSACAO,
       (CASE WHEN M.DTCOMPENSACAO IS NULL THEN C.DTLANC ELSE M.DTCOMPENSACAO END) DATA, --PARA NAO FICAR SEM DATA EM SITUAÇÕES AONDE NAO FOI CONCILIADO
       C.CODIGO AS CODCRED, --USADO NA CONSTRUCAO DA VIEW_JC_PCPREST_BAIXA_CRED
       M.CODBANCO,
       B.CODCONTABIL AS CODCONTABILBANCO,      
       C.NUMTRANS,
       C.VALOR AS VLPAGO,
       C.VALOR,
       (M.NUMTRANS || ' - ' || 'ADIANT. CLIENTE - ' || T.CLIENTE) AS HISTORICO
  FROM PCCRECLI C
 INNER JOIN PCMOVCR M
    ON C.NUMTRANS = M.NUMTRANS
   AND C.CODMOVIMENTO = M.CODBANCO
  LEFT JOIN PCBANCO B
    ON M.CODBANCO = B.CODBANCO
  LEFT JOIN PCCLIENT T
    ON C.CODCLI = T.CODCLI
 WHERE C.NUMERARIO = 'S' -- PARA PUXAR APENAS ADIANTAMENTOS QUE MOVIMENTARAM BANCOS
   AND C.NUMTRANSBAIXA IS NULL --PARA NÃO PUXAR PAGAMENTO DEVOLVIDO DOS ADIANTAMENTOS
   AND M.DTESTORNO IS NULL --PARA NAO TRAZER LANCAMENTO DUPLICADOS OU TRIPILICADOS QUE TENHA SIDO ESTORNADOS NA PCMOVCR   
   AND M.CODBANCO NOT IN (17, 20, 35, 50, 52, 53, 54) --BANCOS DE BONIFICACAO E ACERTO MOTORISTA E EXTRAVIO DE MERCADORIA
   AND C.VALOR > 0 --PARA NAO TRAZER DESDOBRAMENTOS DO ADIANTAMENTO INICIAL
UNION ALL   
--RELAÇÃO DOS LANÇAMENTOS DE DEVOLUÇÃO DO ADIANTAMENTO AO CLIENTE
SELECT C.CODFILIAL,
       --C.DTLANC,
       --M.DTCOMPENSACAO,
       (CASE WHEN M.DTCOMPENSACAO IS NULL THEN C.DTLANC ELSE M.DTCOMPENSACAO END) DATA, --PARA NAO FICAR SEM DATA EM SITUAÇÕES AONDE NAO FOI CONCILIADO
       0 AS CODCRED, --USADO NA CONSTRUCAO DA VIEW_JC_PCPREST_BAIXA_CRED
       M.CODBANCO,
       B.CODCONTABIL AS CODCONTABILBANCO,
       C.NUMTRANSBAIXA AS NUMTRANS,
       C.VALOR AS VLPAGO,
       (CASE
         WHEN C.VALOR < 0 THEN
          C.VALOR * -1
         ELSE
          C.VALOR
       END) AS VALOR, --TRANSFORMAR OS VALORES NEGATIVOS PARA ARQUIVO CONTABILIDADE
       (M.NUMTRANS || ' - ' || 'DEV ADIANT. CLIENTE - ' || T.CLIENTE) AS HISTORICO
  FROM PCCRECLI C
 INNER JOIN PCMOVCR M
    ON C.NUMTRANSBAIXA = M.NUMTRANS
   AND C.CODMOVIMENTO = M.CODBANCO
  LEFT JOIN PCBANCO B
    ON M.CODBANCO = B.CODBANCO
  LEFT JOIN PCCLIENT T
    ON C.CODCLI = T.CODCLI
 WHERE C.NUMERARIO = 'S' -- PARA PUXAR APENAS ADIANTAMENTOS QUE MOVIMENTARAM BANCOS
   AND C.NUMTRANS IS NULL --PARA NÃO PUXAR PAGAMENTO RECEBIDO COMO ADIANTAMENTOS
   AND M.DTESTORNO IS NULL --PARA NAO TRAZER LANCAMENTO DUPLICADOS OU TRIPILICADOS QUE TENHA SIDO ESTORNADOS NA PCMOVCR   
   AND M.CODBANCO NOT IN (17, 20, 35, 50, 52, 53, 54) --BANCOS DE BONIFICACAO E ACERTO MOTORISTA E EXTRAVIO DE MERCADORIA
;
