CREATE OR REPLACE VIEW VIEW_JC_ADIANT_CLIENTE AS
    SELECT B.CODFILIAL,
           (
               CASE
                   WHEN B.DTCOMPENSACAO IS NULL THEN B.DTLANC
                   ELSE B.DTCOMPENSACAO
               END
           ) AS DATA,
     --PARA NAO FICAR SEM DATA EM SITUAÇÕES AONDE NAO FOI CONCILIADO
           B.CODCRED,
           B.CODBANCO,
           B.CODCONTABILBANCO,
           B.NUMTRANS,
           B.VLPAGO,
           B.VALOR,
           (B.NUMTRANS || ' - ' || 'ADIANT. CLIENTE - ' || B.CLIENTE) AS HISTORICO
      FROM VIEW_JC_ADIANTCLI_RECEBIDO B
     WHERE NVL (B.CODBACEN, '0') NOT IN (
        'MARKETPLACE'
    )
    UNION ALL
        --MARKETPLACES
    SELECT B.CODFILIAL,
           B.DTLANC AS DATA,
           B.CODCRED,
           B.CODBANCO,
           B.CODCONTABILBANCO,
           B.NUMTRANS,
           B.VLPAGO,
           B.VALOR,
           (B.NUMTRANS || ' - ' || 'ADIANT. CLIENTE - ' || B.CLIENTE) AS HISTORICO
      FROM VIEW_JC_ADIANTCLI_RECEBIDO B
     WHERE NVL (B.CODBACEN, '0') IN (
        'MARKETPLACE'
    )
    UNION ALL
        --RELAÇÃO DOS LANÇAMENTOS DE DEVOLUÇÃO DO ADIANTAMENTO AO CLIENTE
    SELECT B.CODFILIAL,
           (
               CASE
                   WHEN B.DTCOMPENSACAO IS NULL THEN B.DTLANC
                   ELSE B.DTCOMPENSACAO
               END
           ) AS DATA,
     --PARA NAO FICAR SEM DATA EM SITUAÇÕES AONDE NAO FOI CONCILIADO
           B.CODCRED,
           B.CODBANCO,
           B.CODCONTABILBANCO,
           B.NUMTRANSBAIXA AS NUMTRANS,
           B.VLPAGO,
           B.VALOR,
           (B.NUMTRANSBAIXA || ' - ' || 'DEV ADIANT. CLIENTE - ' || B.CLIENTE) AS HISTORICO
      FROM VIEW_JC_ADIANTCLI_DEVOLVIDO B
     WHERE NVL (B.CODBACEN, '0') NOT IN (
        'MARKETPLACE'
    )
    UNION ALL
        --MARKETPLACES
    SELECT B.CODFILIAL,
           B.DTLANC AS DATA,
           B.CODCRED,
           B.CODBANCO,
           B.CODCONTABILBANCO,
           B.NUMTRANSBAIXA AS NUMTRANS,
           B.VLPAGO,
           B.VALOR,
           (B.NUMTRANSBAIXA || ' - ' || 'DEV ADIANT. CLIENTE - ' || B.CLIENTE) AS HISTORICO
      FROM VIEW_JC_ADIANTCLI_DEVOLVIDO B
     WHERE NVL (B.CODBACEN, '0') IN (
        'MARKETPLACE'
    );
/