CREATE OR REPLACE VIEW VIEW_JC_ADIANTCLI_RECEBIDO AS
    SELECT C.CODFILIAL,
           M.DTCOMPENSACAO,
           C.DTLANC,
           C.CODCRED,
           C.NUMCRED,
           M.CODBANCO,
           B.CODBACEN,
           B.CODCONTABIL AS CODCONTABILBANCO,
           C.NUMTRANS,
           C.NUMTRANSBAIXA,
           C.VLPAGO,
           C.VALOR,
           C.CLIENTE
      FROM VIEW_JC_BASE_ADIANT_CLIENTE C
     INNER JOIN PCMOVCR M ON C.NUMTRANS = M.NUMTRANS
       AND C.CODMOVIMENTO = M.CODBANCO
      LEFT JOIN PCBANCO B ON M.CODBANCO = B.CODBANCO
     WHERE M.DTESTORNO IS NULL
     /*PARA NAO TRAZER LANCAMENTO DUPLICADOS OU TRIPILICADOS QUE TENHA SIDO ESTORNADOS NA PCMOVCR*/
       AND M.CODBANCO NOT IN (
        17, 20, 35, 50, 52, 53, 54
    )
     /*BANCOS DE BONIFICACAO E ACERTO MOTORISTA E EXTRAVIO DE MERCADORIA*/
       AND C.NUMTRANS IS NOT NULL
     /*PARA NÃO PUXAR PAGAMENTO RECEBIDOS DOS ADIANTAMENTOS*/
       AND C.VLPAGO > 0
     /*PARA NAO TRAZER DESDOBRAMENTOS DO ADIANTAMENTO INICIAL*/
       AND C.CODROTINA = 618
     /*PARA NAO TRAZER SALDOS E ABERTO COMO SE FOSSE NOVO LANÇAMENTO*/;
/