CREATE OR REPLACE VIEW VIEW_JC_ADIANT_BAIXA_DUPLICATA AS 
SELECT C.CODFILIAL,
       (CASE
         WHEN (C.CODROTINA = 1286 AND C.DTESTORNO IS NOT NULL) THEN
          C.DTLANC
         ELSE
          C.DTDESCONTO
       END) AS DATA,
       C.CODIGO AS CODCRED,
       C.NUMCRED,
       C.NUMTRANSVENDADESC AS NUMTRANSACAO,
       T.CODCONTAB,
       B.CODCONTABIL AS CODCONTABILBANCO,
       (CASE
         WHEN C.VALOR < 0 THEN
          C.VALOR * -1
         ELSE
          C.VALOR
       END) AS VALOR,
       (CASE
         WHEN (C.CODROTINA = 1286 AND C.DTESTORNO IS NOT NULL) THEN
          'CE'
         WHEN (C.CODROTINA = 1209 AND C.VALOR < 0) THEN
          'E'
         ELSE
          'C'
       END) AS TIPO,
       (CASE
         WHEN (C.CODROTINA = 1286 AND C.DTESTORNO IS NOT NULL) THEN
          ('NF ' || S.NUMNOTA || ' - ' || 'BAIXA ADIANT Nº TRANSACAO - ' ||
          C.NUMTRANSVENDADESC || ' - ' || T.CLIENTE)
         WHEN (C.CODROTINA = 1209 AND C.VALOR < 0) THEN
          ('NF ' || S.NUMNOTA || ' - ' || 'BAIXA ESTORNO Nº TRANSACAO - ' ||
          C.NUMTRANSVENDADESC || ' - ' || T.CLIENTE)
         ELSE
          ('NF ' || C.NUMNOTADESC || ' - ' || 'BAIXA ADIANT Nº TRANSACAO - ' ||
          C.NUMTRANSVENDADESC || ' - ' || T.CLIENTE)
       END) AS HISTORICO
  FROM PCCRECLI C
 INNER JOIN VW_JC_ADIANT_CLIENTE V ON C.NUMTRANS = V.NUMTRANSACAO
  LEFT JOIN PCCLIENT T ON C.CODCLI = T.CODCLI
  LEFT JOIN PCNFSAID S ON C.NUMTRANSVENDADESC = S.NUMTRANSVENDA
  LEFT JOIN PCMOVCR M ON C.NUMTRANS = M.NUMTRANS
                     AND M.DTESTORNO IS NULL
  LEFT JOIN PCBANCO B ON M.CODBANCO = B.CODBANCO
 WHERE C.NUMTRANSVENDADESC IS NOT NULL
   AND NOT (C.CODROTINA IN (618, 1400) AND C.DTESTORNO IS NOT NULL);
