CREATE OR REPLACE VIEW VIEW_JC_ADIANTCLI_DEVOLVIDO AS
    SELECT C.CODFILIAL,
           M.DTCOMPENSACAO,
           C.DTLANC,
           C.CODCRED,
     /*USADO NA CONSTRUCAO DA VIEW_JC_PCPREST_BAIXA_CRED    */
           M.CODBANCO,
           B.CODBACEN,
           B.CODCONTABIL AS CODCONTABILBANCO,
           C.NUMTRANS,
           C.NUMTRANSBAIXA,
           C.VLPAGO,
           C.VALOR,
           C.CLIENTE
      FROM VIEW_JC_BASE_ADIANT_CLIENTE C
     INNER JOIN PCMOVCR M ON C.NUMTRANSBAIXA = M.NUMTRANS
       AND C.CODMOVIMENTO = M.CODBANCO
      LEFT JOIN PCBANCO B ON M.CODBANCO = B.CODBANCO
     WHERE M.DTESTORNO IS NULL
     /*PARA NAO TRAZER LANCAMENTO DUPLICADOS OU TRIPILICADOS QUE TENHA SIDO ESTORNADOS NA PCMOVCR   */
       AND M.CODBANCO NOT IN (
        17, 20, 35, 50, 52, 53, 54
    )
     /*BANCOS DE BONIFICACAO E ACERTO MOTORISTA E EXTRAVIO DE MERCADORIA*/
       AND C.NUMTRANSBAIXA IS NOT NULL
     /*PARA PUXAR PAGAMENTOS DEVOLVIDOS DOS ADIANTAMENTOS*/
       AND NOT (C.HISTORICO LIKE '%TAXA%'
       AND CODMOVIMENTO = 11);
/