CREATE OR REPLACE VIEW VIEW_JC_ADIANT_RECEITA_SIMPLES AS
SELECT C.CODFILIAL,
       C.DTLANC AS DATA,
       C.CODIGO AS CODCRED,
       C.NUMCRED,
       '' AS CODCONTAB,
       0 AS CODCONTABILBANCO,
       C.NUMLANCBAIXA AS NUMTRANSACAO,
       C.NUMTRANS,
       (CASE
         WHEN C.VALOR < 0 THEN
          C.VALOR * -1
         ELSE
          C.VALOR
       END) AS VALOR,
       'R' AS TIPO,
       ('Nº LANC. ' || C.NUMLANCBAIXA || ' - RECEITA CRED ' || C.NUMCRED || ' - ' || T.CLIENTE) AS HISTORICO
  FROM PCCRECLI C
 INNER JOIN VIEW_JC_ADIANT_CLIENT_RECEBIDO V ON C.NUMCRED = V.NUMCRED
 LEFT JOIN PCCLIENT T ON C.CODCLI = T.CODCLI
 WHERE C.NUMLANCBAIXA IS NOT NULL;
 /
