CREATE OR REPLACE VIEW VIEW_JC_ADIANT_RECEITA_SIMPLES AS
SELECT C.CODFILIAL,
       C.DTLANC AS DATA,
       C.CODIGO AS CODCRED,
       C.NUMCRED,
       0 AS CODBANCO,
       '' AS CODBACEN,
       0 AS CODCONTABILBANCO,
       C.NUMLANCBAIXA AS NUMTRANSACAO,
       (CASE
         WHEN C.VALOR < 0 THEN
          C.VALOR * -1
         ELSE
          C.VALOR
       END) AS VLPAGO,
       'RS' AS TIPO,
       ('RECEITA CRED ' || C.NUMCRED || ' - ' || T.CLIENTE) AS HISTORICO
  FROM PCCRECLI C
 INNER JOIN VW_JC_ADIANT_CLIENTE V ON C.NUMCRED = V.NUMCRED
 LEFT JOIN PCCLIENT T ON C.CODCLI = T.CODCLI
 WHERE C.NUMLANCBAIXA IS NOT NULL;
 /
