/*PRODUTOS CST ICMS 00 DESTAQUE DE 18%*/
CREATE OR REPLACE VIEW VIEW_JC_TABELABASE_ICMS18 AS
    SELECT A.*
      FROM VIEW_JC_TABELABASE A
      LEFT JOIN VIEW_JC_TABELABASE_SP_ICMS12 B ON A.CODFILIAL = B.CODFILIAL
       AND A.UFDESTINO = B.UFDESTINO
       AND A.CODPROD = B.CODPROD
      LEFT JOIN VIEW_JC_TABELABASE_SP_ICMS25 C ON A.CODFILIAL = C.CODFILIAL
       AND A.UFDESTINO = C.UFDESTINO
       AND A.CODPROD = C.CODPROD
      LEFT JOIN VIEW_JC_TABELABASE_ICMS_CST41 D ON A.CODFILIAL = D.CODFILIAL
       AND A.UFDESTINO = D.UFDESTINO
       AND A.CODPROD = D.CODPROD
      LEFT JOIN VIEW_JC_TABELABASE_ICMS_CST40 E ON A.CODFILIAL = E.CODFILIAL
       AND A.UFDESTINO = E.UFDESTINO
       AND A.CODPROD = E.CODPROD
      LEFT JOIN VIEW_JC_TABELABASE_ICMS_CST00 F ON A.CODFILIAL = F.CODFILIAL
       AND A.UFDESTINO = F.UFDESTINO
       AND A.CODPROD = F.CODPROD
     WHERE A.REGIME_ICMS = 'S'
  /*PARA NAO CONSIDERAR PRODUTOS ICMS COM ALIQUOTAS DIFERENTE DE 18%--*/
       AND B.CODPROD IS NULL
       AND C.CODPROD IS NULL
       AND D.CODPROD IS NULL
       AND E.CODPROD IS NULL
       AND F.CODPROD IS NULL;
/