/*TABELA BASE PARA CST ICMS 41     */
CREATE OR REPLACE VIEW VIEW_JC_TABELABASE_ICMS_CST41 AS
    SELECT *
      FROM VIEW_JC_TABELABASE
     WHERE CODNCMEX IN (
        '49011000.', '49019900.'
    );
/

/*TABELA BASE PARA CST ICMS 40     */
CREATE OR REPLACE VIEW VIEW_JC_TABELABASE_ICMS_CST40 AS
    SELECT *
      FROM VIEW_JC_TABELABASE
     WHERE CODNCMEX IN (
        '49030000.', '49111090.1', '49119900.1'
    );
/

/*UNIAO DAS TABELAS COM CST DE ICMS 40 E 41*/
CREATE OR REPLACE VIEW VIEW_JC_ICMS_CST40_41 AS
    SELECT *
      FROM VIEW_JC_TABELABASE_ICMS_CST41
    UNION
    SELECT *
      FROM VIEW_JC_TABELABASE_ICMS_CST40;
/