/*TABELA BASE PARA LUCRO REAL*/
CREATE OR REPLACE VIEW VIEW_JC_TABELABASE_LR AS
    SELECT *
      FROM VIEW_JC_TABELABASE
     WHERE CODFILIAL IN (
        1, 2, 3, 4, 7, 8
    );
/
/*TABELA BASE PARA SIMPLES NACIONAL*/
CREATE OR REPLACE VIEW VIEW_JC_TABELABASE_SN AS
    SELECT *
      FROM VIEW_JC_TABELABASE
     WHERE CODFILIAL IN (
        5, 6, 9, 10
    );
/
/*TABELA BASE PARA SIMPLES NACIONAL EXCESSIVO*/
CREATE OR REPLACE VIEW VIEW_JC_TABELABASE_SNE AS
    SELECT *
      FROM VIEW_JC_TABELABASE
     WHERE CODFILIAL IS NULL;
/