CREATE OR REPLACE VIEW VIEW_JC_TABELABASE AS
 SELECT T.CODFILIALNF         AS CODFILIAL,
         P.DTCADASTRO,
         E.CODPROD,
         P.CODFAB,
         E.GERAICMSLIVROFISCAL REGIME_ICMS,
         P.DESCRICAO,
         P.IMPORTADO,
         P.CODNCMEX,
         T.UFDESTINO,
         T.CODST,
         F.MENSAGEM,
         T.CODTRIBPISCOFINS
    FROM PCTABTRIB T
   INNER JOIN PCPRODUT P
      ON P.CODPROD = T.CODPROD
     AND P.DTEXCLUSAO IS NULL
     AND P.TIPOMERC = 'L'
   INNER JOIN PCPRODFILIAL E
      ON E.CODPROD = T.CODPROD
     AND E.CODFILIAL = T.CODFILIALNF
    LEFT JOIN PCTRIBUT F
      ON T.CODST = F.CODST;/