CREATE OR REPLACE VIEW VIEW_JC_SALDO_BANCOS AS
WITH ULTIMO_SALDO AS
 (SELECT M.CODBANCO,
         M.DATACOMPLETA,
         M.VLSALDO,
         M.DTCONCIL,
         M.VLSALDOCONCIL,
         ROW_NUMBER() OVER(PARTITION BY M.CODBANCO ORDER BY M.DATACOMPLETA DESC) AS RN
    FROM PCMOVCR M
   WHERE M.CODCOB = 'D'
     AND M.DTESTORNO IS NULL
   ORDER BY M.CODBANCO,
            M.DATACOMPLETA DESC),

ULTIMO_SALDO_CONCILIADO AS
 (SELECT M.CODBANCO,
         M.DTCONCIL,
         M.VLSALDOCONCIL,
         ROW_NUMBER() OVER(PARTITION BY M.CODBANCO ORDER BY M.DTCONCIL DESC) AS RN
    FROM PCMOVCR M
   WHERE M.CODCOB = 'D'
     AND M.DTESTORNO IS NULL
     AND M.DTCONCIL IS NOT NULL
   ORDER BY M.CODBANCO,
            M.DATACOMPLETA DESC)

SELECT B.CODFILIAL,
       M.CODBANCO,
       B.NOME BANCO,
       B.TIPOCXBCO,
       M.DATACOMPLETA MAIORDATA,
       M.VLSALDO,
       D.DTCONCIL MAIORDTCONCIL,
       D.VLSALDOCONCIL
  FROM ULTIMO_SALDO M
  LEFT JOIN ULTIMO_SALDO_CONCILIADO D ON M.CODBANCO = D.CODBANCO
  LEFT JOIN PCBANCO B ON B.CODBANCO = M.CODBANCO
 WHERE M.RN = 1
   AND D.RN = 1
   AND NOT (NVL(B.CODBACEN, '0') = 'MARKETPLACE')
   AND NOT (INSTR(B.NOME, 'MOTORISTA') > 0 OR INSTR(B.NOME, 'BONIFIC') > 0 OR
        INSTR(B.NOME, 'COMISSAO') > 0 OR INSTR(B.NOME, 'EXTRAVIO') > 0 OR
        INSTR(B.NOME, 'CARTAO') > 0)
   AND NOT (B.TIPOCXBCO = 'I' AND M.VLSALDO = 0)
;
