CREATE OR REPLACE VIEW VIEW_JC_SALDO_BANCOS AS
WITH ULTIMA_DATA_BANCO_MOV AS
 (SELECT M.CODBANCO, MAX(M.DATACOMPLETA) MAIORDATA
    FROM PCMOVCR M
   WHERE M.CODCOB = 'D'
     AND M.DTESTORNO IS NULL
   GROUP BY M.CODBANCO),
ULTIMO_SALDO AS
 (SELECT M.CODBANCO, D.MAIORDATA, MAX(M.VLSALDO) VLSALDO
    FROM PCMOVCR M
    JOIN ULTIMA_DATA_BANCO_MOV D ON D.CODBANCO = M.CODBANCO
                                AND D.MAIORDATA = M.DATACOMPLETA
  
   GROUP BY M.CODBANCO, D.MAIORDATA),
ULTIMA_DATA_CONCILIADA AS
 (SELECT M.CODBANCO, MAX(M.DTCONCIL) MAIORDTCONCIL
    FROM PCMOVCR M
   WHERE M.CODCOB = 'D'
     AND M.DTESTORNO IS NULL
   GROUP BY M.CODBANCO),
ULTIMO_SALDO_CONCILIADO AS
 (SELECT M.CODBANCO, D.MAIORDTCONCIL, MAX(M.VLSALDOCONCIL) VLSALDOCONCIL
    FROM PCMOVCR M
    JOIN ULTIMA_DATA_CONCILIADA D ON D.CODBANCO = M.CODBANCO
                                 AND D.MAIORDTCONCIL = M.DTCONCIL
   GROUP BY M.CODBANCO, D.MAIORDTCONCIL)
SELECT B.CODFILIAL,
       M.CODBANCO,
       B.NOME BANCO,
       B.TIPOCXBCO,
       M.MAIORDATA,
       M.VLSALDO,
       D.MAIORDTCONCIL,
       D.VLSALDOCONCIL
  FROM ULTIMO_SALDO M
  JOIN ULTIMO_SALDO_CONCILIADO D ON M.CODBANCO = D.CODBANCO
  JOIN PCBANCO B ON B.CODBANCO = M.CODBANCO
 WHERE B.FLUXOCX = 'S'
 ORDER BY M.MAIORDATA DESC;
/