SELECT T.CODFILIAL,
       T.NUMTRANSENT,
       T.DTMOV,
       T.NUMPED,
       T.CODFORNEC,
       F.FORNECEDOR,
       T.CODPROD,
       P.DESCRICAO,
       T.CODOPER,
       T.NUMNOTA,
       T.QT,
       (I.QTPEDIDA - I.QTENTREGUE) QTPENDENTE
  FROM PCMOVPREENT T, PCPRODUT P, PCFORNEC F, PCITEM I
 WHERE T.CODPROD = P.CODPROD
   AND T.CODFORNEC = F.CODFORNEC
   AND I.CODPROD(+) = T.CODPROD
   AND I.NUMPED(+) = T.NUMPED
   AND F.CODFORNECPRINC = 2
   AND NOT EXISTS
 (SELECT NUMTRANSENT FROM PCMOV WHERE NUMTRANSENT = T.NUMTRANSENT)
UNION
SELECT NULL CODFILIAL,
       NULL NUMTRANSENT,
       NULL DTMOV,
       I.NUMPED,
       P.CODFORNEC,
       F.FORNECEDOR,
       I.CODPROD,
       P.DESCRICAO,
       NULL CODOPER,
       NULL NUMNOTA,
       NULL QT,
       (I.QTPEDIDA - I.QTENTREGUE) QTPENDENTE
  FROM PCITEM I, PCPRODUT P, PCFORNEC F
 WHERE I.CODPROD = P.CODPROD
   AND P.CODFORNEC = F.CODFORNEC
   AND (I.QTPEDIDA - I.QTENTREGUE) > 0
   AND F.CODFORNECPRINC = 2
   AND NOT EXISTS (SELECT NUMPED
          FROM PCMOVPREENT
         WHERE NUMPED = I.NUMPED
           AND CODPROD = I.CODPROD)
 ORDER BY CODFORNEC;/