SELECT /*:DTINICIAL,
       :DTFINAL,*/
       M.CODFILIAL,
       P.CODCOMPRADOR,
       E.NOME,
       M.CODFORNEC,
       F.FORNECEDOR,
       P.NUMPED,
       P.VLTOTAL VLPEDIDO,
       ROUND(SUM(M.QT * M.PUNIT),2) VLFATURADO,
       (P.VLTOTAL-ROUND(SUM(M.QT * M.PUNIT),2)) VLPENDENTE     
  FROM PCPEDIDO P, PCFORNEC F, PCEMPR E, PCMOV M
 WHERE F.CODFORNEC = M.CODFORNEC
   AND E.MATRICULA = P.CODCOMPRADOR
   AND M.NUMPED = P.NUMPED
   AND M.DTMOV BETWEEN TO_DATE(:DTINICIAL, 'DD/MM/YYYY') AND TO_DATE(:DTFINAL, 'DD/MM/YYYY')
   AND P.CODFORNEC NOT IN (1, 7543)
       AND P.CODFORNEC IN (:CODFORNEC)
       AND P.CODFILIAL IN (:CODFILIAL)
   AND P.CODCOMPRADOR IN (:CODCOMPRADOR)
 GROUP BY M.CODFILIAL,
       P.CODCOMPRADOR,
       E.NOME,
       M.CODFORNEC,
       P.NUMPED,
       F.FORNECEDOR,
       P.VLTOTAL
 ORDER BY FORNECEDOR, CODFILIAL, CODCOMPRADOR;