SELECT L.CODFILIAL,
       L.DTPAGTO,
       L.RECNUM,
       L.CODCONTA,
       C.CONTA,
       L.HISTORICO,
       L.HISTORICO2,
       L.VPAGO
  FROM PCLANC L
  LEFT JOIN PCCONTA C ON L.CODCONTA = C.CODCONTA
 WHERE (UPPER (HISTORICO) LIKE '%CAMINHAO%'
    OR UPPER (HISTORICO2) LIKE '%CAMINHAO%'
    OR UPPER (HISTORICO) LIKE '%IVECO%'
    OR UPPER (HISTORICO2) LIKE '%IVECO%'
    OR UPPER (HISTORICO) LIKE '%DAILY%'
    OR UPPER (HISTORICO2) LIKE '%DAILY%'
    OR UPPER (HISTORICO) LIKE '%CAMINHÃO%'
    OR UPPER (HISTORICO2) LIKE '%CAMINHÃO%'
    OR UPPER (HISTORICO) LIKE '%CAMINH?O%'
    OR UPPER (HISTORICO2) LIKE '%CAMINH?O%'
    OR UPPER (HISTORICO) LIKE '%DIESEL%'
    OR UPPER (HISTORICO2) LIKE '%DIESEL%'
    OR UPPER (HISTORICO) LIKE '%HR%'
    OR UPPER (HISTORICO2) LIKE '%HR%'
    OR (L.CODFORNEC = 9424
   AND L.TIPOPARCEIRO = 'F'))
   AND L.DTPAGTO IS NOT NULL
   AND L.DTESTORNOBAIXA IS NULL
   AND C.GRUPOCONTA NOT IN (
    515, 520
)
   AND VPAGO > 0
UNION
SELECT L.CODFILIAL,
       L.DTPAGTO,
       L.RECNUM,
       L.CODCONTA,
       C.CONTA,
       L.HISTORICO,
       L.HISTORICO2,
       R.VALOR AS VPAGO
  FROM PCRATEIOCENTROCUSTO R
 INNER JOIN PCLANC L ON R.RECNUM = L.RECNUM
  LEFT JOIN PCCONTA C ON L.CODCONTA = C.CODCONTA
 WHERE R.CODCONTA = 545104
   AND R.CODIGOCENTROCUSTO = '200.201'
   AND L.DTPAGTO IS NOT NULL
   AND L.DTESTORNOBAIXA IS NULL;
/