SELECT E.DATA,
       E.CODFILIAL,
       E.CODPROD,
       P.DESCRICAO,
       E.PROGRAMA,
       E.USUARIO,
       E.MAQUINA,
       E.QTESTGERANT,
       E.QTESTGER,
       E.QTESTANT,
       E.QTEST,
       ROUND (ABS (E.VALORULTENT_ANT / E.VALORULTENT), 2) DIF_VL,
       E.VALORULTENT_ANT,
       E.VALORULTENT,
       T.VALORULTENT VLULTENT_ATUAL,
       E.CUSTOFIN_ANT,
       E.CUSTOFIN,
       T.CUSTOFIN CUSTOFIN_ATUAL
  FROM PCLOGESTOQUE E,
       PCPRODUT P,
       PCEST T
 WHERE E.CODPROD = P.CODPROD
   AND E.CODPROD = T.CODPROD
   AND E.CODFILIAL = T.CODFILIAL
   AND E.CODFILIAL IN (
    1, 2, 7
)
   AND E.DATA > TRUNC (SYSDATE) - 30
   AND (E.VALORULTENT_ANT <> E.VALORULTENT
    OR E.CUSTOFIN_ANT <> E.CUSTOFIN)
   AND ABS (E.VALORULTENT_ANT / E.VALORULTENT) > 1.05
   AND E.PROGRAMA LIKE '%1124%'
   AND E.VALORULTENT <> 0
 ORDER BY E.DATA DESC;
/