SELECT T.CODFILIAL,
       T.DATA,
       T.CODPROD,
       T.QTESTGERANT,
       T.QTESTGER,
       T.QTESTANT,
       T.QTEST,
       T.VALORULTENT_ANT,
       T.VALORULTENT,
       T.CUSTOFIN_ANT,
       T.CUSTOFIN,
       T.CUSTOCONT_ANT,
       T.CUSTOCONT,
       T.PROGRAMA,
       T.USUARIO,
       T.MAQUINA
  FROM PCLOGESTOQUE T
 WHERE T.DATA BETWEEN TO_DATE ('12/06/2023', 'DD/MM/YYYY') AND TO_DATE ('14/06/2023', 'DD/MM/YYYY')
   AND T.CODPROD = 448
   AND CODFILIAL IN ('10')
 ORDER BY DATA;
 
 
