SELECT T.CODFILIAL,
       T.DATA,
       T.CODPROD,
       T.QTESTGERANT,
       T.QTESTGER,
       T.QTESTANT,
       T.QTEST,
       T.VALORULTENT_ANT,
       T.VALORULTENT,
       T.CUSTOFIN_ANT,
       T.CUSTOFIN,
       T.CUSTOCONT_ANT,
       T.CUSTOCONT,
       T.PROGRAMA,
       T.USUARIO,
       T.MAQUINA
  FROM PCLOGESTOQUE T
 WHERE T.DATA BETWEEN TO_DATE ('17/06/2020', 'DD/MM/YYYY') AND TO_DATE ('19/06/2020', 'DD/MM/YYYY')
   AND T.CODPROD = 800081
   AND CODFILIAL = 7
 ORDER BY DATA;