SELECT E.DATA,
       E.CODFILIAL,
       E.CODPROD,
       P.DESCRICAO,
       E.PROGRAMA,
       E.USUARIO,
       E.MAQUINA,
       E.QTESTGERANT,
       E.QTESTGER,
       E.QTESTANT,
       E.QTEST,
       E.VALORULTENT_ANT,
       E.VALORULTENT,
       T.VALORULTENT VLULTENT_ATUAL,
       E.CUSTOFIN_ANT,
       E.CUSTOFIN,
       T.CUSTOFIN CUSTOFIN_ATUAL,
       E.CUSTOREAL_ANT,
       E.CUSTOREAL,
       E.CUSTOREP_ANT,
       E.CUSTOREP,
       E.CUSTOCONT_ANT,
       E.CUSTOCONT
  FROM PCLOGESTOQUE E,
       PCPRODUT P,
       PCEST T
 WHERE E.CODPROD = P.CODPROD
   AND E.CODPROD = T.CODPROD
   AND E.CODFILIAL = T.CODFILIAL
   AND E.CODFILIAL IN (
    1, 2, 7
)
   AND E.DATA > TRUNC (SYSDATE) - 365
   AND (((E.VALORULTENT_ANT <> E.VALORULTENT
    OR E.CUSTOFIN_ANT <> E.CUSTOFIN)
    OR (E.CUSTOREP_ANT <> E.CUSTOREP))
    OR (E.CUSTOCONT_ANT <> E.CUSTOCONT))
   AND (PROGRAMA <> 'PL/SQL Developer'
   AND USUARIO = 'usuario002')
   AND PROGRAMA NOT LIKE '%1301%'
   AND PROGRAMA NOT LIKE '%1124%'
   AND PROGRAMA NOT LIKE '%507%'
 ORDER BY E.DATA DESC;
/