SELECT T.CODFILIAL,
       T.DATA,
       T.CODPROD,
       T.QTESTGERANT,
       T.QTESTGER,
       T.QTESTANT,
       T.QTEST,
       T.VALORULTENT_ANT,
       T.VALORULTENT,
       T.CUSTOFIN_ANT,
       T.CUSTOFIN,
       T.CUSTOCONT_ANT,
       T.CUSTOCONT,
       T.PROGRAMA,
       T.USUARIO,
       T.MAQUINA
  FROM PCLOGESTOQUE T
 WHERE T.DATA BETWEEN TO_DATE ('20/08/2022', 'DD/MM/YYYY') AND TO_DATE ('26/08/2022', 'DD/MM/YYYY')
   AND T.CODPROD = 806699
   AND CODFILIAL = '7'
 ORDER BY DATA;