WITH PENDENTE_COMPRAS AS (
    SELECT CODPROD,
           QTPENDCOMPRA_F7
      FROM (
        SELECT CODPROD,
               SUM (NVL (QTPEDIDA, 0)) - SUM (NVL (QTENTREGUE, 0)) QTPENDCOMPRA_F7
          FROM (
            SELECT I.CODPROD,
                   I.QTPEDIDA,
                   (
                       CASE
                           WHEN I.QTENTREGUE > I.QTPEDIDA THEN I.QTPEDIDA
                           ELSE I.QTENTREGUE
                       END
                   ) AS QTENTREGUE
              FROM PCITEM I
             INNER JOIN PCPEDIDO P ON I.NUMPED = P.NUMPED
             WHERE P.CODCOMPRADOR NOT IN (
                14
            )
               AND P.CODFILIAL = 7
        ) I
         WHERE QTPEDIDA <> QTENTREGUE
         GROUP BY CODPROD
    )
     WHERE QTPENDCOMPRA_F7 > 0
), PRODUTO_ESTOQUE AS (
    SELECT E.CODFILIAL,
           P.CODPROD,
           P.IMPORTADO,
           P.CODMARCA,
           M.MARCA,
           E.QTESTGER AS QTESTOQUE,
           E.CUSTOPROXIMACOMPRA
      FROM PCPRODUT P
     INNER JOIN PCPRODFILIAL D ON P.CODPROD = D.CODPROD
      LEFT JOIN PCFORNEC F ON P.CODFORNEC = F.CODFORNEC
      LEFT JOIN PCEST E ON P.CODPROD = E.CODPROD
       AND D.CODFILIAL = E.CODFILIAL
      LEFT JOIN PCMARCA M ON P.CODMARCA = M.CODMARCA
     WHERE P.DTEXCLUSAO IS NULL
)
SELECT *
  FROM (
    SELECT P.CODFILIAL,
           P.CODPROD,
           P.DESCRICAO,
           E.IMPORTADO,
           E.CODMARCA,
           E.MARCA,
           P.NUMREGIAO,
           P.REGIAO,
           NVL (C.QTPENDCOMPRA_F7, 0) AS QTPENDCOMPRA_F7,
           E.QTESTOQUE,
           P.MARGEM AS MIDEAL,
           ROUND (P.MARGEMPRECIFICACAO, 2) AS MPRECO,
           ROUND (E.CUSTOPROXIMACOMPRA, 4) CUSTOPROXCOMPRA,
           ROUND (L.PLIQUIDO, 4) AS CUSTOLIQAPLIC,
           ROUND (P.CUSTOSELECIONADO / (1 - ((P.CODICMTAB + P.MARGEM) / 100)), 4) AS PSUGERIDO,
           TO_NUMBER (CONCAT (TRUNC (ROUND (P.CUSTOSELECIONADO / (1 - ((P.CODICMTAB + P.MARGEM) / 100)), 4), 0), '.99')) AS PSUGALTER
           ,
           ROUND (P.PVENDA, 4) AS PVENDA
      FROM VW_PRECIFICACAO P
      LEFT JOIN VIEW_JC_CUSTOLIQ_240 L ON P.CODPROD = L.CODPROD
       AND P.CODFILIAL = L.CODFILIAL
      LEFT JOIN PRODUTO_ESTOQUE E ON P.CODPROD = E.CODPROD
       AND P.CODFILIAL = E.CODFILIAL
      LEFT JOIN PENDENTE_COMPRAS C ON P.CODPROD = C.CODPROD
     WHERE P.CODFILIAL IN (
        7
    )
       AND P.NUMREGIAO IN (
        102
    )
     ORDER BY E.CODMARCA,
              E.QTESTOQUE DESC,
              C.QTPENDCOMPRA_F7 DESC
)
 WHERE NOT (MPRECO = 0
   AND CUSTOPROXCOMPRA = 0)
   AND (QTESTOQUE > 0
    OR QTPENDCOMPRA_F7 > 0)
    OR (CUSTOPROXCOMPRA <> CUSTOLIQAPLIC
    OR PSUGALTER <> PVENDA);
/