SELECT *
  FROM (
    SELECT P.CODFILIAL,
           P.CODPROD,
           P.DESCRICAO,
           R.IMPORTADO,
           L.CODLINHA,
           L.DESCRICAO AS LINHA_PROD,
           P.NUMREGIAO,
           P.REGIAO,
           P.MARGEM AS MIDEAL,
           ROUND (P.MARGEMPRECIFICACAO, 2) AS MPRECO,
           ROUND (E.CUSTOPROXIMACOMPRA, 4) CUSTOPROXIMACOMPRA,
           ROUND (P.CUSTOSELECIONADO, 4) AS CUSTOLIQAPLIC,
           ROUND (P.CUSTOSELECIONADO / (1 - ((P.CODICMTAB + P.MARGEM) / 100)), 4) AS PSUGERIDO,
           ROUND (P.PVENDA, 4) AS PVENDA
      FROM VW_PRECIFICACAO P
      LEFT JOIN PCEST E ON P.CODFILIAL = E.CODFILIAL
       AND P.CODPROD = E.CODPROD
      LEFT JOIN PCFORNEC F ON P.CODFORNEC = F.CODFORNEC
      LEFT JOIN PCPRODFILIAL D ON P.CODFILIAL = D.CODFILIAL
       AND P.CODPROD = D.CODPROD
      LEFT JOIN PCPRODUT R ON P.CODPROD = R.CODPROD
      LEFT JOIN PCLINHAPROD L ON R.CODLINHAPROD = L.CODLINHA
     WHERE P.CODFILIAL = 2
       AND P.NUMREGIAO IN (
        1, 3, 4
    )
       AND F.CODFORNECPRINC = 2
       AND D.ENVIARFORCAVENDAS = 'S'
       AND NVL (R.OBS2, '0') NOT IN (
        'FL'
    )
     ORDER BY P.CODPROD,
              P.NUMREGIAO
)
 WHERE MIDEAL <> MPRECO
    OR CUSTOPROXIMACOMPRA <> CUSTOLIQAPLIC
    OR PSUGERIDO <> PVENDA;
/