SELECT M.CODFILIAL,
       M.DTMOV,
       M.NUMNOTA,
       M.CODOPER,
       M.CODPROD,
       P.DESCRICAO,
       M.QT,
       M.PUNIT,
       M.CODFISCAL,
       M.QTESTGERANT,
       M.QTESTANT,
       M.CUSTOFINANT,
       M.CUSTOREALANT,
       M.CUSTOULTENTANT,
       M.CUSTOFIN,
       M.CUSTOREAL,
       M.CUSTOULTENT
  FROM PCMOV M
  LEFT JOIN PCPRODUT P ON M.CODPROD = P.CODPROD
 WHERE M.CUSTOFINANT < 0
    OR M.CUSTOREALANT < 0
    OR M.CUSTOULTENTANT < 0
 ORDER BY DTMOV DESC;
/