--CUSTO UNITARIO TRANSFERENCIA DIVEREGENTE ENTRE ENTRADA E SAIDA--
WITH ENTRADA AS
 (SELECT M.CODPROD,
         M.PUNITCONT AS PUNITENT,
         T.NUMTRANSVENDAORIG,
         M.NUMTRANSENT
    FROM PCMOV M
   INNER JOIN PCNFENT T
      ON M.NUMTRANSENT = T.NUMTRANSENT)
SELECT M.DTMOV,
       M.CODPROD,
       P.DESCRICAO,
       E.PUNITENT,
       M.PUNITCONT AS PUNITSAID,
       E.NUMTRANSENT,
       M.NUMTRANSVENDA
  FROM PCMOV M
 INNER JOIN ENTRADA E
    ON E.CODPROD = M.CODPROD
   AND E.NUMTRANSVENDAORIG = M.NUMTRANSVENDA
  LEFT JOIN PCPRODUT P
    ON M.CODPROD = P.CODPROD
 WHERE M.CODOPER = 'ST'
   AND E.PUNITENT <> M.PUNITCONT;
