SELECT E.CODFILIAL,
       T.NUMREGIAO,
       P.DTCADASTRO,
       P.CODPRODMASTER CODMASTER,
       E.CODPROD,
       P.DESCRICAO,
       ROUND(E.CUSTOFIN,2) CUSTOFIN,
       ROUND((F.CUSTOREP * ((100 - F.PERCDESC) / 100)), 2) PBRUTO_240,
       ROUND(E.CUSTOPROXIMACOMPRA,2) PROXIMACOMPRA,
       ROUND(T.PVENDA,2) PVENDA,
       T.MARGEM
  FROM PCEST E, PCPRODUT P, PCPRODFILIAL F, PCTABPR T
 WHERE E.CODPROD = P.CODPROD
 AND F.CODPROD = P.CODPROD
 AND E.CODFILIAL = F.CODFILIAL
 AND T.CODPROD = P.CODPROD
 AND P.DTEXCLUSAO IS NULL
 AND P.TIPOMERC = 'L'
 AND P.REVENDA = 'S'
 AND P.CODPROD = P.CODPRODMASTER
 AND NUMREGIAO IN (1,3,4)
 AND E.CODFILIAL IN (2)
 AND E.CODPROD = 797027;