/*WITH PRODUTOS AS
 (SELECT CODPROD FROM PCMOV M WHERE M.NUMTRANSENT IN (1863525))
*/
SELECT E.CODFILIAL,
       T.NUMREGIAO,
       P.DTCADASTRO,
       P.CODPRODMASTER CODMASTER,
       E.CODPROD,
       P.DESCRICAO,
       ROUND(E.CUSTOFIN, 2) CUSTOFIN,
       ROUND((F.CUSTOREP * ((100 - F.PERCDESC) / 100)), 2) PBRUTO_240,
       ROUND(E.CUSTOPROXIMACOMPRA, 2) PROXIMACOMPRA,
       ROUND(T.PVENDA, 2) PVENDA,
       T.MARGEM
  FROM PCEST E,
       PCPRODUT P,
       PCPRODFILIAL F,
       PCTABPR T
       --,PRODUTOS S
 WHERE E.CODPROD = P.CODPROD
   AND F.CODPROD = P.CODPROD
   AND E.CODFILIAL = F.CODFILIAL
   AND T.CODPROD = P.CODPROD
   --AND E.CODPROD = S.CODPROD
   AND P.DTEXCLUSAO IS NULL
   AND P.TIPOMERC = 'L'
   AND P.REVENDA = 'S'
   AND P.CODPROD = P.CODPRODMASTER
   AND NUMREGIAO IN (4)
   AND E.CODFILIAL IN (11)
   AND E.CODPROD IN (110045, 823747, 823753, 814350)
	 ;
