/*VÍNCULO ENTRE NF MAE E NOTA FILHA*/
WITH MOVT7 AS (
    SELECT M.NUMTRANSVENDA,
           M.DTMOV AS DTMOV_TV7,
           M.NUMTRANSITEM AS NUMTRANSITEM_TV7,
           M.CODPROD,
           M.CUSTOCONT AS CUSTOCONT_TV7
      FROM PCMOV M
     INNER JOIN PCNFSAID S ON M.NUMTRANSVENDA = S.NUMTRANSVENDA
     WHERE S.CONDVENDA = 7
)
SELECT M8.DTMOV,
       T7.DTMOV_TV7,
       M8.NUMTRANSVENDA AS NUMTRANSVENDA_TV8,
       S.NUMTRANSVENDA AS NUMTRANSVENDA_TV7,
       T7.NUMTRANSITEM_TV7,
       M8.CODPROD,
       M8.QTCONT,
       (M8.QTCONT * T7.CUSTOCONT_TV7) VLTOTAL_TV8,
       ROUND (M8.QTCONT * T7.CUSTOCONT_TV7, 2) ARREDTOTAL_TV8,
       M8.CUSTOCONT AS CUSTOCONT_TV8,
       M8.NUMTRANSITEM AS NUMTRANSITEM_TV8,
       T7.CUSTOCONT_TV7
  FROM PCMOV M8
 INNER JOIN PCPEDC C ON M8.NUMTRANSVENDA = C.NUMTRANSVENDA
 INNER JOIN PCNFSAID S ON C.NUMPEDENTFUT = S.NUMPED
 INNER JOIN MOVT7 T7 ON S.NUMTRANSVENDA = T7.NUMTRANSVENDA
   AND M8.CODPROD = T7.CODPROD
 WHERE C.DTCANCEL IS NULL
   AND M8.DTCANCEL IS NULL
   AND C.CONDVENDA = 8
   
   /*AND M8.NUMTRANSITEM  = 627534*/
  /*AND M8.NUMTRANSVENDA IN (10075388, 10075390)*/
   AND S.NUMTRANSVENDA IN (
    10070214
)
  /*AND M8.CODPROD = 799301*/
 ORDER BY M8.NUMTRANSVENDA,
          M8.CODPROD;
/


/*SOMATORIA DOS CUSTOS NOTA MÃE--*/
SELECT *
  FROM VIEW_JC_PCMOV_SAID
 WHERE NUMTRANSACAO = 10070214
   AND TIPOCONTABIL = 'S';
/



/*SOMATÓRIA DOS CUSTOS NOTA FILHO PARA COMPARAR COM A NOTA MÃE--*/
WITH MOVT7 AS (
    SELECT M.NUMTRANSVENDA,
           M.DTMOV AS DTMOV_TV7,
           M.NUMTRANSITEM AS NUMTRANSITEM_TV7,
           M.CODPROD,
           M.CUSTOCONT AS CUSTOCONT_TV7
      FROM PCMOV M
     INNER JOIN PCNFSAID S ON M.NUMTRANSVENDA = S.NUMTRANSVENDA
     WHERE S.CONDVENDA = 7
), VENDATV8 AS (
    SELECT M8.DTMOV,
           T7.DTMOV_TV7,
           M8.NUMTRANSVENDA AS NUMTRANSVENDA_TV8,
           S.NUMTRANSVENDA AS NUMTRANSVENDA_TV7,
           T7.NUMTRANSITEM_TV7,
           M8.CODPROD,
           M8.QTCONT,
           (M8.QTCONT * T7.CUSTOCONT_TV7) VLTOTAL_TV8,
           ROUND (M8.QTCONT * T7.CUSTOCONT_TV7, 2) ARREDTOTAL_TV8,
           M8.CUSTOCONT AS CUSTOCONT_TV8,
           M8.NUMTRANSITEM AS NUMTRANSITEM_TV8,
           T7.CUSTOCONT_TV7
      FROM PCMOV M8
     INNER JOIN PCPEDC C ON M8.NUMTRANSVENDA = C.NUMTRANSVENDA
     INNER JOIN PCNFSAID S ON C.NUMPEDENTFUT = S.NUMPED
     INNER JOIN MOVT7 T7 ON S.NUMTRANSVENDA = T7.NUMTRANSVENDA
       AND M8.CODPROD = T7.CODPROD
     WHERE C.DTCANCEL IS NULL
       AND M8.DTCANCEL IS NULL
       AND C.CONDVENDA = 8
)
SELECT S.CODPROD,
       S.PRODUTO,
       S.QTCONT,
       S.PUNITCONT,
       S.CUSTOCONT,
       S.VLTOTALCUSTOCONT
  FROM VIEW_JC_PCMOV_SAID S
 INNER JOIN VENDATV8 C ON S.NUMTRANSITEM = C.NUMTRANSITEM_TV8
   AND C.NUMTRANSVENDA_TV7 IN (
    10070214
);
/