WITH MOV_SAIDA AS
 (SELECT DISTINCT (NUMTRANSVENDA), MIN(CODFISCAL) AS CFOP_SAIDA
    FROM PCMOV
   WHERE CODFISCAL IN ('5915', '6915')
   GROUP BY NUMTRANSVENDA),

REMESSA_SAIDA AS
 (SELECT S.CODFILIALNF,
         S.CODCLI,
         C.CLIENTE AS FORNECEDOR,
         MAX(S.DTSAIDA) AS ULT_DTSAIDA,
         M.CFOP_SAIDA,
         SUM(S.VLTOTAL) AS VLTOTAL_SAIDA
    FROM PCNFSAID S
   INNER JOIN MOV_SAIDA M
      ON S.NUMTRANSVENDA = M.NUMTRANSVENDA
    LEFT JOIN PCCLIENT C
      ON S.CODCLI = C.CODCLI
   GROUP BY S.CODFILIALNF, S.CODCLI, C.CLIENTE, M.CFOP_SAIDA
  HAVING SUM(S.VLTOTAL) > 0),

MOV_ENTRADA AS
 (SELECT DISTINCT (NUMTRANSENT), MIN(CODFISCAL) AS CFOP_ENT
    FROM PCMOV
   WHERE CODFISCAL IN ('1916', '2916')
   GROUP BY NUMTRANSENT),

REMESSA_ENTRADA AS
 (SELECT E.CODFILIALNF,
         E.CODFORNEC,
         F.FORNECEDOR,
         MAX(E.DTENT) AS ULT_DTENTRADA,
         M.CFOP_ENT,
         SUM(E.VLTOTAL) AS VLTOTAL_ENT,
         F.CODCLI
    FROM PCNFENT E
   INNER JOIN MOV_ENTRADA M
      ON E.NUMTRANSENT = M.NUMTRANSENT
    LEFT JOIN PCFORNEC F
      ON E.CODFORNEC = F.CODFORNEC
   GROUP BY E.CODFILIALNF, E.CODFORNEC, F.FORNECEDOR, M.CFOP_ENT, F.CODCLI)

SELECT *
  FROM (SELECT S.CODFILIALNF,
               S.CODCLI,
               S.FORNECEDOR,
               S.ULT_DTSAIDA,
               S.CFOP_SAIDA,
               S.VLTOTAL_SAIDA,
               E.ULT_DTENTRADA,
               E.CFOP_ENT,
               E.VLTOTAL_ENT,
               (S.VLTOTAL_SAIDA - E.VLTOTAL_ENT) AS DIF
          FROM REMESSA_SAIDA S
          LEFT JOIN REMESSA_ENTRADA E
            ON S.CODCLI = E.CODCLI
           AND S.CODFILIALNF = E.CODFILIALNF
         ORDER BY S.FORNECEDOR, S.CODFILIALNF)
 WHERE DIF NOT IN (0, 0.01, -0.01)
    OR DIF IS NULL
 ORDER BY CODCLI, ULT_DTSAIDA;
/