SELECT E.DTENT,
       (E.CODFORNEC || ' - ' || E.FORNECEDOR) FORNECEDOR,
       (E.ESPECIE || ' - ' || E.NUMNOTA) NOTA,
       B.CODFISCAL CFOP,
       E.UFCODIGO UF,
       E.VLTOTAL,
       E.VLST,
       ROUND((E.VLTOTAL * 0.06), 2) DIFAL
  FROM PCNFENT E
  LEFT JOIN PCNFBASE B ON B.NUMTRANSENT = E.NUMTRANSENT
 WHERE E.DTSAIDA IS NULL
   AND E.ESPECIE = 'NF'
   AND UFCODIGO <> 'SP'
   AND B.CODFISCAL NOT IN (2923, 2949)
   AND DTENT >= TO_DATE('01/01/2023', 'DD/MM/YYYY')
   AND E.VLST <> ROUND((E.VLTOTAL * 0.06), 2);
