SELECT E.DTENT,
       (E.CODFORNEC || ' - ' || E.FORNECEDOR) FORNECEDOR,
       (E.ESPECIE || ' - ' || E.NUMNOTA) NOTA,
       B.CODFISCAL CFOP,
       E.UFCODIGO UF,
       E.VLTOTAL,
       E.VLST,
       ROUND((E.VLTOTAL * 0.07317073), 2) DIFAL
  FROM PCNFENT E
  LEFT JOIN PCNFBASE B ON B.NUMTRANSENT = E.NUMTRANSENT
 WHERE E.DTSAIDA IS NULL  
   AND E.ESPECIE = 'NF'
   AND UFCODIGO <> 'SP'
   AND B.CODFISCAL NOT IN (2910, 2923, 2949)
	 AND E.CODCONT NOT IN (210204)
   AND DTENT >= TO_DATE('01/05/2024', 'DD/MM/YYYY')
   AND E.CODFILIAL NOT IN ('5', '6', '9', '10')
   AND E.VLST <> ROUND((E.VLTOTAL * 0.07317073), 2);
