/*Notas faturadas com CFOP incorreto*/
    SELECT S.CODFILIAL,
           R.DESCRICAO AS REDE,
           S.CODCLI,
           S.CLIENTE,
           C.IEENT,
           S.NUMNOTA,
           M.DTMOV,
           M.CODPROD,
           P.DESCRICAO,
           M.CODFISCAL AS CFOP_NF,
           6108 AS CFOP_CORRETO
      FROM PCMOV M
      LEFT JOIN PCNFSAID S ON M.NUMTRANSVENDA = S.NUMTRANSVENDA
      LEFT JOIN PCCLIENT C ON S.CODCLI = C.CODCLI
      LEFT JOIN PCREDECLIENTE R ON C.CODREDE = R.CODREDE
      LEFT JOIN PCPRODUT P ON M.CODPROD = P.CODPROD
     WHERE C.CONSUMIDORFINAL = 'S'
       AND M.CODFISCAL = '6102'
       AND S.SITUACAONFE = 100
        AND M.DTMOV >= TO_DATE ('01/10/2021', 'DD/MM/YYYY')
       AND M.CODFILIAL IN (2,5,6,7,9,10)
    UNION ALL
    SELECT S.CODFILIAL,
           R.DESCRICAO AS REDE,
           S.CODCLI,
           S.CLIENTE,
           C.IEENT,
           S.NUMNOTA,
           M.DTMOV,
           M.CODPROD,
           P.DESCRICAO,
           M.CODFISCAL AS CFOP_NF,
           6102 AS CFOP_CORRETO
      FROM PCMOV M
      LEFT JOIN PCNFSAID S ON M.NUMTRANSVENDA = S.NUMTRANSVENDA
      LEFT JOIN PCCLIENT C ON S.CODCLI = C.CODCLI
      LEFT JOIN PCREDECLIENTE R ON C.CODREDE = R.CODREDE
      LEFT JOIN PCPRODUT P ON M.CODPROD = P.CODPROD
     WHERE C.CONSUMIDORFINAL = 'N'
       AND M.CODFISCAL = '6108'
       AND S.SITUACAONFE = 100
       AND M.DTMOV >= TO_DATE ('01/10/2021', 'DD/MM/YYYY')
       AND M.CODFILIAL IN (2,5,6,7,9,10)
;/