SELECT T.CODFILIALNF,
       T.CODPROD,
       P.DESCRICAO,
       P.IMPORTADO,
       P.DTCADASTRO
  FROM PCTABTRIB T
  LEFT JOIN PCPRODUT P ON T.CODPROD = P.CODPROD
 WHERE (T.CODST = 0
    OR T.CODTRIBPISCOFINS = 0)
   AND P.DTEXCLUSAO IS NULL;
/