SELECT *
  FROM (
    SELECT TO_NUMBER (TO_CHAR (L.DTCOMPETENCIA, 'YYYY')) AS ANO,
           L.CODCONTA,
           C.CONTA,
           SUM (L.VPAGO) AS VPAGO
      FROM PCLANC L
      LEFT JOIN PCCONTA C ON L.CODCONTA = C.CODCONTA
     WHERE C.GRUPOCONTA IN (
        140, 810
    )
       AND L.DTCOMPETENCIA BETWEEN TO_DATE ('01/01/2018', 'DD/MM/YYYY') AND TO_DATE ('31/12/2021', 'DD/MM/YYYY')
       AND L.DTPAGTO IS NOT NULL
     GROUP BY L.CODCONTA,
              C.CONTA,
              TO_NUMBER (TO_CHAR (L.DTCOMPETENCIA, 'YYYY'))
) PIVOT (
    SUM (VPAGO)
    FOR ANO
    IN (2018, 2019, 2020, 2021)
)
 ORDER BY CODCONTA;
/