SELECT M.CODFILIAL,
       M.DTMOV,
       M.CODPROD,
       P.DESCRICAO,
       M.NUMNOTA,
       M.CODOPER,
       M.QT,
       M.STATUS,
       M.CODFISCAL,
       M.CODST
  FROM PCMOV M, PCPRODUT P
 WHERE P.CODPROD = M.CODPROD
 AND (M.CODST = 3 OR M.CODST = 4)
   AND M.CODFISCAL <> 1152
   AND M.CODOPER = 'ET'
   AND M.CODFILIAL = 7
 ORDER BY DTMOV DESC;