CREATE OR REPLACE VIEW VIEW_JC_FUNCIONARIOS AS
SELECT MATRICULA,
       NOME        AS NOME_COMPLETO,
       NOME_GUERRA AS NOME_APELIDO,
       DTNASC,
       CPF,
       ENDERECO,
       BAIRRO,
       CIDADE,
       ESTADO,
       CEP,
       SITUACAO
  FROM PCEMPR
  WHERE NVL(TIPOCARGO,'T') NOT IN ('O') --RETIRAR FUNCIONARIOS CADASTRADOS QUE NAO EXISTEM FISICAMENTE
  ORDER BY MATRICULA
  ;
