SELECT E.CODFILIAL,
       E.CODPROD,
       (NVL (E.QTESTGER, 0) - NVL (E.QTBLOQUEADA, 0) - NVL (E.QTFRENTELOJA, 0) - NVL (QTRESERV, 0)) QTDISP
  FROM PCEST E
 INNER JOIN PCPRODUT P ON E.CODPROD = P.CODPROD
 WHERE P.DTEXCLUSAO IS NULL
   AND P.CODPROD = P.CODPRODMASTER
   AND E.CODFILIAL IN (
    1, 2, 3, 4, 7
);
/