--CONTA A RECEBER
SELECT P.CODFILIAL,
       P.NUMTRANS,
       P.NUMTRANSVENDA,
       P.DTESTORNO,
       M.DTCOMPENSACAO,
       P.DTPAG,
       P.DUPLIC,
       P.PREST,
       P.CODCOB,
       P.DTBAIXA,
       P.DTVENC,
       P.DTEMISSAO,
       P.CODCLI,
       C.CLIENTE,
       M.CODBANCO,
       B.NOME AS BANCO,
       P.VALOR,
       P.VPAGO
  FROM PCPREST P
 INNER JOIN PCMOVCR M ON P.NUMTRANS = M.NUMTRANS
  LEFT JOIN PCBANCO B ON M.CODBANCO = B.CODBANCO
  LEFT JOIN PCCLIENT C ON P.CODCLI = C.CODCLI
 WHERE TO_NUMBER(EXTRACT(YEAR FROM M.DTCOMPENSACAO) || LPAD(EXTRACT(MONTH FROM M.DTCOMPENSACAO),2,'0')) <>
       TO_NUMBER(EXTRACT(YEAR FROM P.DTPAG) || LPAD(EXTRACT(MONTH FROM P.DTPAG),2,'0'))
   AND M.CODBANCO IN (1, 2, 5, 13, 16, 27, 29, 31, 33, 42, 44, 46, 48, 55)
   --AND P.CODCLI NOT IN (25053)
   AND M.CODCOB = 'D'
   AND TO_NUMBER(EXTRACT(YEAR FROM P.DTPAG) ||  LPAD(EXTRACT(MONTH FROM P.DTPAG),2,'0')) >= 202406
 ORDER BY P.DTPAG DESC;
/
--UPDATE PCPREST
MERGE
  INTO PCPREST P
  USING (
  SELECT P.NUMTRANSVENDA, P.PREST, P.DTPAG, M.DTCOMPENSACAO
    FROM PCPREST P
   INNER JOIN PCMOVCR M ON P.NUMTRANS = M.NUMTRANS
    LEFT JOIN PCBANCO B ON M.CODBANCO = B.CODBANCO
    LEFT JOIN PCCLIENT C ON P.CODCLI = C.CODCLI
   WHERE TO_NUMBER(EXTRACT(YEAR FROM M.DTCOMPENSACAO) || LPAD(EXTRACT(MONTH FROM M.DTCOMPENSACAO),2,'0')) <>
       TO_NUMBER(EXTRACT(YEAR FROM P.DTPAG) || LPAD(EXTRACT(MONTH FROM P.DTPAG),2,'0'))
   AND M.CODBANCO IN (1, 2, 5, 13, 16, 27, 29, 31, 33, 42, 44, 46, 48, 55)
   AND M.CODCOB = 'D'
   AND TO_NUMBER(EXTRACT(YEAR FROM P.DTPAG) ||  LPAD(EXTRACT(MONTH FROM P.DTPAG),2,'0')) >= 202406) X 
 ON (P.NUMTRANSVENDA = X.NUMTRANSVENDA AND P.PREST = X.PREST) 
 WHEN MATCHED 
	 THEN UPDATE SET P.DTPAG = X.DTCOMPENSACAO;
/
--CONTAS A PAGAR
  SELECT --L.ROWID,
   L.CODFILIAL,
   L.NUMTRANS,
   L.RECNUM,
   M.DTCOMPENSACAO,
   L.DTPAGTO,
   L.CODFORNEC,
   M.CODBANCO,
   B.NOME AS BANCO,
   L.CODCONTA,
   L.VALOR,
   L.VPAGO
    FROM PCLANC L
   INNER JOIN PCMOVCR M ON L.NUMTRANS = M.NUMTRANS
    LEFT JOIN PCBANCO B ON M.CODBANCO = B.CODBANCO
   WHERE TO_NUMBER(TO_CHAR(M.DTCOMPENSACAO, 'YYYY') ||
                   TO_CHAR(M.DTCOMPENSACAO, 'MM')) <>
         TO_NUMBER(TO_CHAR(L.DTPAGTO, 'YYYY') || TO_CHAR(L.DTPAGTO, 'MM'))
     AND M.CODBANCO IN
         (1, 2, 5, 13, 16, 27, 29, 31, 33, 42, 44, 46, 48, 55)
     AND M.CODCOB = 'D'
     AND L.CODCONTA NOT IN (4001, 4102)
     AND TO_NUMBER(TO_CHAR(L.DTPAGTO, 'YYYY') || TO_CHAR(L.DTPAGTO, 'MM')) >
         202405
     AND L.DTESTORNOBAIXA IS NULL
     AND M.DTESTORNO IS NULL
  --AND L.NUMTRANS = 266138
   ORDER BY L.DTPAGTO DESC;
/
--UPDATE PCLANC
MERGE
  INTO PCLANC L
  USING (
  SELECT L.CODFILIAL,
         L.RECNUM,
         L.NUMTRANS,
         M.DTCOMPENSACAO,
         L.DTPAGTO,
         L.CODFORNEC,
         M.CODBANCO,
         B.NOME AS BANCO,
         L.CODCONTA,
         L.VALOR,
         L.VPAGO
    FROM PCLANC L
   INNER JOIN PCMOVCR M ON L.NUMTRANS = M.NUMTRANS
    LEFT JOIN PCBANCO B ON M.CODBANCO = B.CODBANCO
   WHERE TO_NUMBER(TO_CHAR(M.DTCOMPENSACAO, 'YYYY') ||
                   TO_CHAR(M.DTCOMPENSACAO, 'MM')) <>
         TO_NUMBER(TO_CHAR(L.DTPAGTO, 'YYYY') || TO_CHAR(L.DTPAGTO, 'MM'))
     AND M.CODBANCO IN
         (1, 2, 5, 13, 16, 27, 29, 31, 33, 42, 44, 46, 48, 55)
     AND M.CODCOB = 'D'
     AND L.CODCONTA NOT IN (4001, 4102)
     AND TO_NUMBER(TO_CHAR(L.DTPAGTO, 'YYYY') || TO_CHAR(L.DTPAGTO, 'MM')) >
         202405
     AND L.DTESTORNOBAIXA IS NULL
     AND M.DTESTORNO IS NULL) X ON (L.RECNUM = X.RECNUM) WHEN MATCHED THEN UPDATE SET L.DTPAGTO = X.DTCOMPENSACAO;
/
