------- ENCONTRAR O NUMPED A PARTIR DO NUMPEDWEB (INFORMADO NO SITE DA PAGAR.ME)------
SELECT C.NUMPED, C.* FROM PCPEDC C WHERE NUMPEDRCA = 37161501;


------- ENCONTRAR NUMNOTA
SELECT C.NUMNOTA, C.* FROM PCNFSAID C WHERE NUMPED = 37050623;


------- ENCONTRAR O NUMTRANS QUE É O AGRUPAMENTO DE DUPLICATAS BAIXADAS------
SELECT P.NUMTRANS, P.* FROM PCPREST P WHERE  CODCLI = 25037 AND DUPLIC = 69483;


------- ENCONTRAR A DATA DE COMPENSACAO QUE A DUPLICATA FOI CONCILIADA------
SELECT C.DTCOMPENSACAO, C.* FROM PCMOVCR C WHERE NUMTRANS IN (58837, 59878);


------- VER TODAS AS DUPLICATAS QUE FORAM CONCILIADAS COM DATA DE COMPETENCIA IGUAL A INFORMADA NA PESQUISA------
SELECT C.NUMTRANS, C.* FROM PCMOVCR C WHERE DTCOMPENSACAO = TO_DATE ('03/07/2018', 'DD/MM/YYYY') AND C.CODBANCO = 11;

------- VER TODAS AS DUPLICATAS DENTRO DO NUMTRANS QUE É O AGRUPAMENTO DE DUPLICATAS BAIXADAS------
SELECT P.NUMTRANS,
       P.DTEMISSAO,
       P.CODCLI,
       P.DUPLIC,
       P.PREST,
       P.CODCOBORIG,
       P.CODCOB,
       P.VALORORIG,
       P.VALOR,
       P.VALORDESC,
       P.VPAGO,
       P.NSUTEF,
       P.NSUHOST,
       P.DTVENC,
       P.DTPAG,
       P.DTBAIXA,
       P.CODBANCO,
       P.CODCOBBANCO
  FROM PCPREST P
 WHERE NUMTRANS = 59222;