WITH VLDEBITO AS
 (SELECT CODBANCO, SUM(NVL(VALOR, 0)) AS VLDEBITO
    FROM PCMOVCR
   WHERE TIPO = 'D'
     AND CODCOB = 'D'
     AND CODBANCO IN (17, 20, 35, 50, 52, 53)
   GROUP BY CODBANCO),
VLCREDITO AS
 (SELECT CODBANCO, SUM(NVL(VALOR, 0)) AS VLCREDITO
    FROM PCMOVCR
   WHERE TIPO = 'C'
     AND CODCOB = 'D'
     AND CODBANCO IN (17, 20, 35, 50, 52, 53)
   GROUP BY CODBANCO)
SELECT *
  FROM (SELECT B.CODBANCO,
               B.NOME AS CAIXA,
               D.VLDEBITO,
               C.VLCREDITO,
               (D.VLDEBITO - C.VLCREDITO) AS SALDO
          FROM PCBANCO B
         INNER JOIN VLDEBITO D
            ON B.CODBANCO = D.CODBANCO
         INNER JOIN VLCREDITO C
            ON B.CODBANCO = C.CODBANCO)
 WHERE SALDO <> 0;