WITH FORNECEDOR AS (
    SELECT CODFORNEC,
           FORNECEDOR
      FROM PCFORNEC
), CLIENTE AS (
    SELECT CODCLI,
           CLIENTE
      FROM PCCLIENT
)
SELECT L.CODFILIAL,
       L.RECNUM,
       L.DTLANC,
       L.TIPOPARCEIRO AS TIPO,
       L.CODFORNEC,
       (
           CASE
               WHEN L.TIPOPARCEIRO = 'C' THEN C.CLIENTE
               WHEN L.TIPOPARCEIRO = 'F' THEN F.FORNECEDOR
               ELSE NULL
           END
       ) FORNECEDOR_CLIENTE,
       L.NUMNOTA,
       L.VPAGO,
       L.HISTORICO,
       L.CODCONTA,
       T.CONTA,
       L.NUMBANCO,
       B.NOME AS BANCO,
       L.CODFUNCBAIXA AS CODFUNC,
       E.NOME_GUERRA
  FROM PCLANC L
  LEFT JOIN PCBANCO B ON L.NUMBANCO = B.CODBANCO
  LEFT JOIN PCEMPR E ON L.CODFUNCBAIXA = E.MATRICULA
  LEFT JOIN FORNECEDOR F ON L.CODFORNEC = F.CODFORNEC
  LEFT JOIN CLIENTE C ON L.CODFORNEC = C.CODCLI
  LEFT JOIN PCCONTA T ON L.CODCONTA = T.CODCONTA
 WHERE L.DTESTORNOBAIXA IS NULL
   AND L.CODROTINABAIXA = 631
   AND L.DTLANC >= TRUNC (SYSDATE) - 3
   AND (B.CODBACEN = 'MARKETPLACE' OR B.CODBANCO = 12)
 ORDER BY L.NUMBANCO,
          L.DTLANC;
/