/*BAIXA RECEBIMENTO PIX LOJAS EM ABERTO--*/
SELECT T.CODFILIAL, 
       T.DTEMISSAO,
       T.DUPLIC,
       T.PREST,
       T.CODCOB,
       T.VALOR,
       T.DTVENC,
       T.NSUPAGDIGITAL
  FROM PCPREST T
 WHERE CODCOB = 'PIXL'
   AND DTPAG IS NULL;
/