SELECT CODFILIAL,
       CODCLI,
       DTEMISSAO,
       DUPLIC,
       PREST,
       VALOR,
       DTVENC,
       CODUSUR
  FROM PCPREST
 WHERE CODCLI IN (
    8630, 13106
)
   AND DTPAG IS NULL
   AND DTVENC < TRUNC (SYSDATE) + 7;
/