SELECT L.RECNUM,
       L.CODFILIAL,
       L.DTLANC,
       L.DTVENC,
       L.CODFORNEC,
       F.FORNECEDOR,
       L.NUMNOTA,
       L.DUPLIC,
       L.HISTORICO,
       L.HISTORICO2
  FROM PCLANC L
  LEFT JOIN PCFORNEC F
    ON L.CODFORNEC = F.CODFORNEC
 WHERE L.DTCANCEL IS NULL
   AND L.DTPAGTO IS NULL
   AND F.CODFORNECPRINC = 2
 ORDER BY L.DTVENC