WITH ADIANTAMENTO AS
 (SELECT L.CODFILIAL,
         SUM(L.VPAGO) VALOR_ADIANTADO
    FROM PCLANC L
    JOIN PCMOVCR M ON L.NUMTRANS = M.NUMTRANS
   WHERE L.DTCANCEL IS NULL
     AND L.DTESTORNOBAIXA IS NULL
     AND M.DTESTORNO IS NULL
     AND M.CODROTINALANC NOT IN (1209)
     AND L.ADIANTAMENTO = 'S'
     AND L.CODFILIAL IN ('5', '6', '9', '10')
     AND L.CODFORNEC IN (1, 7543)
   GROUP BY L.CODFILIAL),

BAIXA_ADIANTAMENTO AS
 (SELECT L.CODFILIAL,
         SUM(L.VPAGO) AS VALOR_BAIXADO
    FROM PCLANC L
    JOIN PCLANCADIANTFORNEC C ON L.RECNUM = C.RECNUMPAGTO
   WHERE L.DTCANCEL IS NULL
     AND L.DTESTORNOBAIXA IS NULL
     AND L.NUMTRANS IS NULL
     AND L.CODFILIAL IN ('5', '6', '9', '10')
     AND L.CODFORNEC IN (1, 7543)
   GROUP BY L.CODFILIAL),

VALOR_ABERTO AS
 (SELECT L.CODFILIAL,
         SUM(L.VALOR - NVL(L.VALORDEV, 0) - NVL(L.DESCONTOFIN, 0)) VALOR_A_PAGAR
    FROM PCLANC L
   WHERE L.CODFILIAL IN ('5', '6', '9', '10')
     AND L.CODFORNEC IN (1, 7543)
     AND L.DTPAGTO IS NULL
   GROUP BY L.CODFILIAL),

SALDO_ADIANTAMENTO AS
 (SELECT A.CODFILIAL,
         (A.VALOR_ADIANTADO - B.VALOR_BAIXADO) SALDO_ADIANTADO,
         V.VALOR_A_PAGAR
    FROM ADIANTAMENTO A
    LEFT JOIN BAIXA_ADIANTAMENTO B ON B.CODFILIAL = A.CODFILIAL
    LEFT JOIN VALOR_ABERTO V ON V.CODFILIAL = A.CODFILIAL),

CREDITO AS
 (SELECT CODCLI,
         SUM(VALOR) AS VALOR_CREDITO
    FROM PCCRECLI
   WHERE DTDESCONTO IS NULL
   GROUP BY CODCLI),

DUPLICATA AS
 (SELECT CODCLI,
         SUM(VALOR) AS VALOR_PREST
    FROM PCPREST T
   WHERE T.DTPAG IS NULL
   GROUP BY CODCLI)
SELECT F.CODIGO,
       C.CODCLI,
       T.CLIENTE,
       C.VALOR_CREDITO,
       D.VALOR_PREST,
       S.SALDO_ADIANTADO,
       S.VALOR_A_PAGAR,
       (C.VALOR_CREDITO - S.SALDO_ADIANTADO) DIF_CREDITO_ADIANTAMENTO,
       (D.VALOR_PREST - S.VALOR_A_PAGAR) DIF_ARECEBER_APAGAR
  FROM CREDITO C
  LEFT JOIN DUPLICATA D ON C.CODCLI = D.CODCLI
  JOIN PCCLIENT T ON C.CODCLI = T.CODCLI
  LEFT JOIN PCFILIAL F ON F.CODCLI = C.CODCLI
  LEFT JOIN SALDO_ADIANTAMENTO S ON S.CODFILIAL = F.CODIGO
 WHERE C.VALOR_CREDITO > 0
   AND C.CODCLI IN (401409, 400430, 18633, 17427);
