WITH ADIANTAMENTO AS
 (SELECT L.CODFILIAL,
         SUM(L.VPAGO) VALOR_ADIANTADO
    FROM PCLANC L
    JOIN PCMOVCR M ON L.NUMTRANS = M.NUMTRANS
   WHERE L.DTCANCEL IS NULL
     AND L.DTESTORNOBAIXA IS NULL
     AND M.DTESTORNO IS NULL
     AND M.CODROTINALANC NOT IN (1209)
     AND L.ADIANTAMENTO = 'S'
     AND L.CODFILIAL IN ('5', '6', '9', '10')
     AND L.CODFORNEC IN (1, 7543, 9505)
   GROUP BY L.CODFILIAL),

BAIXA_ADIANTAMENTO AS
 (SELECT L.CODFILIAL,
         SUM(L.VPAGO) AS VALOR_BAIXADO
    FROM PCLANC L
    JOIN PCLANCADIANTFORNEC C ON L.RECNUM = C.RECNUMPAGTO
   WHERE L.DTCANCEL IS NULL
     AND L.DTESTORNOBAIXA IS NULL
     AND L.NUMTRANS IS NULL
     AND L.CODFILIAL IN ('5', '6', '9', '10')
     AND L.CODFORNEC IN (1, 7543, 9505)
   GROUP BY L.CODFILIAL),

VALOR_PAGAR AS
 (SELECT L.CODFILIAL,
         SUM(L.VALOR - NVL(L.VALORDEV, 0) - NVL(L.DESCONTOFIN, 0)) VALOR_A_PAGAR
    FROM PCLANC L
   WHERE L.CODFILIAL IN ('5', '6', '9', '10')
     AND L.CODFORNEC IN (1, 7543, 9505)
     AND L.DTPAGTO IS NULL
   GROUP BY L.CODFILIAL),

SALDO_ADIANTAMENTO AS
 (SELECT A.CODFILIAL,
         (NVL(A.VALOR_ADIANTADO, 0) - NVL(B.VALOR_BAIXADO, 0)) SALDO_ADIANTADO
    FROM ADIANTAMENTO A
    LEFT JOIN BAIXA_ADIANTAMENTO B ON B.CODFILIAL = A.CODFILIAL),

CREDITO AS
 (SELECT CODCLI,
         SUM(VALOR) AS VALOR_CREDITO
    FROM PCCRECLI
   WHERE DTDESCONTO IS NULL
   GROUP BY CODCLI),

VERBA_DEBITO AS
 (SELECT M.CODFILIAL,
         SUM(M.VALOR) VALOR_VERBA_DEBITO
    FROM PCMOVCRFOR M
   WHERE M.CODFILIAL IN ('5', '6', '9', '10')
     AND M.CODFORNEC IN (1, 7543, 9505)
     AND M.TIPO = 'D'
     AND M.DTCOMPETENCIA IS NULL
   GROUP BY M.CODFILIAL),

VERBA_CREDITO AS
 (SELECT M.CODFILIAL,
         SUM(M.VALOR) VALOR_VERBA_CREDITO
    FROM PCMOVCRFOR M
   WHERE M.CODFILIAL IN ('5', '6', '9', '10')
     AND M.CODFORNEC IN (1, 7543, 9505)
     AND M.TIPO = 'C'
     AND M.DTCOMPETENCIA IS NULL
   GROUP BY M.CODFILIAL),

VERBA AS
 (SELECT M.CODFILIAL,
         COALESCE(MAX(D.VALOR_VERBA_DEBITO) - MAX(C.VALOR_VERBA_CREDITO),
                  SUM(M.VALOR)) VALOR_VERBA
    FROM PCMOVCRFOR M
    LEFT JOIN VERBA_DEBITO D ON M.CODFILIAL = D.CODFILIAL
    LEFT JOIN VERBA_CREDITO C ON M.CODFILIAL = C.CODFILIAL
   WHERE M.CODFILIAL IN ('5', '6', '9', '10')
     AND M.CODFORNEC IN (1, 7543, 9505)
     AND M.DTCOMPETENCIA IS NULL
   GROUP BY M.CODFILIAL),

DUPLICATA AS
 (SELECT CODCLI,
         SUM(VALOR) AS VALOR_PREST
    FROM PCPREST T
   WHERE T.DTPAG IS NULL
   GROUP BY CODCLI)

SELECT F.CODIGO CODFILIAL,
       C.CODCLI,
       T.CLIENTE,
       NVL(C.VALOR_CREDITO, 0) VALOR_CREDITO,
       NVL(D.VALOR_PREST, 0) VALOR_PREST,
       NVL(V.VALOR_VERBA, 0) VALOR_VERBA,
       NVL(S.SALDO_ADIANTADO, 0) + NVL(V.VALOR_VERBA, 0) SALDO_ADIANTADO_MAIS_VERBA,
       NVL(P.VALOR_A_PAGAR, 0) VALOR_A_PAGAR,
       (NVL(C.VALOR_CREDITO, 0) - NVL(S.SALDO_ADIANTADO, 0) -
       NVL(V.VALOR_VERBA, 0)) DIF_CREDITO_ADIANTAMENTO,
       (NVL(D.VALOR_PREST, 0) - NVL(P.VALOR_A_PAGAR, 0)) DIF_ARECEBER_APAGAR
  FROM CREDITO C
  LEFT JOIN DUPLICATA D ON C.CODCLI = D.CODCLI
  JOIN PCCLIENT T ON C.CODCLI = T.CODCLI
  LEFT JOIN PCFILIAL F ON F.CODCLI = C.CODCLI
  LEFT JOIN SALDO_ADIANTAMENTO S ON S.CODFILIAL = F.CODIGO
  LEFT JOIN VALOR_PAGAR P ON P.CODFILIAL = F.CODIGO
  LEFT JOIN VERBA V ON V.CODFILIAL = F.CODIGO
 WHERE C.VALOR_CREDITO > 0
   AND C.CODCLI IN (401409, 400430, 18633, 17427);
