SELECT R.DATA,
       R.CODBANCO,
       B.NOME BANCO,
       C.COBRANCA,
       (CASE R.TIPO
         WHEN 'C' THEN
          NVL(ROUND(R.VALOR,2) * -1,0)
         WHEN 'D' THEN
          NVL(ROUND(R.VALOR,2),0)
         ELSE NVL(ROUND(R.VALOR,2),0)
       END) VALOR,
       R.HISTORICO,
       R.HISTORICO2,
       R.VLSALDO,
       E.NOME_GUERRA FUNCIONARIO,
       R.CODROTINALANC ROTINA
  FROM PCMOVCR R, PCBANCO B, PCCOB C, PCEMPR E
 WHERE B.CODBANCO = R.CODBANCO
   AND C.CODCOB = R.CODCOB
   AND R.CODFUNC = E.MATRICULA
   AND R.CODBANCO = 16
   AND R.DATA > TRUNC(SYSDATE) - 3
 ORDER BY R.DATA;