/* 8056 - RELATORIO DE CONTAS A PAGAR PERIODO - SINTETICO  */
SELECT :PERIODOINI,
       :PERIODOFIM,
       :PERIODOINI || ' à ' || :PERIODOFIM AS PERIODOVENCIMENTO,
       :CODFILIAL,
       L.RECNUM,
       L.DTLANC,
       L.NUMNOTA,
       L.DUPLIC,
       L.CODCONTA,
       C.CONTA,
       L.MOEDA,
       L.DTVENC,
       L.DTPAGTO,
       L.VALOR,
       CASE
         WHEN L.DTPAGTO IS NOT NULL THEN
          (NVL(L.VALOR, 0) + NVL(L.VALORDEV, 0) + NVL(L.TXPERM, 0)) -
          (NVL(L.DESCONTOFIN, 0) - NVL(L.VLVARIACAOCAMBIAL, 0))
         ELSE
          NULL
       END VPAGO,
       L.VPAGOBORDERO,
       L.TXPERM,
       L.DESCONTOFIN,
       L.VALORDEV,
       L.VLVARIACAOCAMBIAL,
       L.TIPOPARCEIRO,
       L.CODFORNEC,
       F.FORNECEDOR,
       F.CGC CNPJ_FORNECEDOR,
       L.CODFILIAL,
       L.TIPOLANC,
       L.NUMTRANSENT,
       L.NUMTRANSVENDA,
       L.HISTORICO,
       L.HISTORICO2,
       L.NUMTRANS,
       L.CODROTINACAD,
       I.RAZAOSOCIAL,
       I.CGC CNPJ_FILIAL,
       T.VALOR_SOMA,
       T.TXPERM_SOMA,
       T.VPAGO_SOMA,
       T.DESCONTOFIN_SOMA
  FROM PCLANC L,
       PCFORNEC F,
       PCCONTA C,
       PCFILIAL I,
       (SELECT L2.CODFILIAL,
               L2.CODFORNEC,
               SUM(L2.VALOR) VALOR_SOMA,
               SUM(CASE
                     WHEN L2.DTPAGTO IS NOT NULL THEN
                      (NVL(L2.VALOR, 0) + NVL(L2.VALORDEV, 0) + NVL(L2.TXPERM, 0)) -
                      (NVL(L2.DESCONTOFIN, 0) - NVL(L2.VLVARIACAOCAMBIAL, 0))
                     ELSE
                      NULL
                   END) VPAGO_SOMA,
               SUM(L2.TXPERM) TXPERM_SOMA,
               SUM(L2.DESCONTOFIN) DESCONTOFIN_SOMA
          FROM PCLANC L2, PCFORNEC F2, PCCONTA C2, PCFILIAL I2
         WHERE 1 = 1
           AND L2.CODFORNEC = F2.CODFORNEC
           AND L2.CODCONTA = C2.CODCONTA
           AND L2.CODFILIAL = I2.CODIGO
           AND L2.TIPOLANC = 'C'
           AND L2.VALOR > 0
           AND L2.CODFILIAL IN (:CODFILIAL)
           AND L2.CODFORNEC IN (:CODFORNEC)
           AND L2.DTVENC BETWEEN TO_DATE(:PERIODOINI, 'DD/MM/YYYY') AND
               TO_DATE(:PERIODOFIM, 'DD/MM/YYYY')
           AND ((SELECT COUNT(1)
                   FROM PCDESDLANC D2
                  WHERE D2.RECNUMORIG = L2.RECNUM
                    AND D2.DTDESD <= TO_DATE(:PERIODOFIM, 'DD/MM/YYYY')) = 0)
           AND ((L2.DTPAGTO IS NULL) OR
               (L2.DTPAGTO >= TO_DATE(:PERIODOINI, 'DD/MM/YYYY')))
           AND L2.DTLANC < TO_DATE(:PERIODOINI, 'DD/MM/YYYY')
         GROUP BY L2.CODFILIAL, L2.CODFORNEC) T
WHERE 1 = 1
   AND L.CODFORNEC = F.CODFORNEC
   AND L.CODCONTA = C.CODCONTA
   AND L.CODFILIAL = I.CODIGO
   AND L.TIPOLANC = 'C'
   AND L.VALOR > 0
   AND L.CODFILIAL IN (:CODFILIAL)
   AND L.CODFORNEC IN (:CODFORNEC)
   AND T.CODFILIAL = L.CODFILIAL
   AND T.CODFORNEC = L.CODFORNEC
   AND L.DTVENC BETWEEN TO_DATE(:PERIODOINI, 'DD/MM/YYYY') AND
       TO_DATE(:PERIODOFIM, 'DD/MM/YYYY')
   AND ((SELECT COUNT(1)
           FROM PCDESDLANC D
          WHERE D.RECNUMORIG = L.RECNUM
            AND D.DTDESD <= TO_DATE(:PERIODOFIM, 'DD/MM/YYYY')) = 0)
   AND ((L.DTPAGTO IS NULL) OR
       (L.DTPAGTO >= TO_DATE(:PERIODOINI, 'DD/MM/YYYY')))
   AND L.DTLANC < TO_DATE(:PERIODOINI, 'DD/MM/YYYY')
ORDER BY L.CODFILIAL, L.CODFORNEC, L.DTLANC, L.DTVENC;