SELECT P.CODFILIAL,
       P.DTVENC,
       P.DTPAG,
       P.CODCLI,
       C.CLIENTE,
       P.DUPLIC,
       P.PREST,
       P.VALORORIG,
       P.VALOR,
       P.VPAGO,
       P.OBS,
       P.CODCOBORIG,
       P.CODCOB,
       P.CODBANCO,
       B.NOME BANCO,
       P.CODCOBBANCO MOEDA,
       P.CODBAIXA CODFUNC,
       E.NOME FUNCIONARIO
  FROM PCPREST P, PCCLIENT C, PCBANCO B, PCEMPR E
 WHERE P.CODCLI = C.CODCLI
   AND P.CODBANCO = B.CODBANCO
   AND P.CODBAIXA = E.MATRICULA
   AND P.CODBANCO = 17
   AND (P.CODCOBORIG <> 'BNF' OR P.CODCOBORIG  IS NULL)
   AND P.DTPAG > TRUNC (SYSDATE)-30
   ORDER BY P.DTPAG;