/* 8055 - RELATORIO DE CONTAS A RECEBER PERIODO  */
SELECT :PERIODOINI,
       :PERIODOFIM,
       :PERIODOINI || ' à ' || :PERIODOFIM AS PERIODOVENCIMENTO,
       :CODFILIAL,
       P.CODFILIAL,
       P.NUMTRANSVENDA,
       P.PREST,
       P.DTEMISSAO,
       P.DUPLIC,
       P.CODCLI,
       C.CLIENTE,
       P.DTVENC,
       P.DTBAIXA,
       P.DTPAG,
       NVL(P.VALOR, 0) VALOR,
       NVL(P.VPAGO, 0) VPAGO,
       NVL(P.VALORDESC, 0) VALORDESC,
       NVL(P.VALORORIG, 0) VALORORIG,
       NVL(P.VLDEVOL, 0) VLDEVOL,
       NVL(TAB_SOMA.VALOR_SOMA, 0) VALOR_SOMA,
       NVL(TAB_SOMA.VPAGO_SOMA, 0) VPAGO_SOMA,
       NVL(TAB_SOMA.VALORDESC_SOMA, 0) VALORDESC_SOMA,
       NVL(TAB_SOMA.VALORORIG_SOMA, 0) VALORORIG_SOMA,
       NVL(TAB_SOMA.VLDEVOL_SOMA, 0) VLDEVOL_SOMA,
       P.CODCOB,
       NVL(P.TXPERM, 0) TXPERM,
       NVL(TAB_SOMA.TXPERM_SOMA, 0) TXPERM_SOMA,
       P.NUMTRANS,
       I.RAZAOSOCIAL,
       I.CGC         CNPJ_FILIAL
  FROM PCPREST P,
       PCCLIENT C,
       PCFILIAL I,
       (SELECT P2.CODFILIAL,
               P2.CODCLI,
               SUM(NVL(P2.VALOR, 0)) VALOR_SOMA,
               SUM(NVL(P2.VPAGO, 0)) VPAGO_SOMA,
               SUM(NVL(P2.VALORDESC, 0)) VALORDESC_SOMA,
               SUM(NVL(P2.VALORORIG, 0)) VALORORIG_SOMA,
               SUM(NVL(P2.VLDEVOL, 0)) VLDEVOL_SOMA,
               SUM(NVL(P2.TXPERM, 0)) TXPERM_SOMA
          FROM PCPREST P2, PCCLIENT C2, PCFILIAL I2
         WHERE 1 = 1
           AND P2.CODCLI = C2.CODCLI
           AND P2.CODFILIAL = I2.CODIGO
           AND P2.CODCLI IN (:CODCLI)
           AND P2.CODFILIAL IN (:CODFILIAL)
           AND P2.DTVENC BETWEEN TO_DATE(:PERIODOINI, 'DD/MM/YYYY') AND
               TO_DATE(:PERIODOFIM, 'DD/MM/YYYY')
           AND ((P2.CODCOB <> 'DESD') OR
               (P2.CODCOB = 'DESD' AND
               P2.DTDESD <= TO_DATE(:PERIODOFIM, 'DD/MM/YYYY')))
           AND ((P2.DTPAG IS NULL) OR
               (P2.DTPAG >= TO_DATE(:PERIODOINI, 'DD/MM/YYYY')))
           AND P2.DTEMISSAO < TO_DATE(:PERIODOINI, 'DD/MM/YYYY')
         GROUP BY P2.CODFILIAL, P2.CODCLI) TAB_SOMA
WHERE 1 = 1
   AND P.CODCLI = C.CODCLI
   AND P.CODFILIAL = I.CODIGO
   AND P.CODFILIAL = TAB_SOMA.CODFILIAL
   AND P.CODCLI = TAB_SOMA.CODCLI
   AND P.CODCLI IN (:CODCLI)
   AND P.CODFILIAL IN (:CODFILIAL)
   AND P.DTVENC BETWEEN TO_DATE(:PERIODOINI, 'DD/MM/YYYY') AND
       TO_DATE(:PERIODOFIM, 'DD/MM/YYYY')
   AND ((P.CODCOB <> 'DESD') OR
       (P.CODCOB = 'DESD' AND
       P.DTDESD <= TO_DATE(:PERIODOFIM, 'DD/MM/YYYY')))
   AND ((P.DTPAG IS NULL) OR (P.DTPAG >= TO_DATE(:PERIODOINI, 'DD/MM/YYYY')))
   AND P.DTEMISSAO < TO_DATE(:PERIODOINI, 'DD/MM/YYYY')
ORDER BY P.CODFILIAL, P.CODCLI, P.DTVENC;