WITH TRANSACAO_DNI AS (
    SELECT M.DTCOMPENSACAO,
           M.CODBANCO,
           M.NUMTRANS
      FROM PCMOVCR M
     WHERE M.CODCOB = 'DNI'
)
SELECT D.DTCOMPENSACAO,
       T.DTPAG,
       T.DTBAIXA,
       T.CODCLI,
       C.CLIENTE,
       T.DUPLIC,
       T.PREST,
       T.VALOR,
       T.VPAGO,
       D.CODBANCO,
       B.NOME AS BANCO,
       T.CODBAIXA AS CODFUNCBAIXA
  FROM PCPREST T
 INNER JOIN TRANSACAO_DNI D ON T.NUMTRANS = D.NUMTRANS
  LEFT JOIN PCCLIENT C ON T.CODCLI = C.CODCLI
  LEFT JOIN PCBANCO B ON D.CODBANCO = B.CODBANCO
 WHERE TO_CHAR (D.DTCOMPENSACAO, 'MM') <> TO_CHAR (T.DTPAG, 'MM')
   AND D.DTCOMPENSACAO BETWEEN TO_DATE ('01/01/2021', 'DD/MM/YYYY') AND TO_DATE ('31/01/2021', 'DD/MM/YYYY');
/