SELECT *
  FROM (SELECT P.CODFILIAL AS FILIAL,
               PCUSUARI.CODUSUR,
               PCUSUARI.NOME RCA,
               C.CODCLI,
               C.CLIENTE CLIENTE,
               P.NUMTRANSVENDA,
               P.DUPLIC || '-' || P.PREST DUPLIC,
               P.DTEMISSAO EMISSAO,
               P.DTVENC VENCIMENTO,
               P.CODCOB,
               PCCOB.COBRANCA,
               P.VALOR,
               P.CARTORIO
          FROM PCPREST P, PCCLIENT C, PCCOB, PCSUPERV, PCUSUARI, PCEMPR
         WHERE P.CODCLI = C.CODCLI
           AND P.DTPAG IS NULL
           AND P.CODSUPERVISOR = PCSUPERV.CODSUPERVISOR
           AND P.CODAGENTECOBRANCA = PCEMPR.MATRICULA(+)
           AND P.CODUSUR = PCUSUARI.CODUSUR
           AND P.CODCOB = PCCOB.CODCOB
           AND P.CODCOB NOT IN
               ('DBFU', 'DEBM', 'CH', 'DH', 'PEND', 'DEVP', 'DEVT', 'PERD')
           AND NOT EXISTS
         (SELECT C.CODCOB FROM PCCOB C WHERE C.CODCOBCC = PCCOB.CODCOB)
           AND NVL(PCCOB.CARTAO, 'N') = 'N'
           AND P.DTVENC <= TRUNC(SYSDATE) - [DATA]
           AND P.DTVENC >= TRUNC(SYSDATE) - [DATAINI]
           AND ((P.CODFILIAL IN ([FILIAL])) OR ('99' IN ([FILIAL])))
           AND P.DTFECHA IS NOT NULL
           AND NOT EXISTS
         (SELECT PCHISTCOBI.NUMTRANSVENDA
                  FROM PCHISTCOB, PCHISTCOBI
                 WHERE PCHISTCOB.NUMREGCOB = PCHISTCOBI.NUMREGCOB
                   AND PCHISTCOBI.NUMTRANSVENDA = P.NUMTRANSVENDA
                   AND PCHISTCOBI.PREST = P.PREST))
 ORDER BY VENCIMENTO DESC, CLIENTE;