SELECT PCBANCO.CODFILIAL FILIAL,
       PCESTCR.DTULTCONCILIA,
       PCBANCO.CODBANCO || ' - ' || PCBANCO.NOME BANCO,
       PCMOEDA.CODMOEDA || ' - ' || PCMOEDA.MOEDA MOEDA,
       PCESTCR.VALORCONCILIADO VALORCONCILIADO
  FROM PCBANCO, PCMOEDA, PCESTCR
 WHERE PCESTCR.CODBANCO = PCBANCO.CODBANCO
   AND PCESTCR.CODCOB = PCMOEDA.CODMOEDA
   AND PCESTCR.CODCOB IN ('SANG', 'SUPR')
   AND PCESTCR.VALORCONCILIADO <> 0
 ORDER BY PCBANCO.CODBANCO, PCESTCR.DTULTCONCILIA