CREATE OR REPLACE VIEW VIEW_JC_LANC_GERENCIAL AS
    WITH PCMOV_NUMTRANSENT AS
/*TODAS AS MOVIMENTACOES DA PCMOV PARA DESCONSIDERAR POSTERIORMENTE*/ (
        SELECT DISTINCT (NUMTRANSENT)
          FROM PCMOV
    ), NOTAS_DESPESAS_FISCAIS AS (
        SELECT E.CODFORNEC,
               E.NUMNOTA
          FROM PCNFENT E
          LEFT JOIN PCMOV_NUMTRANSENT M ON E.NUMTRANSENT = M.NUMTRANSENT
         WHERE E.DTCANCEL IS NULL
     /*NAO TRAZER NOTAS CANCELADAS*/
           AND M.NUMTRANSENT IS NULL
     /*NAO TRAZER NOTAS COM MOVIMENTACAO NA PCMOV*/
           AND E.ESPECIE NOT IN (
            'OE', 'NE', 'TP'
        )
    )
    SELECT L.CODFILIAL,
           L.RECNUM,
           L.DTCOMPETENCIA AS DATA,
           L.VALOR,
           C.GRUPOCONTA,
           L.CODCONTA,
           (
               CASE
                   WHEN (L.NUMNOTA IS NULL
                       OR L.NUMNOTA = 0) THEN L.HISTORICO
                   ELSE ('NFS ' || L.NUMNOTA || ' - ' || L.HISTORICO)
               END
           ) AS HISTORICO,
           L.CODFORNEC,
           C.CONTACONTABIL
      FROM PCLANC L
      LEFT JOIN PCCONTA C ON L.CODCONTA = C.CODCONTA
      LEFT JOIN PCFORNEC F ON L.CODFORNEC = F.CODFORNEC
       AND L.TIPOPARCEIRO = 'F'
      LEFT JOIN NOTAS_DESPESAS_FISCAIS D ON L.CODFORNEC = D.CODFORNEC
       AND L.NUMNOTA = D.NUMNOTA
       AND L.TIPOPARCEIRO = 'F'
     WHERE L.DTCANCEL IS NULL
     /*NAO CONSIDERAR LANCAMENTOS CANCELADOS*/
       AND L.DTESTORNOBAIXA IS NULL
     /*NAO CONSIDERAR LANCAMENTOS ESTORNADOS  */
       AND (L.TIPOLANC = 'C'
        OR L.DTPAGTO IS NOT NULL)
     /*SOMENTE LANÇAMENTOS CONFIRMADOS OU PAGOS*/
       AND (D.CODFORNEC IS NULL
       AND D.NUMNOTA IS NULL)
       AND L.TIPOPARCEIRO = 'F'
     /*RETIRAR DESPESAS QUE JÁ ESTEJAM NO LIVRO FISCAL*/
       AND L.CODCONTA NOT IN (
        200133, 200139
    )
     /*RETIRAR LANCAMENTOS DE ADIANTAMENTO FORNECEDOR*/
       AND L.VALOR > 0
       AND (L.CODCONTA IN (
        810101, 810102, 810103
    )
        OR F.OBS2 = 'DESP');
/