CREATE OR REPLACE VIEW VIEW_JC_LANC_GERENCIAL AS
WITH LANC_ROTINA631 AS --PARA CONSIDERAR LANCAMENTOS DA 631 APENAS NOTAS DE COMISSAO OU CARTAO CREDITO
 (SELECT RECNUM
    FROM PCLANC
   WHERE NUMBANCO NOT IN (40, 41)
     AND CODROTINABAIXA = 631),
LANC_DESD AS --CONSIDERAR APENAS LANCAMENTO INICIAL QUANDO HÁ DESDOBRAMENTO
 (SELECT RECNUM
    FROM PCLANC
   WHERE DTDESD IS NOT NULL
     AND LOCALIZACAO IS NOT NULL)
SELECT L.CODFILIAL,
       L.RECNUM,
       L.DTLANC,
       L.DTCOMPETENCIA,
       L.DTVENC,
       C.CONTACONTABIL AS CONTADEBITO,       
       C.GRUPOCONTA, --PARA FILTRO DENTRO DO POWER QUERY
       L.CODCONTA,
	   L.NUMNOTA,
       (CASE WHEN L.TIPOPARCEIRO = 'C' THEN NVL(F.CODFORNEC, L.CODFORNEC) ELSE L.CODFORNEC END) AS CODFORNEC,
       (CASE WHEN (L.NUMNOTA IS NULL OR L.NUMNOTA = 0) THEN L.HISTORICO ELSE ('NSº '|| L.NUMNOTA ||' - ' || L.HISTORICO) END) AS HISTORICO,
       L.VALOR,
       (CASE
         WHEN L.TIPOLANC = 'C' THEN
          'CONFIRMADO'
         WHEN L.TIPOLANC = 'P' THEN
          'PROVISIONADO'
         WHEN L.TIPOLANC IS NULL THEN
          CASE
            WHEN DTPAGTO IS NULL THEN
             'PROVISIONADO'
            ELSE
             'CONFIRMADO'
          END
       END) AS TIPOLANC
  FROM PCLANC L
  LEFT JOIN PCCONTA C
    ON L.CODCONTA = C.CODCONTA
  LEFT JOIN PCFORNEC F --PARA TERMOS O CODFORNEC QUANDO O LANCAMENTO FOR EM CLIENTE
    ON L.CODFORNEC = F.CODCLI
  LEFT JOIN LANC_ROTINA631 R
    ON L.RECNUM = R.RECNUM
  LEFT JOIN LANC_DESD D
    ON L.RECNUM = D.RECNUM
 WHERE L.DTCANCEL IS NULL --NAO CONSIDERAR LANCAMENTOS CANCELADOS
   AND L.DTESTORNOBAIXA IS NULL --NAO CONSIDERAR LANCAMENTOS ESTORNADOS  
   --NAO CONSIDERAR LANCAMENTOS DE NOTAS DE COMPRA DE MERCADORIA, ICMS, ADIANTAMENTOS, CTES, RECEITAS E DESPESAS FINANCEIRAS, VERBAS, IMPOSTOS E DIV
   AND C.GRUPOCONTA NOT IN (100, 101, 140, 200, 420, 580, 610, 620, 650, 680, 820) 
   AND L.VALOR > 0 --NAO CONSIDERAR LANCAMENTOS DE RECEITA
   AND L.TIPOPARCEIRO NOT IN ('O') --CONSIDERAR SOMENTE FORNECEDORES
   AND L.CODFORNEC NOT IN (1, 7543) --NAO CONSIDERAR O FORNECEDOR JC BROTHERS
   AND R.RECNUM IS NULL --CONSIDERAR APENAS LANCAMENTOS DE CARTAO E COMISSAO NA ROTINA 631
   AND D.RECNUM IS NULL --CONSIDERAR APENAS O LANCAMENTO INICIAL QUE SOFREU DESDOBRAMENTO 
   AND NVL(F.CODFORNEC, L.CODFORNEC) IS NOT NULL; --NÃO TRAZER REGISTROS EM BRANCO    
/