/*-------------CONSULTA CUSTO REAL + ICMS DOS PRODUTOS------------*/
SELECT CUSTOREP
  FROM PCEST
 WHERE CODFILIAL = 2
   AND CODPROD IN (
    805561, 805562
);
/

/*---------ATUALIZAÇÃO DO CUSTO REAL + ICMS PARA INSUMOS----------------*/
UPDATE PCEST
   SET
    CUSTOREP = 1
 WHERE CODFILIAL = 2
   AND CODPROD IN (
    805561, 805562
);
/