CREATE OR REPLACE VIEW VIEW_JC_DEVCLIENTE_DESCPREST AS
SELECT T.CODFILIALNF AS CODFILIAL,
       T.DTPAG AS DATA,
       T.VPAGO AS VALOR,
       C.CODCONTAB AS CODCONTAB_CLI,
       T.CODUSUR,
       E.NUMNOTA AS NUMNOTA_DEV,
       (CASE
         WHEN T.CODCOB = 'DEVT' THEN
          'BAIXA TOTAL NFD ' || E.NUMNOTA || ' - DUPLIC - ' || T.DUPLIC || '-' ||
          T.PREST || ' - ' || C.CLIENTE
         ELSE
          'BAIXA PARCIAL NFD ' || E.NUMNOTA || ' - DUPLIC - ' || T.DUPLIC || '-' ||
          T.PREST || ' - ' || C.CLIENTE
       END) AS HISTORICO
  FROM PCPREST T
  LEFT JOIN PCCLIENT C
    ON T.CODCLI = C.CODCLI
  LEFT JOIN PCNFENT E
    ON T.NUMTRANSENTDEVCLI = E.NUMTRANSENT
 WHERE T.DTCANCEL IS NULL
   AND T.CODCOB IN ('DEVT', 'DEVP')
   AND VALOR > 0
 ORDER BY T.DTPAG DESC;