/*CREATE OR REPLACE VIEW VIEW_JC_DEVCLIENTE_CREDITO AS*/
WITH NUMTRANSCLIDEV1400 AS
     /*REGISTROS DESDOBRADOS PELA ROTINA 1400*/
 (
    SELECT L.CODIGO
      FROM PCCRECLI L
     WHERE L.NUMTRANSENTDEVCLI IS NOT NULL
       AND L.CODROTINA = 1400
       AND L.DTESTORNO IS NOT NULL
), NUMTRANSCLIDEV_DEVOLUCOES AS
     /*REGISTROS CRIADOS A PARTIR DAS ROTINA DE DEVOLUÇÃO*/
 (
    SELECT L.CODIGO
      FROM PCCRECLI L
     WHERE L.NUMTRANSENTDEVCLI IS NOT NULL
       AND L.CODROTINA IN (
        1303, 1346, 1360
    )
       AND L.HISTORICO LIKE 'DESDOBRAMENTO EM BAIXA%'
), CFOPMOV AS (
    SELECT NUMTRANSENT,
           MAX (CODFISCAL) CFOP
      FROM PCMOV
     GROUP BY NUMTRANSENT
), VER_DTLANC_DTDESC_BAIXA_DUPLIC AS (
    SELECT CODIGO,
           (
               CASE
                   WHEN ((MES_DTDESCONTO <> MES_DTLANC)
                      AND DTESTORNO IS NOT NULL
                      AND HISTORICO LIKE '%REF. DIF. NA BAIXA CR%') THEN 1
                   ELSE 0
               END
           ) AS VERIFICAR_DATA
      FROM (
        SELECT L.CODIGO,
               L.HISTORICO,
               TO_NUMBER (TO_CHAR (L.DTDESCONTO, 'YYYY') || TO_CHAR (L.DTDESCONTO, 'MM')) AS MES_DTDESCONTO,
               TO_NUMBER (TO_CHAR (L.DTLANC, 'YYYY') || TO_CHAR (L.DTLANC, 'MM')) AS MES_DTLANC,
               L.DTESTORNO
          FROM PCCRECLI L
    )
), VER_DTLANC_DTDESC_BAIXA_DIN AS (
    SELECT CODIGO,
           (
               CASE
                   WHEN ((MES_DTDESCONTO <> MES_DTLANC)
                      AND DTESTORNO IS NOT NULL
                      AND HISTORICO LIKE 'devolucao-EST BX%') THEN 1
                   ELSE 0
               END
           ) AS VERIFICAR_DATA
      FROM (
        SELECT L.CODIGO,
               L.HISTORICO,
               TO_NUMBER (TO_CHAR (L.DTDESCONTO, 'YYYY') || TO_CHAR (L.DTDESCONTO, 'MM')) AS MES_DTDESCONTO,
               TO_NUMBER (TO_CHAR (L.DTLANC, 'YYYY') || TO_CHAR (L.DTLANC, 'MM')) AS MES_DTLANC,
               L.DTESTORNO
          FROM PCCRECLI L
    )
)

/*SELECT * FROM (*/
SELECT L.CODFILIAL,
       E.NUMNOTA AS NUMNOTA_DEV,
       (
           CASE
               WHEN VERIFICAR_DATA = 1 THEN L.DTLANC
               ELSE L.DTDESCONTO
           END
       ) AS DATA,
       L.CODIGO,
       L.NUMLANCBAIXA,
       (
           CASE
               WHEN L.VALOR < 0 THEN (L.VALOR * - 1)
               ELSE L.VALOR
           END
       ) AS VALOR,
       C.CODCONTAB AS CODCONTAB_CLI,
       0 AS CODCONTAB_BANCO,
       (
           CASE
               WHEN (L.NUMTRANSVENDADESC IS NOT NULL
                   OR VERIFICAR_DATA = 1) THEN 'C'
               ELSE 'R'
           END
       ) AS TIPO,
       (
           CASE
               WHEN (L.NUMTRANSVENDADESC IS NOT NULL
                   OR VERIFICAR_DATA = 1) THEN 'BAIXA CRED NFD ' || E.NUMNOTA || ' - DUPLIC - ' || L.NUMNOTADESC || ' - ' || C.CLIENTE
               ELSE 'RECEITA CRED NFD ' || E.NUMNOTA || ' - ' || C.CLIENTE
           END
       ) AS HISTORICO
  FROM PCCRECLI L
  LEFT JOIN PCCLIENT C ON L.CODCLI = C.CODCLI
  LEFT JOIN PCNFENT E ON L.NUMTRANSENTDEVCLI = E.NUMTRANSENT
  LEFT JOIN CFOPMOV M ON L.NUMTRANSENTDEVCLI = M.NUMTRANSENT
  LEFT JOIN VER_DTLANC_DTDESC_BAIXA_DUPLIC V ON L.CODIGO = V.CODIGO
  LEFT JOIN NUMTRANSCLIDEV1400 R ON L.CODIGO = R.CODIGO
  LEFT JOIN NUMTRANSCLIDEV_DEVOLUCOES D ON L.CODIGO = D.CODIGO
 WHERE L.NUMTRANSENTDEVCLI IS NOT NULL
     /*SOMENTE REGISTROS ORIUNDOS DE DEVOLUÇÃO DE CLIENTE*/
   AND (L.NUMTRANSVENDADESC IS NOT NULL
    OR L.NUMLANCBAIXA IS NOT NULL
    OR VERIFICAR_DATA = 1)
     /*DESCONTO NO A RECEBER OU BAIXA COMO RECEITA*/
   AND L.DTDESCONTO IS NOT NULL
     /*SOMENTE LANÇAMENTOS UTILIZADOS*/
   AND M.CFOP NOT IN (
    1913, 2913
)
     /*RETIRAR OS LANCAMENTOS GERADOS POR RETORNO DE AMOSTRA DE SHOWROOM*/
   AND R.CODIGO IS NULL
     /*DESCONSIDERAR OS REGISTROS QUE FORAM DESDOBRADOS PELA 1400 */
   AND D.CODIGO IS NULL
     /*DESCONSIDERAR OS REGISTROS QUE FORAM DESDOBRADOS PELA ROTINAS DE DEVOLUCAO*/
UNION ALL
SELECT L.CODFILIAL,
       E.NUMNOTA AS NUMNOTA_DEV,
       (
           CASE
               WHEN VERIFICAR_DATA = 1 THEN L.DTLANC
               ELSE L.DTDESCONTO
           END
       ) AS DATA,
       L.CODIGO,
       L.NUMLANCBAIXA,
       (
           CASE
               WHEN L.VALOR < 0 THEN (L.VALOR * - 1)
               ELSE L.VALOR
           END
       ) AS VALOR,
       '' AS CODCONTAB_CLI,
       B.CODCONTABIL AS CODCONTAB_BANCO,
       'D' AS TIPO,
       ('PAG CRED NFD ' || E.NUMNOTA || ' - ' || C.CLIENTE) AS HISTORICO
  FROM PCCRECLI L
  LEFT JOIN PCCLIENT C ON L.CODCLI = C.CODCLI
  LEFT JOIN PCMOVCR V ON L.NUMTRANSBAIXA = V.NUMTRANS
  LEFT JOIN PCBANCO B ON V.CODBANCO = B.CODBANCO
  LEFT JOIN PCNFENT E ON L.NUMTRANSENTDEVCLI = E.NUMTRANSENT
  LEFT JOIN CFOPMOV M ON L.NUMTRANSENTDEVCLI = M.NUMTRANSENT
  LEFT JOIN VER_DTLANC_DTDESC_BAIXA_DIN F ON L.CODIGO = F.CODIGO
  LEFT JOIN NUMTRANSCLIDEV1400 R ON L.CODIGO = R.CODIGO
  LEFT JOIN NUMTRANSCLIDEV_DEVOLUCOES D ON L.CODIGO = D.CODIGO
 WHERE L.NUMTRANSENTDEVCLI IS NOT NULL
     /*SOMENTE REGISTROS ORIUNDOS DE DEVOLUÇÃO DE CLIENTE*/
   AND L.NUMTRANSVENDADESC IS NULL
     /*RETIRAR REGISTROS QUE FORAM APLICADOS COMO DESCONTO NO CONTAS A RECEBER*/
   AND (L.NUMTRANSBAIXA IS NOT NULL
    OR F.VERIFICAR_DATA = 1)
     /*SOMENTE REGISTROS QUE FORAM BAIXADO EM BANCOS MOV NUMERARIOS*/
   AND L.DTDESCONTO IS NOT NULL
     /*SOMENTE LANÇAMENTOS UTILIZADOS*/
   AND M.CFOP NOT IN (
    1913, 2913
)
     /*RETIRAR OS LANCAMENTOS GERADOS POR RETORNO DE AMOSTRA DE SHOWROOM*/
   AND R.CODIGO IS NULL
     /*DESCONSIDERAR OS REGISTROS QUE FORAM DESDOBRADOS PELA 1400 */
   AND D.CODIGO IS NULL
     /*DESCONSIDERAR OS REGISTROS QUE FORAM DESDOBRADOS PELA ROTINAS DE DEVOLUCAO*/
/*)
WHERE NUMNOTA_DEV IN (103157, 209200 )*/;