CREATE OR REPLACE VIEW VIEW_JC_DEVCLIENTE_RECEITAPAG AS
SELECT L.CODFILIAL,
       L.RECNUM,
       (CASE
         WHEN L.VPAGO < 0 THEN
          (L.VPAGO * -1)
         ELSE
          L.VPAGO
       END) VALOR,
       L.DTPAGTO AS DATA,
       L.CODCONTA,
       B.CODCONTABIL AS CODCONTAB_BANCO,
       L.NUMTRANS,
       C.CODUSUR1 AS CODUSUR,
       (CASE
         WHEN L.NUMTRANS IS NULL THEN
          'R'
         ELSE
          'D'
       END) AS TIPO,
       (CASE
         WHEN L.NUMTRANS IS NULL THEN
          'RECEITA NFD ' || L.NUMNOTA || ' - ' || C.CLIENTE || ' - ' ||
          L.HISTORICO
         ELSE
          'PAG NFD ' || L.NUMNOTA || ' - ' || C.CLIENTE || ' - ' ||
          L.HISTORICO
       END) AS HISTORICO
  FROM PCLANC L
  LEFT JOIN PCMOVCR M
    ON L.NUMTRANS = M.NUMTRANS
  LEFT JOIN PCBANCO B
    ON M.CODBANCO = B.CODBANCO
  LEFT JOIN PCCLIENT C
    ON L.CODFORNEC = C.CODCLI
 WHERE L.DTCANCEL IS NULL --RETIRAR REGISTROS CANCELADOS
   AND (L.CODROTINACAD LIKE '%1346%' OR L.CODROTINACAD LIKE '%1303%' OR
       L.CODROTINACAD LIKE '%1360%') --BUSCAR LANCAMENTOS ORIUNDOS DAS DEVOLUCOES APENAS
   AND (L.HISTORICO NOT LIKE '%SHOW ROOM%' AND
       L.HISTORICO NOT LIKE '%SHOWROOM%' AND
       L.HISTORICO NOT LIKE '%AMOSTRA%' AND
       L.HISTORICO NOT LIKE '%AMOSTRAS%') --RETIRAR OS LANCAMENTOS GERADOS POR RETORNO DE AMOSTRA DE SHOWROOM
;