CREATE OR REPLACE VIEW VIEW_JC_DEVCLIENTE_CREDITO AS
WITH NUMTRANSCLIDEV_DEVOLUCOES AS
--REGISTROS CRIADOS A PARTIR DAS ROTINA DE DEVOLUÇÃO OU ROTINA 1400
 (SELECT L.CODIGO AS CODCRED
    FROM PCCRECLI L
   WHERE L.NUMTRANSENTDEVCLI IS NOT NULL
     AND L.HISTORICO LIKE 'DESDOBRAMENTO EM BAIXA%'
     AND L.CODROTINA IN (1303, 1346, 1360, 1400)),
CFOPMOV AS
 (SELECT NUMTRANSENT, MAX(CODFISCAL) CFOP FROM PCMOV GROUP BY NUMTRANSENT),
CODIGO_POR_MES_ANO AS
 (SELECT L.CODIGO AS CODCRED,
         TO_NUMBER(EXTRACT (YEAR FROM L.DTDESCONTO) || EXTRACT (MONTH FROM L.DTDESCONTO)) AS MES_DTDESCONTO,
         TO_NUMBER(EXTRACT (YEAR FROM L.DTESTORNO) || EXTRACT (MONTH FROM L.DTESTORNO)) AS MES_DTESTORNO,
         TO_NUMBER(EXTRACT (YEAR FROM L.DTLANC) || EXTRACT (MONTH FROM L.DTLANC)) AS MES_DTLANC
    FROM PCCRECLI L
   WHERE L.NUMTRANSENTDEVCLI IS NOT NULL),
VER_DTLANC_DTDESC_BAIXA_DUPLIC AS
 (SELECT L.CODCRED,
         (CASE
           WHEN ((L.MES_DTDESCONTO <> L.MES_DTLANC) AND
                L.MES_DTESTORNO IS NOT NULL) THEN
            1
           ELSE
            0
         END) AS VERIFICAR_DATA
    FROM CODIGO_POR_MES_ANO L),
PCCRECLI_BASE AS
 (SELECT L.CODFILIAL,
         E.NUMNOTA,
         A.MES_DTDESCONTO,
         A.MES_DTLANC,
         A.MES_DTESTORNO,
         L.DTESTORNO,
         L.DTLANC,
         L.DTDESCONTO,
         L.CODIGO AS CODCRED,
         L.CODROTINA,
         L.ROTINABAIXA,
         L.ROTINAESTORNO,
         L.ROTINAINSERT,
         L.NUMLANCBAIXA,
         L.NUMTRANSENTDEVCLI,
         L.NUMTRANSVENDADESC,
         L.NUMTRANSBAIXA,
         L.VALOR AS VALOR_ORIG,
         (CASE
           WHEN L.VALOR < 0 THEN
            (L.VALOR * -1)
           ELSE
            L.VALOR
         END) AS VALOR,
         C.CODCONTAB AS CODCONTAB_CLI,
         B.CODCONTABIL AS CODCONTAB_BANCO,
         L.HISTORICO,
         L.NUMNOTADESC,
         C.CLIENTE
    FROM PCCRECLI L
    LEFT JOIN PCPREST P ON P.NUMTRANSVENDA = L.NUMTRANSVENDADESC AND P.PREST = L.PRESTRESTCLI
    LEFT JOIN PCCLIENT C ON C.CODCLI = P.CODCLI
    LEFT JOIN PCNFENT E ON L.NUMTRANSENTDEVCLI = E.NUMTRANSENT
    LEFT JOIN PCMOVCR CR ON L.NUMTRANSBAIXA = CR.NUMTRANS
    LEFT JOIN PCBANCO B ON CR.CODBANCO = B.CODBANCO
    LEFT JOIN CFOPMOV M ON L.NUMTRANSENTDEVCLI = M.NUMTRANSENT
    LEFT JOIN NUMTRANSCLIDEV_DEVOLUCOES D ON L.CODIGO = D.CODCRED
    LEFT JOIN CODIGO_POR_MES_ANO A ON L.CODIGO = A.CODCRED
   WHERE L.NUMTRANSENTDEVCLI IS NOT NULL
        --SOMENTE REGISTROS ORIUNDOS DE DEVOLUÇÃO DE CLIENTE
     AND L.DTDESCONTO IS NOT NULL
        --SOMENTE LANÇAMENTOS UTILIZADOS
     AND NOT (L.HISTORICO LIKE 'DESDOBRAMENTO EM BAIXA%')
        --RETIRAR LANÇAMENTOS DE DESDOBRAMENTO
     AND NOT (L.ROTINABAIXA LIKE '%619%' AND L.CODROTINA = 1209)
     AND M.CFOP NOT IN (1913, 2913)
        --RETIRAR OS LANCAMENTOS GERADOS POR RETORNO DE AMOSTRA DE SHOWROOM
     AND D.CODCRED IS NULL
  --DESCONSIDERAR OS REGISTROS QUE FORAM DESDOBRADOS PELA 1400 E ROTINAS DE DEVOLUÇÃO 
  )
SELECT B.CODFILIAL,
       B.NUMNOTA,
       /*(CASE
         WHEN V.VERIFICAR_DATA = 1 THEN
          B.DTLANC
         ELSE
          B.DTDESCONTO
       END) AS DATA,*/
			 B.DTDESCONTO AS DATA,
       B.CODCRED,
       B.NUMLANCBAIXA,
       B.VALOR,
       B.CODCONTAB_CLI,
       0 AS CODCONTAB_BANCO,
       (CASE
         WHEN B.NUMTRANSVENDADESC IS NOT NULL THEN
          'C'
         WHEN B.ROTINABAIXA LIKE '%1286%' THEN
          'C'
         ELSE
          'R'
       END) AS TIPO,
       (CASE
         WHEN (B.NUMTRANSVENDADESC IS NOT NULL OR
              B.ROTINABAIXA LIKE '%1286%') THEN
          'BAIXA CRED NFD ' || B.NUMNOTA || ' - DUPLIC - ' || B.NUMNOTADESC ||
          ' - ' || B.CLIENTE
         ELSE
          'RECEITA CRED NFD ' || B.NUMNOTA || ' - ' || B.CLIENTE
       END) AS HISTORICO
  FROM PCCRECLI_BASE B
  LEFT JOIN VER_DTLANC_DTDESC_BAIXA_DUPLIC V ON B.CODCRED = V.CODCRED
 WHERE (B.VALOR_ORIG > 0 OR (B.CODROTINA = 619 AND B.VALOR_ORIG < 0))
   AND B.NUMTRANSBAIXA IS NULL
      --RETIRAR LANCAMENTOS TIPO R QUE NÃO MOVIMENTARAM NUMERARIOS E NAO GERARAM LANCAMENTOS NA PCLANC
   AND (CASE
         WHEN B.NUMTRANSVENDADESC IS NOT NULL THEN
          1
         WHEN B.ROTINABAIXA LIKE '%1286%' THEN
          1
         WHEN B.NUMLANCBAIXA IS NOT NULL THEN
          1
         ELSE
          0
       END) = 1
   AND NOT (NVL(B.ROTINAESTORNO, '0') LIKE '%1316%' OR
        NVL(B.ROTINAESTORNO, '0') LIKE '%1409%' OR
        NVL(B.ROTINAESTORNO, '0') LIKE '%ORACLE.EXE%' OR
        (NVL(B.ROTINAINSERT, '0') LIKE '%ORACLE.EXE%' AND
        B.ROTINAESTORNO IS NOT NULL) OR
        (NVL(B.ROTINAINSERT, '0') LIKE '%1286%' AND
        NVL(B.ROTINAESTORNO, '0') LIKE '%619%' AND
        NVL(B.ROTINABAIXA, '0') LIKE '%619%') OR
        (NVL(B.ROTINAINSERT, '0') LIKE '%1402%' AND
        NVL(B.ROTINAESTORNO, '0') LIKE '%619%' AND
        NVL(B.ROTINABAIXA, '0') LIKE '%619%') OR
        (NVL(B.ROTINAINSERT, '0') LIKE '%1303%' AND
        NVL(B.ROTINAESTORNO, '0') LIKE '%1402%' AND
        NVL(B.ROTINABAIXA, '0') LIKE '%1402%'))
--RETIRAR LANÇAMENTOS BAIXADO EM BANCOS PARA EVITAR DUPLICIDADE

UNION ALL
SELECT B.CODFILIAL,
       B.NUMNOTA,
       (CASE
         WHEN V.VERIFICAR_DATA = 1 THEN
          B.DTLANC
         ELSE
          B.DTDESCONTO
       END) AS DATA,
       B.CODCRED,
       B.NUMLANCBAIXA,
       B.VALOR,
       '' AS CODCONTAB_CLI,
       B.CODCONTAB_BANCO,
       (CASE
         WHEN (B.ROTINABAIXA LIKE '%1286%' OR NVL(B.ROTINABAIXA, '1303') = '1303') THEN
          'C'
         ELSE
          'D'
       END) AS TIPO,
       (CASE
         WHEN (B.ROTINABAIXA LIKE '%1286%' OR NVL(B.ROTINABAIXA, '1303') = '1303') THEN
          'BAIXA CRED NFD ' || B.NUMNOTA || ' - DUPLIC - ' || B.NUMNOTADESC ||
          ' - ' || B.CLIENTE
         ELSE
          'PAG CRED NFD ' || B.NUMNOTA || ' - ' || B.CLIENTE
       END) AS HISTORICO
  FROM PCCRECLI_BASE B
  LEFT JOIN VER_DTLANC_DTDESC_BAIXA_DUPLIC V ON B.CODCRED = V.CODCRED
 WHERE B.NUMTRANSBAIXA IS NOT NULL
UNION ALL
SELECT B.CODFILIAL,
       B.NUMNOTA,
       B.DTDESCONTO AS DATA,
       B.CODCRED,
       B.NUMLANCBAIXA,
       B.VALOR,
       B.CODCONTAB_CLI,
       B.CODCONTAB_BANCO,
       'E' AS TIPO,
       ('ESTORNO BAIXA CRED NFD ' || B.NUMNOTA || ' - DUPLIC - ' ||
       B.NUMNOTADESC || ' - ' || B.CLIENTE) AS HISTORICO
  FROM PCCRECLI_BASE B
 WHERE (B.CODROTINA = 1209 AND B.ROTINABAIXA LIKE '%1209%') AND
 B.VALOR_ORIG < 0;
