----PCCLIENT
SELECT * FROM PCCLIENT C WHERE C.CLIENTE LIKE '%ASTRA%';


----PCCRECLI
SELECT ROWID, C.* FROM PCCRECLI C WHERE DTDESCONTO >= TRUNC(SYSDATE) - 20 AND CODFILIAL = '7' AND CODROTINA = 619 ORDER BY CODCLI;
SELECT ROWID, C.* FROM PCCRECLI C WHERE C.NUMCRED IN (743211) ORDER BY C.NUMCRED;
SELECT ROWID, C.* FROM PCCRECLI C WHERE C.NUMTRANSENTDEVCLI IN (496720) ORDER BY C.NUMCRED;
SELECT ROWID, C.* FROM PCCRECLI C WHERE C.CODCLI = 426170 ORDER BY C.CODIGO;
SELECT ROWID, C.* FROM PCCRECLI C WHERE C.NUMNOTADESC = 14418 ORDER BY C.CODIGO;


----PCLANC
SELECT ROWID, L. * FROM PCLANC L WHERE L.CODFILIAL = '9' AND L.CODCONTA = 610199 AND L.DTLANC = '20/01/2023';
SELECT ROWID, L. * FROM PCLANC L WHERE L.RECNUM IN (2334741);


----PCMOVCR
SELECT ROWID, M.* FROM PCMOVCR M WHERE M.NUMTRANS IN (302266);


----PCMOV
SELECT M.NUMTRANSENT, M.DESCRICAO, M.* FROM PCMOV M WHERE M.NUMTRANSDEV IN (11587876);
SELECT M.NUMTRANSENT, M.NUMTRANSVENDA, M.DESCRICAO, M.CODFISCAL, M.* FROM PCMOV M WHERE M.CODPROD IN (815022) AND CODFILIAL = '2' AND CODOPER = 'ER';
SELECT M.NUMTRANSENT, M.NUMTRANSVENDA, M.DESCRICAO, M.CODFISCAL, M.* FROM PCMOV M WHERE M.NUMNOTA IN (317491) AND CODFILIAL = '7';
SELECT M.DESCRICAO, M.* FROM PCMOV M WHERE M.NUMTRANSVENDA = 11440794;
SELECT M.NUMTRANSDEV, M.DESCRICAO, M.CODFISCAL, M.* FROM PCMOV M WHERE M.NUMTRANSENT IN (489005);


----PCNFENT
SELECT E.VLFRETE, E.FORNECEDOR, E.* FROM PCNFENT E WHERE E.NUMTRANSENT IN (489005);
SELECT E.* FROM PCNFENT E WHERE E.NUMNOTA = 3976;


----PCNFSAID
SELECT S.VLFRETE, S.* FROM PCNFSAID S WHERE S.NUMTRANSVENDA = 11440794;
SELECT S.NUMTRANSVENDA, S.* FROM PCNFSAID S WHERE S.CODFILIAL = '9' AND S.CODCLI = 459656 AND S.DTSAIDA >= TRUNC(SYSDATE) - 180;
SELECT S.NUMTRANSVENDA, S.* FROM PCNFSAID S WHERE S.CODFILIAL = '7' AND S.NUMNOTA IN (317949);


-----PCPREST
SELECT ROWID, P.CODBANCO, P. * FROM PCPREST P WHERE P.NUMTRANS IN (302266);
SELECT P.NUMTRANSVENDA, P.* FROM PCPREST P WHERE P.CODFILIAL = '7' AND P.DUPLIC = 340752;
SELECT P.NUMTRANSVENDA, P.* FROM PCPREST P WHERE P.DTPAG IS NULL AND  P.NUMTRANSVENDA IN (11458872);
