/*ANALISE DE FORNECEDORES*/
SELECT ROWID, CODFORNEC, FORNECEDOR, F.CGC, F.* FROM PCFORNEC F WHERE CODFORNEC IN (362, 10210); --8864
SELECT ROWID, F.OBS2,  F.CODCONTAB,  F.* FROM PCFORNEC F WHERE F.CODFORNEC = 10170;
SELECT ROWID, F.OBS2, F.* FROM PCFORNEC F WHERE F.OBS2 = 'GOV';
SELECT F.ROWID, F.CODCLI, F. * FROM PCFORNEC F WHERE F.FORNECEDOR LIKE '%FFJ%';
SELECT F.CODCLI, F. * FROM PCCLIENT F WHERE F.CLIENTE LIKE '%JC BROTHERS%';
SELECT * FROM PCCLIENT F WHERE F.CLIENTE LIKE '%TRAVAGIN%';
SELECT * FROM PCCLIENT WHERE CODCLI = 36628;

SELECT ROWID,  L. * FROM PCLANC L WHERE CODFORNEC = 8965 AND TIPOPARCEIRO = 'F' AND CODFILIAL = 2 ORDER BY DTPAGTO;

SELECT B.ROWID,  B.* FROM BROKERCONTABIL B WHERE CODFORNEC IN (65722, 10008);

SELECT  B.ROWID, B.* FROM BROKERCONTABIL B WHERE CODCONTAB IN (1290) ORDER BY CODFORNEC, CODFILIAL;

SELECT CODFORNEC, COUNT(CODCONTAB)
  FROM BROKERCONTABIL
 WHERE CODFILIAL = 10
 GROUP BY CODFORNEC
HAVING COUNT(CODCONTAB) > 1;


SELECT TO_CHAR(TO_DATE('01-JAN-2000', 'DD-MON-YYYY') + ROWNUM - 1,
               'DD/MM/YYYY') AS "Data"
  FROM DUAL --DBA_TABLES
 WHERE ROWNUM <= TO_DATE('31-JAN-2016', 'DD-MON-YYYY') -
       TO_DATE('01-JAN-2000', 'DD-MON-YYYY') + 1;


WITH P(DATA) AS
 (SELECT TO_DATE('01/01/2022', 'DD/MM/YYYY') DATA
    FROM DUAL
  UNION ALL
  SELECT TRUNC(P.DATA) + 1
    FROM P
   WHERE P.DATA < TO_DATE('15/01/2022', 'DD/MM/YYYY'))
SELECT P.DATA FROM P;

