--DUPLICATAS ANALÍTICO
SELECT P.ROWID,
       NUMCHEQUE,
       P.CODBANCO,
       C.CLIENTE,
       P.VALORESTORNO,
       P.PRESTTEF,
       P.NUMTRANSVENDA,
       P.NUMTRANS,
       P.OBSTITULO,
       P.DTPAG,
       P.NSUHOST, 
       P.NSUTEF,
       P.DTTRANSACAOCC,
       P.NUMRESUMO,
       P.PDV,
       P.CODBAIXACARTAOREDE,
       P.DTFECHA,
       P.*
  FROM PCPREST P
  LEFT JOIN PCCLIENT C ON P.CODCLI = C.CODCLI --08/05/2023 - FALTA DEVOLUÇÃO - FAVOR VERIFICAR
 WHERE P.NUMTRANSVENDA IN (11674578)
 ORDER BY DUPLIC, TO_NUMBER(PREST);

--CREDITOS_ABERTOS
WITH TRANSACAO_VENDA_DEVOLVIDA AS
 (SELECT NUMTRANSENT, MAX(M.NUMTRANSDEV) AS NUMTRANSVENDA
    FROM PCMOV M
   WHERE NVL(NUMTRANSDEV, 0) <> 0
     AND NVL(NUMTRANSDEV, 0) <> 0
   GROUP BY NUMTRANSENT)
SELECT (C.CODCLI || '-' || T.CLIENTE) CLIENTE,
       C.VALOR AS VALOR_CREDITO,
       C.DTLANC DTLANC_CRED,
       D.NUMTRANSVENDA
  FROM PCCRECLI C
  JOIN PCCLIENT T ON C.CODCLI = T.CODCLI
  JOIN TRANSACAO_VENDA_DEVOLVIDA D ON C.NUMTRANSENTDEVCLI = D.NUMTRANSENT
 WHERE T.CODCLI = 481973;

--CORREÇÃO CLIENTES
SELECT C.ROWID, C.* FROM PCCLIENT C WHERE C.CLIENTE LIKE 'PAYMEE%';

--OBSERVAÇÃO TITULOS
SELECT P.ROWID, P.NUMTRANSVENDA, C.CLIENTE, P.OBSTITULO, P.*
  FROM PCPREST P JOIN PCNFSAID C ON C.NUMTRANSVENDA = P.NUMTRANSVENDA
 WHERE P.DTPAG IS NULL
 AND P.NUMTRANSVENDA IN (11688307);

--UPDATE OBSERVACAO TITULO
UPDATE PCPREST
   SET OBSTITULO = '27/06/2023 - MEDIACAO FINALIZADA COM REEMBOLSO PARA COMPRADOR - FAVOR VERIFICAR' 
 WHERE DTPAG IS NULL
   AND NUMTRANSVENDA IN (11688307);
	 
--UPDATE OBSERVACAO TITULO
UPDATE PCPREST
   SET OBSTITULO = '19/06/2023 - DEV A CAMINHO - PRAZO ATE 22/06' 
 WHERE DTPAG IS NULL
   AND NUMTRANSVENDA IN (11675084);

--UPDATE OBSERVACAO TITULO
UPDATE PCPREST
   SET OBSTITULO = '19/06/2023 - CANCELADO PELO COMPRADOR - FAVOR VERIFICAR' 
 WHERE DTPAG IS NULL
   AND NUMTRANSVENDA IN (11679802);

--UPDATE OBSERVACAO TITULO
UPDATE PCPREST
   SET OBSTITULO = '20/06/2023 - FALTA DEVOLUCAO - FAVOR VERIFICAR' 
 WHERE DTPAG IS NULL
   AND NUMTRANSVENDA IN (11653911);
	 
--UPDATE OBSERVACAO TITULO
UPDATE PCPREST
   SET OBSTITULO = '28/06/2023 - REEMBOLSO SOB GARANTIA DE A-Z - FAVOR VERIFICAR' --ENTREGUE NO DIA 16/06/2023 - QUANDO RECEBEREMOS ESSE VALOR - FAVOR VERIFICAR
 WHERE DTPAG IS NULL
   AND NUMTRANSVENDA IN (	11667798 );

--UPDATE PRESTTEF
MERGE INTO PCPREST P
USING (SELECT NUMTRANSVENDA,
              DUPLIC,
              PREST,
              PRESTTEF,
              (TO_NUMBER(PREST) - 2) PRESTTEFCALC,
              VALOR,
              CODCOB,
              VPAGO
         FROM PCPREST P
        WHERE VPAGO IS NULL
          AND PRESTTEF IS NULL
          AND P.NUMTRANSVENDA IN (11657497)
        ORDER BY DUPLIC, TO_NUMBER(PREST)) X
ON (P.NUMTRANSVENDA = X.NUMTRANSVENDA AND P.PREST = X.PREST)
WHEN MATCHED THEN
  UPDATE SET P.PRESTTEF = X.PRESTTEFCALC;

--DUPLICATA A ESTORNAR EM LOTE
SELECT P.ROWID, P.NUMCHEQUE, P.NUMCUSTODIA, P.*
  FROM PCPREST P
 WHERE P.NUMTRANS IS NULL
   --AND P.CODCLI = 25047
   AND DTPAG IS NULL 
   AND P.NUMTRANSVENDA IN (11639022, 11597254)
;

--UPDATE DUPLICATA A ESTORNAR EM LOTE
UPDATE PCPREST
   SET NUMCHEQUE = 3
 WHERE NUMTRANS IS NOT NULL
   AND NUMTRANSVENDA IN (11654788);

SELECT P.ROWID, P.NUMCHEQUE, P.* FROM PCPREST P WHERE P.NUMCHEQUE = 3;

--UPDATE LIMPAR NUMCHEQUE
UPDATE PCPREST SET NUMCHEQUE = NULL WHERE NUMCHEQUE = 3;
