---------UPDATE AMAZON PCPEDC.NUMPEDCLI--------------
MERGE INTO PCPEDC C
USING (SELECT DISTINCT W.NUMTRANSVENDA, CT.NUMPEDCLI NV_NUMPEDCLI
         FROM PCPEDC W
         JOIN PCPEDCTEMP CT ON W.NUMPEDWEB = CT.NUMPEDWEB
        WHERE W.NUMPEDCLI IS NULL
          AND W.NUMTRANSVENDA IS NOT NULL
          AND W.DTCANCEL IS NULL
          AND CT.NUMPEDCLI IS NOT NULL
          AND (W.CODCLI = 63722 OR W.CODCOB IN ('AMAZ') OR W.CODUSUR = 38)) X
ON (C.NUMTRANSVENDA = X.NUMTRANSVENDA)
WHEN MATCHED THEN
  UPDATE SET C.NUMPEDCLI = X.NV_NUMPEDCLI;
/
---------UPDATE B2W PCPEDC.NUMPEDCLI--------------
MERGE
  INTO PCPEDC C
  USING (
  SELECT DISTINCT P.DTEMISSAO,
                  W.NUMPEDCLI NUMPEDCLI_C,
                  CT.NUMPEDCLI NUMPEDCLI_CT,
                  SUBSTR(CT.NUMPEDCLI, INSTR(CT.NUMPEDCLI, '-') + 1) NV_NUMPEDCLI,
                  P.NUMTRANSVENDA
    FROM PCPREST P
    LEFT JOIN PCPEDC W ON W.NUMTRANSVENDA = P.NUMTRANSVENDA
    LEFT JOIN PCPEDCTEMP CT ON W.NUMPEDWEB = CT.NUMPEDWEB
   WHERE P.DTPAG IS NULL
     AND P.DTVENC < TRUNC(SYSDATE) - 1
     AND W.NUMPEDCLI IS NULL
     AND CT.NUMPEDCLI IS NOT NULL
     AND (P.CODCLI = 25053 OR P.CODCOB IN ('CABW') OR P.CODUSUR = 45)) X ON (C.NUMTRANSVENDA = X.NUMTRANSVENDA) WHEN MATCHED THEN UPDATE SET C.NUMPEDCLI = X.NV_NUMPEDCLI;
/
---------UPDATE RIHAPPY PCPEDC.NUMPEDCLI--------------
MERGE
  INTO PCPEDC C
  USING (
  SELECT DISTINCT W.NUMTRANSVENDA,
                  COALESCE(CT.ARQUIVO, CT.NUMPEDMKTPLACE) NV_NUMPEDCLI
    FROM PCPEDC W
    JOIN PCPEDCTEMP CT ON W.NUMPEDWEB = CT.NUMPEDWEB
   WHERE W.NUMPEDCLI IS NULL
     AND W.NUMTRANSVENDA IS NOT NULL
     AND W.DTCANCEL IS NULL
     AND COALESCE(CT.ARQUIVO, CT.NUMPEDMKTPLACE) IS NOT NULL
     AND (W.CODCLI = 326041 OR W.CODCOB IN ('RIHP') OR W.CODUSUR = 55)) X ON (C.NUMTRANSVENDA = X.NUMTRANSVENDA) WHEN MATCHED THEN UPDATE SET C.NUMPEDCLI = X.NV_NUMPEDCLI;
/
---------UPDATE CARREFOUR PCPEDC.NUMPEDCLI--------------
MERGE
  INTO PCPEDC C
  USING (
  SELECT DISTINCT W.NUMTRANSVENDA, CT.NUMPEDCLI NV_NUMPEDCLI
    FROM PCPEDC W
    JOIN PCPEDCTEMP CT ON W.NUMPEDWEB = CT.NUMPEDWEB
   WHERE W.NUMPEDCLI IS NULL
     AND W.NUMTRANSVENDA IS NOT NULL
     AND W.DTCANCEL IS NULL
     AND CT.NUMPEDCLI IS NOT NULL
     AND (W.CODCLI = 96092 OR W.CODCOB IN ('CAFR') OR W.CODUSUR = 47)) X ON (C.NUMTRANSVENDA = X.NUMTRANSVENDA) WHEN MATCHED THEN UPDATE SET C.NUMPEDCLI = X.NV_NUMPEDCLI;
/
---------UPDATE MERCADO LIVRE PCPEDC.NUMPEDCLI--------------
MERGE
  INTO PCPEDC C
  USING (
  SELECT DISTINCT W.NUMTRANSVENDA, CT.NUMPEDCLI NV_NUMPEDCLI
    FROM PCPEDC W
    JOIN PCPEDCTEMP CT ON W.NUMPEDWEB = CT.NUMPEDWEB
   WHERE W.NUMTRANSVENDA IS NOT NULL
     AND W.DTCANCEL IS NULL
     AND CT.NUMPEDCLI IS NOT NULL
     AND W.NUMPEDCLI IS NULL
     AND (W.CODCLI = 25047 OR W.CODCOB IN ('MERC') OR W.CODUSUR = 42)
     AND NVL(LENGTH(W.NUMPEDCLI), 0) < LENGTH(CT.NUMPEDCLI)) X ON (C.NUMTRANSVENDA = X.NUMTRANSVENDA) WHEN MATCHED THEN UPDATE SET C.NUMPEDCLI = X.NV_NUMPEDCLI;

---------UPDATE GIMBA PCPEDC.NUMPEDCLI--------------
MERGE INTO PCPEDC C
USING (SELECT DISTINCT W.NUMTRANSVENDA, CT.NUMPEDCLI NV_NUMPEDCLI
         FROM PCPEDC W
         JOIN PCPEDCTEMP CT ON W.NUMPEDWEB = CT.NUMPEDWEB
        WHERE W.NUMTRANSVENDA IS NOT NULL
          AND W.DTCANCEL IS NULL
          AND CT.NUMPEDCLI IS NOT NULL
          AND W.NUMPEDCLI IS NULL
          AND (W.CODCLI = 473516 OR W.CODCOB IN ('CGBA') OR W.CODUSUR = 70)) X
ON (C.NUMTRANSVENDA = X.NUMTRANSVENDA)
WHEN MATCHED THEN
  UPDATE SET C.NUMPEDCLI = X.NV_NUMPEDCLI;
