---------UPDATE AMAZON PCPEDC.NUMPEDCLI--------------
MERGE INTO PCPEDC C
USING (SELECT DISTINCT W.NUMTRANSVENDA, CT.NUMPEDCLI NV_NUMPEDCLI
         FROM PCPEDC W
         JOIN PCPEDCTEMP CT ON W.NUMPEDWEB = CT.NUMPEDWEB
        WHERE W.NUMPEDCLI IS NULL
          AND W.NUMTRANSVENDA IS NOT NULL
          AND W.DTCANCEL IS NULL
          AND CT.NUMPEDCLI IS NOT NULL
          AND (W.CODCLI = 63722 OR W.CODCOB IN ('AMAZ') OR W.CODUSUR = 38)) X
ON (C.NUMTRANSVENDA = X.NUMTRANSVENDA)
WHEN MATCHED THEN
  UPDATE SET C.NUMPEDCLI = X.NV_NUMPEDCLI;
/

---------UPDATE RIHAPPY PCPEDC.NUMPEDCLI--------------
MERGE
  INTO PCPEDC C
  USING (
  SELECT DISTINCT W.NUMTRANSVENDA,
                  SUBSTR(CT.NUMPEDMKTPLACE, 0, INSTR(CT.NUMPEDMKTPLACE, '-') -1 ) NV_NUMPEDCLI
    FROM PCPEDC W
    JOIN PCPEDCTEMP CT ON W.NUMPEDWEB = CT.NUMPEDWEB
   WHERE W.NUMPEDCLI IS NULL
     AND W.NUMTRANSVENDA IS NOT NULL
     AND W.DTCANCEL IS NULL
     AND COALESCE(CT.ARQUIVO, CT.NUMPEDMKTPLACE) IS NOT NULL
     AND (W.CODCLI = 326041 OR W.CODCOB IN ('RIHP') OR W.CODUSUR = 55)) X ON (C.NUMTRANSVENDA = X.NUMTRANSVENDA) 
    WHEN MATCHED THEN UPDATE SET C.NUMPEDCLI = X.NV_NUMPEDCLI;


---------UPDATE ITAUSHOP PCPEDC.NUMPEDCLI--------------
MERGE
  INTO PCPEDC C
  USING (
SELECT DISTINCT W.NUMTRANSVENDA, CT.NUMPEDCLI NV_NUMPEDCLI
         FROM PCPEDC W
         JOIN PCPEDCTEMP CT ON W.NUMPEDWEB = CT.NUMPEDWEB
        WHERE W.NUMPEDCLI IS NULL
          AND W.NUMTRANSVENDA IS NOT NULL
          AND W.DTCANCEL IS NULL
          AND CT.NUMPEDCLI IS NOT NULL
          AND (W.CODCLI = 560317 OR W.CODCOB IN ('ISHP') OR W.CODUSUR = 112)
     AND NVL(LENGTH(W.NUMPEDCLI), 0) < LENGTH(CT.NUMPEDCLI)) X ON (C.NUMTRANSVENDA = X.NUMTRANSVENDA) 
    WHEN MATCHED THEN UPDATE SET C.NUMPEDCLI = X.NV_NUMPEDCLI;


---------UPDATE NUMVEMSHOP PCPEDC.NUMPEDCLI--------------
MERGE
  INTO PCPEDC C
  USING (
SELECT DISTINCT W.NUMTRANSVENDA, CT.NUMPEDCLI NV_NUMPEDCLI
         FROM PCPEDC W
         JOIN PCPEDCTEMP CT ON W.NUMPEDWEB = CT.NUMPEDWEB
        WHERE W.NUMPEDCLI IS NULL
          AND W.NUMTRANSVENDA IS NOT NULL
          AND W.DTCANCEL IS NULL
          AND CT.NUMPEDCLI IS NOT NULL
          AND (W.CODCLI = 594595 OR W.CODCOB IN ('CNVS'))
     AND NVL(LENGTH(W.NUMPEDCLI), 0) < LENGTH(CT.NUMPEDCLI)) X ON (C.NUMTRANSVENDA = X.NUMTRANSVENDA) 
    WHEN MATCHED THEN UPDATE SET C.NUMPEDCLI = X.NV_NUMPEDCLI;
