/*MUDAR PARA 9185 PACER*/
SELECT ROWID,
       L.CODFORNEC,
       L.*
  FROM PCLANC L
 WHERE CODFORNEC = 9712
   AND DTEMISSAO >= '01-JAN-2022' AND CODFILIAL IN ('5', '6');

/*MUDAR PARA 9298 PAULINERES*/ 
SELECT ROWID,
       L.CODFORNEC,
       L.*
  FROM PCLANC L
 WHERE CODFORNEC = 7902
   AND DTEMISSAO >= '01-JAN-2022' AND CODFILIAL = '6';

/*MUDAR PARA 7607 RODONAVES*/ 
SELECT ROWID,
       L.CODFORNEC,
       L.*
  FROM PCLANC L
 WHERE CODFORNEC = 8166
   AND DTEMISSAO >= '01-JAN-2023' AND CODFILIAL = '2';
 
/*MUDAR PARA 8965 PAULISTA*/ 
SELECT ROWID,
       E.CODCONT, E.CODFUNCLANC,
       E.CODFILIAL,
       E.CODFILIALNF,
       E.CODFORNEC,
       E.CODFORNECNF,
       E.NUMTRANSENT,
       E.VLST,
       E.VLOUTRAS,
       E.*
  FROM PCNFENT E
 WHERE CODFORNEC = 129
       ORDER BY DTENT;

--UPDATE
UPDATE PCNFENT
   SET CODFORNEC = 8965, CODFORNECNF = 8965
 WHERE CODFORNEC = 129;
