WITH PRODUTOS_CORP AS
 (SELECT L.CODPROD,
         P.DESCRICAO
    FROM PCPRODFILIAL L
    LEFT JOIN PCPRODUT P ON P.CODPROD = L.CODPROD
    LEFT JOIN PCFORNEC F ON F.CODFORNEC = P.CODFORNEC
   WHERE 1=1
	   AND L.ENVIARFORCAVENDAS = 'S'
     AND F.CODFORNECPRINC NOT IN (2)
     AND P.CODMARCA NOT IN (225
     AND L.CODFILIAL = '6'
		 --AND L.CODPROD = 826832
		 )

SELECT V.CODFILIAL,
       V.CODPROD,
       P.DESCRICAO,
       E.CUSTOPROXIMACOMPRA,
       V.PCOMPRA,
       E.CUSTOREAL,
       E.CUSTOFIN,
       E.CUSTOREP
  FROM VIEW_JC_CUSTOLIQ_240 V
  JOIN PRODUTOS_CORP P ON P.CODPROD = V.CODPROD
  LEFT JOIN PCEST E ON E.CODPROD = V.CODPROD
                   AND E.CODFILIAL = V.CODFILIAL
 WHERE V.CODFILIAL = '11'
   AND (E.CUSTOREAL = 0 OR E.CUSTOFIN = 0 OR E.CUSTOREP = 0)
	 ;

-------UPDATE PCEST
MERGE INTO PCEST E
USING (
  WITH PRODUTOS_CORP AS
   (SELECT L.CODPROD,
           P.DESCRICAO
      FROM PCPRODFILIAL L
      LEFT JOIN PCPRODUT P ON P.CODPROD = L.CODPROD
      LEFT JOIN PCFORNEC F ON F.CODFORNEC = P.CODFORNEC
     WHERE L.ENVIARFORCAVENDAS = 'S'
       AND F.CODFORNECPRINC NOT IN (2)
       AND P.CODMARCA NOT IN (225)
       AND L.CODFILIAL = '6')
  
  SELECT V.CODFILIAL,
         V.CODPROD,
         P.DESCRICAO,
         E.CUSTOPROXIMACOMPRA,
         V.PCOMPRA
    FROM VIEW_JC_CUSTOLIQ_240 V
    JOIN PRODUTOS_CORP P ON P.CODPROD = V.CODPROD
    LEFT JOIN PCEST E ON E.CODPROD = V.CODPROD
                     AND E.CODFILIAL = V.CODFILIAL
   WHERE V.CODFILIAL = '11'
     AND (E.CUSTOREAL = 0 OR E.CUSTOFIN = 0 OR E.CUSTOREP = 0)) X ON (E.CODPROD = X.CODPROD AND E.CODFILIAL = X.CODFILIAL) WHEN MATCHED THEN
    UPDATE
       SET E.CUSTOREAL = X.CUSTOPROXIMACOMPRA,
           E.CUSTOFIN  = X.CUSTOPROXIMACOMPRA,
           E.CUSTOREP  = X.PCOMPRA;
