--sem myaudit
--TODAS AS MOVIMENTACOES DA PCMOV PARA DESCONSIDERAR POSTERIORMENTE 
WITH PCMOV_NUMTRANSENT AS
 (SELECT DISTINCT (NUMTRANSENT) FROM PCMOV)
SELECT E.CODFILIALNF AS CODFILIAL,
       E.DTEMISSAO,
       E.DTENT,
       E.NUMTRANSENT,
       (CASE
         WHEN E.ESPECIE = 'CT' THEN
          420102
         ELSE
          E.CODCONT
       END) AS CODCONTA,
       E.ESPECIE,
       B.CODFISCAL,
       E.CODFORNEC,
       (E.ESPECIE || ' ' || E.NUMNOTA || ' - CNPJ: ' || E.CGC || ' - ' ||
       E.FORNECEDOR) AS HISTORICO,
       B.VLCONTABIL AS VALOR,
       B.VLBASE,
       B.ALIQUOTA AS ALIQ_ICMS,
       B.VLICMS,
       E.VLST,
       B.VLISENTAS,
       E.VLOUTRAS,
       ROUND(P.VLPIS, 2) AS VLPIS,
       ROUND(P.VLCOFINS, 2) AS VLCOFINS
  FROM PCNFENT E
  LEFT JOIN PCNFBASE B ON E.NUMTRANSENT = B.NUMTRANSENT
  LEFT JOIN PCNFENTPISCOFINS P ON B.NUMTRANSPISCOFINS = P.NUMTRANSPISCOFINS
  LEFT JOIN PCMOV_NUMTRANSENT M ON E.NUMTRANSENT = M.NUMTRANSENT
 WHERE E.DTCANCEL IS NULL
   AND ((E.ESPECIE = 'NF' AND B.CODFISCAL IN (1911, 1923, 2923, 1949, 2949)) OR
       (E.ESPECIE = 'NS' AND
       B.CODFISCAL NOT IN
       (1253, 1353, 2353, 1933, 2933, 1923, 2923, 1949, 2949)))
   AND E.CODCONT NOT IN (200159, 100001, 100023)
   AND M.NUMTRANSENT IS NULL
   AND E.DTENT >= '01-06-2022'
 ORDER BY DTENT DESC;
