--RODAR A 507 FILIAL 3 PARAMETRO 14 REGIAO 5
--DEPOIS RODAR 552 PARAMETRO 1 REGIAO 5
WITH PRODUTOS AS
 (SELECT E.CODFILIAL,
         E.CODPROD,
         P.DESCRICAO,
         M.MARCA,
         P.NBM,
         T.NUMREGIAO,
         R.REGIAO,
         L.PCOMPRA,
         L.PBRUTO,
         L.CUSTOLIQ,
         T.MARGEM MIDEAL,
         FN_JF_MARGEM_PRECO(L.CUSTOLIQ,
                            T.PVENDA,
                            FN_JF_TRANSFORMA_EM_PERCENTUAL(B.CODICMTAB)) MPRECO,
        /* FN_JF_MARGEM_PRECO(L.CUSTOLIQ,
                            L.PCOMPRA,
                            FN_JF_TRANSFORMA_EM_PERCENTUAL(B.CODICMTAB)) MSUGERIDA,*/
				 FN_JF_MARGEM_PRECO(L.CUSTOLIQ,
            FN_JF_PRECO_VENDA(L.CUSTOLIQ,
                           17,
                           FN_JF_TRANSFORMA_EM_PERCENTUAL(B.CODICMTAB)),
                            FN_JF_TRANSFORMA_EM_PERCENTUAL(B.CODICMTAB)) MSUGERIDA,
        /* FN_JF_PRECO_VENDA(L.CUSTOLIQ,
                           FN_JF_MARGEM_PRECO(L.CUSTOLIQ,
                                              L.PCOMPRA,
                                              FN_JF_TRANSFORMA_EM_PERCENTUAL(B.CODICMTAB)),
                           FN_JF_TRANSFORMA_EM_PERCENTUAL(B.CODICMTAB)) PSUGERIDO,*/
				FN_JF_PRECO_VENDA(L.CUSTOLIQ,
                           0.17,
                           FN_JF_TRANSFORMA_EM_PERCENTUAL(B.CODICMTAB)) PSUGERIDO,
         T.PTABELA,
         ROUND(NVL(T.PVENDA, 0), 4) AS PVENDA
    FROM PCEST E
    JOIN PCPRODUT P ON P.CODPROD = E.CODPROD
    JOIN PCMARCA M ON M.CODMARCA = P.CODMARCA
    LEFT JOIN PCTABPR T ON T.CODPROD = E.CODPROD
    JOIN PCREGIAO R ON R.NUMREGIAO = T.NUMREGIAO
    JOIN PCTABTRIB I ON I.UFDESTINO = R.UF
                    AND I.CODFILIALNF = E.CODFILIAL
                    AND I.CODPROD = E.CODPROD
    JOIN PCTRIBUT B ON B.CODST = I.CODST
    JOIN MV_JF_CUSTOS_ENTRADA L ON L.CODPROD = E.CODPROD
                               AND L.CODFILIAL = E.CODFILIAL
   WHERE E.CODFILIAL IN ('2', '7')
     AND T.NUMREGIAO = 5
     AND P.DTEXCLUSAO IS NULL
     AND P.CODMARCA <> 255 --KITS
     AND L.CUSTOLIQ > 0),
PRODUTOS_F7 AS
 (SELECT P.* FROM PRODUTOS P WHERE P.CODFILIAL = '7'),
PRODUTOS_F2 AS
 (SELECT P.*
    FROM PRODUTOS P
    LEFT JOIN PRODUTOS_F7 F7 ON F7.CODPROD = P.CODPROD
   WHERE P.CODFILIAL = '2'
     AND F7.CODPROD IS NULL),
PRODUTOS_TRATADOS AS
 (SELECT * FROM PRODUTOS_F7 UNION ALL SELECT * FROM PRODUTOS_F2)
SELECT *
  FROM PRODUTOS_TRATADOS
 WHERE PSUGERIDO <> PVENDA
    OR PTABELA <> PSUGERIDO;
/
--UPDATE---
MERGE
  INTO PCTABPR P
  USING (
  WITH PRODUTOS AS
   (SELECT E.CODFILIAL,
           E.CODPROD,
           T.NUMREGIAO,
				 FN_JF_MARGEM_PRECO(L.CUSTOLIQ,
            FN_JF_PRECO_VENDA(L.CUSTOLIQ,
                           17,
                           FN_JF_TRANSFORMA_EM_PERCENTUAL(B.CODICMTAB)),
                            FN_JF_TRANSFORMA_EM_PERCENTUAL(B.CODICMTAB)) MSUGERIDA,
				FN_JF_PRECO_VENDA(L.CUSTOLIQ,
                           0.17,
                           FN_JF_TRANSFORMA_EM_PERCENTUAL(B.CODICMTAB)) PSUGERIDO,
           T.PTABELA,
           ROUND(NVL(T.PVENDA, 0), 4) AS PVENDA
      FROM PCEST E
      JOIN PCPRODUT P ON P.CODPROD = E.CODPROD
      JOIN PCMARCA M ON M.CODMARCA = P.CODMARCA
      LEFT JOIN PCTABPR T ON T.CODPROD = E.CODPROD
      JOIN PCREGIAO R ON R.NUMREGIAO = T.NUMREGIAO
      JOIN PCTABTRIB I ON I.UFDESTINO = R.UF
                      AND I.CODFILIALNF = E.CODFILIAL
                      AND I.CODPROD = E.CODPROD
      JOIN PCTRIBUT B ON B.CODST = I.CODST
      JOIN MV_JF_CUSTOS_ENTRADA L ON L.CODPROD = E.CODPROD
                                 AND L.CODFILIAL = E.CODFILIAL
     WHERE E.CODFILIAL IN ('2', '7')
       AND T.NUMREGIAO = 5
       AND P.DTEXCLUSAO IS NULL
       AND P.CODMARCA <> 255 --KITS
       AND L.CUSTOLIQ > 0),
  PRODUTOS_F7 AS
   (SELECT P.* FROM PRODUTOS P WHERE P.CODFILIAL = '7'),
  PRODUTOS_F2 AS
   (SELECT P.*
      FROM PRODUTOS P
      LEFT JOIN PRODUTOS_F7 F7 ON F7.CODPROD = P.CODPROD
     WHERE P.CODFILIAL = '2'
       AND F7.CODPROD IS NULL),
  PRODUTOS_TRATADOS AS
   (SELECT * FROM PRODUTOS_F7 UNION ALL SELECT * FROM PRODUTOS_F2)
  SELECT *
    FROM PRODUTOS_TRATADOS
   WHERE PSUGERIDO <> PVENDA
      OR PTABELA <> PSUGERIDO) X ON (P.CODPROD = X.CODPROD AND P.NUMREGIAO = X.NUMREGIAO) WHEN MATCHED THEN UPDATE SET P.MARGEM = X.MSUGERIDA, P.PTABELA = X.PSUGERIDO;
