--CAIXAS MKT A CONCILIAR
SELECT DISTINCT M.DATA,
                M.CODBANCO,
                B.NOME BANCO,
                M.DTCOMPENSACAO,
                M.TIPO,
                SUM(M.VALOR) OVER(PARTITION BY M.CODBANCO, M.DATA, M.TIPO) VALOR
  FROM PCMOVCR M
  JOIN PCBANCO B ON B.CODBANCO = M.CODBANCO
 WHERE (B.CODBACEN = 'MARKETPLACE' OR (B.CODBANCO = 12 AND M.TIPO = 'C'))
   AND M.DTCONCIL IS NULL
   AND M.CODCOB = 'D'
   ORDER BY M.DATA DESC;
