--CONSULTA
SELECT C.CODCLI, C.CLIENTE, C.USACRECLIFAT
  FROM PCCLIENT C
  JOIN PCUSUARI U ON U.CODUSUR = C.CODUSUR1
  JOIN PCSUPERV V ON V.CODSUPERVISOR = U.CODSUPERVISOR
 WHERE V.CODSUPERVISOR IN (7, 8)
   AND C.USACRECLIFAT = 'S';

--UPDATE
MERGE INTO PCCLIENT C
USING (SELECT C.CODCLI, C.USACRECLIFAT
         FROM PCCLIENT C
         JOIN PCUSUARI U ON U.CODUSUR = C.CODUSUR1
         JOIN PCSUPERV V ON V.CODSUPERVISOR = U.CODSUPERVISOR
        WHERE V.CODSUPERVISOR IN (7, 8)
          AND C.USACRECLIFAT = 'S') X
ON (X.CODCLI = C.CODCLI)
WHEN MATCHED THEN
  UPDATE SET C.USACRECLIFAT = 'N';
