WITH PRODUTO_MASTER AS
 (SELECT F.CODFILIAL,
         P.CODPRODMASTER CODMASTER,
         P.DESCRICAO PRODUTO_MASTER,
         ROUND(F.CUSTOREP, 2) CUSTOREP_MASTER,
         F.PERCDESC1 PERCDESC1_MASTER,
         F.PERCDESC2 PERCDESC2_MASTER,
         F.PERCDESC3 PERCDESC3_MASTER,
         F.PERCDESC4 PERCDESC4_MASTER,
         F.PERCDESC PERCDESC_MASTER
    FROM PCPRODFILIAL F
   INNER JOIN PCPRODUT P ON F.CODPROD = P.CODPROD
   WHERE P.CODPROD = P.CODPRODMASTER)
SELECT *
  FROM (SELECT F.CODFILIAL,
               M.CODMASTER,
               M.PRODUTO_MASTER,
               M.CUSTOREP_MASTER,
               M.PERCDESC1_MASTER,
               M.PERCDESC2_MASTER,
               M.PERCDESC3_MASTER,
               M.PERCDESC4_MASTER,
               M.PERCDESC_MASTER,
               (SELECT ROUND(CUSTOPROXIMACOMPRA, 2)
                  FROM PCEST
                 WHERE CODPROD = P.CODPRODMASTER
                   AND CODFILIAL = F.CODFILIAL) PROXIMACOMPRA_MASTER,
               F.CODPROD,
               P.DESCRICAO PRODUTO_FILHO,
               F.CUSTOREPTAB,
               F.PERCDESC1TAB,
               F.PERCDESC2TAB,
               F.PERCDESC3TAB,
               F.PERCDESC4TAB,
               F.PERCDESC,
               ROUND(E.CUSTOPROXIMACOMPRA, 2) CUSTOPROXIMACOMPRA
          FROM PCPRODFILIAL F
         INNER JOIN PCPRODUT P ON F.CODPROD = P.CODPROD
         INNER JOIN PCEST E ON E.CODPROD = F.CODPROD
                           AND E.CODFILIAL = F.CODFILIAL
         INNER JOIN PRODUTO_MASTER M ON M.CODMASTER = P.CODPRODMASTER
                                    AND M.CODFILIAL = F.CODFILIAL
        
         WHERE P.DTEXCLUSAO IS NULL
           AND F.CODFILIAL IN (1, 7, 8))
 WHERE (PERCDESC <> PERCDESC_MASTER OR
       ABS(CUSTOPROXIMACOMPRA - PROXIMACOMPRA_MASTER) > 0.01)
 ORDER BY CODMASTER, CODFILIAL;
/

  WITH PRODUTO_MASTER AS
   (SELECT F.CODFILIAL,
           P.CODPRODMASTER CODMASTER,
           P.DESCRICAO PRODUTO_MASTER,
           ROUND(F.CUSTOREP, 2) CUSTOREP_MASTER,
           F.PERCDESC1 PERCDESC1_MASTER,
           F.PERCDESC2 PERCDESC2_MASTER,
           F.PERCDESC3 PERCDESC3_MASTER,
           F.PERCDESC4 PERCDESC4_MASTER,
           F.PERCDESC PERCDESC_MASTER,
           F.DTULTATUPCOMPRA DTULTATUPCOMPRA_MASTER,
           F.CODUSUULTALTCOM CODFUNC_MASTER
      FROM PCPRODFILIAL F
     INNER JOIN PCPRODUT P ON F.CODPROD = P.CODPROD
     WHERE P.CODPROD = P.CODPRODMASTER)
  SELECT *
    FROM (SELECT F.CODFILIAL,
                 M.CODMASTER,
                 M.PRODUTO_MASTER,
                 M.CUSTOREP_MASTER,
                 M.PERCDESC1_MASTER,
                 M.PERCDESC2_MASTER,
                 M.PERCDESC3_MASTER,
                 M.PERCDESC4_MASTER,
                 M.PERCDESC_MASTER,
                 (SELECT ROUND(CUSTOPROXIMACOMPRA, 2)
                    FROM PCEST
                   WHERE CODPROD = P.CODPRODMASTER
                     AND CODFILIAL = F.CODFILIAL) PROXIMACOMPRA_MASTER,
                 M.DTULTATUPCOMPRA_MASTER,
                 M.CODFUNC_MASTER,
                 F.CODPROD,
                 P.DESCRICAO PRODUTO_FILHO,
                 F.CUSTOREPTAB,
                 F.PERCDESC,
                 ROUND(E.CUSTOPROXIMACOMPRA, 2) CUSTOPROXIMACOMPRA,
                 F.DTULTATUPCOMPRA,
                 F.CODUSUULTALTCOM AS CODFUNC
            FROM PCPRODFILIAL F
           INNER JOIN PCPRODUT P ON F.CODPROD = P.CODPROD
           INNER JOIN PCEST E ON E.CODPROD = F.CODPROD
                             AND E.CODFILIAL = F.CODFILIAL
           INNER JOIN PRODUTO_MASTER M ON M.CODMASTER = P.CODPRODMASTER
                                      AND M.CODFILIAL = F.CODFILIAL
           WHERE P.DTEXCLUSAO IS NULL
             AND F.CODFILIAL IN (1, 7, 8))
   WHERE (PERCDESC <> PERCDESC_MASTER OR
         ABS(CUSTOPROXIMACOMPRA - PROXIMACOMPRA_MASTER) > 0.01)
   ORDER BY CODMASTER, CODFILIAL;
/

WITH PRODUTO_MASTER AS
 (SELECT F.CODFILIAL,
         P.CODPRODMASTER CODMASTER,
         P.DESCRICAO PRODUTO_MASTER,
         ROUND(F.CUSTOREP, 2) CUSTOREP_MASTER,
         F.PERCDESC1 PERCDESC1_MASTER,
         F.PERCDESC2 PERCDESC2_MASTER,
         F.PERCDESC3 PERCDESC3_MASTER,
         F.PERCDESC4 PERCDESC4_MASTER,
         F.PERCDESC PERCDESC_MASTER,
         F.DTULTATUPCOMPRA DTULTATUPCOMPRA_MASTER,
         F.CODUSUULTALTCOM CODFUNC_MASTER
    FROM PCPRODFILIAL F
   INNER JOIN PCPRODUT P ON F.CODPROD = P.CODPROD
   WHERE P.CODPROD = P.CODPRODMASTER)
SELECT CODMASTER,
       PRODUTO_MASTER,
       CUSTOREP_MASTER,
       PERCDESC_MASTER,
       PROXIMACOMPRA_MASTER,
       DTULTATUPCOMPRA_MASTER,
       CODFUNC_MASTER
  FROM (SELECT F.CODFILIAL,
               M.CODMASTER,
               M.PRODUTO_MASTER,
               M.CUSTOREP_MASTER,
               M.PERCDESC1_MASTER,
               M.PERCDESC2_MASTER,
               M.PERCDESC3_MASTER,
               M.PERCDESC4_MASTER,
               M.PERCDESC_MASTER,
               (SELECT ROUND(CUSTOPROXIMACOMPRA, 2)
                  FROM PCEST
                 WHERE CODPROD = P.CODPRODMASTER
                   AND CODFILIAL = F.CODFILIAL) PROXIMACOMPRA_MASTER,
               M.DTULTATUPCOMPRA_MASTER,
               M.CODFUNC_MASTER,
               F.CODPROD,
               P.DESCRICAO PRODUTO_FILHO,
               F.CUSTOREPTAB,
               F.PERCDESC,
               ROUND(E.CUSTOPROXIMACOMPRA, 2) CUSTOPROXIMACOMPRA,
               F.DTULTATUPCOMPRA,
               F.CODUSUULTALTCOM AS CODFUNC
          FROM PCPRODFILIAL F
         INNER JOIN PCPRODUT P ON F.CODPROD = P.CODPROD
         INNER JOIN PCEST E ON E.CODPROD = F.CODPROD
                           AND E.CODFILIAL = F.CODFILIAL
         INNER JOIN PRODUTO_MASTER M ON M.CODMASTER = P.CODPRODMASTER
                                    AND M.CODFILIAL = F.CODFILIAL
         WHERE P.DTEXCLUSAO IS NULL
           AND F.CODFILIAL IN (1, 7, 8))
 WHERE (PERCDESC <> PERCDESC_MASTER OR
       ABS(CUSTOPROXIMACOMPRA - PROXIMACOMPRA_MASTER) > 0.01)
 GROUP BY CODMASTER,
          PRODUTO_MASTER,
          CUSTOREP_MASTER,
          PERCDESC_MASTER,
          PROXIMACOMPRA_MASTER,
          DTULTATUPCOMPRA_MASTER,
          CODFUNC_MASTER
 ORDER BY CODMASTER;
 /