---CONSULTA
WITH NOTA_VENDA AS
 (SELECT S.NUMTRANSVENDA, D.NUMTRANSENT, M.CODPROD
    FROM PCNFSAID S
    JOIN PCDEVAVULSO D ON D.CHAVENFE = S.CHAVENFE
    JOIN PCMOV M ON M.NUMTRANSVENDA = S.NUMTRANSVENDA),
RESULTADO AS
 (SELECT DISTINCT M.CODFILIAL,
                  M.NUMTRANSDEV,
                  E.CODFORNEC,
                  E.FORNECEDOR,
                  M.NUMTRANSENT,
                  M.NUMTRANSITEM,
                  M.NUMNOTA NUMNOTADEV,
                  NVL(S.NUMTRANSVENDA,
                      MIN(V.NUMTRANSVENDA) OVER(PARTITION BY NUMTRANSITEM)) NUMTRANSVENDA,
                  M.DTMOV,
                  M.CODPROD,
                  M.DESCRICAO
    FROM PCMOV M
    LEFT JOIN PCNFENT E ON E.NUMTRANSENT = M.NUMTRANSENT
    LEFT JOIN PCNFSAID S ON S.CODFILIAL = E.CODFILIAL
                        AND S.NUMNOTA = E.NUMNOTAVENDA
    LEFT JOIN NOTA_VENDA V ON V.NUMTRANSENT = M.NUMTRANSENT
                          AND V.CODPROD = M.CODPROD
   WHERE M.CODOPER = 'ED'
     AND M.NUMTRANSDEV = 0
     AND M.DTMOV >= '01/01/2022'
   ORDER BY DTMOV DESC, M.NUMTRANSENT, M.NUMTRANSITEM)
SELECT * FROM RESULTADO WHERE NUMTRANSVENDA IS NOT NULL;

--UPDATE
MERGE INTO PCMOV M
USING (
  WITH NOTA_VENDA AS
   (SELECT S.NUMTRANSVENDA, D.NUMTRANSENT, M.CODPROD
      FROM PCNFSAID S
      JOIN PCDEVAVULSO D ON D.CHAVENFE = S.CHAVENFE
      JOIN PCMOV M ON M.NUMTRANSVENDA = S.NUMTRANSVENDA),
  RESULTADO AS
   (SELECT DISTINCT M.CODFILIAL,
                    M.NUMTRANSDEV,
                    E.CODFORNEC,
                    E.FORNECEDOR,
                    M.NUMTRANSENT,
                    M.NUMTRANSITEM,
                    M.NUMNOTA NUMNOTADEV,
                    NVL(S.NUMTRANSVENDA,
                        MIN(V.NUMTRANSVENDA) OVER(PARTITION BY NUMTRANSITEM)) NUMTRANSVENDA,
                    M.DTMOV,
                    M.CODPROD,
                    M.DESCRICAO
      FROM PCMOV M
      LEFT JOIN PCNFENT E ON E.NUMTRANSENT = M.NUMTRANSENT
      LEFT JOIN PCNFSAID S ON S.CODFILIAL = E.CODFILIAL
                          AND S.NUMNOTA = E.NUMNOTAVENDA
      LEFT JOIN NOTA_VENDA V ON V.NUMTRANSENT = M.NUMTRANSENT
                            AND V.CODPROD = M.CODPROD
     WHERE M.CODOPER = 'ED'
       AND M.NUMTRANSDEV = 0
       AND M.DTMOV >= '01/01/2022'
     ORDER BY DTMOV DESC, M.NUMTRANSENT, M.NUMTRANSITEM)
  SELECT *
    FROM RESULTADO
   WHERE NUMTRANSVENDA IS NOT NULL) X ON (M.NUMTRANSITEM = X.NUMTRANSITEM) WHEN MATCHED THEN
    UPDATE SET M.NUMTRANSDEV = X.NUMTRANSVENDA;

--SCRIPT PARA BUSCAR NOTA QUE DEVERIA TER SIDO REFERENCIADA
WITH CLIENTE_PRINCIPAL AS
 (SELECT CODCLIPRINC FROM PCCLIENT WHERE CODCLI = 158113),
CLIENTES AS
 (SELECT CODCLI
    FROM PCCLIENT C
    JOIN CLIENTE_PRINCIPAL P ON P.CODCLIPRINC = C.CODCLIPRINC),
TRANSACAO_VENDA AS
 (SELECT S.NUMTRANSVENDA, S.NUMNOTA, S.CHAVENFE, S.DTSAIDA, S.SERIE
    FROM PCNFSAID S
    JOIN CLIENTES C ON C.CODCLI = S.CODCLI
   WHERE S.DTSAIDA <= '26/01/2022'
     AND S.DTCANCEL IS NULL
     AND S.CONDVENDA IN (1, 7)),
TRANSACAO_VENDA_RECENTE AS
 (SELECT MAX(V.NUMTRANSVENDA) NUMTRANSVENDA
    FROM PCMOV M
    JOIN TRANSACAO_VENDA V ON V.NUMTRANSVENDA = M.NUMTRANSVENDA
   WHERE M.CODPROD = 797357)
SELECT S.DTSAIDA, S.NUMNOTA, S.SERIE, S.CHAVENFE
  FROM PCNFSAID S
  JOIN TRANSACAO_VENDA_RECENTE V ON V.NUMTRANSVENDA = S.NUMTRANSVENDA;
