/*****CORRECAO CUSTO NA VENDA ******/
--CONSULTA
WITH MOV_COMPRA AS
 (SELECT M.DTMOV DTCOMPRA,
         M.NUMTRANSITEM NUMITEMCOMPRA,
         M.CODFISCAL CODCOMPRA,
         M.PUNITCONT
    FROM PCMOV M
   WHERE M.DTCANCEL IS NULL
     AND M.STATUS IN ('A', 'AB')
     AND M.CODFILIAL IN ('5', '6', '9', '10')
     AND M.CODOPER = 'E'),
MOV_VENDA AS
 (SELECT M.CODFILIAL,
         M.NUMTRANSITEM NUMITEMVENDA,
         (SELECT MIN(C.NUMTRANSITEM)
            FROM PCMOV C
           WHERE C.CODPROD = M.CODPROD
             AND C.CODFILIAL = M.CODFILIAL
             AND C.DTMOV >= M.DTMOV
             AND C.CODOPER = 'E'
             AND C.DTCANCEL IS NULL) NUMITEMCOMPRA,
         M.DTMOV DTVENDA,
         M.CODFISCAL CODVENDA,
         M.CODPROD,
         M.DESCRICAO,
         M.CUSTOCONT CUSTOCONT_VENDA,
         M.CUSTOFINEST CUSTOFINEST_VENDA
    FROM PCMOV M
   WHERE M.DTCANCEL IS NULL
     AND M.STATUS IN ('A', 'AB')
     AND M.CODFILIAL IN ('5', '6', '9', '10')
     AND M.CODOPER IN ('S', 'SB')
     AND M.CODFISCAL NOT IN (5117, 6117, 5923, 6923)
     AND M.DTMOV >= TRUNC(SYSDATE) - 2)

SELECT V.CODFILIAL,
       V.NUMITEMVENDA,
       V.DTVENDA,
       C.DTCOMPRA,
       V.CODVENDA,
       C.CODCOMPRA,
       V.CODPROD,
       V.DESCRICAO,
       V.CUSTOFINEST_VENDA,
       V.CUSTOCONT_VENDA,
       C.PUNITCONT
  FROM MOV_VENDA V
  LEFT JOIN MOV_COMPRA C ON C.NUMITEMCOMPRA = V.NUMITEMCOMPRA
 WHERE V.CUSTOCONT_VENDA <> C.PUNITCONT
    OR V.CUSTOFINEST_VENDA <> C.PUNITCONT;

--UPDATE
MERGE INTO PCMOV M
USING (
  WITH MOV_COMPRA AS
   (SELECT M.NUMTRANSITEM NUMITEMCOMPRA, M.PUNITCONT
      FROM PCMOV M
     WHERE M.DTCANCEL IS NULL
       AND M.STATUS IN ('A', 'AB')
       AND M.CODFILIAL IN ('5', '6', '9', '10')
       AND M.CODOPER = 'E'),
  MOV_VENDA AS
   (SELECT M.NUMTRANSITEM NUMITEMVENDA,
           (SELECT MIN(C.NUMTRANSITEM)
              FROM PCMOV C
             WHERE C.CODPROD = M.CODPROD
               AND C.CODFILIAL = M.CODFILIAL
               AND C.DTMOV >= M.DTMOV
               AND C.CODOPER = 'E'
               AND C.DTCANCEL IS NULL) NUMITEMCOMPRA,
           M.CUSTOCONT CUSTOCONT_VENDA,
           M.CUSTOFINEST CUSTOFINEST_VENDA
      FROM PCMOV M
     WHERE M.DTCANCEL IS NULL
       AND M.STATUS IN ('A', 'AB')
       AND M.CODFILIAL IN ('5', '6', '9', '10')
       AND M.CODOPER IN ('S', 'SB')
       AND M.CODFISCAL NOT IN (5117, 6117, 5923, 6923)
       AND M.DTMOV >= TRUNC(SYSDATE) - 2)
  
  SELECT V.NUMITEMVENDA, C.PUNITCONT
    FROM MOV_VENDA V
    LEFT JOIN MOV_COMPRA C ON C.NUMITEMCOMPRA = V.NUMITEMCOMPRA
   WHERE V.CUSTOCONT_VENDA <> C.PUNITCONT
      OR V.CUSTOFINEST_VENDA <> C.PUNITCONT) X 
   ON (M.NUMTRANSITEM = X.NUMITEMVENDA) 
   WHEN MATCHED THEN
    UPDATE
       SET M.CUSTOCONT   = X.PUNITCONT,
           M.CUSTOFINEST = X.PUNITCONT,
           M.CUSTOFIN    = X.PUNITCONT,
           M.CUSTOULTENT = X.PUNITCONT,
           M.VALORULTENT = X.PUNITCONT;
/*****************************************************/

/*****CORRECAO CUSTO DEVOLUCOES DE CLIENTES ******/
--CONSULTA
WITH DEV_FORNECEDOR AS
 (SELECT M.DTMOV DTDEVFORNEC,
         M.NUMTRANSITEM NUMITEMDEVFORNEC,
         M.CODFISCAL CODDEVFORNEC,
         M.PUNITCONT PRECODEVFORNEC
    FROM PCMOV M
   WHERE M.DTCANCEL IS NULL
     AND M.STATUS IN ('A', 'AB')
     AND M.CODFILIAL IN ('5', '6', '9', '10')
     AND M.CODOPER = 'SD'),
DEV_CLIENTE AS
 (SELECT M.CODFILIAL,
         M.NUMTRANSITEM NUMITEMDEVCLI,
         (SELECT MIN(C.NUMTRANSITEM)
            FROM PCMOV C
           WHERE C.CODPROD = M.CODPROD
             AND C.CODFILIAL = M.CODFILIAL
             AND C.DTMOV >= M.DTMOV
             AND C.CODOPER = 'SD'
             AND C.DTCANCEL IS NULL) NUMITEMDEVFORNEC,
         M.DTMOV DTDEVCLI,
         M.CODFISCAL CODDEVCLI,
         M.CODPROD,
         M.DESCRICAO,
         M.CUSTOCONT CUSTOCONT_DEVCLI,
         M.CUSTOFINEST CUSTOFINEST_DEVCLI
    FROM PCMOV M
   WHERE M.DTCANCEL IS NULL
     AND M.STATUS IN ('A', 'AB')
     AND M.CODFILIAL IN ('5', '6', '9', '10')
     AND M.CODOPER IN ('ED')
     AND M.CODFISCAL NOT IN (1117, 2117, 1923, 2923))

SELECT C.CODFILIAL,
       C.NUMITEMDEVCLI,
       C.DTDEVCLI,
       F.DTDEVFORNEC,
       C.CODDEVCLI,
       F.CODDEVFORNEC,
       C.CODPROD,
       C.DESCRICAO,
       C.CUSTOFINEST_DEVCLI,
       C.CUSTOCONT_DEVCLI,
       F.PRECODEVFORNEC
  FROM DEV_CLIENTE C
  LEFT JOIN DEV_FORNECEDOR F ON F.NUMITEMDEVFORNEC = C.NUMITEMDEVFORNEC
 WHERE C.CUSTOCONT_DEVCLI <> F.PRECODEVFORNEC
    OR C.CUSTOFINEST_DEVCLI <> F.PRECODEVFORNEC;

---UPDATE DEVOLUCOES DE CLIENTES--
MERGE INTO PCMOV M
USING (
  WITH DEV_FORNECEDOR AS
   (SELECT M.NUMTRANSITEM NUMITEMDEVFORNEC,
           M.PUNITCONT PRECODEVFORNEC
      FROM PCMOV M
     WHERE M.DTCANCEL IS NULL
       AND M.STATUS IN ('A', 'AB')
       AND M.CODFILIAL IN ('5', '6', '9', '10')
       AND M.CODOPER = 'SD'),
  DEV_CLIENTE AS
   (SELECT M.NUMTRANSITEM NUMITEMDEVCLI,
           (SELECT MIN(C.NUMTRANSITEM)
              FROM PCMOV C
             WHERE C.CODPROD = M.CODPROD
               AND C.CODFILIAL = M.CODFILIAL
               AND C.DTMOV >= M.DTMOV
               AND C.CODOPER = 'SD'
               AND C.DTCANCEL IS NULL) NUMITEMDEVFORNEC,
           M.CUSTOCONT CUSTOCONT_DEVCLI,
           M.CUSTOFINEST CUSTOFINEST_DEVCLI
      FROM PCMOV M
     WHERE M.DTCANCEL IS NULL
       AND M.STATUS IN ('A', 'AB')
       AND M.CODFILIAL IN ('5', '6', '9', '10')
       AND M.CODOPER IN ('ED')
       AND M.CODFISCAL NOT IN (1117, 2117, 1923, 2923))
  SELECT C.NUMITEMDEVCLI,
         F.PRECODEVFORNEC
    FROM DEV_CLIENTE C
    LEFT JOIN DEV_FORNECEDOR F ON F.NUMITEMDEVFORNEC = C.NUMITEMDEVFORNEC
   WHERE C.CUSTOCONT_DEVCLI <> F.PRECODEVFORNEC
      OR C.CUSTOFINEST_DEVCLI <> F.PRECODEVFORNEC) X 
   ON (M.NUMTRANSITEM = X.NUMITEMDEVCLI) 
   WHEN MATCHED THEN
    UPDATE
       SET M.CUSTOCONT   = X.PRECODEVFORNEC,
           M.CUSTOFINEST = X.PRECODEVFORNEC,
           M.CUSTOFIN    = X.PRECODEVFORNEC
/*****************************************************/
