--DUPLICATAS ANALÍTICO
SELECT P.ROWID,
       C.CLIENTE, P.VALORESTORNO,
       P.PRESTTEF,
       P.NUMTRANSVENDA,
       P.NUMTRANS,
       P.OBSTITULO,
       P.DTPAG,
       P.NSUHOST,
       P.NSUTEF,
       P.DTTRANSACAOCC,
       P.NUMRESUMO,
       P.PDV,
       P.CODBAIXACARTAOREDE,
       P.DTFECHA,
       P.*
  FROM PCPREST P
  LEFT JOIN PCCLIENT C ON P.CODCLI = C.CODCLI --18/01/2023 - FALTA DEVOLUÇÃO - FAVOR VERIFICAR / 16/01/2023 - DEVOLUCAO PELA MANDAE - PRAZO 27/01/2023
 WHERE P.NUMTRANSVENDA IN (11595362)  --11614812 b2b
--DUPLIC (76742 ) / NSU ( 379565007 )
--P.CODCLI = 8998 AND 
--DTEMISSAO >= TRUNC(SYSDATE) - 2 AND P.CODFILIAL = '2' AND P.CODCOB LIKE 'B2%'
--(P.NSUTEF IN (754037433) OR P.NSUHOST IN (754037433))
--P.VALOR = 92.97 AND DTEMISSAO >= TRUNC(SYSDATE) - 4 AND P.CODFILIAL = '1'
 ORDER BY DUPLIC, TO_NUMBER(PREST);

--CREDITOS_ABERTOS
WITH TRANSACAO_VENDA_DEVOLVIDA AS
 (SELECT NUMTRANSENT, MAX(M.NUMTRANSDEV) AS NUMTRANSVENDA
    FROM PCMOV M
   WHERE NVL(NUMTRANSDEV, 0) <> 0
     AND NVL(NUMTRANSDEV, 0) <> 0
   GROUP BY NUMTRANSENT)
SELECT (C.CODCLI || '-' || T.CLIENTE) CLIENTE,
       C.VALOR AS VALOR_CREDITO,
       C.DTLANC DTLANC_CRED,
       D.NUMTRANSVENDA
  FROM PCCRECLI C
  JOIN PCCLIENT T ON C.CODCLI = T.CODCLI
  JOIN TRANSACAO_VENDA_DEVOLVIDA D ON C.NUMTRANSENTDEVCLI = D.NUMTRANSENT
 WHERE --C.DTDESCONTO IS NULL AND 
--AND T.CODCLIPRINC = 459050
 T.CODCLI = 355192;

--CORREÇÃO CLIENTES
SELECT C.ROWID, C.* FROM PCCLIENT C WHERE C.CLIENTE LIKE 'PAYMEE%';

--UPDATE OBSERVACAO TITULO
UPDATE PCPREST
   SET OBSTITULO = '23/01/2023 - FALTA DEVOLUÇÃO - FAVOR VERIFICAR'
 WHERE DTPAG IS NULL
   --AND CODCLI = 25053 --AND codfilial = '9'
   AND NUMTRANSVENDA IN (11573550);

--UPDATE PRESTTEF
MERGE INTO PCPREST P
USING (SELECT NUMTRANSVENDA,
              DUPLIC,
              PREST,
              PRESTTEF,
              (TO_NUMBER(PREST) - 2) PRESTTEFCALC,
              VALOR,
              CODCOB,
              VPAGO
         FROM PCPREST P
        WHERE VPAGO IS NULL
          AND PRESTTEF IS NULL
          AND P.NUMTRANSVENDA IN (11571632)
        ORDER BY DUPLIC, TO_NUMBER(PREST)) X
ON (P.NUMTRANSVENDA = X.NUMTRANSVENDA AND P.PREST = X.PREST)
WHEN MATCHED THEN
  UPDATE SET P.PRESTTEF = X.PRESTTEFCALC;
