--FORNECEDORES SEM CONTA CONTABIL CADASTRADA--
WITH FORNEC_CONTABIL AS
 (SELECT (CODFILIAL || '-' || CODFORNEC) AS COD_ID FROM BROKERCONTABIL)
SELECT L.CODFILIAL,
       L.DTEMISSAO, L.DTLANC,
       L.RECNUM,
       L.CODCONTA,
       C.CONTA,
       L.NUMNOTA, 
      -- L.VPAGO,
       L.CODFORNEC,
       F.FORNECEDOR,
       F.CGC,
       F.ESTADO
  FROM PCLANC L
  LEFT JOIN PCFORNEC F
    ON L.CODFORNEC = F.CODFORNEC
  LEFT JOIN PCCONTA C
    ON L.CODCONTA = C.CODCONTA
  LEFT JOIN FORNEC_CONTABIL B
    ON (L.CODFILIAL || '-' || L.CODFORNEC) = B.COD_ID
 WHERE L.TIPOPARCEIRO = 'F'
   AND C.GRUPOCONTA NOT IN (820, 810, 140, 680, 650, 300, 200)
   AND L.CODCONTA NOT IN (410105, 620107, 530106)
   AND L.CODFORNEC NOT IN (1, 7543, 8215)
   AND L.TIPOLANC = 'C'
   AND L.DTEMISSAO BETWEEN '01-JAN-2020' AND ADD_MONTHS( LAST_DAY( TRUNC(SYSDATE) ), 0 )
   AND B.COD_ID IS NULL
 GROUP BY L.CODFILIAL,
          L.DTEMISSAO,L.DTLANC,
          L.RECNUM,
          L.CODCONTA,
          C.CONTA,
          L.NUMNOTA,  
         -- L.VPAGO,
          L.CODFORNEC,
          F.FORNECEDOR,
          F.CGC,
          F.ESTADO
 ORDER BY F.FORNECEDOR;
 
   

SELECT ROWID, F.CGC, F.* FROM PCFORNEC F WHERE CODFORNEC = 9745; 

SELECT F.CGC, F.* FROM PCFORNEC F WHERE CGC = '12.621.274/0005-00'; 



WITH FORNEC_CONTABIL AS
 (SELECT (CODFILIAL || '-' || CODFORNEC) AS COD_ID FROM BROKERCONTABIL)
SELECT L.CODFORNEC,
       F.FORNECEDOR,
       F.CGC,
       F.ESTADO
  FROM PCLANC L
  LEFT JOIN PCFORNEC F
    ON L.CODFORNEC = F.CODFORNEC
  LEFT JOIN PCCONTA C
    ON L.CODCONTA = C.CODCONTA
  LEFT JOIN FORNEC_CONTABIL B
    ON (L.CODFILIAL || '-' || L.CODFORNEC) = B.COD_ID
 WHERE L.TIPOPARCEIRO = 'F'
   AND C.GRUPOCONTA NOT IN (820, 810, 140, 680, 650, 300, 200)
   AND L.CODCONTA NOT IN (410105, 620107, 530106)
   AND L.CODFORNEC NOT IN (1, 7543, 82215)
   AND L.TIPOLANC = 'C'
   AND L.DTEMISSAO BETWEEN '01-JAN-2020' AND ADD_MONTHS( LAST_DAY( TRUNC(SYSDATE) ), -1 )
   AND B.COD_ID IS NULL
 GROUP BY L.CODFORNEC,
          F.FORNECEDOR,
          F.CGC,
          F.ESTADO
 ORDER BY F.FORNECEDOR;
