/*NOTAS DE ENTRADA COM FORNECEDORES SEM CONTA CONTABIL CADASTRADA--*/
WITH FORNEC_CONTABIL AS (
    SELECT (CODFILIAL || '-' || CODFORNEC) AS COD_ID
      FROM BROKERCONTABIL
)
SELECT E.CODFILIAL,
       E.DTEMISSAO,
       E.DTENT,
       E.CODCONT AS CODCONTA,
       C.CONTA,
       E.NUMNOTA,
       E.VLTOTAL,
       E.CODFORNEC,
       F.FORNECEDOR,
       F.CGC,
       F.ESTADO
  FROM PCNFENT E
  LEFT JOIN PCFORNEC F ON E.CODFORNEC = F.CODFORNEC
  LEFT JOIN PCCONTA C ON E.CODCONT = C.CODCONTA
  LEFT JOIN FORNEC_CONTABIL B ON (E.CODFILIAL || '-' || E.CODFORNEC) = B.COD_ID
 WHERE E.DTENT BETWEEN '01-JAN-2020' AND ADD_MONTHS (LAST_DAY (TRUNC (SYSDATE)), 0)
   AND E.TIPODESCARGA NOT IN (
    '6', '7', 'T'
)
     /*RETIRAR NOTAS DE DEVOLUÇÃO DE CLIENTE*/
   AND E.CODFILIAL IN (
    1, 2, 5, 6, 7
)
     /*RETIRAR NOTAS DE DEVOLUÇÃO DE CLIENTE*/
   AND E.ESPECIE NOT IN (
    'OE'
)
     /*SOMENTE FILIAIS FISCAIS*/
   AND B.COD_ID IS NULL
     /*SOMENTE LANÇAMENTOS QUE NÃO TENHAM CONTA CONTABIL DO FORNECEDOR*/
 ORDER BY E.CODFORNEC;
/
/*ANALISE DE FORNECEDORES*/
SELECT ROWID,
       F.CGC,
       F.*
  FROM PCFORNEC F
 WHERE CODFORNEC = 9745;
/
SELECT F.CGC,
       F.*
  FROM PCFORNEC F
 WHERE CGC = '12.621.274/0005-00';
/
/*FORNECEDORES SEM CONTA CONTABIL CADASTRADA*/
WITH FORNEC_CONTABIL AS (
    SELECT (CODFILIAL || '-' || CODFORNEC) AS COD_ID
      FROM BROKERCONTABIL
)
SELECT *
  FROM (
    SELECT (
        CASE
            WHEN E.CODFILIAL IN (
                1, 2, 7
            ) THEN 'JC BROTHERS'
            WHEN E.CODFILIAL = 6 THEN 'BROKER CORP'
            ELSE 'JFF'
        END
    ) AS FILIAL,
           E.CODFORNEC,
           F.FORNECEDOR,
           F.CGC,
           F.ESTADO
      FROM PCNFENT E
      LEFT JOIN PCFORNEC F ON E.CODFORNEC = F.CODFORNEC
      LEFT JOIN PCCONTA C ON E.CODCONT = C.CODCONTA
      LEFT JOIN FORNEC_CONTABIL B ON (E.CODFILIAL || '-' || E.CODFORNEC) = B.COD_ID
     WHERE E.DTENT BETWEEN '01-JAN-2020' AND ADD_MONTHS (LAST_DAY (TRUNC (SYSDATE)), - 1)
       AND E.TIPODESCARGA NOT IN (
        '6', '7', 'T'
    )
     /*RETIRAR NOTAS DE DEVOLUÇÃO DE CLIENTE*/
       AND E.CODFILIAL IN (
        1, 2, 5, 6, 7
    )
     /*SOMENTE FILIAIS FISCAIS*/
       AND B.COD_ID IS NULL
     /*SOMENTE LANÇAMENTOS QUE NÃO TENHAM CONTA CONTABIL DO FORNECEDOR*/
)
 GROUP BY FILIAL,
          CODFORNEC,
          FORNECEDOR,
          CGC,
          ESTADO
 ORDER BY FILIAL,
          CODFORNEC;
/
/*ANALISE DE CONTAS CONTABEIS DE FORNECEDORES*/
SELECT DISTINCT F.CODFORNEC,
                F.FORNECEDOR,
                F.CGC,
                F.ESTADO,
                B.CODCONTAB
  FROM PCFORNEC F
  LEFT JOIN BROKERCONTABIL B ON F.CODFORNEC = B.CODFORNEC
 WHERE NVL (B.CODFILIAL, 0) IN (
    0, 1, 2, 7
)
   AND F.CODFORNEC IN (
    9193, 9804
)
 GROUP BY F.CODFORNEC,
          F.FORNECEDOR,
          F.CGC,
          F.ESTADO,
          B.CODCONTAB
 ORDER BY F.FORNECEDOR;
/