/*-----INSERÇÃO DO GÊNERO FISCAL NCM NOS PRODUTOS NULOS------*/
SELECT ROWID, NBM, CODNCMEX, CODGENEROFISCAL, DTEXCLUSAO, PCPRODUT.* FROM PCPRODUT WHERE PCPRODUT.CODGENEROFISCAL IS NULL;

--UPDATE
UPDATE PCPRODUT
   SET PCPRODUT.CODGENEROFISCAL = SUBSTR(NBM, 1, 2)
 WHERE PCPRODUT.CODGENEROFISCAL IS NULL;

/*-----CORREÇÃO DO GÊNERO FISCAL NCM------*/
SELECT NBM, CODNCMEX, CODGENEROFISCAL, PCPRODUT.* FROM PCPRODUT WHERE PCPRODUT.CODGENEROFISCAL <> SUBSTR(NBM, 1, 2);

--UPDATE
UPDATE PCPRODUT
   SET PCPRODUT.CODGENEROFISCAL = SUBSTR(NBM, 1, 2)
 WHERE PCPRODUT.CODGENEROFISCAL <> SUBSTR(NBM, 1, 2);

--correcao
UPDATE PCPRODUT
   SET PCPRODUT.NBM = '61149090'
 WHERE PCPRODUT.CODGENEROFISCAL IS NULL  AND CODNCMEX = '61149090.';
