/*-----INSERÇÃO DO GÊNERO FISCAL NCM NOS PRODUTOS NULOS------*/
SELECT *
  FROM PCPRODUT
 WHERE PCPRODUT.CODGENEROFISCAL IS NULL;
/
UPDATE PCPRODUT
   SET
    PCPRODUT.CODGENEROFISCAL = SUBSTR (NBM, 1, 2)
 WHERE PCPRODUT.CODGENEROFISCAL IS NULL;
/


/*-----CORREÇÃO DO GÊNERO FISCAL NCM------*/
SELECT *
  FROM PCPRODUT
 WHERE PCPRODUT.CODGENEROFISCAL <> SUBSTR (NBM, 1, 2);
/
UPDATE PCPRODUT
   SET
    PCPRODUT.CODGENEROFISCAL = SUBSTR (NBM, 1, 2)
 WHERE PCPRODUT.CODGENEROFISCAL <> SUBSTR (NBM, 1, 2);
/           