---PRODUTOS QUE ESTÃO COMO FL MAS NÃO DEVERIAM ESTAR
WITH MOVIMENTADOS AS
 (SELECT M.CODPROD,
         MAX(M.DTMOV) MAIORDTMOV
    FROM PCMOV M
   GROUP BY M.CODPROD),
ESTOQUE AS
 (SELECT E.CODPROD,
         NVL(SUM(E.QTESTGER), 0) QTESTOQUE
    FROM PCEST E
   WHERE E.QTESTGER > 0
   GROUP BY E.CODPROD)
SELECT P.CODPROD,
       P.DESCRICAO,
       P.DTCADASTRO,
       M.MAIORDTMOV,
       NVL(E.QTESTOQUE, 0) QTESTOQUE,
       P.OBS2
  FROM PCPRODUT P
  LEFT JOIN MOVIMENTADOS M ON M.CODPROD = P.CODPROD
  LEFT JOIN ESTOQUE E ON E.CODPROD = P.CODPROD
 WHERE P.OBS2 = 'FL'
   AND (M.MAIORDTMOV >= '01/01/2022' OR NVL(E.QTESTOQUE, 0) <> 0 OR
       P.DTCADASTRO >= '01/01/2024');

MERGE INTO PCPRODUT P
USING (
  WITH MOVIMENTADOS AS
   (SELECT M.CODPROD,
           MAX(M.DTMOV) MAIORDTMOV
      FROM PCMOV M
     GROUP BY M.CODPROD),
  ESTOQUE AS
   (SELECT E.CODPROD,
           NVL(SUM(E.QTESTGER), 0) QTESTOQUE
      FROM PCEST E
     WHERE E.QTESTGER > 0
     GROUP BY E.CODPROD)
  SELECT P.CODPROD,
         P.DESCRICAO,
         P.DTCADASTRO,
         M.MAIORDTMOV,
         NVL(E.QTESTOQUE, 0) QTESTOQUE,
         P.OBS2
    FROM PCPRODUT P
    LEFT JOIN MOVIMENTADOS M ON M.CODPROD = P.CODPROD
    LEFT JOIN ESTOQUE E ON E.CODPROD = P.CODPROD
   WHERE P.OBS2 = 'FL'
     AND (M.MAIORDTMOV >= '01/01/2022' OR NVL(E.QTESTOQUE, 0) <> 0 OR
         P.DTCADASTRO >= '01/01/2024')) X ON (P.CODPROD = X.CODPROD) WHEN MATCHED THEN
    UPDATE SET P.OBS2 = NULL;

---PRODUTOS QUE ESTÃO ATIVOS MAS NÃO DEVERIAM ESTAR FL
WITH MOVIMENTADOS AS
 (SELECT M.CODPROD,
         MAX(M.DTMOV) MAIORDTMOV
    FROM PCMOV M
   GROUP BY M.CODPROD),
ESTOQUE AS
 (SELECT E.CODPROD,
         NVL(SUM(E.QTESTGER), 0) QTESTOQUE
    FROM PCEST E
   WHERE E.QTESTGER > 0
   GROUP BY E.CODPROD)
SELECT P.CODPROD,
       P.DESCRICAO,
       P.DTCADASTRO,
       M.MAIORDTMOV,
       NVL(E.QTESTOQUE, 0) QTESTOQUE,
       P.OBS2
  FROM PCPRODUT P
  LEFT JOIN MOVIMENTADOS M ON M.CODPROD = P.CODPROD
  LEFT JOIN ESTOQUE E ON E.CODPROD = P.CODPROD
 WHERE (NVL(P.OBS2, 'A') <> 'FL' AND P.OBS2 <> '  ')
   AND (M.MAIORDTMOV < '01/01/2022' OR NVL(E.QTESTOQUE, 0) = 0 OR
       P.DTCADASTRO < '01/01/2024');
