/*Relatório Produtos sem flag Gera ICMS no livro fiscal   */
WITH NCM_ICMS_OU_ST AS
 (SELECT DISTINCT P.CODNCMEX, F.GERAICMSLIVROFISCAL GERAICMS
    FROM PCPRODUT P
    JOIN PCPRODFILIAL F ON P.CODPROD = F.CODPROD
   WHERE F.CODFILIAL = '12'
     AND F.GERAICMSLIVROFISCAL IS NOT NULL)
SELECT p.rowid, 
       T.DTCADASTRO,
       P.CODFILIAL,
       T.CODPRODMASTER,
       P.CODPROD,
       T.DESCRICAO,
       T.CODNCMEX,
       P.GERAICMSLIVROFISCAL REGIME_ICMS,
       P.GERAICMSLIVROFISCALENT ICMS_ENT,
       P.GERAICMSLIVROFISCALDEVFORNEC ICMS_DEV,
       N.GERAICMS
  FROM PCPRODFILIAL P
  JOIN PCPRODUT T ON T.CODPROD = P.CODPROD
  LEFT JOIN NCM_ICMS_OU_ST N ON T.CODNCMEX = N.CODNCMEX
 WHERE ((P.GERAICMSLIVROFISCAL IS NULL OR
       P.GERAICMSLIVROFISCAL <> N.GERAICMS OR
       (P.GERAICMSLIVROFISCALENT IS NULL OR
       P.GERAICMSLIVROFISCALENT <> N.GERAICMS)) OR
       (P.GERAICMSLIVROFISCALDEVFORNEC IS NULL OR
       P.GERAICMSLIVROFISCALDEVFORNEC <> N.GERAICMS))
   AND T.DTCADASTRO <= TRUNC(SYSDATE)
   AND T.DTEXCLUSAO IS NULL
   AND T.CODPRODMASTER IS NOT NULL
	 AND P.GERAICMSLIVROFISCAL IS NULL 
	 AND P.CODFILIAL IN ('1','11','12')
	 --AND T.CODNCMEX  IN ( '82142000.', '90251199.', '96032900.')
	 --AND P.CODPROD IN (821089, 821090, 821091, 821092)
 ORDER BY T.CODNCMEX, T.DTCADASTRO DESC, P.CODPROD, TO_NUMBER(P.CODFILIAL);
/
---UPDATE MARGE---
MERGE
  INTO PCPRODFILIAL F
  USING (
  WITH NCM_ICMS_OU_ST AS
   (SELECT DISTINCT P.CODNCMEX, F.GERAICMSLIVROFISCAL GERAICMS
      FROM PCPRODUT P
      JOIN PCPRODFILIAL F ON P.CODPROD = F.CODPROD
     WHERE F.CODFILIAL = '12'
       AND F.GERAICMSLIVROFISCAL IS NOT NULL)
  SELECT P.CODFILIAL,
         P.CODPROD,
         T.DESCRICAO,
         T.CODNCMEX,
         P.GERAICMSLIVROFISCAL REGIME_ICMS,
         N.GERAICMS
    FROM PCPRODFILIAL P
    JOIN PCPRODUT T ON T.CODPROD = P.CODPROD
    JOIN NCM_ICMS_OU_ST N ON T.CODNCMEX = N.CODNCMEX
   WHERE ((P.GERAICMSLIVROFISCAL IS NULL OR
         P.GERAICMSLIVROFISCAL <> N.GERAICMS OR
         (P.GERAICMSLIVROFISCALENT IS NULL OR
         P.GERAICMSLIVROFISCALENT <> N.GERAICMS)) OR
         (P.GERAICMSLIVROFISCALDEVFORNEC IS NULL OR
         P.GERAICMSLIVROFISCALDEVFORNEC <> N.GERAICMS))
      AND T.DTCADASTRO <= TRUNC(SYSDATE)
      AND T.DTEXCLUSAO IS NULL
      AND T.CODPRODMASTER IS NOT NULL
      AND P.GERAICMSLIVROFISCAL IS NULL ) X 
	ON (F.CODPROD = X.CODPROD AND F.CODFILIAL = X.CODFILIAL AND F.CODFILIAL IN ('1','12'))
	WHEN MATCHED THEN UPDATE SET F.GERAICMSLIVROFISCAL = X.GERAICMS, F.GERAICMSLIVROFISCALENT = X.GERAICMS, F.GERAICMSLIVROFISCALDEVFORNEC = X.GERAICMS;

------FILIAL 11
WITH NCM_ICMS_OU_ST AS
 (SELECT DISTINCT P.CODNCMEX, F.GERAICMSLIVROFISCAL GERAICMS
    FROM PCPRODUT P
    JOIN PCPRODFILIAL F ON P.CODPROD = F.CODPROD
   WHERE F.CODFILIAL = '11'
     AND F.GERAICMSLIVROFISCAL IS NOT NULL)
SELECT p.rowid, 
       T.DTCADASTRO,
       P.CODFILIAL,
       T.CODPRODMASTER,
       P.CODPROD,
       T.DESCRICAO,
       T.CODNCMEX,
       P.GERAICMSLIVROFISCAL REGIME_ICMS,
       P.GERAICMSLIVROFISCALENT ICMS_ENT,
       P.GERAICMSLIVROFISCALDEVFORNEC ICMS_DEV,
       N.GERAICMS
  FROM PCPRODFILIAL P
  JOIN PCPRODUT T ON T.CODPROD = P.CODPROD
  LEFT JOIN NCM_ICMS_OU_ST N ON T.CODNCMEX = N.CODNCMEX
 WHERE ((P.GERAICMSLIVROFISCAL IS NULL OR
       P.GERAICMSLIVROFISCAL <> N.GERAICMS OR
       (P.GERAICMSLIVROFISCALENT IS NULL OR
       P.GERAICMSLIVROFISCALENT <> N.GERAICMS)) OR
       (P.GERAICMSLIVROFISCALDEVFORNEC IS NULL OR
       P.GERAICMSLIVROFISCALDEVFORNEC <> N.GERAICMS))
   AND T.DTCADASTRO <= TRUNC(SYSDATE)
   AND T.DTEXCLUSAO IS NULL
   AND T.CODPRODMASTER IS NOT NULL
	 AND P.GERAICMSLIVROFISCAL IS NULL 
	 AND P.CODFILIAL = '11'
	 --AND T.CODNCMEX NOT IN ('39249000.2', 39249000.)
	 --AND P.CODPROD IN (821089, 821090, 821091, 821092)
 ORDER BY T.CODNCMEX, T.DTCADASTRO DESC, P.CODPROD, TO_NUMBER(P.CODFILIAL);
/
---UPDATE MARGE---
MERGE
  INTO PCPRODFILIAL F
  USING (
  WITH NCM_ICMS_OU_ST AS
   (SELECT DISTINCT P.CODNCMEX, F.GERAICMSLIVROFISCAL GERAICMS
      FROM PCPRODUT P
      JOIN PCPRODFILIAL F ON P.CODPROD = F.CODPROD
     WHERE F.CODFILIAL = '11'
       AND F.GERAICMSLIVROFISCAL IS NOT NULL)
  SELECT P.CODFILIAL,
         P.CODPROD,
         T.DESCRICAO,
         T.CODNCMEX,
         P.GERAICMSLIVROFISCAL REGIME_ICMS,
         N.GERAICMS
    FROM PCPRODFILIAL P
    JOIN PCPRODUT T ON T.CODPROD = P.CODPROD
    JOIN NCM_ICMS_OU_ST N ON T.CODNCMEX = N.CODNCMEX
   WHERE P.CODFILIAL = '11'
	 AND ((P.GERAICMSLIVROFISCAL IS NULL OR
         P.GERAICMSLIVROFISCAL <> N.GERAICMS OR
         (P.GERAICMSLIVROFISCALENT IS NULL OR
         P.GERAICMSLIVROFISCALENT <> N.GERAICMS)) OR
         (P.GERAICMSLIVROFISCALDEVFORNEC IS NULL OR
         P.GERAICMSLIVROFISCALDEVFORNEC <> N.GERAICMS))
     AND T.DTCADASTRO <= TRUNC(SYSDATE)
     AND T.DTEXCLUSAO IS NULL 
     --AND P.GERAICMSLIVROFISCAL = 'S'
		 --AND P.GERAICMSLIVROFISCAL = null
     --AND T.CODNCMEX <> '39249000.'
     AND T.CODPRODMASTER IS NOT NULL) X 
	ON (F.CODPROD = X.CODPROD AND F.CODFILIAL = X.CODFILIAL) 
	WHEN MATCHED THEN UPDATE SET F.GERAICMSLIVROFISCAL = X.GERAICMS, F.GERAICMSLIVROFISCALENT = X.GERAICMS, F.GERAICMSLIVROFISCALDEVFORNEC = X.GERAICMS;


UPDATE PCPRODFILIAL
   SET GERAICMSLIVROFISCAL = 'N', GERAICMSLIVROFISCALENT = 'N', GERAICMSLIVROFISCALDEVFORNEC = 'N'
 WHERE GERAICMSLIVROFISCALENT = 'S'
 AND CODFILIAL <> '11'
   AND CODPROD IN (826954);

UPDATE PCPRODFILIAL
   SET GERAICMSLIVROFISCAL = 'S', GERAICMSLIVROFISCALENT = 'S', GERAICMSLIVROFISCALDEVFORNEC = 'S'
 WHERE GERAICMSLIVROFISCALENT = 'S'
   --AND CODFILIAL = '11'
   AND CODPROD IN (826954) ;

SELECT P.ROWID, T.DTCADASTRO,
       P.CODFILIAL,
       T.CODPRODMASTER,
       P.CODPROD,
       T.DESCRICAO,
       T.CODNCMEX,
       P.GERAICMSLIVROFISCAL REGIME_ICMS,
       P.GERAICMSLIVROFISCALENT ICMS_ENT,
       P.GERAICMSLIVROFISCALDEVFORNEC ICMS_DEV
  FROM PCPRODFILIAL P, PCPRODUT T
 WHERE T.CODPROD = P.CODPROD
   AND P.CODPROD IN (824487);
	 
	 SELECT P.ROWID, T.DTCADASTRO,
       P.CODFILIAL,
       T.CODPRODMASTER,
       P.CODPROD,
       T.DESCRICAO,
       T.CODNCMEX,
       P.GERAICMSLIVROFISCAL REGIME_ICMS,
       P.GERAICMSLIVROFISCALENT ICMS_ENT,
       P.GERAICMSLIVROFISCALDEVFORNEC ICMS_DEV
  FROM PCPRODFILIAL P, PCPRODUT T
 WHERE T.CODPROD = P.CODPROD
   AND T.CODNCMEX IN ('42029200.2')
	 AND P.CODFILIAL NOT IN ('11')
	 AND P.GERAICMSLIVROFISCAL = 'S';
	 
MERGE
  INTO PCPRODFILIAL F
  USING (SELECT T.DTCADASTRO,
       P.CODFILIAL,
       T.CODPRODMASTER,
       P.CODPROD,
       T.DESCRICAO,
       T.CODNCMEX,
       P.GERAICMSLIVROFISCAL REGIME_ICMS,
       P.GERAICMSLIVROFISCALENT ICMS_ENT,
       P.GERAICMSLIVROFISCALDEVFORNEC ICMS_DEV
  FROM PCPRODFILIAL P, PCPRODUT T
 WHERE T.CODPROD = P.CODPROD
   AND T.CODNCMEX IN ('42029200.2')
	 AND P.CODFILIAL NOT IN ('11')
	 AND P.GERAICMSLIVROFISCAL = 'S') X
	 ON (F.CODPROD = X.CODPROD AND F.CODFILIAL = X.CODFILIAL) 
	WHEN MATCHED THEN UPDATE SET F.GERAICMSLIVROFISCAL = 'N', F.GERAICMSLIVROFISCALENT = 'N', F.GERAICMSLIVROFISCALDEVFORNEC = 'N';
