WITH RATEIO AS
 (SELECT RECNUM,
         ROUND(SUM(R.PERCRATEIO), 2) PERCRATEIO,
         ROUND(SUM(VALOR), 2) VLRATEIO
    FROM PCRATEIOCENTROCUSTO R
   GROUP BY RECNUM)

SELECT L.DTLANC,
       L.DTCOMPETENCIA,
       L.CODCONTA,
       L.RECNUM,
       R.PERCRATEIO,
       L.VALOR,
       R.VLRATEIO,
       (L.VALOR - R.VLRATEIO) DIF
  FROM PCLANC L
  JOIN RATEIO R ON R.RECNUM = L.RECNUM
 WHERE (L.VALOR <> R.VLRATEIO OR R.PERCRATEIO <> 100)
 ORDER BY PERCRATEIO,
          L.DTCOMPETENCIA DESC
