WITH ADIANTAMENTO AS
 (SELECT CODFILIAL, RECNUM, CODFORNEC, SUM(VALOR) AS VALOR_ADIANTADO
    FROM PCLANC
   WHERE ADIANTAMENTO = 'S'
   GROUP BY CODFILIAL, RECNUM, CODFORNEC),
BAIXA_ADIANTAMENTO AS
 (SELECT RECNUMADIANTAMENTO, SUM(VALOR) AS VALOR_BAIXADO
    FROM PCLANCADIANTFORNEC
   GROUP BY RECNUMADIANTAMENTO),
LANC_ABERTOS AS
 (SELECT CODFILIAL, RECNUM, CODFORNEC, SUM(VALOR) AS VALOR_ABERTO
    FROM PCLANC
   WHERE DTPAGTO IS NULL
     AND TIPOLANC = 'C'
     AND ADIANTAMENTO = 'N'
   GROUP BY CODFILIAL, RECNUM, CODFORNEC)
SELECT *
  FROM (SELECT L.CODFILIAL,
               L.CODFORNEC,
               F.FORNECEDOR,
               SUM(A.VALOR_ADIANTADO) AS VALOR_ADIANTADO,
               SUM(B.VALOR_BAIXADO) AS VALOR_BAIXADO,
               (SUM(A.VALOR_ADIANTADO) - SUM(B.VALOR_BAIXADO)) AS SALDO,
               SUM(LA.VALOR_ABERTO) AS VALOR_ABERTO
          FROM PCLANC L
         INNER JOIN PCFORNEC F
            ON L.CODFORNEC = F.CODFORNEC
          LEFT JOIN LANC_ABERTOS LA
            ON L.RECNUM = LA.RECNUM
          LEFT JOIN ADIANTAMENTO A
            ON L.RECNUM = A.RECNUM
          LEFT JOIN BAIXA_ADIANTAMENTO B
            ON A.RECNUM = B.RECNUMADIANTAMENTO
         GROUP BY L.CODFILIAL, L.CODFORNEC, F.FORNECEDOR)
 WHERE VALOR_ABERTO <= SALDO;
