WITH LANC_POR_MES_ANO AS (
    SELECT L.RECNUM,
           TO_NUMBER(EXTRACT(YEAR FROM L.DTCOMPETENCIA) || LPAD(EXTRACT(MONTH FROM L.DTCOMPETENCIA),2,'0')) MES_DTCOMPETENCIA,
           TO_NUMBER(EXTRACT(YEAR FROM L.DTLANC) || LPAD(EXTRACT(MONTH FROM L.DTLANC),2,'0')) MES_DTLANC
      FROM PCLANC L
)
SELECT L.ROWID,
       L.DTCOMPETENCIA,
       L.DTEMISSAO,
       L.DTLANC,
       L.DTPAGTO,
       L.RECNUM,
       L.CODCONTA,
       'NF '||L.CODFORNEC || '-'|| F.FORNECEDOR FORNECEDOR,
       L.NUMNOTA,
       L.HISTORICO,
       L.VALOR
  FROM PCLANC L
  JOIN LANC_POR_MES_ANO A ON L.RECNUM = A.RECNUM
  LEFT JOIN PCCONTA C ON L.CODCONTA = C.CODCONTA
  LEFT JOIN PCFORNEC F ON F.CODFORNEC = L.CODFORNEC AND L.TIPOPARCEIRO = 'F'
 WHERE ( ( L.DTCOMPETENCIA > TRUNC(SYSDATE) AND L.DTPAGTO IS NOT NULL ) 
    OR ( L.DTCOMPETENCIA < L.DTEMISSAO - 30 ) 
    OR ( L.VALOR < 0 AND A.MES_DTCOMPETENCIA <> MES_DTLANC AND L.NUMBANCO = 41 AND L.DTCOMPETENCIA <= L.DTLANC - 15 ) ) 
   AND L.DTEMISSAO >= TO_DATE('01/01/2020' , 'DD/MM/YYYY') 
   AND L.DTESTORNOBAIXA IS NULL 
   AND L.DTLANC >= TO_DATE('01/02/2021', 'DD/MM/YYYY') 
   AND C.GRUPOCONTA NOT IN ( 240, 610, 620, 650 );
/
