WITH DESPESA AS
 (SELECT M.NUMCARR,
         SUM(M.VALOR) VLDESP
    FROM PCMOVCR M
   WHERE M.CODBANCO = 41
     AND M.ESTORNO = 'N'
     AND M.CODCOB = 'D'
     AND M.TIPO = 'D'
   GROUP BY M.NUMCARR),
PAGAMENTO AS
 (SELECT M.NUMCARR,
         SUM(M.VALOR) VLPAG
    FROM PCMOVCR M
   WHERE M.CODBANCO = 41
     AND M.CODCOB = 'D'
     AND M.ESTORNO = 'N'
     AND M.TIPO = 'C'
   GROUP BY M.NUMCARR)

SELECT M.NUMCARR,
       D.VLDESP,
       P.VLPAG,
       (D.VLDESP - P.VLPAG) DIF
  FROM PCMOVCR M
  LEFT JOIN DESPESA D ON D.NUMCARR = M.NUMCARR
  LEFT JOIN PAGAMENTO P ON P.NUMCARR = M.NUMCARR
 WHERE M.CODBANCO = 41
   AND M.CODCOB = 'D'
   AND M.ESTORNO = 'N'
   AND (D.VLDESP - P.VLPAG) <> 0
 GROUP BY M.NUMCARR,
          D.VLDESP,
          P.VLPAG
 ORDER BY M.NUMCARR;
 
 SELECT ROWID, M.* FROM PCMOVCR M WHERE CODBANCO = 41 AND NUMCARR IN (15958, 51897) ORDER BY NUMCARR, NUMTRANS;
