SELECT L.CODFILIAL,
       L.RECNUM,
       L.DTLANC,
       L.CODFORNEC,
       C.CLIENTE,
       L.HISTORICO,
       L.NUMNOTA,
       L.VALOR,
       L.NOMEFUNC
  FROM PCLANC L
  LEFT JOIN PCCLIENT C ON L.CODFORNEC = C.CODCLI
 WHERE L.CODCONTA = 100020
   AND L.DTLANC >= TRUNC (SYSDATE) - 90
 ORDER BY L.DTLANC DESC;
/