SELECT L.DTLANC,
       L.RECNUM,
       L.TIPOPARCEIRO,
       L.CODFORNEC,
       F.FORNECEDOR,
       L.NUMNOTA,
       L.VALOR,
       L.CODCONTA,
       L.CODFUNCBAIXA,
       E.NOME_GUERRA,
       L.CODROTINABAIXA
  FROM PCLANC L
  LEFT JOIN PCFORNEC F ON L.CODFORNEC = F.CODFORNEC
  LEFT JOIN PCEMPR E ON L.CODFUNCBAIXA = E.MATRICULA
 WHERE L.NUMBANCO = 40
   AND L.DTESTORNOBAIXA IS NULL
   AND L.CODROTINABAIXA NOT IN (
    638
)
   AND L.DTLANC >= TO_DATE ('01/01/2020', 'DD/MM/YYYY')
   AND (L.TIPOPARCEIRO NOT IN (
    'F'
)
    OR L.CODFORNEC IS NULL
    OR L.CODFORNEC = 0
    OR (L.VALOR < 0
   AND L.CODCONTA IN (
    410104, 620106, 620109
))
    OR L.NUMNOTA IS NULL
    OR L.NUMNOTA = 0)
/