SELECT C.CODFILIAL,
       C.DTLANC,
       C.CODROTINA,
       C.CODCLI,
       C.HISTORICO,
       C.NUMPED,
       U.NOME MKT,
       P.NUMNOTA,
       C.VALOR
  FROM PCCRECLI C, PCPEDC P, PCUSUARI U
 WHERE C.NUMPED = P.NUMPEDRCA
   AND U.CODUSUR = P.CODUSUR
   AND C.HISTORICO LIKE '%DIF ENTRE NOTA E FINANCEIRO PED.%'
   AND C.NUMLANCBAIXA IS NULL
   AND C.DTDESCONTO IS NULL
 ORDER BY C.DTLANC DESC;


SELECT *
  FROM PCPREST
 WHERE NUMPED = 3800000564
   AND DTCANCEL IS NULL;
SELECT * FROM PCNFSAID WHERE NUMPED = 3800000564;