SELECT L.DTCOMPETENCIA,
       T.DTPAG,
       L.RECNUM,
       TO_DATE(M.DTCOMPENSACAO, 'DD/MM/YYYY') AS DTCOMPENSACAO,
       L.CODCONTA,
       L.NUMNOTA,
       L.DUPLIC,
       L.NUMTRANS,
       L.VALOR
  FROM PCLANC L
 INNER JOIN PCMOVCR M
    ON L.NUMTRANS = M.NUMTRANS
 RIGHT JOIN PCPREST T
    ON T.NUMTRANS = L.NUMTRANS
   AND T.DUPLIC = L.NUMNOTA
   AND T.PREST = L.DUPLIC
   AND T.CODFILIAL = L.CODFILIAL
 WHERE L.CODCONTA = 610102
   AND T.DTPAG <> L.DTCOMPETENCIA
   AND M.DTESTORNO IS NULL
   AND T.VALORESTORNO IS NULL
 ORDER BY L.DTPAGTO DESC;
