SELECT R.CODFILIAL,
       R.DTLANC,
       R.RECNUM,
       R.CODCONTA,
       R.VALOR,
       R.PERCRATEIO,
       R.CODIGOCENTROCUSTO AS CENTROCUSTO,
       R.ROTINAINSERT
  FROM PCRATEIOCENTROCUSTO R
 WHERE NOT EXISTS (
    SELECT RECNUM
      FROM PCLANC L
     WHERE L.RECNUM = R.RECNUM
);