SELECT E.CODFILIAL,
       E.DTENT,
       E.CODFORNEC || ' - ' || E.FORNECEDOR FORNECEDOR,
       E.ESPECIE || ' - ' || E.NUMNOTA NOTA,
       E.VLTOTAL,
       B.VLCONTABIL
  FROM PCNFENT E
  LEFT JOIN PCNFBASE B ON B.NUMTRANSENT = E.NUMTRANSENT
 WHERE E.VLTOTAL <> B.VLCONTABIL
   AND DTSAIDA IS NULL
   AND ESPECIE IN ('NF', 'NS')
 ORDER BY DTENT DESC;
