SELECT L.CODFILIAL,
       L.TIPOLANC,
       L.RECNUM,
       L.DTLANC,
       L.DTCOMPETENCIA COMPETENCIA,
       L.CODCONTA,
       C.CONTA,
       L.TIPOPARCEIRO TIPO,
       L.CODFORNEC,
       F.FORNECEDOR,
       L.HISTORICO,
       L.VALOR,
       L.DTVENC
  FROM PCLANC L, PCFORNEC F, PCCONTA C
 WHERE F.CODFORNEC = L.CODFORNEC
   AND C.CODCONTA = L.CODCONTA
   AND L.DTPAGTO IS NULL
   AND L.DTVENC < TRUNC(SYSDATE)
   AND L.TIPOLANC = 'P'
   ORDER BY L.DTCOMPETENCIA;