SELECT T.CHAVECTE,
       T.DTENT,
       T.DTEMISSAO,
       T.CODFILIALNF,
       T.NUMNOTA,
       T.CODFORNEC,
       F.FORNECEDOR,
       T.VLTOTAL
  FROM PCNFENT T, PCFORNEC F
 WHERE T.CODFORNEC = F.CODFORNEC
   AND ESPECIE = 'CT'
   AND CODFORNEC IN (:CODFORNEC)
   AND DTENT BETWEEN TO_DATE(:DTENTINICIAL, 'DD/MM/YYYY') AND TO_DATE(:DTENTFINAL, 'DD/MM/YYYY')
   AND DTEMISSAO BETWEEN TO_DATE(:DTEMISSAOINICIAL, 'DD/MM/YYYY') AND TO_DATE(:DTEMISSAOFINAL, 'DD/MM/YYYY')
  ORDER BY T.DTENT, T.DTEMISSAO;
