SELECT C.CODCLI,
       C.CLIENTE,
       C.CLIENTE_REDE,
       V.CODUSUR
  FROM VIEW_JC_CLIENTE C
  LEFT JOIN VIEW_JC_VENDEDOR V ON C.CODUSUR1 = V.CODUSUR
 WHERE V.CODGERENTE IN (
    1, 8, 9, 10
)
   AND C.BLOQUEIODEFINITIVO = 'N';
/