--Fazer inclusão de títulos a receber manual e gerar um credito manual, utilizando a mesma conta gerencial


----AJUSTE DATA DE EMISSÃO PARA FICAR IGUAL A DATA DE EMISSÃO DA DUPLICATA EMITIDA-------
SELECT ROWID, P. * FROM PCPREST P WHERE CODCLI  = 10149 ORDER BY DTEMISSAO;


-----------AJUSTE DO CODFILIAL PARA FICAR IGUAL AO DA FILIAL QUE FOI GERADO O CRÉDITO MANUAL----------
SELECT ROWID, L.CODFILIAL, L.* FROM PCLANC L WHERE CODCONTA = 620103 AND DTLANC = TRUNC(SYSDATE);
