SELECT ROWID,
       M.CODBANCO,
       M.*
  FROM PCMOVCR M
 WHERE M.NUMTRANS IN (318249);
/
SELECT ROWID,
       T.CODBANCO,
       T.*
  FROM PCPREST T
 WHERE T.NUMTRANS IN (318249);
/

UPDATE PCPREST SET CODBANCO = 66 WHERE NUMTRANS = 318249 AND CODBANCO = 65;

/*RODAR ATUALIZACAO DO CAIXA NA 507*/
