SELECT ROWID,
       M.CODBANCO,
       M.*
  FROM PCMOVCR
 WHERE M.NUMTRANS = 269149;
/
SELECT ROWID,
       T.CODBANCO,
       T.*
  FROM PCPREST T
 WHERE T.NUMTRANS = 269149;
/

/*RODAR ATUALIZACAO DO CAIXA NA 507*/