--VERIFICAR BAIXA NA PCPREST INFORMANDO NUMTRANS
SELECT P.CODBANCO, P.* FROM PCPREST P WHERE P.NUMTRANS = 308763;

--UPDATE NA PCPREST CORRIGINDO O CAIXA
UPDATE PCPREST SET CODBANCO = 69 WHERE NUMTRANS = 308763;

--VERIFICAR LANCAMENTO NA PCMOVCR
SELECT * FROM PCMOVCR M WHERE M.NUMTRANS = 308763;

--UPDATE NA PCMOVCR CORRIGINDO O CAIXA
UPDATE PCMOVCR SET CODBANCO = 69 WHERE NUMTRANS = 308763;

--REALIZAR O RECALCULO DO SALDO DOS CAIXAS ENVOLVIDOS NA ROT 507
