CREATE OR REPLACE VIEW VIEW_JC_LANC_ADIANTAMENTOFOR AS
SELECT L.CODFILIAL,
       L.RECNUM,
       L.VPAGO, --SE O VALOR FOR  > 0 ENTÃO HOUVE O ADIANTAMENTO, SE FOR < 0 HOUVE DEVOLUÇÃO DO ADIANTAMENTO
       (CASE
         WHEN L.VPAGO < 0 THEN
          NVL(L.VPAGO, 0) * -1
         ELSE
          L.VPAGO
       END) AS VALOR, --TRANSFORMAR OS VALORES NEGATIVOS PARA ARQUIVO CONTABILIDADE
       --L.DTCOMPETENCIA,
       L.DTPAGTO AS DATA,
       --M.DTCOMPENSACAO,
       B.CODFILIAL AS CODFILIALBANCO,
       M.CODBANCO,
       B.CODCONTABIL AS CODCONTABILBANCO,
       L.CODCONTA,
       L.CODFORNEC,
       L.TIPOPARCEIRO,
       (CASE
         WHEN L.VPAGO < 0 THEN
          (L.NUMTRANS || ' - ' || 'DEV ADIANT. - ' || F.FORNECEDOR || ' - ' || L.HISTORICO)
         ELSE
          (L.NUMTRANS || ' - ' || 'ADIANT. - ' || F.FORNECEDOR || ' - ' || L.HISTORICO)
       END) HISTORICO,
       L.NUMTRANS
  FROM PCLANC L
 INNER JOIN PCMOVCR M
    ON L.NUMTRANS = M.NUMTRANS
  LEFT JOIN PCBANCO B
    ON M.CODBANCO = B.CODBANCO
  LEFT JOIN PCFORNEC F
    ON L.CODFORNEC = F.CODFORNEC
 WHERE L.DTCANCEL IS NULL --NAO CONSIDERAR LANCAMENTOS CANCELADOS
   AND L.DTESTORNOBAIXA IS NULL --NAO CONSIDERAR LANCAMENTOS ESTORNADOS
   AND M.CODBANCO NOT IN (17, 20, 35, 50, 52, 53, 54) --BANCOS DE BONIFICACAO E ACERTO MOTORISTA E EXTRAVIO DE MERCADORIA
   AND M.DTESTORNO IS NULL --PARA NAO TRAZER LANCAMENTO DUPLICADOS OU TRIPILICADOS QUE TENHA SIDO ESTORNADOS NA PCMOVCR   
   AND M.CODROTINALANC NOT IN (1209) --NAO CONSIDERAR MOVIMETACOES QUE FORAM ESTORNADAS
   AND L.ADIANTAMENTO = 'S' --PARA TRAZER SOMENTE LANCAMENTOS QUE FORAM ADIANTAMENTOS PARA FORNECEDOR
;