CREATE OR REPLACE VIEW VIEW_JC_PCCENTROCUSTO AS
SELECT CODIGOCENTROCUSTO AS CODCENTROCUSTO,
       (CODIGOCENTROCUSTO || ' - ' || DESCRICAO) CENTROCUSTO
  FROM PCCENTROCUSTO
 WHERE RECEBE_LANCTO = 'S';
