CREATE OR REPLACE VIEW VIEW_JC_PCFILIAL AS
SELECT CODIGO AS CODFILIAL,
       (CASE
         WHEN FANTASIA IS NULL THEN
          'FILIAL 99'
         ELSE
          FANTASIA
       END) AS FILIAIS,
       (CASE
         WHEN NOMEREMETENTE IS NULL THEN
          'FILIAL 99'
         ELSE
          NOMEREMETENTE
       END) AS EMPRESAS
  FROM PCFILIAL
 ORDER BY CODIGO;
