CREATE OR REPLACE VIEW VIEW_JC_PCDIASUTEIS AS
WITH DIAS_UTEIS AS
 (SELECT D.DATA,
         D.DIAFINANCEIRO,
         (SELECT MIN(D2.DATA) DATA
            FROM PCDIASUTEIS D2
           WHERE D2.DIAFINANCEIRO = 'S'
             AND D.DATA <= D2.DATA
             AND D2.CODFILIAL = D.CODFILIAL) AS DTVENC_UTIL
    FROM PCDIASUTEIS D
   WHERE CODFILIAL = 1)

SELECT U.CODFILIAL,
       U.DATA,
       U.DIAFINANCEIRO,
       U.DIAVENDAS,
       D.DTVENC_UTIL
  FROM PCDIASUTEIS U
  JOIN DIAS_UTEIS D ON D.DATA = U.DATA
 WHERE CODFILIAL NOT IN (3, 4)
 ORDER BY CODFILIAL,
          DATA;
