CREATE OR REPLACE VIEW VIEW_BI_DIASUTEIS AS
    SELECT CAST(CODFILIAL AS NUMBER) AS CODFILIAL,
           DATA,
           DIAFINANCEIRO,
           DIAVENDAS
      FROM PCDIASUTEIS
     WHERE CODFILIAL NOT IN (
        3, 4
    );
/