CREATE OR REPLACE VIEW VIEW_JC_LANC_CRED_AVULSO AS
--LANCAMENTOS DE CREDITOS MOVIMENTANDO CONTA GERENCIAL--
WITH LANC_CRED_AVULSO AS
 (SELECT I.CODFILIAL,
         I.NUMLANC AS CODLANC,
         I.NUMCRED,
         I.CODIGO,
         I.DTLANC AS DATA,
         I.VALOR,
         I.CODMOVIMENTO AS CODCONTA,
         C.CODUSUR1 AS CODUSUR,
         'L' AS TIPO,
         ('CRED AVULSO COD. ' || I.CODIGO || ' - ' || C.CLIENTE) AS HISTORICO
    FROM PCCRECLI I
    LEFT JOIN PCCLIENT C
      ON I.CODCLI = C.CODCLI
   WHERE I.NUMLANC IS NOT NULL --APENAS LANÇAMENTOS QUE GERARAM PCLANC
     AND I.NUMERARIO = 'N' --APENAS LANÇAMENTOS QUE NÃO MOVIMENTARAM NUMERÁRIOS
     AND I.VALOR > 0 --APENAS REGISTROS QUE FORAM LANCAMENTOS DE CREDITO COM CONTA GERENCIAL
     AND NVL(I.CODMOVIMENTO, 0) NOT IN (37, 620108, 620109) --RETIRAR LANÇAMENTOS DE AJUSTE E TAXAS DE MKT 
  ),
LANC_NUMCRED AS
 (SELECT DISTINCT (R.NUMCRED)
    FROM PCCRECLI R
   INNER JOIN LANC_CRED_AVULSO L
      ON R.NUMLANC = L.CODLANC
   WHERE R.NUMCRED IS NOT NULL)
SELECT *
  FROM LANC_CRED_AVULSO
UNION ALL
--BAIXA DOS CREDITOS AVULSO COMO RECEITA--
SELECT T.CODFILIAL,
       T.NUMLANCBAIXA AS CODLANC,
       T.NUMCRED,
       T.CODIGO,
       T.DTDESCONTO AS DATA,
       (T.VALOR * -1) AS VALOR, --TRANSFORMAR OS VALORES EM POSITIVO PARA ARQUIVO CONTABILIDADE
       T.CODMOVIMENTO AS CODCONTA,
       C.CODUSUR1 AS CODUSUR,
       'E' AS TIPO,
       ('EST CRED AVULSO COD. ' || T.CODIGO || ' - ' || C.CLIENTE) AS HISTORICO
  FROM PCCRECLI T
 INNER JOIN LANC_NUMCRED F
    ON T.NUMCRED = F.NUMCRED
  LEFT JOIN PCCLIENT C
    ON T.CODCLI = C.CODCLI
 WHERE T.NUMLANCBAIXA IS NOT NULL --APENAS LANÇAMENTOS QUE GERARAM RECEITA NA PCLANC
   AND NVL(ORIGEM, 0) NOT IN ('M') --RETIRAR LANÇAMENTOS DE DIF ENTRE NOTA E FINANCEIRO
UNION ALL
--BAIXA DOS CREDITOS AVULSO DOS CLIENTES--
SELECT T.CODFILIAL,
       T.NUMTRANSVENDADESC AS CODLANC,
       T.NUMCRED,
       T.CODIGO,
       T.DTDESCONTO AS DATA,
       T.VALOR,
       T.CODMOVIMENTO AS CODCONTA,
       C.CODUSUR1 AS CODUSUR,
       'B' AS TIPO,
       ('BAIXA CRED AVULSO COD. ' || T.CODIGO || ' - ' || C.CLIENTE) AS HISTORICO
  FROM PCCRECLI T
 INNER JOIN LANC_CRED_AVULSO F
    ON T.CODIGO = F.CODIGO
  LEFT JOIN PCCLIENT C
    ON T.CODCLI = C.CODCLI
 WHERE T.NUMTRANSVENDADESC IS NOT NULL --APENAS LANÇAMENTOS QUE APLICADOS COMO DESCONTO DUPLICATA  
UNION ALL
--BAIXA DOS CREDITOS AVULSO NOS RECEBIVEIS DOS CLIENTES--
SELECT T.CODFILIAL,
       T.NUMTRANSVENDADESC AS CODLANC,
       T.NUMCRED,
       T.CODIGO,
       T.DTDESCONTO AS DATA,
       T.VALOR,
       T.CODMOVIMENTO AS CODCONTA,
       C.CODUSUR1 AS CODUSUR,
       'D' AS TIPO,
       ('DESC NF. ' || (CASE
         WHEN T.NUMNOTADESC IS NULL THEN
          T.NUMCUPOM
         ELSE
          T.NUMNOTADESC
       END) || ' - ' || C.CLIENTE) AS HISTORICO
  FROM PCCRECLI T
 INNER JOIN LANC_CRED_AVULSO F
    ON T.CODIGO = F.CODIGO
  LEFT JOIN PCCLIENT C
    ON T.CODCLI = C.CODCLI
 WHERE T.NUMTRANSVENDADESC IS NOT NULL --APENAS LANÇAMENTOS QUE APLICADOS COMO DESCONTO DUPLICATA  
UNION ALL
--BAIXA DOS CREDITOS AVULSO DOS BANCOS-- 
SELECT T.CODFILIAL,
       T.NUMTRANSBAIXA AS CODLANC,
       T.NUMCRED,
       T.CODIGO,
       T.DTDESCONTO AS DATA,
       (T.VALOR * -1) AS VALOR, --TRANSFORMAR OS VALORES EM POSITIVO PARA ARQUIVO CONTABILIDADE
       T.CODMOVIMENTO AS CODCONTA,
       C.CODUSUR1 AS CODUSUR,
       'B' AS TIPO,
       ('BAIXA CRED AVULSO COD. ' || T.CODIGO || ' - ' || C.CLIENTE) AS HISTORICO
  FROM PCCRECLI T
 INNER JOIN LANC_NUMCRED F
    ON T.NUMCRED = F.NUMCRED
  LEFT JOIN PCCLIENT C
    ON T.CODCLI = C.CODCLI
 WHERE T.NUMTRANSBAIXA IS NOT NULL --APENAS LANCAMENTOS QUE MOVIMENTARAM BANCO
   AND T.CODMOVIMENTO NOT IN (17, 20, 35, 50, 52, 53, 54) --BANCOS DE BONIFICACAO E ACERTO MOTORISTA E EXTRAVIO DE MERCADORIA
UNION ALL
--BAIXA DOS CREDITOS AVULSO COMO MOVIMENTACAO DE NUMERÁRIO - BANCOS-- 
SELECT T.CODFILIAL,
       T.NUMTRANSBAIXA AS CODLANC,
       T.NUMCRED,
       T.CODIGO,
       T.DTDESCONTO AS DATA,
       (T.VALOR * -1) AS VALOR, --TRANSFORMAR OS VALORES EM POSITIVO PARA ARQUIVO CONTABILIDADE
       B.CODCONTABIL AS CODCONTA,
       C.CODUSUR1 AS CODUSUR,
       'M' AS TIPO,
       ('PAG CLIENTE' || ' - ' || C.CLIENTE) AS HISTORICO
  FROM PCCRECLI T
 INNER JOIN LANC_NUMCRED F
    ON T.NUMCRED = F.NUMCRED
  LEFT JOIN PCCLIENT C
    ON T.CODCLI = C.CODCLI
  LEFT JOIN PCBANCO B
    ON T.CODMOVIMENTO = B.CODBANCO  
 WHERE T.NUMTRANSBAIXA IS NOT NULL --APENAS LANCAMENTOS QUE MOVIMENTARAM BANCO
   AND T.CODMOVIMENTO NOT IN (17, 20, 35, 50, 52, 53, 54) --BANCOS DE BONIFICACAO E ACERTO MOTORISTA E EXTRAVIO DE MERCADORIA
;