CREATE OR REPLACE VIEW VIEW_JC_LANC_OUTROS AS
WITH TODOS_LANC_FINANCEIROJUR AS
/*SELECAO DE TODOS OS LANCAMENTOS DE DESCONTOS E JUROS*/
 (SELECT L.RECNUM
    FROM PCLANC L
   INNER JOIN VIEW_JC_LANC_DESC_JUR T
      ON L.RECNUMBAIXA = T.RECNUM);/
