CREATE OR REPLACE VIEW VIEW_JC_LANC_MUTUOS AS
SELECT B.CODFILIAL,
       B.RECNUM,
       B.VPAGO,
       B.VALOR,
       B.DTCOMPETENCIA,
       B.DTPAGTO,
       B.DTCOMPENSACAO,
       B.CODFILIALBANCO,
       B.CODBANCO,
       B.CODCONTABILBANCO,
       B.CODCONTA,
       B.GRUPOCONTA,
       B.CODFORNEC,
       '' AS CODCONTABCLIENTE,
       B.TIPOPARCEIRO,
       B.NUMTRANS,
       'MT' AS TIPO,
       (B.RECNUM || ' - ' || B.HISTORICO) AS HISTORICO
  FROM VIEW_JC_LANC_BASE B
 WHERE B.CODBANCO IN (14, 15, 63, 100, 101, 102, 103)
      /*SOMENTE BANCOS DOS MUTUOS E EMPRESTIMOS BANCARIOS*/
   AND NOT ((B.CODBANCO = 14 AND B.CODCONTA IN (2403)) OR
        (B.CODBANCO = 15 AND B.CODCONTA IN (2402)) OR
        (B.CODCONTA IN (2401, 2101, 2102, 2103, 2109) AND B.CODBANCO IN (63, 100, 101, 102, 103)) OR
        (B.CODCONTA IN ( 4112, 620112) AND B.VPAGO < 0)) 
/*RETIRAR LANCAMENTOS DE APORTE E PAGAMENTO*/
;
/
