CREATE OR REPLACE VIEW VIEW_JC_LANC_DESP_GER AS
 SELECT B.CODFILIAL,
         B.RECNUM,
         B.VPAGO,
         B.VALOR,
         B.DTCOMPETENCIA,
         B.DTPAGTO,
         B.DTCOMPENSACAO,
         B.CODFILIALBANCO,
         B.CODBANCO,
         B.CODCONTABILBANCO,
         B.CODCONTA,
         B.GRUPOCONTA,
         B.CODFORNEC,
         '' AS CODCONTABCLIENTE,
         B.TIPOPARCEIRO,
         B.NUMTRANS,
         'O' TIPO,
         (
           CASE
             WHEN B.NUMNOTA IS NULL OR B.NUMNOTA = '0' THEN B.RECNUM || ' - ' || B.HISTORICO
             WHEN B.DUPLIC IS NULL OR B.DUPLIC = '0' THEN 'NF ' || B.NUMNOTA || ' - ' || B.HISTORICO
             ELSE 'NF ' || B.NUMNOTA || ' - ' || B.DUPLIC || ' - ' || B.HISTORICO
           END
         ) HISTORICO
    FROM VIEW_JC_LANC_BASE B
    LEFT JOIN VIEW_JC_LANC_FISCAL V ON B.CODFORNEC = V.CODFORNEC AND B.NUMNOTA = V.NUMNOTA
    WHERE B.TIPOPARCEIRO = 'F'
    --COPARTICIPACAO DA OMINT 
    AND B.CODFORNEC IN (10109)
    --RETIRAR LANCAMENTOS COM NOTA LANCADA NO LIVRO FISCAL
    AND V.CODFORNEC IS NULL;