CREATE OR REPLACE VIEW VIEW_JC_LANC_VERBA_AVULSA AS
    SELECT L.CODFILIAL,
           L.RECNUM,
           L.VPAGO,
           (
               CASE
                   WHEN L.VPAGO < 0 THEN (L.VPAGO * - 1)
                   ELSE L.VPAGO
               END
           ) AS VALOR,
           L.DTCOMPETENCIA,
           L.DTPAGTO,
           M.DTCOMPENSACAO,
           M.CODFILIAL AS CODFILIALBANCO,
           M.CODBANCO,
           B.CODCONTABIL AS CODCONTABILBANCO,
           L.CODCONTA,
           C.GRUPOCONTA,
           L.CODFORNEC,
           '' AS CODCONTABCLIENTE,
           L.TIPOPARCEIRO,
           L.NUMTRANS,
           'V' AS TIPO,
           (L.RECNUM || ' - VERBA FORNECEDOR - ' || L.HISTORICO) AS HISTORICO
      FROM PCLANC L
     INNER JOIN PCMOVCR M ON L.NUMTRANS = M.NUMTRANS
      LEFT JOIN PCBANCO B ON M.CODBANCO = B.CODBANCO
      LEFT JOIN PCCONTA C ON L.CODCONTA = C.CODCONTA
      LEFT JOIN VIEW_JC_DEVFORNEC_PAGTO D ON L.RECNUM = D.RECNUM
     WHERE L.DTCANCEL IS NULL
     /*NAO CONSIDERAR LANCAMENTOS CANCELADOS*/
       AND L.DTESTORNOBAIXA IS NULL 
     /*NAO CONSIDERAR LANCAMENTOS ESTORNADOS*/
       AND M.DTESTORNO IS NULL
     /*PARA NAO TRAZER LANCAMENTO DUPLICADOS OU TRIPILICADOS QUE TENHA SIDO ESTORNADOS NA PCMOVCR*/
       AND M.CODROTINALANC NOT IN (
        1209
    )
     /*NAO CONSIDERAR MOVIMENTACOES QUE FORAM ESTORNADAS*/
       AND L.DTPAGTO IS NOT NULL
     /*APENAS LANCAMENTOS PAGOS*/
       AND M.CODBANCO NOT IN (
        17, 20, 35, 50, 52, 53, 54, 40, 41
    )
     /*BANCOS DE BONIFICACAO, ACERTO MOTORISTA, EXTRAVIO DE MERCADORIA, COMISSAO MKT E CARTAO DE CREDITO*/
       AND L.CODROTINABAIXA = '1803'
     /*SOMENTE VERBAS RECEBIDAS EM DINHEIRO*/
       AND D.RECNUM IS NULL
     /*RETIRAR LANÇAMENTOS DE VERBAS COM ORIGEM EM DEVOLUCAO A FORNECEDOR RECEBIDAS COMO DINHEIRO*/;
/