CREATE OR REPLACE VIEW VIEW_JC_CFOP AS
WITH CODCFOP (CODFISCAL) AS
 (SELECT DISTINCT (CODFISCAL)
    FROM PCNFBASEENT
   WHERE CODFISCAL IS NOT NULL
     AND CODFISCAL <> 0
  UNION
  SELECT DISTINCT (CODFISCAL)
    FROM PCNFBASESAID
   WHERE CODFISCAL IS NOT NULL
     AND CODFISCAL <> 0) --UNIAO DOS CFOP DISTINTOS UTILIZADOS NAS TABELAS FISCAIS DE ENTRADA E SAIDA
SELECT A.CODFISCAL, A.DESCCFO
  FROM PCCFO A, CODCFOP
 WHERE A.CODFISCAL = CODCFOP.CODFISCAL;
