
    /*-----------------------------------------------VERIFICAÇÃO DO CODST SP LUCRO REAL-----------------------------------------------*/

CREATE OR REPLACE VIEW VIEW_JC_VERIFICA_CODST_SP_LC AS
WITH 
--LUCRO REAL SP CST ICMS 00 DESTAQUE DE 18% E CST PIS COFINS 01
LR_SP_ICM00_PC1 AS
 (SELECT A.* 
    FROM VIEW_JC_TABELABASE_SP_ICMS18 A
   INNER JOIN VIEW_JC_TABELABASE_LR B --FILTRO PARA TRAZER FILIAIS LUCRO REAL
      ON A.CODFILIAL = B.CODFILIAL
     AND A.UFDESTINO = B.UFDESTINO
     AND A.CODPROD = B.CODPROD
   WHERE A.UFDESTINO = 'SP'
     AND ((CASE WHEN A.IMPORTADO = 'N' THEN
            (CASE WHEN A.CODST = 3 THEN 1 ELSE 0 END) --SE FOR NACIONAL
           ELSE (CASE WHEN A.CODST = 4 THEN 1 ELSE 0 END) --SE FOR IMPORTADO
         END) = 0)),

--LUCRO REAL SP CST ICMS 00 DESTAQUE DE 12% E CST PIS COFINS 01
LR_SP_ICM12_PC1 AS
 (SELECT A.*
    FROM VIEW_JC_TABELABASE_LR A
   INNER JOIN VIEW_JC_TABELABASE_SP_ICMS12 B --FILTRAR NCM
      ON A.CODFILIAL = B.CODFILIAL
     AND A.UFDESTINO = B.UFDESTINO
     AND A.CODPROD = B.CODPROD
   WHERE A.UFDESTINO = 'SP'
     AND ((CASE WHEN A.REGIME_ICMS = 'S' THEN 1 ELSE 0 END) = 0 --VERIFICAR REGIME TRIBUTARIO PRODUTO
      OR (CASE WHEN A.IMPORTADO = 'N' THEN
            (CASE WHEN A.CODST = 60 THEN 1 ELSE 0 END) --SE FOR NACIONAL
           ELSE (CASE WHEN A.CODST = 61 THEN 1 ELSE 0 END) --SE FOR IMPORTADO
         END) = 0)),

--LUCRO REAL SP CST ICMS 00 DESTAQUE DE 25% E CST PIS COFINS 01
LR_SP_ICM25_PC1 AS
 (SELECT A.*
    FROM VIEW_JC_TABELABASE_LR A
   INNER JOIN VIEW_JC_TABELABASE_SP_ICMS25 B --FILTRAR NCM
      ON A.CODFILIAL = B.CODFILIAL
     AND A.UFDESTINO = B.UFDESTINO
     AND A.CODPROD = B.CODPROD
   WHERE A.UFDESTINO = 'SP'
     AND ((CASE WHEN A.REGIME_ICMS = 'S' THEN 1 ELSE 0 END) = 0 --VERIFICAR REGIME TRIBUTARIO PRODUTO
      OR (CASE WHEN A.IMPORTADO = 'N' THEN
            (CASE WHEN A.CODST = 71 THEN 1 ELSE 0 END) --SE FOR NACIONAL
           ELSE (CASE WHEN A.CODST = 72 THEN 1 ELSE 0 END) --SE FOR IMPORTADO
         END) = 0)),

--LUCRO REAL SP CST ICMS 41 E CST PIS COFINS 06         
LR_TODOS_ICM41_PC3 AS 
 (SELECT A.*
    FROM VIEW_JC_TABELABASE_LR A
   INNER JOIN VIEW_JC_TABELABASE_ICMS_CST41 B --FILTRAR NCM
      ON A.CODFILIAL = B.CODFILIAL
     AND A.UFDESTINO = B.UFDESTINO
     AND A.CODPROD = B.CODPROD
   WHERE ((CASE WHEN A.REGIME_ICMS = 'S' THEN 1 ELSE 0 END) = 0 --VERIFICAR REGIME TRIBUTARIO PRODUTO
      OR (CASE WHEN A.IMPORTADO = 'N' THEN
            (CASE WHEN A.CODST = 1 THEN 1 ELSE 0 END) --SE FOR NACIONAL
           ELSE (CASE WHEN A.CODST = 2 THEN 1 ELSE 0 END) --SE FOR IMPORTADO
         END) = 0)),

--LUCRO REAL SP CST ICMS 40 E CST PIS COFINS 06         
LR_TODOS_ICM40_PC3 AS 
 (SELECT A.*
    FROM VIEW_JC_TABELABASE_LR A
   INNER JOIN VIEW_JC_TABELABASE_ICMS_CST40 B --FILTRAR NCM
      ON A.CODFILIAL = B.CODFILIAL
     AND A.UFDESTINO = B.UFDESTINO
     AND A.CODPROD = B.CODPROD
   WHERE ((CASE WHEN A.REGIME_ICMS = 'S' THEN 1 ELSE 0 END) = 0 --VERIFICAR REGIME TRIBUTARIO PRODUTO
      OR (CASE WHEN A.IMPORTADO = 'N' THEN
            (CASE WHEN A.CODST = 32 THEN 1 ELSE 0 END) --SE FOR NACIONAL
           ELSE (CASE WHEN A.CODST = 35 THEN 1 ELSE 0 END) --SE FOR IMPORTADO
         END) = 0)),

--LUCRO REAL SP CST ICMS 00 E CST PIS COFINS 06         
LR_SP_ICM00_PC3 AS 
 (SELECT A.*
    FROM VIEW_JC_TABELABASE_LR A
   INNER JOIN VIEW_JC_TABELABASE_ICMS_CST00 B --FILTRAR NCM
      ON A.CODFILIAL = B.CODFILIAL
     AND A.UFDESTINO = B.UFDESTINO
     AND A.CODPROD = B.CODPROD
   WHERE A.UFDESTINO = 'SP'
     AND ( (CASE WHEN A.REGIME_ICMS = 'S' THEN 1 ELSE 0 END) = 0 --VERIFICAR REGIME TRIBUTARIO PRODUTO
      OR (CASE WHEN A.IMPORTADO = 'N' THEN
            (CASE WHEN A.CODST = 82 THEN 1 ELSE 0 END) --SE FOR NACIONAL
           ELSE (CASE WHEN A.CODST = 83 THEN 1 ELSE 0 END) --SE FOR IMPORTADO
         END) = 0)),

--LUCRO REAL SP PRODUTO ST E CST PIS COFINS 06 
LR_SP_ST_PC3 AS
 (SELECT A.*
    FROM VIEW_JC_TABELABASE_LR A
   INNER JOIN VIEW_JC_TABELABASE_SP_ST_PC3 B --FILTRAR NCM
      ON A.CODFILIAL = B.CODFILIAL
     AND A.UFDESTINO = B.UFDESTINO
     AND A.CODPROD = B.CODPROD
   WHERE A.UFDESTINO = 'SP'
     AND ((CASE WHEN A.REGIME_ICMS = 'N' THEN 1 ELSE 0 END) = 0 --VERIFICAR REGIME TRIBUTARIO PRODUTO
      OR (CASE WHEN A.IMPORTADO = 'N' THEN
            (CASE WHEN A.CODST = 122 THEN 1 ELSE 0 END) --SE FOR NACIONAL
           ELSE (CASE WHEN A.CODST = 8 THEN 1 ELSE 0 END) --SE FOR IMPORTADO
         END) = 0)),

--LUCRO REAL SP PRODUTO ST E CST PIS COFINS 04
LR_SP_ST_PC2 AS
 (SELECT A.*
    FROM VIEW_JC_TABELABASE_LR A
   INNER JOIN VIEW_JC_TABELABASE_SP_ST_PC2 B --FILTRAR NCM
      ON A.CODFILIAL = B.CODFILIAL
     AND A.UFDESTINO = B.UFDESTINO
     AND A.CODPROD = B.CODPROD
   WHERE A.UFDESTINO = 'SP'
     AND ((CASE WHEN A.REGIME_ICMS = 'N' THEN 1 ELSE 0 END) = 0 --VERIFICAR REGIME TRIBUTARIO PRODUTO
      OR  (CASE WHEN A.IMPORTADO = 'N' THEN
            (CASE WHEN A.CODST = 122 THEN 1 ELSE 0 END) --SE FOR NACIONAL
          ELSE (CASE WHEN A.CODST = 8 THEN 1 ELSE 0 END) --SE FOR IMPORTADO
          END) = 0) ),

--LUCRO REAL SP PRODUTO ST E CST PIS COFINS 01
LR_SP_ST_PC1 AS
 (SELECT A.*
    FROM VIEW_JC_TABELABASE_LR A
   INNER JOIN VIEW_JC_TABELABASE_SP_ST_PC1 B --FILTRAR NCM
      ON A.CODFILIAL = B.CODFILIAL
     AND A.UFDESTINO = B.UFDESTINO
     AND A.CODPROD = B.CODPROD
   WHERE A.UFDESTINO = 'SP'
     AND ((CASE WHEN A.REGIME_ICMS = 'N' THEN 1 ELSE 0 END) = 0 --VERIFICAR REGIME TRIBUTARIO PRODUTO
      OR  (CASE WHEN A.IMPORTADO = 'N' THEN
            (CASE WHEN A.CODST = 23 THEN 1 ELSE 0 END) --SE FOR NACIONAL
          ELSE (CASE WHEN A.CODST = 5 THEN 1 ELSE 0 END) --SE FOR IMPORTADO
          END) = 0) )


          
-------RESULTADO DAS TABELAS VIRTUAIS-------------
      SELECT * FROM LR_SP_ICM00_PC1
UNION SELECT * FROM LR_SP_ICM12_PC1
UNION SELECT * FROM LR_SP_ICM25_PC1
UNION SELECT * FROM LR_TODOS_ICM41_PC3
UNION SELECT * FROM LR_TODOS_ICM40_PC3
UNION SELECT * FROM LR_SP_ICM00_PC3
UNION SELECT * FROM LR_SP_ST_PC3  
UNION SELECT * FROM LR_SP_ST_PC2
UNION SELECT * FROM LR_SP_ST_PC1;/

         
/*---------------------------------------------VERIFICAÇÃO DO CODST SIMPLES NACIONAL-----------------------------------------------*/
CREATE OR REPLACE VIEW VIEW_JC_VERIFICA_CODST_SP_SN AS
WITH 
--SIMPLES NACIONAL SP COM ICMS 
SN_SP_ICMS AS
 (SELECT A.* 
    FROM VIEW_JC_TABELABASE_SN A
  LEFT JOIN VIEW_JC_TABELABASE_ICMS_CST41 B
    ON A.CODFILIAL = B.CODFILIAL
   AND A.UFDESTINO = B.UFDESTINO
   AND A.CODPROD = B.CODPROD  
  LEFT JOIN VIEW_JC_TABELABASE_ICMS_CST40 C
    ON A.CODFILIAL = C.CODFILIAL
   AND A.UFDESTINO = C.UFDESTINO
   AND A.CODPROD = C.CODPROD 
 WHERE A.UFDESTINO = 'SP'
   AND A.REGIME_ICMS = 'S'       
   AND (B.CODFILIAL IS NULL AND C.CODFILIAL IS NULL)--PARA NAO CONSIDERAR PRODUTOS ICMS COM ALIQUOTAS 0%--
   AND (CASE WHEN A.CODST = 118 THEN 1 ELSE 0 END) = 0 ),

--SIMPLES NACIONAL SP ISENTO DE ICMS        
SN_TODOS_ISENTO_ICMS AS 
 (SELECT A.*
    FROM VIEW_JC_TABELABASE_SN A
    INNER JOIN VIEW_JC_ICMS_CST40_41 B
      ON A.CODFILIAL = B.CODFILIAL
     AND A.UFDESTINO = B.UFDESTINO
     AND A.CODPROD = B.CODPROD
   WHERE (CASE WHEN A.CODST = 119 THEN 1 ELSE 0 END) = 0 ),

--SIMPLES NACIONAL SP COM ST 
SN_SP_ST AS
 (SELECT A.* 
    FROM VIEW_JC_TABELABASE_SN A
 WHERE A.UFDESTINO = 'SP'
   AND A.REGIME_ICMS = 'N' 
   AND (CASE WHEN A.CODST = 120 THEN 1 ELSE 0 END) = 0 )    
      
-------RESULTADO DAS TABELAS VIRTUAIS-------------
      SELECT * FROM SN_SP_ICMS
UNION SELECT * FROM SN_TODOS_ISENTO_ICMS
UNION SELECT * FROM SN_SP_ST  


 /*-----------------------------------------VERIFICAÇÃO DO CODST SP SIMPLES NACIONAL EXCESSIVO-----------------------------------------*/

CREATE OR REPLACE VIEW VIEW_JC_VERIFICA_CODST_SP_SNE AS
WITH 
--SIMPLES NACIONAL EXCESSIVO SP CST ICMS 00 DESTAQUE DE 18%
SNE_SP_ICM18 AS
 (SELECT A.* 
    FROM VIEW_JC_TABELABASE_SP_ICMS18 A
   INNER JOIN VIEW_JC_TABELABASE_SNE B --FILTRO PARA TRAZER FILIAL SNE
      ON A.CODFILIAL = B.CODFILIAL
     AND A.UFDESTINO = B.UFDESTINO
     AND A.CODPROD = B.CODPROD
   WHERE A.UFDESTINO = 'SP'
     AND (CASE WHEN A.CODST = 82 THEN 1 ELSE 0 END) = 0 ),  

--SIMPLES NACIONAL EXCESSIVO SP CST ICMS 00 DESTAQUE DE 12%
SNE_SP_ICM12 AS
 (SELECT A.*
    FROM VIEW_JC_TABELABASE_SNE A
   INNER JOIN VIEW_JC_TABELABASE_SP_ICMS12 B --FILTRAR NCM
      ON A.CODFILIAL = B.CODFILIAL
     AND A.UFDESTINO = B.UFDESTINO
     AND A.CODPROD = B.CODPROD
   WHERE A.UFDESTINO = 'SP'
     AND ((CASE WHEN A.REGIME_ICMS = 'S' THEN 1 ELSE 0 END) = 0 --VERIFICAR REGIME TRIBUTARIO PRODUTO
      OR (CASE WHEN A.CODST = 21 THEN 1 ELSE 0 END) = 0) ), 

--SIMPLES NACIONAL EXCESSIVO SP CST ICMS 00 DESTAQUE DE 25%
SNE_SP_ICM25 AS
 (SELECT A.*
    FROM VIEW_JC_TABELABASE_SNE A
   INNER JOIN VIEW_JC_TABELABASE_SP_ICMS25 B --FILTRAR NCM
      ON A.CODFILIAL = B.CODFILIAL
     AND A.UFDESTINO = B.UFDESTINO
     AND A.CODPROD = B.CODPROD
   WHERE A.UFDESTINO = 'SP'
     AND ((CASE WHEN A.REGIME_ICMS = 'S' THEN 1 ELSE 0 END) = 0 --VERIFICAR REGIME TRIBUTARIO PRODUTO
      OR (CASE WHEN A.CODST = 22 THEN 1 ELSE 0 END) = 0) ), 

--SIMPLES NACIONAL EXCESSIVO CST ICMS 41       
SNE_TODOS_ICM41 AS 
 (SELECT A.*
    FROM VIEW_JC_TABELABASE_SNE A
   INNER JOIN VIEW_JC_TABELABASE_ICMS_CST41 B --FILTRAR NCM
      ON A.CODFILIAL = B.CODFILIAL
     AND A.UFDESTINO = B.UFDESTINO
     AND A.CODPROD = B.CODPROD
   WHERE ((CASE WHEN A.REGIME_ICMS = 'S' THEN 1 ELSE 0 END) = 0 --VERIFICAR REGIME TRIBUTARIO PRODUTO
      OR (CASE WHEN A.CODST = 1 THEN 1 ELSE 0 END) = 0) ), 

--SIMPLES NACIONAL EXCESSIVO CST ICMS 40        
SNE_TODOS_ICM40 AS 
 (SELECT A.*
    FROM VIEW_JC_TABELABASE_SNE A
   INNER JOIN VIEW_JC_TABELABASE_ICMS_CST40 B --FILTRAR NCM
      ON A.CODFILIAL = B.CODFILIAL
     AND A.UFDESTINO = B.UFDESTINO
     AND A.CODPROD = B.CODPROD
   WHERE ((CASE WHEN A.REGIME_ICMS = 'S' THEN 1 ELSE 0 END) = 0 --VERIFICAR REGIME TRIBUTARIO PRODUTO
      OR (CASE WHEN A.CODST = 32 THEN 1 ELSE 0 END) = 0) ), 

--SIMPLES NACIONAL EXCESSIVO SP CST ICMS 00       
SNE_SP_ICM00 AS 
 (SELECT A.*
    FROM VIEW_JC_TABELABASE_SNE A
   INNER JOIN VIEW_JC_TABELABASE_ICMS_CST00 B --FILTRAR NCM
      ON A.CODFILIAL = B.CODFILIAL
     AND A.UFDESTINO = B.UFDESTINO
     AND A.CODPROD = B.CODPROD
   WHERE A.UFDESTINO = 'SP'
     AND (CASE WHEN A.CODST = 82 THEN 1 ELSE 0 END) = 0 ), 

--SIMPLES NACIONAL EXCESSIVO SP PRODUTO ST
SNE_SP_ST_03 AS
 (SELECT A.*
    FROM VIEW_JC_TABELABASE_SNE A
   INNER JOIN VIEW_JC_TABELABASE_SP_ST_PC3 B --FILTRAR NCM
      ON A.CODFILIAL = B.CODFILIAL
     AND A.UFDESTINO = B.UFDESTINO
     AND A.CODPROD = B.CODPROD
   WHERE A.UFDESTINO = 'SP'
     AND (CASE WHEN A.CODST = 122 THEN 1 ELSE 0 END) = 0 ), 

--SIMPLES NACIONAL EXCESSIVO SP PRODUTO ST
SNE_SP_ST_02 AS
 (SELECT A.*
    FROM VIEW_JC_TABELABASE_SNE A
   INNER JOIN VIEW_JC_TABELABASE_SP_ST_PC2 B --FILTRAR NCM
      ON A.CODFILIAL = B.CODFILIAL
     AND A.UFDESTINO = B.UFDESTINO
     AND A.CODPROD = B.CODPROD
   WHERE A.UFDESTINO = 'SP'
     AND (CASE WHEN A.CODST = 122 THEN 1 ELSE 0 END) = 0 ),

--SIMPLES NACIONAL EXCESSIVO SP PRODUTO ST
SNE_SP_ST_01 AS
 (SELECT A.*
    FROM VIEW_JC_TABELABASE_SNE A
   INNER JOIN VIEW_JC_TABELABASE_SP_ST_PC1 B --FILTRAR NCM
      ON A.CODFILIAL = B.CODFILIAL
     AND A.UFDESTINO = B.UFDESTINO
     AND A.CODPROD = B.CODPROD
   WHERE A.UFDESTINO = 'SP'
     AND (CASE WHEN A.CODST = 122 THEN 1 ELSE 0 END) = 0 )

          
-------RESULTADO DAS TABELAS VIRTUAIS-------------
      SELECT * FROM SNE_SP_ICM18
UNION SELECT * FROM SNE_SP_ICM12
UNION SELECT * FROM SNE_SP_ICM25
UNION SELECT * FROM SNE_TODOS_ICM41
UNION SELECT * FROM SNE_TODOS_ICM40
UNION SELECT * FROM SNE_SP_ICM00
UNION SELECT * FROM SNE_SP_ST_03  
UNION SELECT * FROM SNE_SP_ST_02
UNION SELECT * FROM SNE_SP_ST_01;   /