/*VERIFICAR MOVIMENTO BAIXADO E ESTORNADO NO BANCO DE OUTRA EMPRESA*/
SELECT *
  FROM PCMOVCR M
 WHERE CODBANCO = 27
   AND M.DATA = '11-MAR-2021'
   AND TIPO = 'D';
/

/* TIPO D - PUXAR AS PREST PELO NUMTRANS*/
SELECT T.CODBANCO,
       T.*
  FROM PCPREST T
 WHERE T.NUMTRANS = 200630;
/

/* TIPO C - PUXAR AS PREST PELO EXISTS DE NUMTRANS*/
SELECT T.CODBANCO,
       T.*
  FROM PCPREST T
 WHERE EXISTS (
    SELECT NUMTRANS
      FROM PCMOVCR M
     WHERE CODBANCO = 27
       AND M.DATA = '11-MAR-2021'
       AND TIPO = 'C'
       AND T.NUMTRANS = M.NUMTRANS
);
/

/*REALIZAR O UPDATE DO CODBANCO PARA O BANCO DA EMPRESA CORRETA*/
UPDATE PCPREST
   SET
    CODBANCO = 48
 WHERE NUMTRANS = 200630;
/
UPDATE PCPREST
   SET
    CODBANCO = 48
 WHERE EXISTS (
    SELECT NUMTRANS
      FROM PCMOVCR M
     WHERE CODBANCO = 27
       AND M.DATA = '11-MAR-2021'
       AND TIPO = 'C'
       AND PCPREST.NUMTRANS = M.NUMTRANS
);
/

/*REALIZAR O UPDATE NO BANCO NA PCMOVCR*/
UPDATE PCMOVCR
   SET
    CODBANCO = 48
 WHERE NUMTRANS = 200630;
/
UPDATE PCMOVCR
   SET
    CODBANCO = 48
 WHERE CODBANCO = 27
   AND DATA = '11-MAR-2021'
   AND TIPO = 'C'
   AND NUMCARR = 0;
/

/*RODAR O RECALCULO DOS SALDOS BANCARIOS*/